### ISSUE TITLE
Would you consider a PR for a Roslyn component?

### ISSUE THREAD

**Issue by mrpmorris** [jbogard/MediatR#1001]
If I wrote a Roslyn component that scanned for all the types that services.AddMediatR would be interested in so they are all pre-collected in an auto-generated class type, and then have a services.AddMediatR overload that took an array of these classes, would that be something you might be interested in?

I'm not sure how much bootstrap time this would save when scaling up web services for large apps, or if it might be useful for AOT.

What do you think?

PS: Pleased to get issue 1001 :)

**Comment by jbogard** [comment]
Would Roslyn be able to do the more sophisticated type checking that's in the scanning today?
