### ISSUE TITLE
Logging any Exception thrown in a handler

### ISSUE THREAD

**Issue by lscorcia** [jbogard/MediatR#1007]
Hi, in my application I need to log any exception thrown by request handlers. To reproduce my issue, replace `PingHandler` `Handle` method from the samples as follows:

```
public Task<Pong> Handle(Ping request, CancellationToken cancellationToken)
{
    throw new NotImplementedException();
}
```

Then put some breakpoints in https://github.com/jbogard/MediatR/blob/513c20214a84d7486d50eddf9eea8591c7360894/samples/MediatR.Examples/ExceptionHandler/LogExceptionAction.cs . 

The default implementation of `LogExceptionAction` is tied to the `Ping` request and works just fine. In my first iteration, I replaced the type of the request parameter to a generic `TRequest`:

```
public class LogExceptionAction<TRequest> : IRequestExceptionAction<TRequest, Exception>
{
    private readonly TextWriter _writer;

    public LogExceptionAction(TextWriter writer) => _writer = writer;

    public Task Execute(TRequest request, Exception exception, CancellationToken cancellationToken)
        => _writer.WriteLineAsync($"--- Exception: '{exception.GetType().FullName}'");
}
```

This doesn't seem to be invoked at all. Neither the breakpoint in the constructor nor the one in the `Execute` method are hit.

Then I tried replacing the exception parameter with a generic `TException`:

```
public class LogExceptionAction<TRequest, TException> : IRequestExceptionAction<TRequest, TException>
    where TException: Exception
{
    private readonly TextWriter _writer;

    public LogExceptionAction(TextWriter writer) => _writer = writer;

    public Task Execute(TRequest request, TException exception, CancellationToken cancellationToken) 
        => _writer.WriteLineAsync($"--- Exception: '{exception.GetType().FullName}'");
}
```

This one is correctly reached, BUT it's called three times - debugging shows that `RequestExceptionProcessorBehavior` invokes the action once for every base class in the Exception type hierarchy (`NotImplementedException`, `SystemException`, `Exception`). I understand why this is the case, but maybe it should be noted in the documentation as it's pretty counterintuitive.

However the thing that puzzles me is why the first attempt isn't working correctly. It seems it should be pretty straightforward. What am I doing wrong? What's the correct way to achieve my goal?

**Comment by xaviervv** [comment]
While stale or closed, this is still an issue I am experiencing now.
When `MyCustomException:Exception` is thrown from the handler, the` IRequestExceptionAction<TRequest, Exception> `gets called twice
