### ISSUE TITLE
Irequest in library and handler in web api project 

### ISSUE THREAD

**Issue by FBicsharp** [jbogard/MediatR#1034]
Hello to everyone,
I'm playing with mediator, and I make the following project structure.
- Library project
  contains dtos and the requests definition
-web api project 
Contains controllers  and entity framework and handlers for the requests define in the library project

I got the compile time error because the requests is outside the project, the main reasons is that I want to use the library project in others projects and send requests using  the library as contracts.

The other project il loading at runtime.
There is any way to have the requests on library project?

**Comment by Danielovich** [comment]
Hi there,

It would be a lot easier if you could provide code samples, preferably in a repo, so one could investigate the issues you are experiencing.

**Comment by FBicsharp** [comment]
Hi, I'm sorry, I was referencing the wrong object in Handler class.
