### ISSUE TITLE
Multiple declarations of IAsyncRequest with a common type

### ISSUE THREAD

**Issue by laitang2000** [jbogard/MediatR#104]
Hi,
I'm new to Mediatr and I'm not sure if it is a limitation of Mediatr or the ioc library Unity.

When I declare for example two request classes like so - 

```
public class Query1 :  IAsyncRequest<CommonResult>{
}

public class Query2 :  IAsyncRequest<CommonResult>{
}
```

I get a Microsoft.Practices.Unity.DuplicateTypeMappingException. Can anyone point me in the write direction? 

Cheers

**Comment by jbogard** [comment]
What do the handlers look like?

**Comment by laitang2000** [comment]
Hi, 

the handlers look like

```
public class GetQuery1Handler : HandlerBase, IAsyncRequestHandler<Query1 , CommonResult>{
}


public class GetQuery2Handler : HandlerBase, IAsyncRequestHandler<Query2 , CommonResult>{
}
```

**Comment by jbogard** [comment]
Those look fine to me. What does the registration look like?

**Comment by laitang2000** [comment]
the registration was taken from your sample for unity - 

`            container.RegisterType<IMediator, Mediator>();
            container.RegisterTypes(AllClasses.FromAssemblies(typeof (MyLib.CQS.RequestBase).Assembly),
                WithMappings.FromAllInterfaces, GetName, GetLifetimeManager);
            //unity.RegisterType(typeof(INotificationHandler<>), typeof(GenericHandler), GetName(typeof(GenericHandler)));
            //unity.RegisterType(typeof(IAsyncNotificationHandler<>), typeof(GenericAsyncHandler), GetName(typeof(GenericAsyncHandler)));
            container.RegisterInstance<SingleInstanceFactory>(t => container.Resolve(t));
            container.RegisterInstance<MultiInstanceFactory>(t => container.ResolveAll(t));`

**Comment by jbogard** [comment]
Is it that second RegisterTypes call? I honestly don't know - of all the DI containers I added examples for, Unity was the hardest. A few of the scenarios didn't work.

**Comment by laitang2000** [comment]
I am trying to return a generic response type like  FunctionResponse<List<someclass>> 
would that matter?

**Comment by laitang2000** [comment]
I see... looks like I may need to migrate then, can you recommend a DI library that has good property setters like unity?

**Comment by abatishchev** [comment]
"property setters" such as? I'm using Simple Injector in all my projects and absolutely happy with it.

**Comment by laitang2000** [comment]
well in Unity you can decorate a property with [Dependency] and  will resolve the type.

**Comment by jbogard** [comment]
Nooooooo not property injection

**Comment by laitang2000** [comment]
yessssssss I love it!

**Comment by valdisiljuconoks** [comment]
what are benefits or property injections vs constructor injections? property injections are designed for the cases when you have good local default..

**Comment by jbogard** [comment]
Constructor injection = required dependency
Property injection = optional dependency

On Wed, Oct 19, 2016 at 3:32 AM, Wałdis Iljuczonok <notifications@github.com
