### ISSUE TITLE
MediatorPipeline is not assignable to service MediatR.IRequestHandler

### ISSUE THREAD

**Issue by vorosoft** [jbogard/MediatR#105]
I was following [MediatR Pipeline Examples](https://lostechies.com/jimmybogard/2016/10/13/mediatr-pipeline-examples/) and combined this with a simple console app, the [MediatR Extensions for Microsoft Dependency Injection](https://lostechies.com/jimmybogard/2016/07/19/mediatr-extensions-for-microsoft-dependency-injection-released/) and Autofac.

On running the app, I received the following exception:

> The type 'ConsoleApp1.MediatorPipeline`2[TRequest,TResponse]' is not assignable to service 'MediatR.IRequestHandler`2'.

Code to reproduce:

**Programs.cs**

```
using System;
using Autofac;
using Autofac.Extensions.DependencyInjection;
using ConsoleApp1.Data;
using MediatR;
using Microsoft.Extensions.DependencyInjection;

namespace ConsoleApp1
{
    public static class Program
    {
        private static readonly IServiceCollection Services;
        private static IContainer container;

        static Program()
        {
            Services = new ServiceCollection();

            Services.AddMediatR(typeof(Program));

            BuildContainer();
        }

        public static void Main()
        {
            var mediator = container.Resolve<IMediator>();

            Console.ReadKey();
        }

        private static void BuildContainer()
        {
            var builder = new ContainerBuilder();

            builder.Populate(Services);

            container = builder.Build();
        }
    }
}
```

**project.json**

```
{
    "buildOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {
        "Autofac": "4.1.1",
        "Autofac.Extensions.DependencyInjection": "4.0.0",
        "MediatR": "2.1.0",
        "MediatR.Extensions.Microsoft.DependencyInjection": "1.0.1",
         "Microsoft.Extensions.DependencyInjection": "1.0.0",
        "Microsoft.NETCore.App": {
            "type": "platform",
            "version": "1.0.0"
        }
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "portable-net45+win8"
            ]
        }
    },
    "version": "1.0.0-*"
}
```

**MediatorPipeline.cs**

```
using MediatR;

namespace ConsoleApp2
{
    public class MediatorPipeline<TRequest, TResponse>
      : IRequestHandler<TRequest, TResponse>
      where TRequest : IRequest<TResponse>
    {
        private readonly IRequestHandler<TRequest, TResponse> _inner;

        public MediatorPipeline(IRequestHandler<TRequest, TResponse> inner)
        {
            _inner = inner;
        }

        public TResponse Handle(TRequest message)
        {
            return _inner.Handle(message);
        }
    }
}
```

**Comment by valdisiljuconoks** [comment]
Is it so that you need to configure that `MediatorPipeline` will be used as decorator to all `IRequestHandler<,>`?

**Comment by vorosoft** [comment]
Oh, I don't know, I was just following the article. Late to the party, I've found Mediatr to be a fantastic breath of fresh air such that I got quite excited and wanted to see it working in the way described above.

**Comment by valdisiljuconoks** [comment]
Yes, can't agree more. If you are so called late to the party, you might find it interesting to follow second up coming part of blog post about round shaped architectures ("pizza" as I called it). http://blog.tech-fellow.net/2016/10/17/baking-round-shaped-software/

There mediator is acting in one if the main role to communicate between adapters and handlers. Next part will cover all the setups and ceremony required for spinning up the application.
Cheers!

**Comment by paulb2011** [comment]
I am getting this same exception described above when using AddMediatR() - I want to configure MediatorPipline to be used as a decorator for all IRequestHandler<,>. Do I need to manually configure the DI instead of using AddMediatR if I want to use decorators?

**Comment by jbogard** [comment]
Yes, you have to manually register decorators. Or use the new pipeline
stuff:

https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/blob/master/test/MediatR.Extensions.Microsoft.DependencyInjection.Tests/PipelineTests.cs#L178
