### ISSUE TITLE
#1048 and v12.4.0 breaks RequestExceptionProcessorBehavior

### ISSUE THREAD

**Issue by luis-fss** [jbogard/MediatR#1055]
The example code in https://github.com/jbogard/MediatR/wiki#exception-handler-pipeline-step

```csharp
public class RequestExceptionProcessorBehavior<TRequest, TResponse, TException> : IRequestExceptionHandler<TRequest, TResponse, TException>
    where TRequest : notnull where TException : Exception
{
    public Task Handle(TRequest request, TException exception, RequestExceptionHandlerState<TResponse> state, CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }
}
```

will throw an exception on startup: 

```System.ArgumentException: Error registering the generic handler type: PMCM.BlazorApp.Core.Pipeline.RequestExceptionProcessorBehavior`3. When registering generic requests with more than two type parameters, each type parameter must have at least one constraint of type interface or class.```

**Comment by luis-fss** [comment]
Related:
#1047
#1048
#1038

**Comment by zachpainter77** [comment]
I created a PR to remove the logic that causes that error. 

#1057
