### ISSUE TITLE
Error registering the generic handler type.

### ISSUE THREAD

**Issue by mbetanhe** [jbogard/MediatR#1064]
Hi everyone.
Few hours ago I update nuget packages of my Project including MediatoR 10 to latest 12 version  but I have a issue registering generic handler. 

In 10 version it worked fine without problem. However, whe I use the 12 version of MediatR visual reports the next issue registering the service.

Error registering the generic handler type: ResiduosApp.Application.Features.ExtendedAttributes.Queries.GetById.GetExtendedAttributeByIdQueryHandler`4. When registering generic requests with more than two type parameters, each type parameter must have at least one constraint of type interface or class. 

I try to change the implementation to transient but is has not be possible. Also I try register service manually but does not work.

![image](https://github.com/user-attachments/assets/8ae95ef8-513d-4e1f-8822-cea98c2e1ef9)

![image](https://github.com/user-attachments/assets/5f3ecc13-389a-40f2-b834-8f7c87f46fd8)

![image](https://github.com/user-attachments/assets/2e0b6535-806b-40ff-8213-2bbabafb5801)

**Comment by crnd** [comment]
There were changes (#1057) introduced to the registration of generic handlers in `12.3.0` and there is discussion (#1038) going on about the difficulties of the current implementation.

You can get back to the original behavior by downgrading MediatR to `12.2.0` for now.

**Comment by mbetanhe** [comment]
I downgraded to 12.2.0 but does not works. Shows ths same issue

**Comment by zachpainter77** [comment]
The registration of generic handlers is now Opt-In in the latest pull request so this shouldn't be an issue any longer.

**Comment by jbogard** [comment]
This is fixed in the latest release.

**Comment by jbogard** [comment]
Also what the hell is going on with that font, it's an abomination.
