### ISSUE TITLE
pipeline brokes each major version

### ISSUE THREAD

**Issue by uranio-235** [jbogard/MediatR#1067]
This is not a technical issue. Just a feedback. I'm just droping MediatR on all my projects. Because, each time update mediatR to a new major version, the pipelines brokes. 

![image](https://github.com/user-attachments/assets/0d276819-9de5-4179-834e-37c31a003afb)

if you think I'm wrong: Please close the issue.

**Comment by zachpainter77** [comment]
This has been fixed in the latest pull request.  The generic handler registration is now opt in.. meaning MediatR will not try to implement the feature unless you explicitly tell it to from now on.  Your pipeline should be ok for future MediatR releases.
