### ISSUE TITLE
Q: Should we check if the input is null

### ISSUE THREAD

**Issue by nojaf** [jbogard/MediatR#109]
I didn't see it directly in the source code but I was wondering how relevant it is to check if the message is null?

Example:

``` csharp
    public class ImportRequest : IAsyncRequest
    {

    }

    public class ImportRequestHandler : AsyncRequestHandler<ImportRequest>
    {

        protected override async Task HandleCore(ImportRequest message)
        {
            // Should we check?
            await Task.Delay(1);
        }
    }
```

If the message were null, would the handler be found in the first place?

**Comment by no1melman** [comment]
You can easily test this, but you should definitely check that the properties have been set. FluentValidation is great to use with MediatR for that kind of stuff.

**Comment by jbogard** [comment]
Yep, in general I use validation frameworks for this sort of thing.
