### ISSUE TITLE
Question: Once notification(s) are dispatched from a command handler, does control return to the controller/UI?

### ISSUE THREAD

**Issue by mgmccarthy** [jbogard/MediatR#112]
@jbogard sorry about the stupid question, but I wanted to get clarification on the asynchronicity of MediatR when it comes to returning control back to the controller/UI when dispatching notifications.

This is not about async/await API, but rather, the true asynchronicity for the MediatR "pipeline".

Assuming the following scenario, all using the async invocations in MediatR:

1. UI/controller sends a command async
2. command handler does work, then publishes a notification async
3. the notification handler does some db work that will need to be completed before control returns to the controller, which will do a RedirectToAction to a GET (PRG).
4. the controller does a RedirectToAction to a GET action method that reads the updated data that the nofiticatio handler did from step #3.

based on this workflow, do I need to worry about the GET action method doing a read (step #4) against the db that the notification handler needs to have updated (step #3) and the notification handler potentially not having finished its work yet?

I'm asking this b/c my understanding of NServiceBus is it's truly asynchronous. I know in the above statement using NServiceBus, there is no guarantee the notification (event) handler has finished its db work by the time my controller would RedirectToAction to perform a GET against the db that the notification (event) handler updates.

Thanks

**Comment by jbogard** [comment]
Yep, if you're awaiting MediatR, you're a-waiting for it to be done :)

**Comment by mgmccarthy** [comment]
Thanks! This issue can be closed since it was a question.

**Comment by jbogard** [comment]
Just for future reference, you can close issues you open yourself in GitHub.
