### ISSUE TITLE
Adding Mediatr to an existing app, can I configure existing interfaces to replace IRequestHandler and IRequest?

### ISSUE THREAD

**Issue by flipdoubt** [jbogard/MediatR#113]
We have an existing app that uses non-generic ICommandHandler and ICommandRequest interfaces the same way Mediatr uses IRequestHandler<T1, T2> and IRequest<T>, but with an ugly switch statement for routing requests to handlers. Do you have any examples for adding Mediatr to a mature/legacy app that does not require modifying existing classes? Can Mediatr be configured to use my own types for handlers and requests or does it have to use those types from your assembly? Any lessons learned from trying to do this kind of large-scale refactoring to a pattern?

**Comment by abatishchev** [comment]
Inject `IMediator` into your classes implemented by your own `LegacyMediatorDecorator` which accepts `IMediator` implemented by `MediatR.Mediator`. Keep your routing logic in the legacy one.

With Simple Injector container registration would look like this:
```csharp
container.RegisterSingleton<IMediator, Mediator>(...);
container.RegisterDecorator<IMediator, LegacyMediatorDecorator>(Lifestyle.Singleton);

class LegacyMediatorDecorator : IMediator
{
    public LegacyMediatorDecorator(IMediator mediator) { ... }
}
```
