### ISSUE TITLE
Q: Is it possible to inspect a Query/Command and change the object in a pipline?

### ISSUE THREAD

**Issue by nnyegaard** [jbogard/MediatR#120]
Hey,

I have some logic that is shared between features. The logic also have to happen when the Query/Command object have a specific property on it, and I was wondering if it is possible to look for that property? And if it's than located execute some logic and add/change a property on that Query/Command

**Comment by no1melman** [comment]
Sounds to me like you need the pipeline, decorate the handler

**Comment by nnyegaard** [comment]
I'm already using the pipeline with structuremap. What I would like to do
in the decorator is to inspect the object, and if a property exist, than
execute some logic that changes the object before it's send to the next
handler.

Hope that explains it a bit better.

Den søn. 25. dec. 2016 15.32 skrev Callum Linington <
notifications@github.com>:

**Comment by kappy** [comment]
It is also possible without the pipeline. Look here for example http://www.kspace.pt/posts/cqs-on-mvc-crosscutting-concerns

I've created an handlerwrapper that decorates every handler, and if the request has a property decorated with X (or in your case if a certain property exists) set some value on the request.

I do believe this should be now simplyfied with the new pipeline, You should only need to register a PreRequestHandler that does almost the same (but won't need the IoC decoreation setup).

**Comment by ThisNoName** [comment]
What do you mean by "between features"?  If it's just decorator inspect and modify request and response, it seems routine.

**Comment by nnyegaard** [comment]
With features I mean feature folders. So I have a feature that does X and a feature that does Y and they both have their own handler. 

There is then some shared logic between the two features if property Z is present and not null. It's this shared logic and check for property I want to move into a decorator handler.

There link kappy provided gave me the missing info I was looking for, so thanks a lot!
