### ISSUE TITLE
WebApi, Entity Framework, and Autofac Lifetime issue

### ISSUE THREAD

**Issue by jblackburn21** [jbogard/MediatR#121]
I'm trying to use Mediatr to publish domain events for a domain that is built on top of Entity Framework.  Within my web api I use Autofac to configure the db context to be scoped to the lifetime of the web request so that the same context is used throughout the web request.

The issue that I'm running into is when trying to use PublishAsync for my events.  Since all the handle methods are started and then Task.WhenAll() is used, then it causes multiple operations to start on the same db context, which is not supported.

This exception is thrown:
> A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.

I have come up with these options, but neither seem preferred.  

1. Use transient db contexts, but lose the benefits of the shared context
2. Use sync events, but then call into the EF Async methods

Has there been any thought in allowing the consumer to specify that the events should be processed one at a time so that they are not executed in parallel?

**Comment by jbogard** [comment]
Maybe a protected virtual method so that you can subclass and override this
behavior?

**Comment by jblackburn21** [comment]
I just noticed that this is the same request as PR #101 [Added option to enable PublishAsync to invoke handlers sequentially].  Should that discussion be reopened?  I would be fine with subclassing in my case.

**Comment by jbogard** [comment]
Yes, I just rewrote a lot of stuff underneath the covers, so I couldn't
take the PR.

**Comment by GODBS** [comment]
Hey Jimmy, I dont want to reopen this issue but I'm getting the exact same problem as @jblackburn21. Been stuck on this issue for a couple of days trying to figure out how to fix it. Would it be possible to direct me on the right path in order to help me solve this? By the way, this is probably one of the top libraries ive seen, really amazing, thank you for your hard work.

**Comment by jbogard** [comment]
What problem?

**Comment by GODBS** [comment]
thanks for the quick reply, 
the fact that the notifications are run in parallel and since they all share the same entity framework dbcontext, I get the error "A second operation started on this context before a previous asynchronous operation completed."

**Comment by jbogard** [comment]
Ahhhh OK, so the default is to run in parallel. To override that, you can subclass the Mediator class and override the `PublishCore` method to do a `foreach` and `await`: https://github.com/jbogard/MediatR/blob/master/src/MediatR/Mediator.cs#L63

You'd register your custom class over the `Mediator` class.

**Comment by GODBS** [comment]
Ah perfect! Thanks Jimmy.

**Comment by GFoley83** [comment]
Just ran into the same issue but with multiple `IRequestPostProcessor` handlers accessing an EntityFramework context. Similar to above, registering a custom `RequestPostProcessorBehavior` and overriding the `Handle` method to use `await` with `foreach` instead of `Task.WhenAll()`, solved the issue.
