### ISSUE TITLE
Autofac IAsyncRequestHandler not registered with Mediatr 3.0

### ISSUE THREAD

**Issue by maldworth** [jbogard/MediatR#123]
I'm getting an Autofac Error:

> MediatR.IRequestHandler`1[...] has not been registered

And this is when I want to use an IAsyncRequestHandler. If I switch it to IRequestHandler, it works. But I don't want it to be a synchronous handler.

It's very peculiar, because I couldn't reproduce it within the Mediatr source control, but I made a console application (.net 4.5.2), which reproduces the error here: https://github.com/maldworth/mediatr-bug

**Comment by szavoda** [comment]
Same issues with 3.0 version and SimpleInjector...

**Comment by remcoros** [comment]
When running? Or only during debug? I just sent this: https://github.com/jbogard/MediatR/pull/122

**Comment by jbogard** [comment]
I cloned and got this to run just fine. Added "Console.WriteLine" and got "Test Test"

**Comment by remcoros** [comment]
Switch to the non throwing version of the resolve function of your container as I did for ninject (Get > TryGet) so the debugger won't break on it. Or ignore the specific exception using VS exception/debug settings.

**Comment by jbogard** [comment]
Looks like a few of the examples need updating. I run through the rest, in the meantime switch your config to this:

```
builder.Register<SingleInstanceFactory>(ctx =>
{
    var c = ctx.Resolve<IComponentContext>();
    return t =>
    {
        object o;
        return c.TryResolve(t, out o) ? o : null;
    };
});
```

**Comment by jbogard** [comment]
@szavoda looks like SimpleInjector is something else. updating now...

**Comment by maldworth** [comment]
Yep you guys got it for Autofac. That did the trick 👍

**Comment by jbogard** [comment]
@szavoda I just pushed the update to SimpleInjector.
