### ISSUE TITLE
Publishing collection of INotifications

### ISSUE THREAD

**Issue by jblackburn21** [jbogard/MediatR#124]
In v2.1 I was able to loop through a collection of INotifications and publish the events since it used `var notificationType = notification.GetType();` to determine the exact notification type of the handlers to execute.  In v3, it uses `var notificationType = typeof(TNotification);`, which causes it to look for handlers that implement IAsyncNotificationHandler<INotification>.  Can this be changed back to the original behavior?

**Comment by jbogard** [comment]
Not sure what the problem is, do you have a snippet that shows the bad behavior? I want to write a test for this and I'm not sure what I'm aiming for.

**Comment by jblackburn21** [comment]
Here is a variation of the unit test.  I collect a list of events and then publish them at the end of my process, so the list could contain different types.

```
[Fact]
        public async Task Should_resolve_handler_for_list_of_generic_notifications()
        {
            var builder = new StringBuilder();
            var writer = new StringWriter(builder);

            var container = new Container(cfg =>
            {
                cfg.Scan(scanner =>
                {
                    scanner.AssemblyContainingType(typeof(AsyncPublishTests));
                    scanner.IncludeNamespaceContainingType<Ping>();
                    scanner.WithDefaultConventions();
                    scanner.AddAllTypesOf(typeof(IAsyncNotificationHandler<>));
                });
                cfg.For<TextWriter>().Use(writer);
                cfg.For<IMediator>().Use<Mediator>();
                cfg.For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
                cfg.For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));
            });

            var mediator = container.GetInstance<IMediator>();

            var pings = new List<INotification>()
            {
                new Ping {Message = "Ping"}
            };

            foreach (var ping in pings)
            {
                await mediator.Publish(ping);
            }

            var result = builder.ToString().Split(new[] { Environment.NewLine }, StringSplitOptions.None);
            result.ShouldContain("Ping Pong");
        }
```

**Comment by jbogard** [comment]
Ah, makes sense.

**Comment by jblackburn21** [comment]
I was able to get it to work by adding the handler wrappers back in.  Let me know what you think.

https://github.com/jbogard/MediatR/compare/master...jblackburn21:feature/NotificationHandlerWrapper?expand=1

Also, thanks for fixing my other issue.  I was able to verify it after I got this working.

**Comment by remcoros** [comment]
I am running into this as well when dynamically publishing notifications.

I added a failing test here: https://github.com/remcoros/MediatR/commit/244659d8e8392508368a00b4d49f318bf13b5569

Note that it publishes using the notification base type like this:

```csharp
INotification ping = new Ping()
mediatr.Publish(ping);
```

As @jblackburn21 said, this is because typeof(TNotification) is used instead of notification.GetType() as the notification type.
