### ISSUE TITLE
GetHandlerFactory (from RequestHandler) is not cached

### ISSUE THREAD

**Issue by remcoros** [jbogard/MediatR#126]
When working on a fix for #124 I noticed the following in https://github.com/jbogard/MediatR/blob/master/src/MediatR/Internal/RequestHandler.cs#L63

Because 'initialized' is a local variable (and false), GetHandlerFactory is always called and _handlerFactory  re-instantiated. Basically making this dead code.

It is probably intended to be a cache, and the 'initialized' should be moved to a private field.

But... this introduces a possible problem with the (static) handler cache. Currently, RequestHandlerImpl is cached in a static dictionary. So when the handler factory is also cached. I loose the ability to dynamically re-bind handlers in the container during runtime.

For example, I have RequestHandlerFor&lt;Ping&gt; and I want to re-bind (at runtime) it to AsyncRequestHandlerFor&lt;Ping&gt;.

At the moment, this works, but that is a side-effect of the handler factory cache not working.

You can test/debug this by setting a breakpoint on GetHandlerFactory and change SendTests to call 'Send' multiple times.

Possible solutions:
- Make the handler factory cache work by moving 'initialized' to a private field and make the ConcurrentDictionary caches in Mediatr.cs non-static, so that we can re-initialize a new Mediatr instance in our container when re-binding handlers. https://github.com/jbogard/MediatR/compare/master...remcoros:fix-126-non_static_requestwrapper_cache?expand=1
- Remove the handler factory cache and just try to resolve the correct handler from the container on each send. (like notifications). https://github.com/jbogard/MediatR/compare/master...remcoros:fix-126-remove_factory_cache?expand=1

I would prefer option 2, let me know what you think.

**Comment by jbogard** [comment]
So the reason I put the cache in is that I wanted to memoize which handler I needed to instantiate. But if the cache isn't even used lol

**Comment by remcoros** [comment]
@jbogard If the handler is cached, it does mean that it's impossible to switch handlers trough the container during runtime.

For example:
Unbind(IRequestHandler<Ping>)
Bind(IAsyncRequestHandler<Ping>)
("Rebind" in ninject)

This is a highly unlikely scenario, but we do some funky stuff with Ninject and plugins where plugins can override each others implementation. Ie. plugin1 provides a handler, plugin2 overrides the handler.

Currently, we don't use mediatr handlers here. But we most likely will in the future. 

I'd prefer having the cache localized to the Mediator instance (instead of static). Or no cache at all (like how resolving notification handlers work).

Can you have a look at the two proposed fixes? Let me know if I need to sent a MR for one of them
