### ISSUE TITLE
Create a Logo!

### ISSUE THREAD

**Issue by ChrisMissal** [jbogard/MediatR#13]
Because every project should have a logo.

MediatR lets developers create "an object that encapsulates how a series of objects interact". This can be one-to-one or one-to-many. Things we talked about as part of a design were:

- Arrows into, and one or more arrows, out of something.
- It could be thought of kind of like a phone switchboard.
- Probably doesn't need the name in the logo
- Should look nice as a square (for GitHub, and [NuGet](http://www.nuget.org/packages/mediatr) )
- Should scale for both large (128x128) and small (32x32)

Anything else that would be valuable to know?

**Comment by JoeMighty** [comment]
I'm happy to take a stab at this one. Any idea of what you'd like?

**Comment by ChrisMissal** [comment]
Sorry for the delay @una, and thanks for the interest @JoeMighty. I'll update the issue description with some background on what it does and what @jbogard and I (and others) were tossing around the office yesterday and today.

**Comment by una** [comment]
Can you give an example of how MediatR is used?

**Comment by meixger** [comment]
@una please see https://github.com/jbogard/MediatR/issues/8 and http://lostechies.com/jimmybogard/2013/12/19/put-your-controllers-on-a-diet-posts-and-commands/

**Comment by JoeMighty** [comment]
How about something along the lines of this?

![mediatr](https://cloud.githubusercontent.com/assets/1237341/5810026/a811950c-a037-11e4-8a4f-d67ce6e108cc.png)

**Comment by jbogard** [comment]
That's actually pretty rad, here's my first crappy version from a powerpoint diagram:

![picture20](https://cloud.githubusercontent.com/assets/104498/5818058/907e3a72-a077-11e4-89b7-8afe4f545f0d.png)

But that one's waaaaay better

**Comment by jbogard** [comment]
By "that one" I mean @JoeMighty in case that wasn't completely obvious.

**Comment by JoeMighty** [comment]
Thank you, I'm glad you're happy with it. Are there any changes you'd like to make to it? (colour etc). If not then I can put together a few versions and sizes if you like.

**Comment by ByteBlast** [comment]
Nice work @JoeMighty.

**Comment by khalidabuhakmeh** [comment]
:+1: @JoeMighty

**Comment by una** [comment]
Ok I quickly put some things together :)

A) Connections, the MediatR "M"
![mediatr1](https://cloud.githubusercontent.com/assets/1693164/5846544/00d5982a-a18a-11e4-8f2b-983297b983cc.png)

B) A more abstract "M", "holding together" the Geodes (this can be colorized) <-- I like this one more
![mediatr2](https://cloud.githubusercontent.com/assets/1693164/5846557/1eb32178-a18a-11e4-85e4-ed305bfe78bd.png)

**Comment by ByteBlast** [comment]
Wow. Really good work @una! I think your logo is very symbolic and the second version looks especially great too!

**Comment by una** [comment]
![mediatr3](https://cloud.githubusercontent.com/assets/1693164/5846774/3df8fbaa-a18c-11e4-93ba-bfeb4a411281.png)

**Comment by ChrisMissal** [comment]
Nice! I'm really digging this one:
![image](https://cloud.githubusercontent.com/assets/67798/5848178/4cd1bc0c-a19b-11e4-96f5-7152ccc5025a.png)

**Comment by akamud** [comment]
I loved the simplicity in @JoeMighty version

**Comment by kebin** [comment]
@una <https://github.com/una> those are awesome! I love "A". May be add in
colors to represent notification vs request!

**Comment by jbogard** [comment]
So NuGet guidelines specify that an icon needs to be 128x128, *however*, in some places this icon is scaled down to 32x32. Unfortunately, I can't specify multiple icon files so anything I go with has to look good both big and small. Does that affect the design @una @JoeMighty ?

**Comment by akamud** [comment]
From my experience with a recent icon I made for a nuget package, anything with round corners that looks crispy in high res will look bad in low res (like the NuGet package manager window).

I don't know if there is a way to solve this.

**Comment by ChrisMissal** [comment]
Bump :)

**Comment by una** [comment]
![mediatr2](https://cloud.githubusercontent.com/assets/1693164/5970818/74a828c4-a7fe-11e4-90be-1771c1032c93.png)

**Comment by JoeMighty** [comment]
I'll put together some smaller version this evening so you can see what they're like.

**Comment by JoeMighty** [comment]
Here we go, here's the logo in various sizes and also plays well in plainer colours and solid black to take into consideration printed instances.

![mediatr2](https://cloud.githubusercontent.com/assets/1237341/5986141/03c8eb90-a8e7-11e4-8581-b3e5ad440bac.png)

**Comment by una** [comment]
I do really like that concept @joemighty

**Comment by JoeMighty** [comment]
Thank you @una, as I do yours. I particularly like the 'M' connections logos.

**Comment by ChrisMissal** [comment]
For the record, I like them all... except @jbogard's. No offense Jimmy.

Alright, which one wins? I think it's close, but based on responses, it feels like @JoeMighty has the edge. Can others please verify?

_It's okay, I'm used to this, I vote Democrat in Texas..._

**Comment by eddiegroves** [comment]
+1 @JoeMighty's second plainer coloured logo

**Comment by ChrisMissal** [comment]
@JoeMighty can you upload the logo files in an /assets folder? After that I can take care of getting it added to the NuGet package. As soon as whatever files you have are merged in, I'll mark this issue as closed.

**Comment by JoeMighty** [comment]
Will do! I'll get it done over the weekend.

**Comment by ChrisMissal** [comment]
Hey @JoeMighty, any progress on that?

**Comment by JoeMighty** [comment]
Yes, sorry for the delay in this. I've created a pull request (https://github.com/jbogard/MediatR/pull/25)

**Comment by ChrisMissal** [comment]
Thanks @JoeMighty!
