### ISSUE TITLE
How to work with generic handlers?

### ISSUE THREAD

**Issue by JCKodel** [jbogard/MediatR#131]
public class ListItemsRequestHandler<T> : IAsyncRequestHandler<ListItemsRequest<T>, ReadOnlyCollection<T>>
	{
		public Task<ReadOnlyCollection<T>> Handle(ListItemsRequest<T> message)
		{
			return Task.FromResult(new ReadOnlyCollection<T>(new T[] { }));
		}
	}

Then,

    var message = new ListItemsRequest<UserGroup>();
    var model = await Mediator.Send(message); // model is a ReadOnlyCollection<UserGroup>

**Comment by jbogard** [comment]
Hmmmmm....I think this will depend on your container. What are you using?

**Comment by JCKodel** [comment]
.net Core, but it is bugged =\ The handler is being initialized twice =\ (https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/issues/3 )

**Comment by thiagomajesk** [comment]
@jbogard, @JCKodel 

Any updates on this or https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/issues/3?
AFAIK .NET Core container untill 1.X could not work with that. What is the recommended approach nowadays?

**Comment by jbogard** [comment]
The handler getting instantiated twice? That's been fixed in 4.0.

**Comment by thiagomajesk** [comment]
@jbogard Oh, sorry, I should have been clearer - I'm talking about generic handlers.
My perception is that in the end is about the container support. Since I couldn't find reliable information on the current state of this I wanted an quick update.

**Comment by jbogard** [comment]
Oh sure! https://github.com/jbogard/MediatR/wiki/Container-Feature-Support

**Comment by thiagomajesk** [comment]
@jbogard I'm aware of this table 😄. 
What is the feature on the table that translates to generic handler support though?

**Comment by jbogard** [comment]
It's not really in the tests, but that's a partially closed generic type.
That isn't supported in ASP.NET Core DI, where you have to dig into the
generic parameters to close them first, then walk back up.
