### ISSUE TITLE
IAsyncRequestHandler resolved as IRequestHandler when using mediator.Send?

### ISSUE THREAD

**Issue by mdmoura** [jbogard/MediatR#135]
I updated a working AspNetCore 1.1 project from MediatR 2 to MediatR 3. I am using Scrutor:

      services.AddScoped<SingleInstanceFactory>(x => y => x.GetRequiredService(y));
      services.AddScoped<MultiInstanceFactory>(x => y => x.GetRequiredServices(y));

      services
        .Scan(x =>
          x.FromAssembliesOf(typeof(IMediator), typeof(Startup))
            .AddClasses(y => y.AssignableTo(typeof(IMediator))).AsImplementedInterfaces().WithScopedLifetime()            
            .AddClasses(y => y.AssignableTo(typeof(IRequestHandler<,>))).AsImplementedInterfaces().WithScopedLifetime()            
            .AddClasses(y => y.AssignableTo(typeof(IAsyncRequestHandler<,>))).AsImplementedInterfaces().WithScopedLifetime()
            .AddClasses(y => y.AssignableTo(typeof(INotificationHandler<>))).AsImplementedInterfaces().WithScopedLifetime()
            .AddClasses(y => y.AssignableTo(typeof(IAsyncNotificationHandler<>))).AsImplementedInterfaces().WithScopedLifetime());

Then I had the following model:

    public class GetProductsApiModel {
      public class Query : IRequest<Reply> { }
      public class Reply { 
         // Reply properties
      }
    }

And the Handler:

    public class  GetProductsApiModelHandler {

      public class QueryHandler : IAsyncRequestHandler<GetProductsApiModel.Query,  GetProductsApiModel.Reply> {
        public QueryHandler() {
        }
        public async Task<GetProductsApiModel.Reply> Handle(GetProductsApiModel.Query query) {
            // Handler code
        }
      }
    }

I then tried the following in Startup:

    var a = applicationBuilder.ApplicationServices.GetRequiredService<IAsyncRequestHandler< GetProductsApiModel.Query,  GetProductsApiModel.Reply>>();

With this I get the Handler but when I use the mediator on a controller:

      GetProductsApiModel.Query query = newGetProductsApiModel.Query();

      GetProductsApiModel.Reply reply = await _mediator.Send(query);

I get the following error:

    "No service for type 'MediatR.IRequestHandler`2[GetProductsApiModel+Query,
    GetProductsApiModel+Reply]' has been registered."

It seems it is looking for a IRequestHandler but it should look for a IAsyncRequestHandler.

In my code I changed `IAsyncRequest` to `IRequest` and `mediator.SendAsync` to `mediator.Send` because those where changes in MediatR 3, right?

Am I missing something here?

**Comment by remcoros** [comment]
Try to use "GetService" instead of "GetRequiredService" for the SingleInstanceFactory.

Mediator 3 tries to resolve all three variants (sync/async/cancellable). So use the non-throwing version "GetService" of your container to resolve components.

**Comment by mdmoura** [comment]
@remcoros That solved it ... Thanks!
