### ISSUE TITLE
Handler gets instantiated twice

### ISSUE THREAD

**Issue by P14x** [jbogard/MediatR#136]
Hi,

I'm using Autofac and see the constructor of my Handler being executed twice.
The Autofac sample in this repo shows the same behaviour.

I could track this to the RequestHandlerImpl class.
With the changes as in this [gist](https://gist.github.com/P14x/55d9e91e87899103dfa9cd797617a71c)
(lines 38,44,49,55,56,61,67,68) this behaviour disappeared.

Do these changes make sense?
Thanks

**Comment by adamhathcock** [comment]
I see the same thing with AutoFac.  Haven't investigated further on my end.

**Comment by P14x** [comment]
Same issue with Ninject and Simple Injector, but StructureMap and Windsor work fine.

**Comment by jbogard** [comment]
This only happens the first time you instantiate a handler, as MediatR needs to "check" to see if a handler can be created or not. But I don't cache that handler instance as you do in the gist as that means that the instance you created will be used every single time.

**Comment by P14x** [comment]
Hi Jimmy, thanks for your feedback.

I see the double instantiation also for each subsequent request for a handler instance in my ASP.NET MVC application and also in the Autofac sample.

If I understand you correctly, a first call to Runner.Run as here below would do a double instantiation for the check, but the second Runner.Run call would result in only one handler constructor call.

With Autofac, there's always a double instantiation.


        public static void Main(string[] args)
        {
            var mediator = BuildMediator();

            Runner.Run(mediator, Console.Out).Wait();
            Runner.Run(mediator, Console.Out).Wait();

            Console.ReadKey();
        }

**Comment by P14x** [comment]
Passing a Boolean instance field to LazyInitializer.EnsureInitialized instead of a local function variable as in this [gist](https://gist.github.com/P14x/ac14f308087da7c100419e3b89a02f9c) results into the behaviour you explain; a double instantiation once, a single one for subsequent calls.

**Comment by plioi** [comment]
FWIW, I can reproduce the double instantiation as well, on all web requests rather than only the first one.

In each web request, the two constructions follow this pattern:

During the first construction, my call stack includes a line, "System.Threading.LazyInitializer.EnsureInitializedCore...".
During the second 'real' construction, the call stack does not have that line.

**Comment by Andrew-Brad** [comment]
I'm experiencing the same issue as P14x (constructor called twice) in my AspNet Core web API - no additional IoC container, just vanilla Asp.Net services registration.  I've tried a couple variations on service registration methods for Mediatr, but nothing seems to have an impact.  I'm currently in the midst of VS 2017 project migrations, so I'll have to see about posting a project repo to reproduce.

**Comment by P14x** [comment]
The issue is within the call to the LazyInitializer.EnsureInitialized;
this overload uses the ref boolean argument to determine whether the target has already been initialized.

var initialized = false;  
LazyInitializer.EnsureInitialized(ref _handlerFactory, ref initialized, ref _syncLock, 
    () => GetHandlerFactory(t => GetHandler(t, factory))); 

Because a local function variable with value false is being passed in,
the factory is being executed each time, even when the the _handleFactory is not null.
Refactoring this variable to a field resolves the issue, see the gist in my previous post.

**Comment by jbogard** [comment]
Fixed by #148
