### ISSUE TITLE
MediatR in a console project

### ISSUE THREAD

**Issue by grokky1** [jbogard/MediatR#145]
Can MediatR run in a console project?

We have some console projects (auditing, seeding, measurements, etc.) which interact with our main (web app) system. I'd like to put MediatR in there as it would make everything much cleaner.

I assume it's technically possible, but need a pointer for where I should start? All the docs cover ASP.NET and the various DI containers, which don't exist in a console project.

**Comment by adamhathcock** [comment]
you can create `ServiceCollection` and call `Build` manually when using the ASP.NET Core ID.  You don't need to use the ASP.NET Core hosting to use .NET Core.

I use the hosting but just don't have a web server like:
```
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseServer(new NullServer())
        .UseStartup<Startup>()
        .UseEnvironment(ProcessConfiguration.GetEnvironment())
        .Build();

    host.Run();
}
```

**Comment by grokky1** [comment]
@adamhathcock So I fully understand you.

- setup the way you've shown, which looks like a web app, but doesn't have web stuff or a server
- include normal MediatR DI registration in the Startup class
- get MediatR reference: `host.Services.GetService(typeof(IMediator))`
- run the rest of my console project's stuff

**Comment by adamhathcock** [comment]
first two steps are right.

For the classes you want to use `IMediator` just have it injected in the constructor like the controllers in the ASP.NET Core samples.

I guess if you want to use `IMediator` from the start up class you have to do what you said.

**Comment by grokky1** [comment]
@adamhathcock Okay that's an interesting idea. Though that means the console app's "stuff" would run in the webhost, basically in a loop. Which means it'll need to be event driven, or something.

So for a "regular" console app (do something then exit), I could do it my way. But for one that loops without terminating, I'd do it your way.

Very neat! Thanks.

**Comment by grokky1** [comment]
For anyone who needs it, I implemented `NullServer` like this:

    public class NullServer : IServer {
        public void Start<TContext>(IHttpApplication<TContext> application) { }
        public void Dispose() { }
        public IFeatureCollection Features { get { return new FeatureCollection(); } }
    }

**Comment by grokky1** [comment]
Unfortunately, this actually doesn't seem to work. I'm reopening for now.

I have two projects, (1) a web app with all my commands, handlers, pipelines, etc., and (2) a console app which refers to the web app, and uses MediatR.

I've registered the stuff as usual: 

    services.AddMediatR(typeof(MyType));

where `MyType` is a type in the main app, so it scans the correct assembly.

But, when running the console app, and doing a simple `mediator.Send(myFooCommand)`, it fails with:

    Unhandled Exception: System.InvalidOperationException: Handler was not found for request
    of type FooCommand. Container or service locator not configured properly or handlers not
    registered with your container.

Which means that the assembly scan doesn't work as expected, if the handlers are in a different assembly. I think?!

Not sure if this is my config, or a bug, or by design.
