### ISSUE TITLE
PipelineBehaviour for all Requests

### ISSUE THREAD

**Issue by endeffects** [jbogard/MediatR#146]
Hi,

i'm new to MediatR and i tried to create a validation behavior for all my requests (commands and queries). But the example i've found works for queries only. So the question is, do i have to implement all behaviours twice?

```
public class ValidationBehaviour<TRequest, TResponse> : IPipelineBehaviour<TRequest, TResponse> where TRequest : IRequest<TResponse>
    {
        private readonly IEnumerable<IValidator<TRequest>> validators;

        public ValidationBehaviour( IEnumerable<IValidator<TRequest>> validators )
        {
            if (validators == null)
            {
                throw new ArgumentNullException(nameof(validators));
            }

            this.validators = validators;
        }

        public Task<TResponse> Handle( TRequest request, RequestHandlerDelegate<TResponse> next )
        {
            var context = new ValidationContext( request );

            var failures = this.validators.Select( v => v.Validate( context ) ).SelectMany( result => result.Errors ).Where( f => f != null ).ToList();

            if( failures.Any() )
            {
                throw new ValidationException( failures );
            }

            return next();
        }
    }
```

**Comment by jbogard** [comment]
It only works for queries? Why?

For commands that don't return a response, TResponse is Unit.

**Comment by endeffects** [comment]
I have a command handler like:

```
public class AddCustomerHandler : **IRequestHandler<AddCustomerRequest>**
{ }
```

and a command request

```
public class AddCustomerRequest : **IRequest**
{ }
```

but the validation behaviour above gets fired only for handlers and requests that explicit define a return type. So i wonder if i do something wrong in my autofac wire up or if this is not possible at all.

**Comment by endeffects** [comment]
I tried some more things out and the only version that works with the current MediatR implementation is by changing the generic types of the behaviour.

```
public class ValidationBehaviour<TRequest, Unit> : IPipelineBehaviour<TRequest, Unit> 
{ }
```

But here the type Unit hide the type Unit. So a better solution would be something like:

```
public class ValidationBehaviour<TRequest> : IPipelineBehaviour<TRequest, Unit> 
{ }
```

But for a Queries i run into the Pipeline Builder for Handlers with Response Types. So the question is, do we miss here the Void Behaviour Pipelines? From my point we should retrieve them at this point also.
```
private static Task<TResponse> GetPipeline(TRequest request, RequestHandlerDelegate<TResponse> invokeHandler, MultiInstanceFactory factory)
        {
            var behaviours = factory(typeof(IPipelineBehaviour<TRequest, TResponse>)).Cast<IPipelineBehaviour<TRequest, TResponse>>().Reverse();

            var aggregate = behaviours.Aggregate(invokeHandler, (next, pipeline) => () => pipeline.Handle(request, next));

            return aggregate();
        }
```

**Comment by grokky1** [comment]
Your original sample looks identical to what I'm using, and I don't have the problem you've described. Maybe double check your container config?

**Comment by endeffects** [comment]
Well i checked this various times, but i have no clue what's wrong with it.

I'm wire up the base container:

```
            builder.RegisterSource( new ContravariantRegistrationSource() );                                   
            builder.RegisterType<ApplicationService>().As<IApplicationService>().InstancePerRequest();         

            builder.Register<SingleInstanceFactory>( ctx =>
            {
                object o;

                var c = ctx.Resolve<IComponentContext>();
                return t => c.TryResolve( t, out o ) ? o : null;
            } );

            builder.Register<MultiInstanceFactory>( ctx =>
            {
                var c = ctx.Resolve<IComponentContext>();
                return t => ( IEnumerable<object> ) c.Resolve( typeof( IEnumerable<> ).MakeGenericType( t ) );
            } );
```

And additionally loading everything else:

Scanning for Handlers

```
            builder.RegisterAssemblyTypes( assemblies ).AsClosedTypesOf( typeof( IRequestHandler<> ) ).AsImplementedInterfaces().InstancePerRequest();
            builder.RegisterAssemblyTypes( assemblies ).AsClosedTypesOf( typeof( IRequestHandler<,> ) ).AsImplementedInterfaces().InstancePerRequest();
```

Adding Pipeline

`builder.RegisterGeneric( typeof( ValidationBehaviour<,> ) ).AsImplementedInterfaces();`

**Comment by jbogard** [comment]
In your validation behavior, do you need that generic constraint? The underlying pipeline behavior definition does not have that constraint.

**Comment by michielrutting** [comment]
That looks like it could very well be the culprit. 

Since version 3.0.0 with pipelines landed I just registered the built-in pre-processor behavior and implemented validation (and authorization) in IRequestPreProcessors instead of decoratiors/behaviors. Although mine only expects only one IValidator.
```C#
/// <summary>
/// A pre-processor that validates a request.
/// </summary>
/// <typeparam name="TRequest">Request type</typeparam>
public class ValidationRequestPreProcessor<TRequest> : IRequestPreProcessor<TRequest>
{
    private readonly IValidator<TRequest> validator;

    /// <summary>
    /// Initializes a new instance of the ValidationRequestPreProcessor class.
    /// </summary>
    /// <param name="validator">the validator</param>
    public ValidationRequestPreProcessor(IValidator<TRequest> validator)
    {
        this.validator = validator 
            ?? throw new ArgumentNullException(nameof(validator));
    }

    public Task Process(TRequest request)
    {
        return validator.ValidateAndThrowAsync(request);
    }
}
```

**Comment by endeffects** [comment]
I tried to use the PreProcessor also, but it seems like that it can't be used as standalone solution. They have to be injected into the RequestHandlers. But that's not what i need.

**Comment by jbogard** [comment]
You've defined a generic constraint on your validator. Don't. The `where TRequest : IRequest<TResponse>`. Don't do that, the underlying interface doesn't have that, I don't think you should either.

**Comment by endeffects** [comment]
Thanks for your help. I got it working now with the PreRequestProcessor. I found out that i forgot to register the RequestPreProcessorBehaviour. How everything works as expected. 

I have to say that i really like your MediatR library, but it is really hard to find some documentation and examples beyond the standard. Maybe you can improve this in the future. :)

**Comment by jbogard** [comment]
The wiki is open for anyone to contribute.
