### ISSUE TITLE
Wiki guide for Autofac

### ISSUE THREAD

**Issue by grokky1** [jbogard/MediatR#150]
@jbogard Jimmy, I wanted to add [config for Autofac](https://github.com/jbogard/MediatR/wiki#autofac), so edited the wiki page thinking that it would send you a PR. But it did a live edit somehow! Never encountered that before!!

I guess you should review the security settings on your repo. 😆 

Anyway, please have a look and roll back if you don't like? All I did was add a section on Autofac integration, because there was lots of differing and conflicting code samples on SO, and we need a definitive guide.

**Comment by jbogard** [comment]
Anyone can edit the wiki, that's the beauty of it! Thanks for the edit!

I don't use AutoFac so 🤷‍♂️
