### ISSUE TITLE
Sending notifications from handlers

### ISSUE THREAD

**Issue by davidkeaveny** [jbogard/MediatR#153]
Is it possible to send a notification from within a handler? So for instance, I'm working on a handler that deals with the termination of a manager's employment, and need to handle any workflows that the manager may be currently working on, delegating them to another manager. I could probably do that using the pipeline, with a post-request handler for each workflow, but it seems like a minor perversion of the intent of the pipeline; and it would make more sense to publish a notification saying, "Reassign these workflows"

**Comment by jbogard** [comment]
Yes. Your handler can depend on IMediator and awaaaaaay we go.
