### ISSUE TITLE
Pipeline / Pre or Post Request Handler only for some specific  Domain events

### ISSUE THREAD

**Issue by shibukraj** [jbogard/MediatR#156]
Hi there,
Thanks for the great library and we are using this for one of our projects. So far every thing is working as expected. We came across a requirement and like to understand the best way to implement the same. Like to know how others have accomplished the similar requirements.

Requirement is as follows. We need to implement a profiling/ auditing for certain handlers only. Our initial thought was to implement as follows. 

public interface IMarkerInterface {}

public class DomainObject : IMarkerInterface {}

publi class OtherDomainObjects () {}

We expected to implement a behavior that get executed for each and every Request Object that implements the IMarkerInterface.

Is that the right way to do? We are using structure map and we were not successful so far in get this working? Does anyone has tried the same. Any suggestions ideas are greatly appreciated.

Thanks

**Comment by joaomatossilva** [comment]
Hi,

I don't think that is a contraint on MediatR itself, but more on a language specific contraint, of inheritance of interfaces on the generics (the Pre or Post Handlers). I don't think there is a way to configurate the container (structure map) to give you a open generic but just if the type enherites from another (I can be wrong).

What you could do instead, and it's not that far off your proprosal desing, in fact, I even think is a far more suitable one, is to declare some attributes.

Then you could create a PreHandler that is registered on every request that inspects the message object and applies the profiling / auditing you see fit.

**Comment by shibukraj** [comment]
Hi Joao

Thanks for the direction. We will proceed with the design/implementation as you suggested. I have a follow up question. Is there any performance overhead is calling the preHandler for every request. The reason we ask is we have some Pipeline behaviors which does logging of Request/Response for every handler, some pipeline for some cross cutting concerns. So wondering with structure map what is the performance penalty of having too many preHandlers. Just want to do what is best and the minimum.

Thanks

**Comment by joaomatossilva** [comment]
Yes. It will have the overhead of creating the instance (if it's an instance per request) and the check for the attribute present.

**Comment by joaomatossilva** [comment]
@shibukraj An update. 
With Autofac I was able to make your initial scenario, using `builder.RegisterSource(new ContravariantRegistrationSource());` 

With StructureMap I believe that can be acomplish also.
