### ISSUE TITLE
Handler gets lost

### ISSUE THREAD

**Issue by endeffects** [jbogard/MediatR#157]
I'm using the latest MediatR with Autofac and noticed some strange behaviours,
after a couple of hours some of my Handlers that worked before can not be found anymore.

Until i restart the IIS Process i'm getting the Invalid Operation Exception from the RequestHandler Class:
`InvalidOperationException("Handler was not found for request of type " + message.GetType() + ".\r\nContainer or service locator not configured properly or handlers not registered with your container.", innerException);`

I'm using the Autofac Wireup from the Examples
```
            //builder.RegisterSource( new ContravariantRegistrationSource() );  // Does not work for me                                 
            builder.RegisterType<MediatrR>().As<IMediatR>().InstancePerLifetimeScope();

            builder.Register<SingleInstanceFactory>(ctx =>
            {
                var c = ctx.Resolve<IComponentContext>();

                return t =>
                {
                    object o;
                    return c.TryResolve(t, out o) ? o : null;
                };

            }).InstancePerLifetimeScope();
                                         
            builder.Register<MultiInstanceFactory>(ctx =>
            {
                var c = ctx.Resolve<IComponentContext>();
                return t => (IEnumerable<object>) c.Resolve(typeof(IEnumerable<>).MakeGenericType(t));

            }).InstancePerLifetimeScope();
```

I'm not sure if this belongs to the fixed Handler Caching and the usage of:
`LazyInitializer.EnsureInitialized(..)`

But there is no other error recorded in my logs. Any Ideas?

**Comment by endeffects** [comment]
Ok, this seems to be an other problem.

**Comment by jbogard** [comment]
ha ok WHEW
