### ISSUE TITLE
I must be doing something wrong here

### ISSUE THREAD

**Issue by suddenelfilio** [jbogard/MediatR#160]
Okay I have

an interface IDomainEvents
` public interface IDomainEvent
    {
    }`

an interface IDomainEventHandler

`   public interface IDomainEventHandler<T> where T: IDomainEvent
    {
        void Handle(T args);
    }`

an event class
`    public class DataChangedEvent : IDomainEvent
    {
        public int Id { get; set; }

    }`

and my program

`  class Program
    {
        private static IContainer _container;

        static void Main(string[] args)
        {
            _container = ConfigureContainer();

            Console.WriteLine(_container.GetInstance<IDomainEventHandler<IDomainEvent>>() as DefaultEventsHandler<IDomainEvent> != null);
            Console.WriteLine(_container.GetInstance<IDomainEventHandler<DataChangedEvent>>() as DataEventHandler != null);
            Console.ReadLine();

        }

        private static IContainer ConfigureContainer()
        {
            return new Container(x =>
            {
                x.Scan(scanner =>
                {
                    scanner.TheCallingAssembly();
                    scanner.WithDefaultConventions();
                    scanner.ConnectImplementationsToTypesClosing(typeof(IDomainEventHandler<>));
                });
                x.For(typeof(IDomainEventHandler<>)).Use(typeof(DefaultEventsHandler<>));
            });
        }

        public class DefaultEventsHandler<T> : IDomainEventHandler<T> where T : IDomainEvent
        {
            public virtual void Handle(T args)
            {
                Console.ForegroundColor = ConsoleColor.Blue;
                Console.WriteLine(args.GetType().Name);
                Console.ResetColor();
            }
        }

        public class DataEventHandler : IDomainEventHandler<DataChangedEvent>
        {
            public void Handle(DataChangedEvent args)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine(args.Id);
                Console.ResetColor();
            }
        }
    }`

If i run this I would expect:

True
True

except I'm getting

True
False

so the closed type is not picked up here? Did I misunderstand this functionality?

**Comment by adamhathcock** [comment]
Isn't this an AutoFac (or whatever container that is) issue, not a MediatR one?

**Comment by suddenelfilio** [comment]
Idd i'm so in the wrong repo here... apologies...
