### ISSUE TITLE
Transient ViewModel

### ISSUE THREAD

**Issue by ruifaguiar** [jbogard/MediatR#161]
Hello, 
I am doing an application using Mediatr.
When i register a Transient ViewModel that implements a Handle from INotificationHandler<DoStuffDone>
the first time the publish is executed in a Handler, it creates a new instance of the ViewModel.
If i set the life cycle to Singleton it works correctly. 

Notice that the same viewmodel sends the command and has the subscription for the result.

I have a small sample at https://github.com/ruifaguiar/MediatrSample

**Comment by CaseNewmark** [comment]
How has this been solved ? I have the same issue even with singletons.
