### ISSUE TITLE
IRequestHandlers vs  INotificationHandler

### ISSUE THREAD

**Issue by cecilphillip** [jbogard/MediatR#163]
Please excuse my trivial question, but I'm a little unsure about the major differences between IRequestHandler<T&gt; and INotificationHandler<T&gt;.

The interface methods looks fairly similar.

-  INotificationHandler<T&gt; - [void Handle(TNotification notification);](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequestHandler.cs#L30)
- IRequestHandler<T&gt; - [void Handle(TRequest message);](https://github.com/jbogard/MediatR/blob/master/src/MediatR/INotificationHandler.cs#L14)

They also both seem applicable for fire & forget scenarios. When exactly would you use notifications over void returning requests? I'm probably missing something very blatant here.

**Comment by jbogard** [comment]
Requests are for:

1 request to 1 handler. Handler may or may not return a value

Notifications are for:

1 notification to n handlers. Handler may not return a value.

In practical terms, requests are "commands", notifications are "events".
Command would be directing MediatR to do something like
"ApproveInvoiceCommand -> ApproveInvoiceHandler". Event would be
notifications, like "InvoiceApprovedEvent ->
SendThankYouEmailToCustomerHandler"

HTH

**Comment by cecilphillip** [comment]
Gotcha. Thanks!
