### ISSUE TITLE
Update samples to register IRequestHandler<> and IAsyncRequestHandler<>

### ISSUE THREAD

**Issue by jmzagorski** [jbogard/MediatR#169]
I know this seems like a small thing, but it tripped me up in my coding daze...

I cloned your repository and changed to  `PingAsyncHandler` to not have a response (so it would be `IAsyncRequestHandler<PingAsync>`). I did this to try to reproduce an error I am getting in my app. Simpleinjector returns the error below:

`ActivationException: No registration for type IRequestHandler<PingAsync> could be found.`

Then I realized that the samples were not registering `IRequestHandler<>` and `IAsyncRequestHandler<>`. Maybe the samples should be updated? Just a thought.

**Comment by mcganesh5089** [comment]
Is mediatr4 replaced IAsyncRequestHandler from IRequestHandler and Does it cause any performance?
Is IRequestHandler an async method?
