### ISSUE TITLE
Synchronous .Send()?

### ISSUE THREAD

**Issue by jsodeman** [jbogard/MediatR#170]
In looking at Mediatr examples on the web, such as:

https://lostechies.com/jimmybogard/2015/01/20/integrating-mediatr-with-web-api/
https://jonhilton.net/2016/06/06/simplify-your-controllers-with-the-command-pattern-and-mediatr/
https://github.com/rmaziarka/MediatR.Examples

I see examples calling .Send() without using **await** or declaring the controller with **async**. Did this change in a version after these articles were written? When I try the same .Send() only returns a Task<> and the wiki says  

> From the IMediator side, the interface is async-only, designed for modern hosts.

I'm using Mediatr via Simple Injectory as per the Mediatr Simple Injectory wiki example.

**Comment by no1melman** [comment]
See https://github.com/jbogard/MediatR/commit/8f1033e7b26f411dcea04256c03aeb4f2c6a50f0 as it shows when this behaviour changed.

**Comment by jsodeman** [comment]
Thanks, that explains it. I guess it’s turtles all the way down now.
