### ISSUE TITLE
Registering pipeline behaviors problem

### ISSUE THREAD

**Issue by jsodeman** [jbogard/MediatR#172]
I'm struggling to get a validation pipeline working, I think I'm close but I'm getting the following back from Simple Injector. I'm using the latest versions of Mediatr, FluentValidation, and Simple Injector.

`No registration for type IEnumerable<IPipelineBehavior<MyRequest, MyResponse>> could be found.`

I've registered the pipeline using

`container.Register(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));`

and the docs say 

> MediatR uses the MultiInstanceFactory delegate to resolve the IEnumerable<IPipelineBehavior<TRequest, TResponse>> for whatever closed types your request and responses are.

The full set of related registrations is

```
var assemblies = GetAssemblies().ToArray();
container.RegisterSingleton<IMediator, Mediator>();
container.Register(typeof(IRequestHandler<,>), assemblies);
container.Register(typeof(IAsyncRequestHandler<,>), assemblies);
container.Register(typeof(IRequestHandler<>), assemblies);
container.Register(typeof(IAsyncRequestHandler<>), assemblies);
container.Register(typeof(ICancellableAsyncRequestHandler<>), assemblies);
container.RegisterCollection(typeof(INotificationHandler<>), assemblies);
container.RegisterCollection(typeof(IAsyncNotificationHandler<>), assemblies);
container.RegisterCollection(typeof(ICancellableAsyncNotificationHandler<>), assemblies);

container.RegisterSingleton(new SingleInstanceFactory(container.GetInstance));
container.RegisterSingleton(new MultiInstanceFactory(container.GetAllInstances));

container.Register(typeof(IValidator<>), assemblies);
container.RegisterConditional(typeof(IValidator<>), typeof(ValidateNothingDecorator<>), context => !context.Handled);
container.Register(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));
```

**Comment by michielrutting** [comment]
The SimpleInjector example uses the following code to register behaviors:
```
container.RegisterCollection(typeof(IPipelineBehavior<,>), new []
{
    typeof(RequestPreProcessorBehavior<,>),
    typeof(RequestPostProcessorBehavior<,>),
    typeof(GenericPipelineBehavior<,>)
});
```
So it could be this might work for you.

I settled for registering the built in RequestPreProcessorBehavior and then implemented my Validation in an IRequestPreProcessor<>, same for Authorization

**Comment by jsodeman** [comment]
Yep, I got it to work using

`container.RegisterCollection(typeof(IPipelineBehavior<,>), new[] { typeof(ValidationBehavior<,>) });`
