### ISSUE TITLE
IAsyncRequestHandler<TRequestType,ReturnType> not mapping in unity

### ISSUE THREAD

**Issue by HMousa1983** [jbogard/MediatR#175]
So when I have a Request and IAsyncRequestHandler<Request> things work very nicely. However, anytime I add a return type for the Request. For example, Request<bool> IAsyncRequestHandler<Request,bool> I get a unity mapping error saying the following:

InnerException	{"The current type, Epiq.OCR.Common.MediatR.IRequestHandler`2[Epiq.Workers.OCR.Application.OCR.OcrProcessorRequest,System.Int32], is an interface and cannot be constructed. Are you missing a type mapping?"}	System.Exception {System.InvalidOperationException}

Here's my Unity Config:

            container.RegisterType<IMediator,` Mediator>();
	        container.RegisterTypes(AllClasses.FromLoadedAssemblies());
	        container.RegisterTypes(AllClasses.FromAssemblies(typeof(OcrProcessorRequestHandler).Assembly),
	            WithMappings.FromAllInterfaces, MediatRSetupHelper.GetRequestName, MediatRSetupHelper.GetLifetimeManager);

            container.RegisterInstance<SingleInstanceFactory>(t => container.Resolve(t));
	        container.RegisterInstance<MultiInstanceFactory>(t => container.ResolveAll(t));

**Comment by jbogard** [comment]
I have no idea, I couldn't get Unity to completely work so I removed it from the list of samples.

**Comment by HMousa1983** [comment]
I have tried with SimpleInjector and still getting the same issue. I think for some reason it's passing MediatR.IRequestHandler`2 instead of MediatR.IAsyncRequestHandler`2. It's not a unity issue. It's an issue with the AsyncHandler implementation. 

The code below always returns the RequestHandler instead of the AsyncRequestHandler:

  private static Func<TRequest, CancellationToken, SingleInstanceFactory, RequestHandlerDelegate<TResponse>>
            GetHandlerFactory(SingleInstanceFactory factory, ref Collection<Exception> resolveExceptions)
        {
            if (GetHandler<IRequestHandler<TRequest, TResponse>>(factory, ref resolveExceptions) != null)
            {
                return (request, token, fac) => () =>
                {
                    var handler = GetHandler<IRequestHandler<TRequest, TResponse>>(fac);
                    return Task.FromResult(handler.Handle(request));
                };
            }

            if (GetHandler<IAsyncRequestHandler<TRequest, TResponse>>(factory, ref resolveExceptions) != null)
            {
                return (request, token, fac) =>
                {
                    var handler = GetHandler<IAsyncRequestHandler<TRequest, TResponse>>(fac);
                    return () => handler.Handle(request);
                };
            }

            if (GetHandler<ICancellableAsyncRequestHandler<TRequest, TResponse>>(factory, ref resolveExceptions) != null)
            {
                return (request, token, fac) =>
                {
                    var handler = GetHandler<ICancellableAsyncRequestHandler<TRequest, TResponse>>(fac);
                    return () => handler.Handle(request, token);
                };
            }

            return null;
        }

And here's my code:

public class EnqueueMessageRequest : IRequest<bool>
    {
        public string Key { get; set; }
        public string Message { get; set; }
        public Dictionary<string, string> Tags { get; set; }
    }

public class EnqueueMessageHandler:IAsyncRequestHandler<EnqueueMessageRequest,bool>
    {
        private readonly IMessageProducer _messageProducer;
        private readonly IMediator _mediator;

        public EnqueueMessageHandler(IMessageProducer messageProducer, IMediator mediator)
        {
            _messageProducer = messageProducer;
            _mediator = mediator;
        }

        public async Task<bool> Handle(EnqueueMessageRequest message)
        {
            await _messageProducer.EnqueueMessage(message.Key, message.Message, message.Tags);
            await _mediator.Publish(new StatusUpdateNotification()
            {
                Status = "Queued" 
            });
            return true;
        }
    }
