### ISSUE TITLE
Unity example for 3.0

### ISSUE THREAD

**Issue by JamesItSolutionsLtd** [jbogard/MediatR#178]
Unity example for 3.0

**Comment by furier** [comment]
👍

**Comment by jbogard** [comment]
Feel free to open a PR for a Unity example. I don't know Unity, so all the other samples are just people submitting PRs.

**Comment by no1melman** [comment]
Unity is dead now.....

**Comment by JamesItSolutionsLtd** [comment]
Doesn anyone have an example. all i have found elsewhere is for previous versions of MediatR

**Comment by furier** [comment]
Here is an example that works for me: https://gist.github.com/nojaf/a3f1c3fd2d8b924e64348d425c2e9285

**Comment by jbogard** [comment]
@furier can you open a pull request then? Just follow the examples of the other DI examples copy pasting it.

**Comment by furier** [comment]
@jbogard will do. :)

**Comment by furier** [comment]
Done! #183

**Comment by mpaul31** [comment]
struggling to get this to work with notification handlers. i'm seeing the type registered but my handler never hits. anyone get notifications wired up with unity?
