### ISSUE TITLE
Inconsistent dependency resolution results with Microsoft.Unity

### ISSUE THREAD

**Issue by furier** [jbogard/MediatR#180]
**I got the following code for registering all implementations of an interface, and registering Mediator stuff with the unity container.**

    public static class IUnityContainerExtensions
    {
        public static IUnityContainer RegisterMediator(this IUnityContainer container, LifetimeManager lifetimeManager)
        {
            container.RegisterType<IMediator, Mediator>(lifetimeManager);
            container.RegisterInstance<SingleInstanceFactory>(t => container.Resolve(t));
            container.RegisterInstance<MultiInstanceFactory>(t => container.ResolveAll(t));
            return container;
        }

        public static IUnityContainer RegisterMediatorHandlers(this IUnityContainer container, Assembly assembly)
        {
            container.RegisterTypesImplementingType(assembly, typeof(IRequestHandler<>));
            container.RegisterTypesImplementingType(assembly, typeof(IRequestHandler<,>));
            container.RegisterTypesImplementingType(assembly, typeof(IAsyncRequestHandler<>));
            container.RegisterTypesImplementingType(assembly, typeof(IAsyncRequestHandler<,>));
            return container;
        }

        public static IUnityContainer RegisterTypesImplementingType(this IUnityContainer container, Assembly assembly, Type type)
        {
            foreach (var implementation in assembly.GetTypes().Where(t => t.GetInterfaces().Any(implementation => IsSubclassOfRawGeneric(type, implementation))))
            {
                var interfaces = implementation.GetInterfaces();
                foreach (var @interface in interfaces)
                    container.RegisterType(@interface, implementation);
            }
            return container;
        }

        private static bool IsSubclassOfRawGeneric(Type generic, Type toCheck)
        {
            while (toCheck != null && toCheck != typeof(object))
            {
                var currentType = toCheck.IsGenericType ? toCheck.GetGenericTypeDefinition() : toCheck;
                if (generic == currentType)
                    return true;
                toCheck = toCheck.BaseType;
            }
            return false;
        }
    }

**Mediator resources**

    public class RequestModel : IRequest<string> { }

    public class RequestModelHandler : IAsyncRequestHandler<RequestModel, string>
    {
        public async Task<string> Handle(RequestModel message)
        {
            return ...;
        }
    }

**Unity container registration example**

    container
        .RegisterType<..., ...>()
        ...
        .RegisterMediator(new HierarchicalLifetimeManager())
        .RegisterMediatorHandlers(Assembly.GetExecutingAssembly());

> If I check everything registered with the unity container the `RequestModelHandler` is registered fine with the `IAsyncRequestHandler` interface.
> Keep in mind I have a mix of `IAsyncRequestHandler`s and `IRequestHandler`s

**Mediator usage example**

    public async Task<IHttpActionResult> HelloWorld()
    {
        return OK(await Mediator.Send(new RequestModel()));
    }

When calling `HelloWorld()` mediator tries to first resolve `IRequestHandler<RequestModel, string>` and gets a dependency resolution failed exception, which should be fine as none are registered.

Sometimes mediator goes on to try and resolve `IAsyncRequestHandler<RequestModel, string>` after failing with the sync request handler, succeeds and everything works just fine.

However other times the first exception bubbles all the way to the top and mediator never tries to resolve the async request handler, and I'm out of ideas. 

Have tried to look at the source code but much code to digest so I haven't figured out whats going on yet...

Any help please? :)

**Comment by jbogard** [comment]
I dropped the Unity sample because i couldn't get it to work. 🤷‍♂️

**Comment by furier** [comment]
@jbogard I created a [stackoverflow ](https://stackoverflow.com/questions/44822095/mediatr-failing-to-resolve-request-handlers-with-unity-and-structuremap) question and tried with structure map and got the same issue...

**Comment by furier** [comment]
seems like #181 is the same issue I am having.

**Comment by furier** [comment]
@jbogard I have found the problem and resolved it.

The error message received from MediatR is not exactly describing to the underlying error.

```
System.InvalidOperationException : Handler was not found for request of type IN.ServiceLayer.DocumentGeneratorV2.JsReport.MediatR.Requests.CreatePayoutPerformedDocumentRequest.
Container or service locator not configured properly or handlers not registered with your container.
   at MediatR.Internal.RequestHandlerImpl`2.GetHandler(TRequest request, CancellationToken cancellationToken, SingleInstanceFactory factory)
   at MediatR.Internal.RequestHandlerImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, SingleInstanceFactory singleFactory, MultiInstanceFactory multiFactory)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at IN.ServiceLayer.DocumentGeneratorV2.JsReport.Controllers.JsReportController.<CreateDocumentV2>d__3.MoveNext() in C:\dev\projects\innovasjon-norge\Develop\IN\IN.ServiceLayer.DocumentGeneratorV2\JsReport\Controllers\JsReportController.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IN.ServiceLayer.DocumentGeneratorV2.Tests.Integration.Controllers.JsReportControllerTests.<CreatePayoutPerformedDocumentAsync>d__8.MoveNext() in C:\dev\projects\innovasjon-norge\Develop\IN\IN.ServiceLayer.DocumentGeneratorV2.Tests.Integration\Controllers\JsReportControllerTests.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
```
This error occurred due to Unity not being able to resolve something deep in the dependency graph, and the error just being "swallowed". Fixing the issue, making Unity able to resolve all dependencies made MediatR able to get the Handler.

Why is the inner exception not populates with the actual error?

**Comment by jbogard** [comment]
Not sure?
