### ISSUE TITLE
Handler was not found for request of type MyClass+Command. Container or service locator not configured properly or handlers not registered with your container.

### ISSUE THREAD

**Issue by tjrobinson** [jbogard/MediatR#184]
I've got a strange issue which I can only reproduce when I deploy my site as an Azure Web App.

- MediatR 3.0.0
- ASP.NET Core 1.1.2 w/ .NET 4.6.2
- Azure Web App
- AutoMapper.Extensions.Microsoft.DependencyInjection 2.0.1
- MediatR.Extensions.Microsoft.DependencyInjection 2.0.0
- StructureMap.Microsoft.DependencyInjection 1.3.0
- StructureMap 4.5

I get this error in Azure:

`
InvalidOperationException
Handler was not found for request of type Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Command. Container or service locator not configured properly or handlers not registered with your container.`

Running locally from Visual Studio 2017 it works fine.

I've added some logging so I can check what's registered in the container (StructureMap).

```
foreach (var instanceRef in container.Model.AllInstances)
{
    Log.Information("Registered with container: {PluginType} {ReturnedType}", instanceRef.PluginType.FullName, instanceRef.ReturnedType.FullName);
}
```

This shows the following entries relevant to the above error (interestingly I get each one twice, whether locally or in Azure):

* Registered with container: MediatR.IAsyncRequestHandler`2[[Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Command, Empactis.Scheduler.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MediatR.Unit, MediatR, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]] Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Handler
* Registered with container: MediatR.IAsyncRequestHandler`2[[Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Command, Empactis.Scheduler.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MediatR.Unit, MediatR, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]] Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Handler

I've spent a few hours on this trying various things, cleaning environments, checking for config differences etc but nothing adds up.

Any help would be much appreciated.

I realise this probably doesn't contain all the information you need (as I don't know what the likely cause is) so let me know what other information would be helpful.

**Comment by tjrobinson** [comment]
Here's my registration for the handlers.

Worth mentioning that there are some handlers in the project that do work and get resolved, whereas this one `UpdateEvent.Command` and a couple of others don't.

```
    public class MediatRRegistry : Registry
    {
        public MediatRRegistry()
        {
            this.Scan(scanner =>
            {
                scanner.AssemblyContainingType<EventListQuery>();
                scanner.AssemblyContainingType<IMediator>();
                scanner.WithDefaultConventions();
                scanner.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>));
                scanner.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<,>));
                scanner.ConnectImplementationsToTypesClosing(typeof(ICancellableAsyncRequestHandler<,>));
                scanner.ConnectImplementationsToTypesClosing(typeof(INotificationHandler<>));
                scanner.ConnectImplementationsToTypesClosing(typeof(IAsyncNotificationHandler<>));
                scanner.ConnectImplementationsToTypesClosing(typeof(ICancellableAsyncNotificationHandler<>));
                scanner.ConnectImplementationsToTypesClosing(typeof(IValidator<>));
                scanner.ConnectImplementationsToTypesClosing(typeof(IAuthorizationRule<>));
            });
            For(typeof(IPipelineBehavior<,>)).Add(typeof(LoggingBehavior<,>));
            For(typeof(IPipelineBehavior<,>)).Add(typeof(AuthorizationBehavior<,>));
            For(typeof(IPipelineBehavior<,>)).Add(typeof(ValidatorBehavior<,>));
            For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
            For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));
            For<IMediator>().Use<Mediator>();
            
        }
    }
```

**Comment by tjrobinson** [comment]
This is cross-posted as https://github.com/structuremap/structuremap/issues/588 because I'm not sure whether it's a MediatR or a structuremap issue (or more likely just me doing something wrong).

**Comment by tjrobinson** [comment]
I think I've sorted this now. A dependency deep down in the dependency tree can't be resolved, causing the handler to not be able to be resolved. What was throwing me was the wording of the error making me focus on something specific to the handler rather than its dependencies.

**Comment by EliiseS** [comment]
How did you fix this? I have the same issue.

**Comment by tjrobinson** [comment]
@EliiseS I can't remember exactly but I think I removed dependencies on the handler until I found the one that was causing the error. Basically the problem was something not being set up properly, but the error message didn't make this obvious at first.

**Comment by EliiseS** [comment]
It's alright, upgrading to dotnet core 2.0 fixed the issue for me. You can see a more detailed explanation in the above ticket I referenced.
