### ISSUE TITLE
Unable to register IRequestPreProcessor

### ISSUE THREAD

**Issue by seroche** [jbogard/MediatR#185]
Bonjour!

I have been trying to register a dummy IRequestPreProcessor for the past few days in my asp.net core (.net core 1.1) application.

It seems `service.AddMediatr()` tries to load pre-processors automatically. 
> In my case, it fails and throws a `System.ArgumentException: 'Open generic service type 'MediatR.Pipeline.IRequestPreProcessor`1[TRequest]' requires registering an open generic implementation type.'` 

You may find below the details about my pre-processor:         
```
  public class SetTecTacClientIdPreProcessor : IRequestPreProcessor<RegisterUserCommand>
  {
     public async Task Process(RegisterUserCommand request) => await Task.FromResult(true);
  }
```

Here is the container configuration:
```
     // Pipeline engine used internally to simplify controllers
     services.AddMediatR();
     // Pre-processors
     // Registers command validator
     services.AddTransient(typeof(IValidator<RegisterUserCommand>), typeof(RegisterUserCommandValidator));

     // Registers generic behaviors
     services.AddTransient(typeof(IPipelineBehavior<,>), typeof(Pipeline<,>));
     services.AddTransient(typeof(IPipelineBehavior<,>), typeof(AuditBehavior<,>));
     services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));
     services.AddTransient(typeof(IPipelineBehavior<,>), typeof(RequestPreProcessorBehavior<,>));
```

Any idea on what is going on?

Thank you,
Seb

**Comment by jbogard** [comment]
Hmm, do you see anything different in this vs. the sample in the main repo?

**Comment by seroche** [comment]
I do see that you are expecting a generic pre/post processor declaration! I didn't miss that. But it means i need to declare my specialized PreProc like this?
```
public class RegisterUserCommandPreProcessor<TRequest> : IRequestPreProcessor<TRequest>
        where TRequest : RegisterUserCommand 
```

Thanks for your kind help :)
Seb
