### ISSUE TITLE
Trouble running a behavior for some Requests

### ISSUE THREAD

**Issue by JKSnd** [jbogard/MediatR#187]
Hi there,

In my projects, the MediatR library sits behind an adapter layer. It provides some small, additional functionality and insulates my projects from breaking changes to MediatR (super useful for upgrading to v3).

So I pulled the Pipeline tests from the MediatR repo and massaged them a bit to help me test my StructureMap registry for this adapter library.

It seems that the Ping/Pong pipeline hits all of the expected behaviors and pre/post processors, but the Zing/Zong pair does not.

[Here's a gist](https://gist.github.com/JKSnd/6de1ae5208d6649c88a98675e553a30e) with the structuremap registry and the tests as they stand (with the dependency on my abstraction removed and just using MediatR).

Please let me know if you can reproduce the issue using these files and what details I'm missing/mishandling.

Thanks

**Comment by jbogard** [comment]
Check out the latest example in the repo; it looks like it registers pre/post processors differently (explicitly).
