### ISSUE TITLE
MediatR 3.0.1 Cannot get IAsyncRequestHandler working

### ISSUE THREAD

**Issue by john1452** [jbogard/MediatR#189]
I am getting the following error message when executing IRequest with IAsyncRequestHandler. 

    System.InvalidOperationException: 'No service for type 'MediatR.IRequestHandler`2[TestProject.Domain.Requests.Users.CreateUserRequest,TestProject.Domain.Requests.Users.CreateUserResponse]' has been registered.'

This is how i register it in the startup class

    // Add framework services.
       services.AddMvc();                                                
       services.AddMediatR(typeof(CreateUserRequest).GetTypeInfo().Assembly);

CreateUserRequest and Response class

     public class CreateUserRequest : IRequest<CreateUserResponse>
        {
            public string EmailAddress { get; set; }
            public int OrganisationId { get; set; }
            public string Password { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

    public class CreateUserResponse
    {
        public int UserId { get; set; }
        public string EmailAddress { get; set; }

    }

Request handler class

    public class CreateUserRequestHandler : IAsyncRequestHandler<CreateUserRequest, CreateUserResponse>
        {
            private readonly UserManager<User> _userManager;
    
           
            public CreateUserRequestHandler()
            {
               
            }
    
            public async Task<CreateUserResponse> Handle(CreateUserRequest request)
            {
                //create the user and assign it to the organisation
                var user = new User
                {
                    Email = request.EmailAddress,
                    OrganisationUsers = new List<OrganisationUser> { new OrganisationUser { OrganisationId = request.OrganisationId } }
                };
    
                //create new user with password.
                await _userManager.CreateAsync(user, request.Password);
    
                //create response.
                var response = new CreateUserResponse{UserId = user.Id, EmailAddress = user.Email};
    
                return response;
            }

Controller class

     public class UserController : Controller
        {
            private readonly IMediator _mediator;
    
            public UserController(IMediator mediator)
            {
                _mediator = mediator;
            }
    
            [HttpPost]
            public async Task<CreateUserResponse> Post(CreateUserRequest request)
            {
                return await _mediator.Send(request);
            }
        }

the error occurs inside the controller class it does not hit the async request handler.

Is there anything wrong with the DI registration? I have looked at the examples but could not find anything specific to aspnet core.

**Comment by john1452** [comment]
Further to this, all previous version examples are using IAsyncRequest along with the IAsyncRequestHandler. But, IAsyncRequest is not available in 3.0.1. 

Previous version example: https://codeopinion.com/mediatr-behaviors/

Any help is appreciated.

**Comment by Jaxwood** [comment]
@john1452 is `CreateUserRequestHandler` located in the same assembly as `CreateUserRequest`?

**Comment by no1melman** [comment]
@john1452 `IAsyncRequest` was dropped and everything is just a `IRequest` and you define whether you wan't async handling or sync handling by picking the correct handler interface, `IAsyncRequestHandler` or `IRequestHandler`

**Comment by john1452** [comment]
@Jaxwood  yes, I have two projects. 1: .net core web api and a class library  the structure of the class library is the following:
Requests
  Users
     CreateUserRequest.cs
     CreateUserRequestHandler.cs
     CreateUserResponse.cs

@no1melman yes Indeed, but in my case I cannot get IRequest Working with IAsyncRequestHandler. I suspect a problem with version 3.0.1.

**Comment by john1452** [comment]
ok, I found how everyone can replicate the exception I am getting.

Go to "Exception Settings" in visual studio and make sure the "Common Language Runtime Exceptions" is ticked.

Next time you run your application you will receive the following exception if you were using AsyncHandler:

System.InvalidOperationException: 'No service for type 'MediatR.IRequestHandler`2[TestProject.Domain.Requests.Users.CreateUserRequest,TestProject.Domain.Requests.Users.CreateUserResponse]' has been registered.'

I suspect that Send() method first tries to find IRequestHandler object from DI . DI returns the error above and then looks for the AsyncHandler.

Should this exception be ignored?

**Comment by jbogard** [comment]
Yes.

**Comment by MisiM** [comment]
My issue was that I had the query request and the response model in the Domain project and the query hander in the BusinessLogic project.

**Comment by ergincelik** [comment]
You can use this code in the startup.cs
For example, there are 5 projects in your solution and you can use all of them

           public void ConfigureServices(IServiceCollection services)
          {
                 Assembly.GetEntryAssembly().GetReferencedAssemblies()
                                                                .Where(c => c.FullName.StartsWith("App.")).ToList()
                                                               .ForEach(c => Assembly.Load(c.FullName));
          }
