### ISSUE TITLE
Mediatr and Web API

### ISSUE THREAD

**Issue by jphamilton** [jbogard/MediatR#19]
Are there any known issues using Mediatr and StructureMap with Web API? We tried to run the  example from the Mediatr source on two different machines and are [getting an exception](https://gist.github.com/jphamilton/45de6e317db1ed6513aa)

**Comment by jbogard** [comment]
Not that I know of, I was able to run the sample without issues.

Then again, I didn't try to go to those help pages, I usually delete those things in real apps.

**Comment by jphamilton** [comment]
You don't get the exception until you hit the API link. Anyway, I guess I will try to figure out what's going on. I have a feeling it's just missing some initial configuration.

**Comment by ChrisMissal** [comment]
@jphamilton I'm using all three of those right now in an application with no problems. Can you share some of your code?

**Comment by jphamilton** [comment]
@ChrisMissal It's the sample code in Mediar. The StrucureMap/Web API example. We run it, click on the API link and get an exception. The weird thing is that dependency is working. I added ITest/Test and injected it into the HomeController.

**Comment by jphamilton** [comment]
Ok, I just realized my explanation is wonky here. ServiceLocatorProvider is never getting configured in the Web API example, which seems to prevent me from injecting IMediator into MVC controllers. Modify HomeController and you will see.

Adding the follow to the StructureMapMvc.cs does the trick:
var serviceLocatorProvider = new ServiceLocatorProvider(() => StructureMapDependencyScope);
container.Configure(cfg => cfg.For<ServiceLocatorProvider>().Use(serviceLocatorProvider));

Anyway, I was looking to this example to show me how all of these technologies fit together and now I understand. Thanks.

**Comment by jbogard** [comment]
So is there something wrong with the example?

**Comment by jphamilton** [comment]
Technically, no, from a purely Web API perspective. But from a MVC/Web API perspective, yes. Take the example and inject IMediator into HomeController, you will get the exception because the ServiceLocatorProvider is not configured (as it is in the other examples).

**Comment by jbogard** [comment]
Ah OK I gotcha. I'll update the example then.

**Comment by jbogard** [comment]
Updated to include an MVC sample

**Comment by vrs-rajkumarbapu** [comment]
Where is the MVC updated sample. can you please point out to me
