### ISSUE TITLE
Question: One notification handler for several types

### ISSUE THREAD

**Issue by jedielson** [jbogard/MediatR#190]
Hi,

I have these 3 types:
```
public abstract class DomainNotification : INotification
{
}
```
```
public abstract class FaliureDomainNotification : DomainNotification
{
}
```
```
public class ValidationErrorDomainNotification : FaliureDomainNotification
{
}
```

I'm using .net core and `MediatR.Extensions.Microsoft.DependencyInjection` package to register my handlers.

I want to have only one handler, for `FaliureDomainNotification` and when I publish any subtype of `FaliureDomainNotification` it calls this handler.

But it's not working, only if I create a specific handler for `ValidationErrorDomainNotification`.

The most stranger thing is that if I had both handlers, both are called,
But if I have only the `FaliureDomainNotification` handler, it's not called.

Is it possible?
am I doing something wrong?

**Comment by lilasquared** [comment]
@jedielson can you show the code that is registering your handlers?  I just tried your scenario with .net core / structuremap and publishing a notification of type `ValidationErrorDomainNotification` is picked up by an `INotificationHandler<FaliureDomainNotification>`

**Comment by jedielson** [comment]
Hi Thanks for your answer!

It's a call like
`services.AddMediatR(typeof(FaliureDomainNotification))`

As I said, I'm not using none third part container, just .Net Core and `MediatR.Extensions.Microsoft.DependencyInjection`

**Comment by lilasquared** [comment]
Do you have the ability to test this with a different container?  I am wondering if it is a bug in the actual extension and not with mediatr itself

**Comment by jedielson** [comment]
I'll try it. On a hurry here, but asap I'll send results!

Thanks for help!
