### ISSUE TITLE
How many levels of async is appropriate?

### ISSUE THREAD

**Issue by zhangb99** [jbogard/MediatR#195]
Trying to setup a new AspNetCore app here.  The controller can be async, so are error handling middleware and various filters.  Plus IAsyncRequestHandler, micro ORM's FetchAsync and async remote services calls ... 

Do I need async all the way to be truly effective?

**Comment by ardalis** [comment]
Async in C# tends to lead to "async all the way down" structures. So, yes, it's not unusual.

**Comment by zhangb99** [comment]
@ardalis That's an insanely fast response!  You must be multithreaded async head to toe!!

**Comment by ardalis** [comment]
Email alerts... also, async isn't all about speed so much as letting the proc do other things instead of just waiting. :)

**Comment by jbogard** [comment]
lol you replied to an async question nearly sync.

So what doesn't need to happen necessarily is that all methods be marked as
"async". If you can return a Task instead of awaiting, you should do that
instead because the async/await state machine isn't free.

**Comment by lilasquared** [comment]
@jbogard since mediator awaits all requests by default now, if I have a handler that is making a query to the database that might be long running, the application will treat that work as async even if it is a normal synchronous operation right?  Is the value of using async / await in the handler when you are going to be awaiting other asynchronous work?

**Comment by jbogard** [comment]
The benefit is not for the client, but for the server so that it doesn't
block that thread while waiting for I/O to complete.

**Comment by zhangb99** [comment]
> If you can return a Task instead of awaiting, you should do that
> instead because the async/await state machine isn't free.

You mean like this?

    public class MyController : BaseController  {
        public Task<List<string>> Get(MyRequest request) {
            _mediator.Send(request);

    public class MessageListHandler : IAsyncRequestHandler<MyRequest, List<string>> {
        public Task<List<string>> Handle(MyRequest request)  {
                return _database.FetchAsync<string>("MyQuery");

I read about it, sounds [eliding async/await](http://blog.stephencleary.com/2016/12/eliding-async-await.html) is not as simple as eliding async/await ...

And just found out IMediator is async only now.  What if the controller is synchronous?  Do I just return _mediator.Send(request).Result?  Or is there other preferred option?  Thanks.

**Comment by jbogard** [comment]
Don't make the controller synchronous :) just make it async.

**Comment by zhangb99** [comment]
That's what I end up doing.  And for WebApi, clients generated via swagger spec are all async anyway.  Thanks for the help.
