### ISSUE TITLE
Error with SimpleInjector

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [jbogard/MediatR#196]
1) Was trying to do simple request following configuration provided on SimpleInjector and get followinf error: 

` "No registration for type IPipelineBehavior<TestRequest, String> could be found. There is, however, a registration for IEnumerable<IPipelineBehavior<TestRequest, String>>; Did you mean to call GetAllInstances<IPipelineBehavior<TestRequest, String>>() or depend on IEnumerable<IPipelineBehavior<TestRequest, String>>?",`
`
however if I do not register it at all I got another error: 

`"ExceptionMessage": "No registration for type IEnumerable<IPipelineBehavior<TestRequest, String>> could be found.",`

```
 public class TestRequest : IRequest<string>
    {
        public string Test { get; set; }
    }

 public class TestHandler : IRequestHandler<TestRequest, string>
    {
        public string Handle(TestRequest request)
        {
            return "hello";
        }
    }
```

as far as i understand it is related to 

```
container.RegisterCollection(typeof(IPipelineBehavior<,>), new[]
            {
                typeof(RequestPreProcessorBehavior<,>),
                typeof(RequestPostProcessorBehavior<,>),
                typeof(IPipelineBehavior<,>)
            });
```

and i have found solution to use register instead of regsiterCollection but it would break idea that all behaviours should go through requests.

Any idea how to solve this?

my global.asax

```
private void RegisterMediatr(Container container)
        {
            var assemblies = GetAssemblies().ToArray();
            container.RegisterSingleton<IMediator, Mediator>();
            container.Register(typeof(IRequestHandler<,>), assemblies);
            container.Register(typeof(IAsyncRequestHandler<,>), assemblies);
            container.Register(typeof(IRequestHandler<>), assemblies);
            container.Register(typeof(IAsyncRequestHandler<>), assemblies);
            container.Register(typeof(ICancellableAsyncRequestHandler<>), assemblies);

            container.RegisterCollection(typeof(IPipelineBehavior<,>), new[]
            {
                typeof(RequestPreProcessorBehavior<,>),
                typeof(RequestPostProcessorBehavior<,>),
                typeof(IPipelineBehavior<,>)
            });

            container.RegisterCollection(typeof(IRequestPreProcessor<>), new[] { typeof(GenericRequestPreProcessor<>) });
            container.RegisterCollection(typeof(IRequestPostProcessor<,>), new[] { typeof(GenericRequestPostProcessor<,>) });

            container.RegisterSingleton(new SingleInstanceFactory(container.GetInstance));
            container.RegisterSingleton(new MultiInstanceFactory(container.GetAllInstances));
        }
```

2) What if I do not want to use pipes at all? as it looks from second error i should use them always?

3) I was able to get it work by replacing registerCollection provided in example with 
```
container.RegisterCollection(typeof(IPipelineBehavior<,>), assemblies);
```
But then what with 
```
 typeof(RequestPreProcessorBehavior<,>),
 typeof(RequestPostProcessorBehavior<,>),
 typeof(IPipelineBehavior<,>)
```

**Comment by jbogard** [comment]
So the exception you get is around not having anything registered? I'm not familiar with SimpleInjector.

**Comment by MAOliver** [comment]
This isn't a problem with mediatr, it's a problem with how you're registering depedencies in your IoC container.

I would suggest taking a look at (uses autofac) https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/ValidatorBehavior.cs 

And https://github.com/jbogard/MediatR/tree/master/samples/MediatR.Examples.SimpleInjector

I was able to modify the sample project to inject the same style of validator behavior in the console app example (though I have no way to handle the exception thrown other than a try/catch since I can't implement web filters).
