### ISSUE TITLE
How to register a custom IRequest/IRequestHandler interfaces without inheriting from MediatR interfaces?

### ISSUE THREAD

**Issue by ivanpaulovich** [jbogard/MediatR#198]
Hi people,

I would like to use a custom interface in my project for the pattern IRequest/IRequestHandler.
Currently my classes inherit from MediatR interfaces like this:

```
class DisableBlogCommand : IRequest { }
class DisableBlogCommandHandler : IRequestHandler<DisableBlogCommand> { }
```

I was wondering if is possible to use something this way without inheriting from MediatR:

```
class DisableBlogCommand : ICommand { }
class DisableBlogCommandHandler : ICommandHandler<DisableBlogCommand> { }
class DisableBlogDomainEvent : IDomainEvent { }
class DisableBlogCommandHandler : IDomainEventHandler<DisableBlogDomainEvent> { }
```

**Comment by jbogard** [comment]
Yeah you can just copy the code and make up your own interfaces really.

**Comment by ivanpaulovich** [comment]
Thank you @jbogard!
