### ISSUE TITLE
Question: Using Unity and Pipeline Behaviors

### ISSUE THREAD

**Issue by jeh170** [jbogard/MediatR#199]
I am currently implementing MediatR using Microsoft's Unity as my IoC container. I have gotten regular requests to work well using the code from the Unity examples. I would like to have some post process logic for logging/Client side notifications using the `RequestPostProccessorBehavior<,>`. Would there be a way to register the `RequestPostProccessorBehavior<,>` generically along with the example code from [https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.Unity/Program.cs](url)? Thanks.

**Comment by jbogard** [comment]
I have no idea. If you get it to work, can you submit a PR?
