### ISSUE TITLE
Why do we need to register IPipelineBehavior<,> manually with Scrutor's scan?

### ISSUE THREAD

**Issue by FDUdannychen** [jbogard/MediatR#200]
Line 30 in [the example of ASP.NET CORE](https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.AspNetCore/Program.cs)
```
services.AddScoped(typeof(IPipelineBehavior<,>), typeof(GenericPipelineBehavior<,>));
```
IMO `GenericPipelineBehavior<,>` is registered by Scrutor's scan:
```
services.Scan(scan => scan
                .FromAssembliesOf(typeof(IMediator), typeof(Ping))
                .AddClasses()
                .AsImplementedInterfaces());
```
Unfortunately it isn't, which means line 30 is necessary. Why?

**Comment by lilasquared** [comment]
@FDUdannychen this might be due to it being a generic?  I know with structuremap you have to explicitly call `.ConnectImplementationsToTypesClosing()`

**Comment by jbogard** [comment]
Open generics are treated differently in the ASP.NET Core container. Behaviors might not have any explicitly defined closed types, so `T` is not known until runtime.
