### ISSUE TITLE
Is returning command result anti-pattern/bad idea?

### ISSUE THREAD

**Issue by anarchistgeek** [jbogard/MediatR#203]
Hi

I have a command which creates a record in database. At the moment,  I have command as below
```
 public class CreateModelOverrideCommand : IRequest<CommandResult<ModelOverrideDto>
    {
        public CreateModelOverrideCommand(int modelId,  int year, double value)
        {
            ModelId = modelId;
            Year = year;
            Value = value;
        }
        public int ModelId { get; set; }
        public int Year { get; set; }
        public double Value { get; set; }
    }
```

My handler takes this command, creates row and returns the created row as data transfer object.  Is this a correct way to use command? or I should have another query and handler for retrieving created row? 

I have many cases like this, and shedding a bit of light on this will help me a lot  going forward.

Many thanks

**Comment by jbogard** [comment]
Nope, it's not. I think I blogged about it here:
https://jimmybogard.com/domain-command-patterns-validation/ maybe that
helps?

**Comment by anarchistgeek** [comment]
Thanks @jbogard . It is helpful. Closing the issue.
