### ISSUE TITLE
Advice Required

### ISSUE THREAD

**Issue by rjperes** [jbogard/MediatR#207]
Hi,
I'm kind of new to MediaR and I would appreciate some suggestions! My problem is:

- My apps sends messages (IRequest?) of some derived class
- I would like to have several handlers receiving it, and, if possible, in an ordered way, like, one handler (say, security-related) explicitly before the others; any of them might cancel the processing of a message
- I would also like to have handlers hooked to base classes being able to process the message for a derived class

Does this make sense? What I know is:

- In order to have multiple handlers, they have to be notification handlers (and the message be an INotification); must use IMediator.Publish to use them
- Cannot register IPipelineBehavior for a concrete class, only as an open generic class
- Cannot specify the order by which INotificationHandlers are executed
- Handlers bound to base classes are not called

Can you provide any advice on the best way to get something like this?
Thanks!

RP

**Comment by jbogard** [comment]
Pipeline is what you want here, it does what you need to do. But are the different handlers cross-cutting concerns it sounds like? Typically we have the main work in the one handler, but cross-cutting concerns in the pipeline. Pipeline isn't specific to any one request which is why we declare pipeline classes as generic types:

```c#
public class LoggingBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> {
    public Task<TResponse> Handle(TRequest request, RequestHandlerDelegate<TResponse> next) {
         Logger.Info("Before");
         var response = await next();
         Logger.Info("After");
         return response;
    }
}
```

**Comment by rjperes** [comment]
Thanks, Jimmy!
So, to use pipeline I need to Publish INotifications, right?
You are right, what I want is kind of cross cutting, check permissions, log, etc.

**Comment by jbogard** [comment]
No there’s no pipeline for notifications.

**Comment by rjperes** [comment]
Thanks, that was my mistake! So, I managed to overcome all situations:
- I have a generic pipeline behavior and I check the type of the argument to see if it's the one I'm interested in
- Using dependency injection to inject on the constructor of an handler of a derived request an handler for the base request
- Only one handler per request will do
Thanks, @jbogard!

**Comment by jbogard** [comment]
Depending on your container, you _may_ be able to use generic constraints
instead of "checking the type". Something to think about!

**Comment by rjperes** [comment]
Not with .NET Core DI, which is what I want to support! :-)
