### ISSUE TITLE
Processors & Behaviors Called Multiple Times

### ISSUE THREAD

**Issue by rwgridstone** [jbogard/MediatR#209]
Using the Autofac sample, I registered a Mediatr preprocessor as:

builder.RegisterGeneric(typeof(GenericRequestPreProcessor<>)).As(typeof(IRequestPreProcessor<>));

When I run the app, I see the preprocessor is called multiple times. In my case, 13.

How can I stop this happening? Surely, I only want Process() to be called once?

I also see a validation behavior being called multiple times.

Thanks,
Richard

**Comment by rwgridstone** [comment]
Worth saying if I create an abstract base class with a boolean "Processed" property and then set that to true with a guard check in Process(), I can exit without the processor doing work multiple times but I don't understand why I need to.

**Comment by jbogard** [comment]
I'll add behaviors to the samples and investigate.

**Comment by jbogard** [comment]
I can't reproduce this, the sample seems to work just fine?
