### ISSUE TITLE
INotificationHandler for an INotification with a GenericType Argument, is this doable?

### ISSUE THREAD

**Issue by mreyeros** [jbogard/MediatR#21]
I was attempting to create a generic INotification that could then be handled by a single INotificationHandler implementation.  Something like below:
```
public class UpdateEntity<T> : INotification {
public T Entity {get;set;}
}

public class UpdateEntityHandler<T> : INotificationHandler<UpdateEntity<T>> where T : class
{
}
```
I am using Ninject as my DI container and am not sure if this is related to my ninject configuration, but for some reason if I send a mediator.Publish call of my command it cannot identify the notification handler to execute.  Is what I am trying to do possible, or even correct?  Perhaps I have misused the concept of Notifications for handling my commands when in reality I should be using the IRequest interface. Does this make sense?  If it is the case that I should be simply using the RequestHandler implementation for managing my commands as well, how would I be able to implement this same generic concept using RequestHandlers?

**Comment by jbogard** [comment]
You'll need to ask the Ninject guys - I have no idea. I know StructureMap can, but I'm not a Ninject user.
