### ISSUE TITLE
PCL Support for Profile111

### ISSUE THREAD

**Issue by erdmenchen** [jbogard/MediatR#210]
Is there any chance to bring back PCL support for the current nuget version of MediatR?

I am targeting `Profile111` and cannot include the (awesome) MediatR nuget package...

**Comment by jbogard** [comment]
Profile111? I already support that with netstandard1.1.

Why can’t you pull that in? NuGet should support that.

**Comment by erdmenchen** [comment]
When installing version 3.0.1 via Nuget, it complains about 'System.Runtime.InteropServices.RuntimeInformation 4.0.0':

>Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jbogard** [comment]
3.0.1? That version is years old. Have you installed the latest?

**Comment by erdmenchen** [comment]
When searching on nuget, this is the latest stable version, released on march this year??

See: https://www.nuget.org/packages/MediatR

**Comment by jbogard** [comment]
Oh wow I got it confused with AutoMapper lol.

Does NuGet not just handle this?

**Comment by erdmenchen** [comment]
Solved it by manually installing the latest version of the `System.Runtime.InteropServices.RuntimeInformation` and after that installing MediatR.

Thanks for your support.
I think this could be fixed by updating the dependencies of MediatR to the latest versions...

**Comment by jbogard** [comment]
Will do! In the future I'm only going to target `netstandard1.1` and will update for 4.0
