### ISSUE TITLE
.NET 4.5 projects pull in long list of .NET Standard assemblies as dependencies

### ISSUE THREAD

**Issue by TheDanielDoyle** [jbogard/MediatR#215]
Dependencies on NuGet for v4.0.0 list only NETStandard.Library (>= 1.6.1), whereas v3.0.1 also lists .NETFramework 4.5. 

Is this an oversight or intended?

**Comment by rwgridstone** [comment]
I have to use 4.6.2, not standard. Mediatr 4.0 will work fine with 4.6.2, so while I understand wanting to move away from 4.5, couldn't you bump to 4.6.2 or provide a package that doesn't bring in all the netstandard ones to a .Net 4.6.2 class library?

**Comment by jbogard** [comment]
I thought it might be time to move away from targeting full .NET explicitly since .NET Standard already targets those frameworks. But maybe not. I'll push out a version today that targets `net45`

**Comment by jbogard** [comment]
I pushed out a new release, 4.0.1 that adds the `net45` target back.
