### ISSUE TITLE
Is there any way to capture orhaned notificaitions or requests?

### ISSUE THREAD

**Issue by jsystem** [jbogard/MediatR#216]
for example notifications/requests firing but having no handlers at all.
How can I achieve this in a neat way?

**Comment by jbogard** [comment]
If there's no handler for an IRequest, MediatR throws an exception at
runtime. Not with notification handlers, MediatR makes no assumptions about
those.

But you can try this with some reflection code. Find all types that
implement IRequest/INotification, and query your container to see if there
are any registrations for that handler type.
