### ISSUE TITLE
Sharing RequestPostProcessor across multiple Requests sharing same interface

### ISSUE THREAD

**Issue by codeplay87** [jbogard/MediatR#217]
I am trying to see if this is something that is possible using MediatR and if it fits within the paradigm. I have two different Requests with there own request handlers however they share the same interface. I would also like them to both share a RequestPostProcessor after they have been handled.

Example as shown below:

    public class ActivateRental : IUserRequest 
    {
        public string UserId { get;set; }
    }

    public class UpdateUserAccess : IUserRequest 
    {
        public string UserId { get;set; }
    }

    public interface IUserRequest 
    {
        string UserId { get;set; }
    }

Whilst both may have there own handlers for ActivateRental and UpdateUserAccess I am trying to do the post processing via a RequestPostProcessor that only expects a IUserRequest i.e.

    public class UserAccessPostHandler : IRequestPostProcessor<IUserRequest , bool>
    {
        public async Task Process(IUserRequest request, bool success)
        {
            // do something here
        }
    } 

Is this possible? Do I need to do something to hook this all up. Any information would be much appreciated.

**Comment by jbogard** [comment]
What container are you using?

**Comment by jbogard** [comment]
Is this working? I'm not sure if Ninject supports figuring out these base types, I do have the interface marked as contravariant.

Have you tested this with Ninject itself? I can always add more feature tests in the samples to see if it works.

**Comment by jbogard** [comment]
So there is a little bit of an issue here - with request processors, you typically expect some kind of ordering. Collections are easy to do, but behaviors and processors you really want to set up how the items nest. Most containers have different configuration APIs for nesting vs. not.

**Comment by jbogard** [comment]
To do this with StructureMap (and I'll be updating the docs with techniques here), you have to use generic constraints:

```c#
public class ConstrainedRequestPostProcessor<TRequest, TResponse>
    : IRequestPostProcessor<TRequest, TResponse>
    where TRequest : Ping
{
    private readonly TextWriter _writer;

    public ConstrainedRequestPostProcessor(TextWriter writer)
    {
        _writer = writer;
    }

    public Task Process(TRequest request, TResponse response)
    {
        return _writer.WriteLineAsync("- All Done with Ping");
    }
}
```

Then your registration:

```c#
//Pipeline
cfg.For(typeof(IPipelineBehavior<,>)).Add(typeof(RequestPreProcessorBehavior<,>));
cfg.For(typeof(IPipelineBehavior<,>)).Add(typeof(RequestPostProcessorBehavior<,>));
cfg.For(typeof(IPipelineBehavior<,>)).Add(typeof(GenericPipelineBehavior<,>));
cfg.For(typeof(IRequestPreProcessor<>)).Add(typeof(GenericRequestPreProcessor<>));
cfg.For(typeof(IRequestPostProcessor<,>)).Add(typeof(GenericRequestPostProcessor<,>));
cfg.For(typeof(IRequestPostProcessor<,>)).Add(typeof(ConstrainedRequestPostProcessor<,>));
```

**Comment by GDnsk** [comment]
Hello, sorry about ressurect this issue. How can i acomplish the same using MediatR.Extensions.Microsoft.DependencyInjection as container? Thank you.
