### ISSUE TITLE
Tags getting ahead of Releases?

### ISSUE THREAD

**Issue by codearoo** [jbogard/MediatR#218]
We just did a NuGet update and picked up ver 4.0.1 of MediatR.. and some things broke because of now the abstract override of "HandleCore" instead of the old way. That's fine.. but when going to this site, we only see Releases as of ver 3. And no release notes for ver 4 which just have tags. Is that going to come soon?

**Comment by jbogard** [comment]
Derp. My bad. Created a release based on my blog post. Thanks!
