### ISSUE TITLE
Dependency on Mediator in Handler implementation

### ISSUE THREAD

**Issue by AlonAmsalem** [jbogard/MediatR#22]
Hi :-)

Do you write Handlers that uses the Mediator to invoke another request/notification?
If so, How do you test such handlers?

Thanks!

**Comment by jbogard** [comment]
I do, occasionally. You can stub the sub-request out if you like, or just allow it to go ahead and call the real thing. I usually let it call the real thing unless the real thing is calling a web service or something I can't control.
