### ISSUE TITLE
HandleCore vs. Handle

### ISSUE THREAD

**Issue by siberianguy** [jbogard/MediatR#222]
I'm integrating the new version of Mediatr for the first time and it feels a little sad the key method is now called HandleCore instead of Handle (in case of deriving from AsyncRequestHandler). Looks a little hackish in my opinion. There was no way to call it Handle due to some C# limitations or was it a design decision?

**Comment by jbogard** [comment]
Yes the previous version contained all the hacks. You don’t have to use the
base classes if you don’t want, we just use the interfaces.

**Comment by siberianguy** [comment]
But then I would have to pass CancellationToken though I don't use it...

**Comment by jbogard** [comment]
IMediator always passes it but we use a default value so you don’t have to
pass it if you don’t want to.

Just had to bite the bullet. It’s what other frameworks have to do in C#
with async (see NServiceBus and ASP.NET Core)

**Comment by siberianguy** [comment]
Got it! Thanks a lot for the clarification
