### ISSUE TITLE
Inconsistent naming for TRequest parameter

### ISSUE THREAD

**Issue by sm-g** [jbogard/MediatR#223]
https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequestHandler.cs
it is `TRequest request` and `TRequest message` sometimes

I'm using SonarLint with rule to have matching [parameters names with interface decalration](http://dist.sonarsource.com/plugins/csharp/rulesdoc/0.10.0-RC/S927.html), so after updating to MediatR I've noticed that.

**Comment by jbogard** [comment]
PR?
