### ISSUE TITLE
Is Mediatr4 replaced IAsyncRequestHandler from IRequestHandler and Does it cause any performance? Is IRequestHandler an async method?

### ISSUE THREAD

**Issue by mcganesh5089** [jbogard/MediatR#224]

**Comment by jbogard** [comment]
Does it cause any performance? I'm not sure of the question. Performance problems? No. I've consolidated all interfaces into one. Yes, IRequestHandler is async.

In fact, this version performs better as it doesn't have to test 3 different interfaces for resolution.
