### ISSUE TITLE
Simple Injector build failure with ncrunch

### ISSUE THREAD

**Issue by bapti** [jbogard/MediatR#23]
I get the following error when running the tests under nCrunch.  To fix I copied the simple injector common service locator implementation into a local class rather than use the packaged version as the packaged version uses 1.0.0.0 instead of 1.3.0.0

```
Assembly 'MediatR, Version=1.0.0.0, 
Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Practices.ServiceLocation, 
Version=1.3.0.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.Practices.ServiceLocation, 
Version=1.0.0.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35'
```

If you'd like a merge request let me know, feels like the proper fix here is to get simple injector to update their CSL package though. 

Thoughts?

Thanks
Neil

**Comment by jbogard** [comment]
This should be able to be addressed via a binding redirect in your app:

```
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="Microsoft.Practices.ServiceLocation" publicKeyToken="31bf3856ad364e35" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>
```

**Comment by bapti** [comment]
Good idea, I've just tried it however it still emits the same error.  Perhaps it's a quirk of ncrunch.

**Comment by jbogard** [comment]
This will go away in 2.0 when I remove the dependency on CSL.
