### ISSUE TITLE
Updated Autofac example in wiki

### ISSUE THREAD

**Issue by mbcrawfo** [jbogard/MediatR#232]
I have updated the wiki's Autofac example to have the `ContravariantRegistrationSource` excluded by default, with a warning about enabling it.  Having it enabling it by default drops users into a small minefield IMO (#128) if/when they start using the pipeline.  It bit me today, and looks like it was probably the root cause behind #209 as well.  I also added a warning to the behaviors page to give a short explanation of the issue and link to #128 if users want to try to work around the issue.  Basically just requesting a review to ensure the changes make sense to someone who hasn't been immersed in this issue for the last few hours.  :)

**Comment by jbogard** [comment]
Thanks!
