### ISSUE TITLE
Update AsyncRequestHandler Wiki

### ISSUE THREAD

**Issue by Brimce** [jbogard/MediatR#235]
Hi,

`public class AsyncNoCancellation : AsyncRequestHandler<Ping, string> {
    protected override Task<string> Handle(Ping request) {
        return Task.FromResult("Pong");
    }
}`

should be :
`public class AsyncNoCancellation : AsyncRequestHandler<Ping, string> {
    protected override Task<string> HandleCore(Ping request) {
        return Task.FromResult("Pong");
    }
}`

Thank's

**Comment by jbogard** [comment]
Wiki is editable by anyone!

**Comment by Brimce** [comment]
ok ! Done :)
