### ISSUE TITLE
dll nuget not signet

### ISSUE THREAD

**Issue by Monchu** [jbogard/MediatR#239]
When I try to download the solution from nuget the assembly is not signed and therefore I get an error when compiling.

**Comment by jbogard** [comment]
What are you building? Really only library developers that depend on MediatR would ever hit this?

**Comment by Monchu** [comment]
I would like to be able to use the dll but since my project is signed when compiling it gives an error publickeytoken = null.

Would it be possible?

Thanks!!
Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by jbogard** [comment]
Why is your project signed?

**Comment by Monchu** [comment]
for versioning and implementation needs the generated dlls have to be strongname, with libraries like autofac etc this problem does not exist.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by jbogard** [comment]
Why does your library need to be strong named?

**Comment by Monchu** [comment]
I'll give you an example:
https://blog.klimczyk.pl/2016/03/29/nuget-and-strong-signed-dll/

**Comment by Monchu** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

**Comment by jbogard** [comment]
What is your situation?
