### ISSUE TITLE
Make Publish Non generic

### ISSUE THREAD

**Issue by afifmohammed** [jbogard/MediatR#24]
Is there a reason why Publish needs to be `Publish<TNotificaiton>(TNotification notification)` and can't be `Publish(INotification notification)`?

Using the latter you can still build

```
var serviceType = typeof(INotificaitonHandler<>).MakeGenericType(notification.GetType());
```

and resolve it using the `MultiInstanceFactory`. Makes it easier for clients to consume the `IMediator` when they need to `Publish` a notification that is passed to them as an object by simply casting it to `INotification`.

**Comment by afifmohammed** [comment]
I am aware that this change would mean you have to invoke the `Handle` method on the `INotificationHandler<>` using reflection.

**Comment by afifmohammed** [comment]
I figured if some one has to use reflection, it did rather be the client, using an extension method that lets them do
` Publish(INotification notification)`

**Comment by jbogard** [comment]
Did you mean to close this?

**Comment by afifmohammed** [comment]
I did originally under the pretext that if you have to use reflection to invoke the notification handlers, then you might as well not have that code inside the mediator, rather capture it explicitly in some other extension method. I later realized that's exactly how you invoke the request handlers, so the notification handlers can follow suit.

**Comment by afifmohammed** [comment]
This is what I have right now to support non generic types. 
```
public static void PublishBoxed(this IMediator mediator, INotification notification)
{
    try
    {
        mediator.GetType()
            .GetMethod("Publish")
            .MakeGenericMethod(notification.GetType())
            .Invoke(mediator, new object[] { notification });
    }
    catch (TargetInvocationException ex)
    {
        ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
    }
}
```

**Comment by Korijn** [comment]
Thanks @afifmohammed, I altered your piece of code to call `PublishAsync` instead, and am using it for the [better domain events pattern](https://lostechies.com/jimmybogard/2014/05/13/a-better-domain-events-pattern/). In the spirit of sharing...

    public async Task PublishBoxedAsync(IMediator mediator, IAsyncNotification notification)
    {
        try
        {
            var task = mediator.GetType()
                .GetMethod("PublishAsync")
                .MakeGenericMethod(notification.GetType())
                .Invoke(mediator, new object[] { notification }) as Task;

            await task;
        }
        catch (TargetInvocationException ex)
        {
            ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
        }
    }

    public override async Task<int> SaveChangesAsync()
    {
        var result = await base.SaveChangesAsync();

        foreach (var entity in ChangeTracker.Entries<IEntity>()
            .Select(po => po.Entity)
            .Where(po => po.Events.Any()))
        {
            var events = entity.Events.ToArray();
            entity.Events.Clear();
            foreach (var domainEvent in events)
            {
                await PublishBoxedAsync(mediator, domainEvent);
            }
        }

        return result;
    }
