### ISSUE TITLE
Some kind of middlewares for Notification

### ISSUE THREAD

**Issue by lucax88x** [jbogard/MediatR#241]
Ciao @jbogard!

1) behaviors are fine for sending message
2) behaviors do not work for publishing notifications

then, is there any way to add some kind of middleware for notifications?

Thanks,
Luca

**Comment by jbogard** [comment]
What kind of middleware? Around all notifications sent, or just one?

**Comment by lucax88x** [comment]
all of them, for example for logging purposes, or just storing events on a CQRS system.

does this make sense?

**Comment by jbogard** [comment]
Depending on your container that you use you can do all of those. The Mediator class itself has a method you can override, and if your container supports decorators you can add wrappers around your notification handlers.

The middleware I put in was just some convenience stuff because some containers are a bit of a pain to deal with, or don't support those features.

**Comment by lucax88x** [comment]
Yeah it does, I can just use the Autofac interceptors to deal with this, and it's working, so I'm actually fine.

Thanks man, keep up the good work.
Luca

**Comment by jbogard** [comment]
Can you show what you’ve got going? I designed the existing behaviors off
of real world usage but we don’t do any sort of notification pipelines so I
don’t have any examples to work with.

**Comment by lucax88x** [comment]
Yeah sure,

here you go.

``
builder.RegisterType<MediatorSnifferInterceptor>();

builder
    .RegisterType<Mediator>()
    .As<IMediator>()
    .InstancePerLifetimeScope()
    .EnableClassInterceptors()                
    .InterceptedBy(typeof(MediatorSnifferInterceptor));
``

``
public class MediatorSnifferInterceptor : IInterceptor
{
    public void Intercept(IInvocation invocation)
    {           
        // your stuff here
        invocation.Proceed();
    }
}
``

It's actually work only for Publishing, not for Sending.. IDK why, so I'm combining pipeline with that.

I wanted to achieve that on my unit tests.

``
_sandbox.ShouldMediator.Be("CreateAccount -> AccountCreated");
``
