### ISSUE TITLE
For Consideration - A way to have a response of a request handler be a notification

### ISSUE THREAD

**Issue by dealproc** [jbogard/MediatR#255]
Playing with Event Sourcing, and having a few folks in the ddd-cqrs-es slack review my progress, it came to my attention i was breaking the rules because i was trying to do a write-back using IRequestHandlers for building an event sourced system.

The problem i ran into was I needed to do a response-less handler, and then pickup an event to be returned to a caller.

This is the first draft of what I came up with to solve the problem.  Not sure if others would find this useful or not... if not, just close/reject this... if its valuable, please let me know naming conventions, etc, and we can drop this into the main MediatR repo.

https://gist.github.com/dealproc/2fcfcadef61d7103c81ecf5f84425728

**Comment by jbogard** [comment]
Have you looked at using the pipeline for this? I've moved away from any kind of decorators to instead using the pipeline.

**Comment by dealproc** [comment]
I had thought about that... but got lost in how I'd implement it.  This just seemed to be the most obvious way of doing what I wanted.

If there is a way to refactor what I have into a pipeline, I'd be much happier, to be honest, and wouldn't mind factoring over to it.

**Comment by jbogard** [comment]
You’d likely look at a post-processor, which is one of the built in
pipeline abilities. With a little generic constraint magic you're good.
