### ISSUE TITLE
ResolveAll usage

### ISSUE THREAD

**Issue by ENikS** [jbogard/MediatR#256]
I think you might get better result if you use IEnumerable<xxx> instead of ResolveAll. The first resolves named and unnamed where ResolveAll resolves only named registrations.

https://github.com/jbogard/MediatR/blob/a8338117ccce8817d4a2bf0a64bf78bbc93a581a/samples/MediatR.Examples.Unity/Program.cs#L62

**Comment by jbogard** [comment]
PR? I didn’t write this stuff, it was sent in from the community.

**Comment by jbogard** [comment]
Ha! Well this is the code that people using MediatR and Unity copy-paste, so if anything can be simplified, I'd be happy.

By the way, any plans to add assembly scanning? I think that's most of the code in the Unity implementation for MediatR.

**Comment by ENikS** [comment]
Perhaps in v6
