### ISSUE TITLE
Problem with AsyncNotificationHandler in another project

### ISSUE THREAD

**Issue by grzechu** [jbogard/MediatR#258]
Hi,
I'm currently working on Asp Core 2 project with MediatR.
I found CQRS sample, which is available here:
https://github.com/footedr/EasyCQRS/tree/master/src/Web
This demo working correctly, but when I move Mediatr with CQRS classes (Commands, Handlers, Queries etc) to another project(Core dll library) and add reference to Web project, NotificationHandler event doesn't fire. CommandHandlers works fine.
What I should do to resolve this problem? Do I need to register NotificationHandler, if yes where?

**Comment by bartosz6** [comment]
In this example notification handlers are registered by assembly scanning `services.AddMediatR(typeof(Startup).Assembly)`, if you move them to different assembly then you need to change your registrations. You can do it manually or by adding another assembly scan.

**Comment by grzechu** [comment]
@bartosz6 
OK, I added `services.AddMediatR(typeof(EmployeeHiredNotification).Assembly)`; to the ConfigureServices method and everything works as expected. Thank You for your help.
