### ISSUE TITLE
Best practices for handling exceptions in ASP.NET Core?

### ISSUE THREAD

**Issue by RPM1984** [jbogard/MediatR#260]
Hi guys 👋  

Let's say i have a ASP.NET MVC Core API, with a route that needs to place an order. (e.g `POST: /orders`). In the handler, i would like to ensure that the Product with the ID supplied in the command _exists_, before i place the order. If it doesn't i would like to return a 404 (not found) as the API result.

What's the best way to handle this?

Only thing that comes to my mind is to throw an exception in the handler, and try/catch that in the call to MediatR in my controller. Doesn't seem very DRY, since i'd need to do this everywhere. This logic is custom to this handler, so i don't see a behavior pipeline solving this.

What do others do here? Any samples i can look to?

Thanks 😃

**Comment by stiankroknes** [comment]
Hi, could try using a exception filter in web api and setup some mappings/rules for exception type to http status code. Create a custom NotFoundException (throw it from the handler) and handle it in the exception filter. Maybe this approach will fit in your stack.

**Comment by ardalis** [comment]
You could use an Action filter like ProductExists. Example here

https://github.com/ardalis/GettingStartedWithFilters/blob/master/Filters101/Filters/ValidateAuthorExistsAttribute.cs

**Comment by hey-red** [comment]
You can use your own Result object.
Generic ex:
```C#
    public class Result<TValue>
    {
        public bool Succeeded => Error == null;
        public string Error { get; protected set; }
        public TValue Value { get; protected set; }

        public static Result<TValue> Success(TValue value) =>
            new Result<TValue> { Value = value };

        public static Result<TValue> Failed(string error) =>
            new Result<TValue> { Error = error };
    }
```

then return 

`Result<Value>.Failed("Product not found"); ` 

if product not found and

`Result<Value>.Success(new Value()));` 

when your handler is done. 

Then handle it in your controller:

```C#
     var result = await mediator.Send(new CreateOrder());
     if (!result.Succeeded)
     {
         return BadRequest(result.Error);
     }
```
You can also create non generic result without value or with specified type, if there's is not needed.

**Comment by RPM1984** [comment]
Wow, thanks for all the answers guys! Didn't expect so many so fast.. 😄 

I'm currently playing with a variation of what you've suggested @hey-red . (was playing with that _before_ your comment, and was kinda stuck.. so your comment helped 😄 )

The next solution i was going to go with was throwing exceptions and catching them in a global handler (kind of what you suggested @stiankroknes ), but ideally i want to avoid throwing exceptions all the time (cost).

@ardalis i thought of an action filter, but doesn't seem very re-usable..every handler would have it's own logic.

Thanks for your help all..got some ideas. Will report back soon with some code on how i did it.

**Comment by RPM1984** [comment]
Hi all, i got the above working..here's the code if anyone else is interested:
https://github.com/RPM1984/Playground

Thanks again all ☺️

**Comment by no1melman** [comment]
I would just throw exceptions and let the aspnet core handle them. I would always expect MediatR to be agnostic of the "UI" layer you are using. So I would say that you shouldn't handle errors in MediatR because you can't doing anything about them (obviously not applicable 100% of the time but generally). Then you can let your "UI" layer make the decision about what an exception means.

**Comment by no1melman** [comment]
@ardalis I generally have MediatR pipeline behaviours to mimic that, only reason why I would prefer behaviours is that it would keep business logic in MediatR. But, I do like those filters
