### ISSUE TITLE
Multiple Notification Handler Instantiated

### ISSUE THREAD

**Issue by rthm93** [jbogard/MediatR#262]
Similar case happened as this issue #136 , just in my case it was notification handler.

I am using ASP.NET core 2.0 web API with default service registration.

**Comment by jbogard** [comment]
What do your handler types look like? Do you have a repro?

**Comment by rthm93** [comment]
Please refer to this [gist](https://gist.github.com/rthm93/492f68d9b041a34c0be3051e6cea65f8)

At startup.cs ConfigureServices method, i call services.AddMediatRServices() 

I have put a breakpoint at line 12, and it always reaches the breakpoint at least twice every time a notification is published. I have also checked the hash code of each object every time it reaches the breakpoint, every time a new instance was created.

**Comment by rluiten** [comment]
Just ran into this myself, added a new Notification handler for a command and it is executed twice on every publish.

**Comment by jbogard** [comment]
New notification handler for a command? That doesn't make sense anyway, commands are requests, not notifications.

@rthm93 There's a few ways to debug this. First, check the service collection to see if the handlers are double registered.

Next, ask the service collection for all `INotificationHandler<T>` where T is your request type.

**Comment by rluiten** [comment]
It may not make logical sense, but a Notification takes a parameter class with data and returns nothing eg  INotificationHandler<Message>

And a IRequestHandler<Message> takes a command and returns nothing.

So for this specific case it makes no practical difference.

It happens to be a SendEmail service so not even sure it should be a Command or a Notification :).

**Comment by joaomatossilva** [comment]
I think I've seen a similar issue with Autofac as the IoC framework, because if the co-variance settings.

**Comment by rluiten** [comment]
We have resolved our double execution issues for INotificationHandler running wice, as you mentioned above Notifications having a run all model, we had a registration error in our container where an interface was added a second time.

Thanks for your comments @jbogard they pointed the way to our correct solution at least.
Hope this follow up might help someone else.

**Comment by jbogard** [comment]
Can this issue be closed?

**Comment by rluiten** [comment]
I can't as I didn't create it.

**Comment by jbogard** [comment]
@rthm93 the next step I think might be to just pull down the code and debug locally. Add a reference to the project itself rather than NuGet.

**Comment by rthm93** [comment]
@jbogard I just tried debugging the code. The issue is in MediatR.Extensions.Microsoft.DependencyInjection. 

Same assembly was scanned multiple times causing the types to be registered multiple times in the service collection, hence when the service factory create multiple instances of the handling type.

I will close this issue and create a new issue in MediatR.Extensions.Microsoft.DependencyInjection project.
