### ISSUE TITLE
Move interfaces into a separate package

### ISSUE THREAD

**Issue by mrpmorris** [jbogard/MediatR#264]
With Blazor on progress it is now possible to share the exact same API request/response classes between server and browser.

Could we have interfaces separated put into a separate nuget package so that the client can compile those shared API classes without having to pull in classes it won't need?

I'm thinking akin to how Microsoft created a separate package for their dependency injection stuff. It would be nice to keep the browser payload small.

**Comment by jbogard** [comment]
What additional classes, the handlers and whatnot? How much does this add to the payload?

**Comment by mrpmorris** [comment]
Yeah, I suppose for a total of 17KB it's not worth it :)

**Comment by nikoudel** [comment]
It's not about size - it's about versions.

Suppose there are a couple of web services with their clients. Service "Micro1" uses MediatR nuget 8.0.1 and service "Micro2" uses MediatR 8.0.2. Now if a third-party service decides to call the API of both micro services it will have the version problem.

The problem can be solved by extracting the API interfaces (namely [IRequest](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequest.cs)) to a separate nuget (something like MediatR.Abstractions) to be referenced by DTO assemblies. The intefrace nuget will be virtually never updateded removing the unnecessary update pressure from these "Micro x" services.
