### ISSUE TITLE
Pipeline for INotification, e.g. for filtering

### ISSUE THREAD

**Issue by jimmcslim** [jbogard/MediatR#265]
I have a particularly generic `INotification` that will ultimately have multiple `INotificationHandlers`. However, each of those handlers is really only interested in processing the notification depending on the value of a property on the notification object.

It would be good if there is a way to implement a filter around notification handlers such that the filter could compare, say, an attribute on the notification handler and see if a property value of the attribute matches the value on the notification; if so pass it through to the notification handler, otherwise continue with the next notification handler.

**Comment by joaomatossilva** [comment]
In my oponion this request is very handler specific. And whatever might get built, nothing would be simpler on the NotificationHandler just doing a simple:

    if (request.Property = true)
    {
        return;
    }

**Comment by jbogard** [comment]
Yeah, I'd go for @joaomatossilva 's solution.
