### ISSUE TITLE
add logging and metrics support

### ISSUE THREAD

**Issue by pwelter34** [jbogard/MediatR#266]
Please consider adding logging and metrics support to this library.   I understand could just add a behavior to accomplish a lot of that.  However in my usages, it still misses stuff.  Having the logging and call metrics timing at the lowest level is the best answer.

I'm willing to work on a pull request if there is interest.  The trick will be to add support without adding dependencies.  Thoughts?

**Comment by jbogard** [comment]
What would you log, and what trick would you use? I'm assuming `System.` dependencies.

**Comment by jafin** [comment]
If your IoC supports interception (ie https://autofac.readthedocs.io/en/latest/advanced/interceptors.html) you could log via that approach, would that be low enough?

**Comment by pwelter34** [comment]
I think there are ways to accomplish this via behaviors or the suggested interception patter.  I'll go a head and close this.  Thanks
