### ISSUE TITLE
Synchronous RequestHandlers and await

### ISSUE THREAD

**Issue by oferns** [jbogard/MediatR#267]
Whats the best way to call the IMediator when the task is synchronous and inherits from RequestHandler? I assume its not to use the "await" keyword. Should I just call .Result? on the IMediater.Send method? Not really an issue I know but I am having a crisis of confidence!

**Comment by remcoros** [comment]
IMediator is async only, so you 'should' always use the async/await when calling IMediator (even when your handlers are not async).

If you need to call IMediator from non async code, wrap it in Task.Run(), or use GetAwaiter().GetResult() (beware for deadlocks though)

**Comment by oferns** [comment]
Sure. But I gather that it is not a good idea to await a Task.FromResult and that is what the abstract class RequestHandler does

https://gist.github.com/ghuntley/e5b5642ecc4428255e61185bb79856e4

**Comment by joaomatossilva** [comment]
From what I know, there is no sync support from version 3.0 and on. There will always be version 2 for that. All handlers are assumed to be async.

There is nothing wrong into calling an handler that returns a Task.FromResult and it's not marked as async, besides the small performance penalty of the plumbing code being marked as async, and creating "the async machinery" as the gist calls it :)

**Comment by oferns** [comment]
Thats not true. There is specifically an abstract class for running synchronous tasks and it is explicitly mentioned in the wiki..

> Or if the request is completely synchronous, inherit from the base RequestHandler class:
> 
> ```
> public class SyncHandler : RequestHandler<Ping, string> {
>     protected override string Handle(Ping request) {
>         return "Pong";
>     }
> }
> 
> ```
>

**Comment by joaomatossilva** [comment]
Sure but the interface is async.

It's all in here:
https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequestHandler.cs

You have a RequestHandler but it's only a wrapper as it shows here.

`Task<TResponse> IRequestHandler<TRequest, TResponse>.Handle(TRequest request, CancellationToken cancellationToken)
            => Task.FromResult(Handle(request));`

**Comment by oferns** [comment]
Exactly! You end up awaiting a Task.FromResult. Which apparently is not a good idea according to this gist https://gist.github.com/ghuntley/e5b5642ecc4428255e61185bb79856e4

> Hot Tip
> 
> In the above situation, you can mark the method with async, however you should never do this. Marking the method with async causes the runtime to instantiate the async machinery for the method, which will have significant performance overhead. If you don’t need this, it is best to avoid it.
> 
> In general, if you can avoid calling await and use Task.FromResult you should.

**Comment by joaomatossilva** [comment]
The only problem with that is a small performance penalty, not really a major issue.

If you want the full Sync support, use version 2.x.

**Comment by oferns** [comment]
Or can I call .Result or RunSynchronously()  on the Send method and avoid the penalty? Thanks for helping me clarify!

**Comment by joaomatossilva** [comment]
I wouldn't do that, becasue you risk yourself into deadlocking.
There is code in the pumbling that do use the `await` before calling the handler.

**Comment by oferns** [comment]
Ok. That makes more sense. It's possible that my sync handler is wrapped by async decorators etc, so it is justified to use await even on a seemingly synchronous request. Again, thanks for the input. Much appreciated.
