### ISSUE TITLE
Request/response vs command query - synonyms?

### ISSUE THREAD

**Issue by enemyofthedawn** [jbogard/MediatR#268]
Is request-response pattern simply a CQRS pattern? Or, how should they be classified, how should I think about it? Given that command in CQRS theoretically shouldn't return any response.

**Comment by bartosz6** [comment]
It is not CQRS. However, it is possible and easy to implement CQRS using MediatR, you just simply need to create interfaces `ICommand : IRequest` and `IQuery<T> : IRequest<T>`.

_Rule of thumb:_
Request = Command + Query
Notification = Event

**Comment by jbogard** [comment]
Yep! Commands and queries are just specific kinds of requests.
