### ISSUE TITLE
[Question] sharing common data in a pipeline

### ISSUE THREAD

**Issue by vdecristofaro** [jbogard/MediatR#269]
As per the title says, it is possible to share data between behaviors within a pipeline?

**Comment by jbogard** [comment]
The only way to "share" data in a pipeline is through the requests/responses themselves. For those two, you can get creative. I didn't want to introduce a "context" parameter to pass through, however.

**Comment by no1melman** [comment]
The pipeline can be injected into, so you just create a class that is registered as per request scope, this class is brought through the constructor. On that class you can store data for the next behaviour (that sort of acts like a http context).
