### ISSUE TITLE
Not Installing on .NET 4.0

### ISSUE THREAD

**Issue by ChrisMiskowiec** [jbogard/MediatR#27]
The wiki says:

> Cross-platform, distributed as a portable class library, supporting .NET 4+, Silverlight 5, Windows 8, Windows Phone 8, Xamarin.Android, Xamarin.iOS, Xamarin.Unified, ASP.NET 5 and ASP.NET Core 5.

When running "Install-Package MediatR" on a .NET 4.0 project, I get this error:

> Could not install package 'MediatR 1.0.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by jbogard** [comment]
I'll update the wiki, it's .NET 4.5+

This is because of the async/await stuff from another issue.

**Comment by flipdoubt** [comment]
Any pointers on what it would take to use this in a .NET 4.0 project if I compile it from source? I see no tags or branches that make the jump to 4.5 look obvious.

**Comment by dittodhole** [comment]
@jbogard You can still include Micorosoft.Bcl.Async to bring async and await to .Net 4.0 - this is no *real* reason for dropping support of .Net 4.0 :(

**Comment by chester89** [comment]
Me too, would love .NET 4.0 support

**Comment by dittodhole** [comment]
@chester89 @ChrisMiskowiec with the latest release (2015-08-05) at https://www.nuget.org/packages/MediatR/ there are also dependencies for .Net 4.0 ... giving it a try right now...

**Comment by jbogard** [comment]
Yeah I added 4.0 support separate from 4.5 support.
