### ISSUE TITLE
Multi-level inheritance on requests

### ISSUE THREAD

**Issue by lindeberg** [jbogard/MediatR#270]
Hi! In my system I have a complex multiple-role resource based authorization on a form with a lot of inputs and for that I have command inheritance and composition on multiple levels that extends the forms input fields. Anyways.. It looks something like this, cut down for readability:
```
namespace Features.Members.Edit.AsMember
{
  public class Command : IHasMemberContactInfoCommand, IHasMemberPersonalInfoCommand, IRequest
    {
        public int MemberNumber { get; set; }
        public ContactInfoCommand ContactInfo { get; set; }
        public PersonalInfoCommand PersonalInfo { get; set; }
    }
}

public class ContactInfoCommand
    {
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name = "Hemtelefon")]
        [Phone(ErrorMessage = @"""{0}"" är inte ett giltigt telefonnummer.")]
    }

namespace Features.Members.Edit.AsSecretary
{
 public class Command : AsMember.Command, IHasMemberInfoCommand, IHasMemberGradesCommand, IRequest<CommandResult>
    {
        public InfoCommand Info { get; set; }
        public GradesCommand Grades { get; set; }
    }
}
```

now when I go
```
            var result = await _mediator.Send(command);
```
in my controller i get the compiler error message
cannot assign void to an implicitly-typed local variable

Because I'm using both ```IRequest``` and ```IRequest<T>```.

Can i get around this?

**Comment by joaomatossilva** [comment]
Can you try casting you command to `IRequest<CommandResult>` ?

I'm not sure if that would work then on the type resolution... Anyway, I would suggest you to not abuse the Inheritance... what you're doing is not really a good design in the terms of the base inheritance rules. You should only derive type B from a type A if the type B **is** a type A.

What you have here is like a Truck inherianting from a Car. they're similar, just not exactly the same.

If you do want to keep using it with inheritance, try to find a middle ground then, create a shared class for all the properties and interfaces, just not the IRequest's ones, let your command to inherit from that shared and mark the IRequest interfaces themselves.

Personally I do not like to reuse this stuff.. Along the time, there is always something that needs to be added to only one of the cases and it ruins all the inheritance chain. Of coure, the same inverse argument can be used to favor inheritance on adding shared behavior.

It's like reusing ViewModels. I really prefer to use one per action, even if the actions are really very similar.

**Comment by jbogard** [comment]
Yeah, don't make the base class implement `IRequest`. It's not a request. Only make the most derived types actually implement that interface, UNLESS you're doing generic types so then it's the closed type that completes the `IRequest<T>` type.
