### ISSUE TITLE
Forced to have entity id on request object when I would like it on the side

### ISSUE THREAD

**Issue by lindeberg** [jbogard/MediatR#271]
For edit actions to me it doesn't make sense to put the entity id on the request object since it is not something the user can change anyway. I usually structure my actions like this instead:

```
 [HttpPost]
 public IActionResult Edit(Edit.Command command, int id)
{
    // Usually I would go
    var user = _db.Users.Find(id);
    _mapper.Map(command, user); 

    // But how is this possible with MediatR? Possibly add parameters?
    _mediator.Send(command, new { Id = id});
}
```

**Comment by jbogard** [comment]
In the first example just set the ID on the command DTO from the action
parameter. Just let the model binding partially fill the object. We do this
frequently to fill the request from multiple sources.

**Comment by lindeberg** [comment]
@jbogard Sorry, I'm not sure I understand what you mean, could you elaborate or give an example? 😃

**Comment by jbogard** [comment]
```c#
command.Id = id;
await _mediator.Send(command);
```

Just set the additional properties before sending.

**Comment by jbogard** [comment]
```

command.Id = id;
await _mediator.Send(command);

```

Just set the additional properties before sending.

**Comment by lindeberg** [comment]
Right, this works, but just feels weird, you also gotta remember to do that step, which I remember someone wise saying is a smell :P

I know very little about the underlying mechanisms of MediatR so I cannot argue for my idea of parameters since I don't know the cons.

**Comment by jbogard** [comment]
You could do some kind of pre processor in the pipeline, but that’s a bit
magic for my taste.

In any case, they could “change” the ID no matter what, it’s a request
variable, you’d still need to enforce authorization that they can change
that resource. This isn’t a problem that MediatR introduced.

**Comment by lindeberg** [comment]
Yeah I will still do resource based authorization for sure. I just don't like having to perform two extra steps that I otherwise wouldn't - setting the id on the request object in the controller and ignoring the key in mapping.

Boils down to personal preference so I'll close. Thanks for quick response!

**Comment by jbogard** [comment]
You don’t have to do the extra set, can’t model binding take care of it?

**Comment by lindeberg** [comment]
Oh, probably! I've never done custom model binding before tbh.

**Comment by jbogard** [comment]
If it’s WebAPI then you can try the attributes like FromBody etc
