### ISSUE TITLE
Unit of Work Decorator

### ISSUE THREAD

**Issue by andrewduffy77** [jbogard/MediatR#272]
Hi Jimmy,

A quick question I'm trying to utilise a unit of work decorator as detailed at the bottom of this article https://lostechies.com/derekgreer/2015/11/01/survey-of-entity-framework-unit-of-work-patterns/

The idea is that all my Mediatr handlers are decorated by a handler which handles the creation and commit/rollback of a unit of work implicitly..

Have you got or seen some code snippets using Autofac, Mediatr and EF which may point me in the right direction?

Mediatr is great by the way... awesome stuff

Andrew

**Comment by joaomatossilva** [comment]
What if you have notifications that do also need to write or read from database? your context may already be disposed with this design.

But, the guidelines shouldn't be very diferent from these ones:
https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples/GenericPipelineBehavior.cs

Just replace the writting of the request starting and finishing with the dbContext initialization or the start of the transactions, encolse the `await next()` on a try catch, and commit afterwards or rollback if an exception is thrown.

Personally I really don't have issues with the dbcontext being configured per request and being injected on the handlers directly. I don't mind the need to be calling the SaveChanges when I need to.

You can also find some examples of using implicit transaction on Jimmy's example https://github.com/jbogard/ContosoUniversity/blob/master/src/ContosoUniversity/Infrastructure/DataAccess/MvcTransactionFilter.cs
