### ISSUE TITLE
Any way to replicate the 4.0 Unit-less interface behavior?

### ISSUE THREAD

**Issue by geirsagberg** [jbogard/MediatR#275]
In 5.0, the signature for `IRequestHandler<TRequest>` is `Task<Unit> Handle(...)` rather than `Task Handle(...)`. I understand this was done to simplify the internals and only require a single factory method, and that I can use the base class `RequestHandlerAsync<TRequest>`.

However, I often want to have the same handler class handle multiple related requests, e.g.:

```csharp
public class ArticleHandler : IRequestHandler<CreateArticleRequest, ArticleResult>,
  IRequestHandler<GetArticleRequest, ArticleResult>,
  IRequestHandler<UpdateArticleRequest>,
  IRequestHandler<DeleteArticleRequest> {

  ...

  public ArticleHandler(IMapper mapper, DataContext context, ILogger logger) {
    ...
  }

  public async Task<ArticleResult> Handle(CreateArticleRequest request) {
    ...
    return result;
  }

  public async Task<ArticleResult> Handle(GetArticleRequest request) {
    ...
    return result;
  }

  public async Task Handle(UpdateArticleRequest request) {
    ...
  }

  public async Task Handle(DeleteArticleRequest request) {
    ...
  }
  
```

In 5.0, I have to change this to:

```csharp
public class ArticleHandler : IRequestHandler<CreateArticleRequest, ArticleResult>,
  IRequestHandler<GetArticleRequest, ArticleResult>,
  IRequestHandler<UpdateArticleRequest>,
  IRequestHandler<DeleteArticleRequest> {

  ...

  public ArticleHandler(IMapper mapper, DataContext context, ILogger logger) {
    ...
  }

  public async Task<ArticleResult> Handle(CreateArticleRequest request) {
    ...
    return result;
  }

  public async Task<ArticleResult> Handle(GetArticleRequest request) {
    ...
    return result;
  }

  public async Task<Unit> Handle(UpdateArticleRequest request) {
    ...
    return Unit.Value;
  }

  public async Task<Unit> Handle(DeleteArticleRequest request) {
    ...
    return Unit.Value;
  }
  
```

Is there any way I could add some custom code, e.g. a new interface and factory method, to avoid having to introduce the extra `Unit` code?

**Comment by geirsagberg** [comment]
> Why do you want to have a handler class implement multiple handlers?

Usually because the handlers are very closely related; e.g. CRUD of a single entity type. They all use the same dependencies, and having a handler for each one of them would be more boilerplate. Sometimes they also share internal logic methods.

**Comment by jbogard** [comment]
There's really not a workaround here. I had to make the interface change because having two interfaces would have meant two pipelines, two sets of processors etc. I think your best option is to unwind the multiple implementations, and instead of doing multi-inheritance, do composition. If there's shared logic, put that shared logic into an explicit dependency rather than multi-inheritance.
