### ISSUE TITLE
Incorrect find and replace values in Migration Guide 4.x to 5.0

### ISSUE THREAD

**Issue by ojraqueno** [jbogard/MediatR#276]
Migration Guide here: https://github.com/jbogard/MediatR/wiki/Migration-Guide-4.x-to-5.0

I believe the method names under the Find column should be HandleCore instead of just Handle.

By the way, please tell me if there was a better way to report this issue.

**Comment by jbogard** [comment]
It’s a wiki, just fix it :)

**Comment by ojraqueno** [comment]
I'm embarrassed to admit that I don't know how T_T I'll research and do it :) Also, thank you for creating this wonderful library!

**Comment by ojraqueno** [comment]
Oh, there's an edit button. Ok.

**Comment by ojraqueno** [comment]
I changed the first row. I'm not sure about the other two rows because I don't have methods with those signatures though. Thanks again!
