### ISSUE TITLE
Should TResponse RequestHandler<TRequest, TResponse>.Handle(TRequest) be public instead of protected? 

### ISSUE THREAD

**Issue by olivermue** [jbogard/MediatR#279]
Just updated from 4.1.0 to 5.0.1 without any bigger issues. 😄 

The biggest manual stuff was adding the `using System.Threading`, cause the `CancellationToken` is needed as parameter and wasn't needed before, but it took less then writing this issue for another case.

A lot of unit tests are having a scheme like this:

    // Prepare mocks, etc.
    // ...

    // Prepare request and handler
    var request = new MyRequest { ... };
    var handler = new MyRequestHandler(dependecyOne, dependencyTwo);

    // Call handler
    var response = await handler.Handle(request, CancellationToken.None);

    // Verify response (however you like)
    response.ShouldNotBeNull();

A bunch of handlers derives from `RequestHandler<TRequest, TResponse>` which holds the `Handle()` method as `protected` instead of `public`. This makes it necessary to explicitly cast the class to the corresponding interface just for the test:

    var handler = (IRequestHandler<MyRequest, MyResponse>))new MyRequestHandler(dependecyOne, dependencyTwo);

Due to the fact that `RequestHandler<TRequest, TResponse>` implements `IRequestHandler<TRequest, TResponse> where TRequest : IRequest<TResponse>` it doesn't make sense to hide the method, cause it is the same that's been called when casted to the interface.

So is there any special reason why this method is `protected` and not `public`? Otherwise I would propose to change this.

**Comment by joaomatossilva** [comment]
It's not the same method.

By calling the interface cast, you're really calling this:

    Task<TResponse> IRequestHandler<TRequest, TResponse>.Handle(TRequest request, CancellationToken cancellationToken)
            => Task.FromResult(Handle(request));

That is the one that calls the protected one but wrapped on a `Task.FromResult` for a non-Async signature.

You can't call the async directly because it's marked interface explicitly and it's not public.

Instead of cast, you could just type it:

    IRequestHandler<MyRequest, MyResponse> handler = new MyRequestHandler(dependecyOne, dependencyTwo);

But that's just another way to write the same thing.

I don't think the non-async method should be public, but I also don't know the reason why the interface one is not public. Maybe because of historical reasons when they both had the same signature (except for the return type) and ence causing overload collapse.

**Comment by olivermue** [comment]
Ah okay. Yes I really missed that the protected method was sync instead of async. But then I would propose (like you already mentioned) to make the interface method public and not explicit to avoid the cast.

**Comment by joaomatossilva** [comment]
I don't know.
the change was done intencionally.

https://github.com/jbogard/MediatR/commit/d858b7d9bfd7e0fe881aed4cf443e9434257536b#diff-d451e8a46a90d41d16aafabc3fe22945R63

**Comment by olivermue** [comment]
Just tried to change the signature. For `RequestHandler` and it builds and all tests succeeded. BUT the problem is the `AsyncRequestHandler`. Just to handle everything the same it should also publicity implement the interface. Unfortunately it will differ from the protected abstract method only in the return type (`Task<Unit>` vs. `Task`), thous leading to an ambiguous call (or back to suffix the abstract methods with `Core`).
So from a designer perspective it makes absolutely sense to come to this solution, but from a library consumer perspective this makes me unhappy. Seems like there must be someone disappointed. And this time it's me. 😉
