### ISSUE TITLE
Possibility to run notification handlers non-concurrently

### ISSUE THREAD

**Issue by kvakulo** [jbogard/MediatR#280]
I'm trying to coordinate several notification handlers, but I run into concurrency issues related to the database context, because notifications handlers are executed concurrently.

Here's a basic example of what I would like achieve. After some change has been made to Entity, I'd would like one or more notification handlers to also be able to make changes to or related to the entity. It's the same instance of `context` that's being injected into all of the handlers.

```csharp

public class UpdateEntityHandler : IRequestHandler<Request>
{
    public UpdateEntityHandler(DbContext context)
    {...}

    public async Task<Result> Handle(Request request, CancellationToken token)
    {
        var entity = await _context.FindAsync<Entity>(request.id);
        entity.Value = request.Value;
        await _context.SaveChangesAsync();

       await _mediator.Publish(new EntityUpdated { Entity = entity });
    }
}

public class FirstEntityUpdatedHandler : INotificationHandler<EntityUpdated>
{
    public FirstEntityUpdatedHandler(DbContext context)
    {...}

    public async Task Handle(EntityUpdated notification, CancellationToken cancellationToken)
    {
        var entity = notification.Entity;
        entity.Updated = DateTime.UtcNow;
        await _context.SaveChangesAsync();
    }
}

public class SecondEntityUpdatedHandler : INotificationHandler<EntityUpdated>
{
    public SecondEntityUpdatedHandler(DbContext context)
    {...}

    public async Task Handle(EntityUpdated notification, CancellationToken cancellationToken)
    {
        var entity = notification.Entity;
        entity.User = UserContext.User;
        await _context.SaveChangesAsync();
    }
}

```

In the `NotificationHandlerWrapperImpl` in MediaR all the notification handlers are called
(https://github.com/jbogard/MediatR/blob/master/src/MediatR/Internal/NotificationHandlerWrapper.cs#L19-L23), and in this way they will run concurrently.

My questions are: Is there someway to instruct MediaR to run notification handlers one after another? Should it be possible? Or is this simply a wrong usage of the notifications?

**Comment by jbogard** [comment]
In the Mediator class you can override a method to dispatch one at a time.

**Comment by kvakulo** [comment]
Thanks for your fast reply @jbogard  👍 

I got it working by overriding `PublishCore`:

```csharp
internal class CustomMediator : Mediator
{
	public CustomMediator(ServiceFactory serviceFactory) : base(serviceFactory)
	{
	}

	protected override async Task PublishCore(IEnumerable<Task> allHandlers)
	{
		foreach (var handler in allHandlers)
		{
			await handler;
		}
	}
}
```
