### ISSUE TITLE
Is there any way to use MediatR with Funq in ServiceStack app ?

### ISSUE THREAD

**Issue by cakpament** [jbogard/MediatR#283]
Hi!

I'm supporting some asp.net application that based on the ServiceStack.
There is some task (refactoring) to apply MediatR and SimpleInjecter.

I'm newer in this theme, so i need some code examples. 

P.S Please don't throw at me a sneaker, this is my first action on gitHub ))

Thanks!

**Comment by jbogard** [comment]
I'm completely unfamiliar with Func and ServiceStack. If you want ASP.NET Core examples, check out my GitHub profile for "ContosoUniversityXyz" repositories. That might help point the way!
