### ISSUE TITLE
Distinguish Command and Query PipelineBahaviors

### ISSUE THREAD

**Issue by jtourvieille** [jbogard/MediatR#284]
Is it possible to distinguish two PipelineBehavior?
For instance, I have a ```ValidatorBehavior```, which is only applicable to Commands. I don't want it to be applicable to Queries. On the other hand, I want to be able to apply specific behaviors on Queries. Finally, I would like to apply some behavior to both sodes (Logging for instance).
Trying to use generic constraint on the behaviors I'd like to make specific renders a ```NullReferenceException```

Here is the declaration of the behavior
```
public class ValidatorBehavior<TRequest, TResponse>
        : IPipelineBehavior<TRequest, TResponse>
        where TRequest : ICommand
```
With the command
```
public class CreateWhateverCommand : IRequest<bool>, ICommand
```
The behavior is registered like this
```
services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidatorBehavior<,>));
```
And finaly, pipeline is called through
```
var commandResult = await _mediator.Send(createWhateverCommand);
```

When sending the command to the mediator, A ```NullReferenceException``` is thrown with this stack trace
```
at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_1.<handle>b__2()
at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
```

Note that removing the ```where TRequest : ICommand``` constraint on the ValidatorBehavior class definition solves the issue: no exception thrown, and pipeline accessed normally.

**Comment by joaomatossilva** [comment]
I've tryed to replicate your behavior, and what I got is a TypeLoadException when requesting a type that do not respect the constraint.

And this is the same issue as seen in 

* https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/issues/12
* https://github.com/aspnet/Home/issues/2341

I'm not 100% sure, but I think it's a limitation of the Container you're using. Some of them just don't support Constrains.
check here for a compatibility list: https://github.com/jbogard/MediatR/wiki/Container-Feature-Support

**Comment by jbogard** [comment]
It's up for consideration to support constraints in the built-in container, so that's something?

**Comment by jtourvieille** [comment]
As an additional information, I can say that my DI is Microsoft.Extensions.DependencyInjection.

The only solution I found for now is to remove the constraint on the ```ValidatorBehavior``` and check the type of the request in the Handle method:
```
public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
{
    if (request is IQuery)
    {
        return await next();
    }
    if (request is ICommand)
    {
        // process validation
    }
}
```

**Comment by bartosz6** [comment]
It's limitation of DI container you're using. 
https://github.com/aspnet/DependencyInjection/issues/471

**Comment by jtourvieille** [comment]
Thanks guys, I'm waiting for the 2.2 version of DependencyInjection to solve this issue.

**Comment by dasiths** [comment]
This still happens if you have multiple pipeline behaviors and one of those has a type constraint. Even with the MSDI 2.2 fix
