### ISSUE TITLE
RequestPostProcessorBehavior does guarantee execution order as implied by the samples

### ISSUE THREAD

**Issue by n-j-m** [jbogard/MediatR#288]
In the samples there is the following bit of code:

```C#
//...
contents.IndexOf("- All Done", StringComparison.OrdinalIgnoreCase),
contents.IndexOf("- All Done with Ping", StringComparison.OrdinalIgnoreCase),
//...
```
followed by:
```C#
//...
OrderedPipelineBehaviors = order.SequenceEqual(order.OrderBy(i => i)),
//...
```
Those two lines of text are written by `GenericRequestPostProcessor` followed by `ConstrainedRequestPostProcessor`.  the `OrderedPipelineBehaviors` property of `RunResults` indicates that these two post processor behaviors are guaranteed to run in that order.

However, `RequestPostProcessorBehavior` executes all `IRequestPostProcessor`s asynchronously.  That means if `GenericRequestPostProcessor` takes longer to run than `ConstrainedRequestPostProcessor`, the order in which those two lines appear will be reversed.  I also found that `OrderedPipelineBehaviors` falsely reports `Y` even when `ConstrainedRequestPostProcessor` completes before `GenericRequestPostProcessor` since `IndexOf("- All Done",...)` reports the same index for both lines `"- All Done"` and `"- All Done with Ping"`.

I'm not sure if the intent of the `RequestPre/PostProcessorBehavior` classes is to execute all Pre/Post Processor Behaviors in sequence.  I'm cool with it being left up to the developer to implement.  The Wiki should probably be updated to state that execution of `IRequestPostProcessors` is asynchronous and order of completion is not guaranteed.  And the samples should probably be updated to remove the `OrderedPipelineBehaviors` bug.

See [this gist](https://gist.github.com/n-j-m/68d39f7a4c81383831534d4c71af6652) for the code to reproduce the issues in the samples.

**Comment by jbogard** [comment]
Probably because of this:

https://github.com/jbogard/MediatR/blob/master/src/MediatR/Pipeline/RequestPostProcessorBehavior.cs#L26

I could supply additionl behaviors that loop over them in order.
