### ISSUE TITLE
How to disambiguate Commands and Queries?

### ISSUE THREAD

**Issue by Korijn** [jbogard/MediatR#29]
I get that Commands and Queries are basically just Requests, and that they both follow very similar structures.

Now, I want to decorate my CommandHandlers so that they automatically Commit after they complete. I don't want to do this for my Queries, obviously.

Using MediatR all I see are IRequest and IRequestHandler objects. I'd like to disambiguate between Commands and Queries so that I can decorate only Commands. Have you done this before? How did you tackle this?

**Comment by jbogard** [comment]
You can do this yourself:
```
public interface ICommand<out TResponse> : IRequest<TResponse> { }
public interface IRequestTransaction<in TRequest, out TResponse> {
    void Commit();
    void Rollback();
}
```
Then in a pipeline do something like:
```
public class MediatorPipeline<TRequest, TResponse> : IRequestHandler<TRequest, TResponse> {
    public MediatorPipeline(IRequestHandler<TRequest, TResponse> inner,
        IRequestTransaction<TRequest, TResponse> txn)
    { /* capture in fields */ }

    public TResponse Handle(TRequest request) {
        TResponse response;
        try {
            response = _inner.Handle(request);
            _txn.Commit();
        } catch {
           _txn.Rollback();
           throw;
        }
        return response;
    }
}
```
Then create the implementations for Command/Query transactions, and make your commands/queries inherit your new interfaces.

Or just commit transactions, everything is in a transaction anyway.

**Comment by michielrutting** [comment]
Just out of curiosity, do you generally create a distinction between commands and queries at the interface level in your projects?

I've just used IRequest<> as is so far and used a class naming convention to make it more obvious what is what.

I can see how the ICommand interface could be useful for things like wrapping a transaction around all commands, but I figured there's other ways to achieve this. For authorization I check for the presence of an AuthorizeAttribute on the request in the pipeline and authorize based on that. I was planning to use a similar approach for caching and transactions.

**Comment by jbogard** [comment]
No, I don't other than the names.

**Comment by eddiegroves** [comment]
I'm thinking of doing something similar with custom Attributes to mark and provide meta data about cross cutting concerns that I don't want applied to every Command/Query.

I came across [this example](http://stackoverflow.com/a/19808445/5769) when searching for ideas. 

The gist is:

```
public sealed class CachingQueryHandlerDecorator<TQuery, TResult>
    : IQueryHandler<TQuery, TResult>
    where TQuery : IQuery<TResult>
{
    private static readonly bool shouldCache;
  
    static CachingQueryHandlerDecorator()
    {
        var attribute = typeof(TQuery).GetCustomAttribute<CachePolicyAttribute>();

        if (attribute != null)
        {
            shouldCache = true;     
        }
    }

    public TResult Handle(TQuery query)
    {
        if (!shouldCache)
        {
            return this._handler.handle(query);
        }

        // do your caching stuff here.
    }
```

Does this approach look like the way to go? I should be easy to adopt with MediatR.

**Comment by michielrutting** [comment]
This is the way I have done it and it has worked out fine for my purposes so far.

Works for caching, authorization, and probably many other scenarios.

I validate the requests in a decorator as well, but that is depends on whether a FluentValidation validator is registered for the type instead of an attribute.

**Comment by jbogard** [comment]
Attributes look interesting, I could even imagine the caching attribute having parameters attached to it.

Though honestly, I typically plug in my caching at the ORM layer.
