### ISSUE TITLE
Casting exception when multiple `IRequest<TResponse>` interfaces are implemented on a single request object

### ISSUE THREAD

**Issue by smolyakoff** [jbogard/MediatR#290]
I'm trying to use the same request object with different response types. Here is a sample code that throws an `InvalidCastException` with the latest version of MediatR.

```csharp
using System;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Autofac;
using MediatR;

namespace MultipleResponseTypesMediatrBug
{
    public class Hello : IRequest<Hi>, IRequest<Bye>
    {
    }

    public class Hi
    {
    }

    public class Bye
    {
    }

    public class HiHandler : IRequestHandler<Hello, Hi>
    {
        public Task<Hi> Handle(Hello request, CancellationToken cancellationToken)
        {
            return Task.FromResult(new Hi());
        }
    }

    public class ByeHandler : IRequestHandler<Hello, Bye>
    {
        public Task<Bye> Handle(Hello request, CancellationToken cancellationToken)
        {
            return Task.FromResult(new Bye());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Run().Wait();
        }

        static async Task Run()
        {
            var builder = new ContainerBuilder();
            builder.RegisterAssemblyTypes(typeof(IMediator).GetTypeInfo().Assembly).AsImplementedInterfaces();
            builder.Register<ServiceFactory>(ctx =>
            {
                var context = ctx.Resolve<IComponentContext>();
                return type => context.Resolve(type);
            });
            builder
                .RegisterAssemblyTypes(typeof(Hi).GetTypeInfo().Assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>))
                .AsImplementedInterfaces();
            var container = builder.Build();

            var mediator = container.Resolve<IMediator>();
            try
            {
                var hi = await mediator.Send<Hi>(new Hello());
                Console.WriteLine(hi);
                var bye = await mediator.Send<Bye>(new Hello());
                Console.WriteLine(bye);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            Console.ReadLine();
        }
    }
}
```

It's happening because internally MediatR caches handler wrappers by request type. To support the mentioned use case, something like `Tuple<RequestType, ResponseType>` should be used instead as a key. 

[MultipleResponseTypesMediatrBug.zip](https://github.com/jbogard/MediatR/files/2183311/MultipleResponseTypesMediatrBug.zip)

**Comment by bartosz6** [comment]
It's throwing by design. You should not reuse requests. 1 request = 1 handler.

**Comment by smolyakoff** [comment]
Then it might be a good idea to mention this somehow in the Wiki. What is not prohibited - that is allowed 😄

**Comment by jbogard** [comment]
The wiki is editable by anyone, feel free to add what makes sense. I think this is the first time this has come up - I never thought of anyone trying to make a class be two requests. Even the `IMediator` interface is designed so that you don't have to specify the response type.

If you have some common set of data between two requests, you can always create an abstract base class with all the members, then specific request types:

```c#
public abstract class FooBaseRequest {
}

public class FooRequest : FooBaseRequest, IRequest<Foo> { }
public class BarRequest : FooBaseRequest, IRequest<Bar> { }
```

**Comment by maheepjyot** [comment]
Clone the code from here: https://github.com/jbogard/MediatR.git
Add class     RequestResponsePair
```
internal class RequestResponsePair
    {
        public Type TRequest { get; set; }
        public Type TResponse { get; set; }
    }
```

update the Mediator.cs file with below changes

    /// <summary>
    /// Default mediator implementation relying on single- and multi instance delegates for resolving handlers.
    /// </summary>
    
       private static readonly ConcurrentDictionary<RequestResponsePair, object> _requestHandlers = new ConcurrentDictionary<RequestResponsePair, object>();
        
        public Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)
        {
            if (request == null)
            {
                throw new ArgumentNullException(nameof(request));
            }
            var requestType = new RequestResponsePair()
            {
                TRequest = request.GetType(),
                TResponse = typeof(TResponse)
            };
            var handler = (RequestHandlerWrapper<TResponse>)_requestHandlers.GetOrAdd(requestType,
                t => Activator.CreateInstance(typeof(RequestHandlerWrapperImpl<,>).MakeGenericType(requestType.TRequest, typeof(TResponse))));
            return handler.Handle(request, cancellationToken, _serviceFactory);
        }

Build the code and use this new DLL, I hope this will solve your problem
