### ISSUE TITLE
Should enumerable tasks default to one-at-a-time?

### ISSUE THREAD

**Issue by jbogard** [jbogard/MediatR#291]
Instead of today being `Task.WhenAll`. It seems this default causes more problems than it solves. See #288

**Comment by bartosz6** [comment]
How about making it configurable?

**Comment by jbogard** [comment]
I just made the methods virtual in my PR, would that be sufficient?

**Comment by bartosz6** [comment]
I think its fair enough. It is the only way to avoid breaking changes.

**Comment by jbogard** [comment]
I like the idea of configuring but without introducing some kind of
factory, not all containers would play nice with the new constructors.

**Comment by sm-g** [comment]
@jbogard Could you publish nuget with recent changes (without `Task.WhenAll`)? I think that could be reason of 
```
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
```

**Comment by jbogard** [comment]
@sm-g pushed today, 5.1.0
