### ISSUE TITLE
Missing regex for find and replace upgrade from 4.x to 5.0

### ISSUE THREAD

**Issue by Hallmanac** [jbogard/MediatR#295]
I discovered one area that was not addressed in the "4.x to 5.0" upgrade guide. It is for `AsyncNotificationHandler<T>`. The regex I used was:

Find:
```: AsyncNotificationHandler<(.*)>```
 
Replace:
```: INotificationHandler<$1>```

Thanks for such a great library!

**Comment by jbogard** [comment]
It’s a wiki, you can add whatever’s missing. Thanks!

**Comment by Hallmanac** [comment]
Oh, sorry. I didn't realize that. I'll add it. Thank you!
