### ISSUE TITLE
UserManager<ApplicationUser> and IMediatR

### ISSUE THREAD

**Issue by MunkeyTH** [jbogard/MediatR#297]
I have an issue that the UserManager injected into the mvc controller with IMediatR errors..."The task was cancelled"

This works fine in other controllers, and IMediatR is working fine.

Btw, love the MediatR way of doing things!

![imediatr and usermanager](https://user-images.githubusercontent.com/39886439/43125299-811b0ae6-8f21-11e8-9b6e-a684f85e1291.png)

**Comment by joaomatossilva** [comment]
Are you using the version 5.x?
If so, that _mediator.Send is async, and you aren't waiting for it to complete. Instead you're returning directly the result of the MVC action, and so, terminating the request.

Meanwhile the execution of the handling has been called, and since the main thread is not waiting for it complete, it get's terminated while the handling is still in the middle of it's execution.

Can't you make the action async and go async all the wait? By that I mean, await on the FindByNameAsync and await the mediator.Send.

You code doesn't makes much sense wither (with `var user` is never used) but I'll assume that was just a test and make up to post the issue code.

**Comment by MunkeyTH** [comment]
Thanks for the reply. Yes using 5.x and the var _user is just a test. In the command I want ask to the UserManager so I can loop the user list and unlock them by Id (string array of Id) however when I use IMediatR and and try to access the usermanager is crashes. What am I missing??

string[] _users = request.UsersToUnlock;

            foreach (var u in _users)
            {
   try
                {
                    var _userToUnlock = await _userManager.FindByIdAsync(u);

                    if (_userManager.IsLockedOutAsync(_userToUnlock).GetAwaiter().GetResult())
                    {
                        var user = _userManager.SetLockoutEndDateAsync(_userToUnlock, null);
                    }
                }
                catch (Exception ex)
                {
                    FrameworkDI.Logger.LogErrorSource($"Unable to unlock user { u }", (int)CodeErrors.EventIdCodes.e1019, ex);
                }
            }

**Comment by joaomatossilva** [comment]
You're missing many things..

First, you action should be marked as asyc.

    public async Task<IActionResult> UnlockUser(string[] users)

Second, you should await the mediator

    await _mediator.Send(new UnlockUserscommand(users));

Third, you should await IsLockedAsync (and not use the GetAwaiter().GetResult())

    if(await _userManager.IsLockedoutAsync(_userToUnlock)))

Forth, you should await SetLockoutEndDateAsync

    var user = await _userManager.SetLockoutEndDateAsync(_userToUnlock, null);

Fifth, you should add ConfigureAwait(false) on all await calls

Sixt, Make sure your command handler is Async.

**Comment by MunkeyTH** [comment]
wow...thanks feel like I have been told off by my teacher at school (Must Try Harder) LOL. Ok I will mod the code and see if this helps however If I take the ImediatR calls and I can access the UserManager object fine.

**Comment by joaomatossilva** [comment]
The rule of thumb is that when you're using async, you should go async/await all the way. from the action to all the methods inside.

and avoid using those GetWaiters() .Result, .Wait() things that can cause deadlocks on your application.

**Comment by MunkeyTH** [comment]
Thanks, the getwaiter was left in when try to get it to work.

**Comment by MunkeyTH** [comment]
Ok Change all code...still not working. Just wont access the UserManager.
 Unable to unlock user c8017f89-2295-432c-98ef-416a48c72f86 [UnlockUsersCommandHandler.cs > Handle() > Line 40]
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByIdAsync(String userId, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Identity.UserManager`1.FindByIdAsync(String userId)
         at ATLAS.APPLICATION.UserManagement.Commands.UnlockUsersCommandHandler.Handle(UnlockUsersCommand request, CancellationToken cancellationToken)

**Comment by joaomatossilva** [comment]
It still seems to me you're returning the controller action early. and this is not MediatR specific.

**Comment by MunkeyTH** [comment]
Ok, FYI Its works out the box on a fresh vs web project so the issue is MY project.
