### ISSUE TITLE
Weakly typed Publish variant

### ISSUE THREAD

**Issue by robbaman** [jbogard/MediatR#299]
Sorry if this has been asked before, but is there a way to publish an event using a `Type` object instead of a strongly typed call?

I'm storing events in a database and in event of a failure these events are sent again after some time. At that point I only have a `Type` object and a deserialized object (of that particular type). I want to publish this event using MediatR, but the `Publish<T>(T notification)` method does not seem to have an overload that accepts a `Type` and an object of said type.

Am I missing something or is this just something that I'm going to have to write something custom for? Didn't see any mention of this in the Wiki and there doesn't seem to be an overload for this.

**Comment by jbogard** [comment]
There's not one for Send, either. This does seem useful - pull request perhaps?

**Comment by bartosz6** [comment]
Well I can't think of any other solution than creating some wrapper for your events, but it would require some custom handlig. Would be easier to overload Publish.
