### ISSUE TITLE
 AsyncRequestHandler<TRequest, TResponse>

### ISSUE THREAD

**Issue by Newmski** [jbogard/MediatR#301]
I am working on a project following the guidance from the ContosoUniversityDotNetCore project which uses MediatR 4.0.0.

Some of the code is using `AsyncRequestHandler<Query, Result>` which was removed in the "Consolidating some handlers; renamed some things for posterity" commit on 9th April.

Should I use the `RequestHandler<TRequest, TResponse>` instead or is there an asynchronous equivalent that will return a response?

**Comment by dmytrohridin** [comment]
@Newmski `RequestHandler<TRequest, TResponse>` contains Handle method that return Task, so you can use this handler

**Comment by Newmski** [comment]
So I should implement the `IRequestHandler `interface rather than inherit from `RequestHandler`?

**Comment by dmytrohridin** [comment]
Yes

**Comment by Newmski** [comment]
ok thanks
