### ISSUE TITLE
Impossibility to retrieve proper notification handler.

### ISSUE THREAD

**Issue by Nabrzmialy** [jbogard/MediatR#302]
>I have a problem that my event handler is not being executed by Mediator. Mediator cannot find handler for the event which derives from the base class. For the base class it is being found without troubles.
**Example:**
Let's assume that we have exemplary class structure. For FrogNotification the event handler won't work. For simple **AnimalNotification it works perfeclty fine.**:

```
public class AnimalNotification : INotification{}
public class FrogNotification : AnimalNotification{}
public class WolfNotification : AnimalNotification{}

public class EventPublisher : IEventPublisher
{
     private readonly IMediator _mediator;
     public EventPublisher(IMediator mediator)
     {
            _mediator = mediator;
      }

       public void Publish(INotification notification) // our notification is FrogNotification
      {
            _mediator.Publish(new FrogNotification ()).ConfigureAwait(false).GetAwaiter().GetResult();
            // or
            _mediator.Publish(notification).ConfigureAwait(false).GetAwaiter().GetResult();
            //both do not execute handler code
       }
}

public class AnimalEventHandler : IMessageHandler<AnimalNotification >
{
      public void Handle(AnimalNotification notification)
        {
            //do staff - it will never be executed
        }
}


```

**Comment by jbogard** [comment]
Your Publish method should be async and generic. Then it will work just fine.

Also see #300 that we're looking at.

And if you *need* to run async as sync, check out https://cpratt.co/async-tips-tricks/. Though I'd still caution against that - so many runtimes are async now I don't know why you'd intentionally go sync.

**Comment by lilasquared** [comment]
@jbogard I am only able to get this to work if I create handlers that have the same class hierarchy structure as the notifications (see #308).  Are you saying it should work as a generic?  Do you have an example somewhere of this?

**Comment by jbogard** [comment]
No, I don't really. You can see how folks do things like `IDomainEvent` sort of ideas. Lots of generic-fu, and only works if your container supports it.
