### ISSUE TITLE
MediatR and Microsoft.AspNetCore.OData for paging/filtering functionalities

### ISSUE THREAD

**Issue by OculiViridi** [jbogard/MediatR#303]
Hi!
I'm creating an API using **.NET Core 2.1** and your beautiful **MediatR** library! :smile:
I want to add some **paging** and **filtering** functionalities to my controller's methods and I was wondering if it is possible to use those offered by the `Microsoft.AspNetCore.OData` package (latest v7.0.1).
I tried to configure my controller as showed in some OData examples but I don't know if it can work out of the box...

My actual controller implementation:

```
[ApiVersion("1.0")]
[SwaggerTag("Test", Description = "Test desc.")]
public class TestController : BaseController
{
	[HttpGet]
	[ProducesResponseType((int)HttpStatusCode.OK)]
	public async Task<ActionResult<List<ArticleCode>>> ArticleCodes()
	{
		return await Mediator.Send(new GetArticleCodeListQuery());
	}

	[HttpGet]
	[ProducesResponseType((int)HttpStatusCode.OK)]
	public async Task<ActionResult<List<LogisticUnit>>> LogisticUnits()
	{
		return await Mediator.Send(new GetLogisticUnitListQuery());
	}
}
```

**Comment by bartosz6** [comment]
Unfortunately it will not work out of the box. You would have to bind queries bound by OData to MediatR queries.

**Comment by OculiViridi** [comment]
@bartosz6 Do you have any sample about how to do it? I didn't find anything around...

**Comment by bartosz6** [comment]
Easiest way - return IQueryable from your requests and use EnableQuery attribute. Paging will then occur after querying data from mediator.

Harder way - handle binding manually from ODataRoute or some other way.

I don't have much experience with OData and haven't heard about anyone trying to put this together.

**Comment by OculiViridi** [comment]
@bartosz6 

> Easiest way - return IQueryable from your requests and use EnableQuery attribute.

Following [these latest suggestions](https://blogs.msdn.microsoft.com/odatateam/2018/07/03/asp-net-core-odata-now-available/) about `Microsoft.AspNetCore.OData` package, the `IQueryable `return type is no longer needed and somewhere else I also red that it was some kind of bad practice indeed.
I'd really like to keep my MediatR pattern that seems really clean and in line with current suggested patterns.

> Harder way - handle binding manually from ODataRoute or some other way.

I've no experience at all with OData. I've only heard about it but never implemented with .NET and C#. So, if you have any further suggestions, they're welcome! 😄 

> haven't heard about anyone trying to use it with mediator

Do you know any other possible "standard" solution, apart from manually constructing my paging/filtering objects for each one of my entities?
