### ISSUE TITLE
Leveraging flow testing

### ISSUE THREAD

**Issue by thiagolunardi** [jbogard/MediatR#304]
I'm implementing Mediatr in a considerable complex system, as an approach to simplify execution flow per command triggered.

The idea is simple: A HTTP request fires a command request, that when it is finished its trigger an event, then the regarding event handler takes the decision to fires or not one or more cascading command requests.

But now I'm having some pain to write some tests, not related about the command request execution - as we have as a test sample here, which actually test the handler configuration - but I want to test that when a specific command request is fired, it is triggering one or another specific event, and the same for the event, so when an event is triggered, I want to assert that one or more command request was fired.

I expect to have something like [NSubstitute](http://nsubstitute.github.io/) does.

    var mediator = container.GetInstance<IMediatorTester>();
    var response = await mediator.Send(new CommandRequest { Message = "Ping" });

    mediator.Published().Event<CommandFinishedEvent>().Times(1);
    mediator.Sent().Request<LogCommandRequest>(cmd => cmd.Message == "Ping");

**Comment by bartosz6** [comment]
Can you register mocked handlers and check if they've been triggered?

**Comment by thiagolunardi** [comment]
No, because I want to test the handler's behavior. If I mock it, I will test the mock, not the handler itself.

**Comment by jbogard** [comment]
Are you wanting to test that a handler sends other requests/events?

**Comment by thiagolunardi** [comment]
@jbogard yes, I want to assert that a handler sends other requests, also with specific properties.

**Comment by jbogard** [comment]
In other times I've done this, I just create a fake implementation.

**Comment by thiagolunardi** [comment]
@stiankroknes I will try something like that.

@jbogard I will try to create a nice reusable tool and request a pull for you to share to all of us.
