### ISSUE TITLE
Issue with IPipelineBehavior<,>

### ISSUE THREAD

**Issue by t11omas** [jbogard/MediatR#307]
Hey,

I am having an issue with a GenericPipelineBehavior, which I am not sure is a MediatR issue or a IoC issue.
[MediatRIssue.zip](https://github.com/jbogard/MediatR/files/2370549/MediatRIssue.zip)

I have attached an example, when i register a generic pipline handler, it doesn't work and throws and array exception.

Any assistance would be much appreciated.

Cheers,
Thomas

**Comment by bartosz6** [comment]
Please create gist for your example. I don't think anyone will download your zip.

**Comment by t11omas** [comment]
` public class DummyCommand
    {
        public string Value = "Test";
    }

    public class DummyResponse
    {
        public string Value = "Test";
    }

    public class CommandContext<TCommand, TResponse> : IRequest<TResponse>
       // where TResponse : class
    {
        public CommandContext(TCommand command)
        {
            this.Command = command;
        }

        public TCommand Command { get; }
    }

    public class CommandResult<TResponse>
    {
        public TResponse Result { get; }
    }

    public class CommandResult
    {
        public object Result { get; }
    }

 public class GenericTestCommandHandler<TCommand, TResponse> : IPipelineBehavior<CommandContext<TCommand, TResponse>, CommandResult<TResponse>>
        where TResponse : class
    {
        public Task<CommandResult<TResponse>> Handle(CommandContext<TCommand, TResponse> request, CancellationToken cancellationToken, RequestHandlerDelegate<CommandResult<TResponse>> next)
        {
            return next();
        }
    }'

**Comment by jbogard** [comment]
What does the registration code look like?

**Comment by t11omas** [comment]
` services.AddTransient(typeof(IPipelineBehavior<,>), typeof(GenericTestCommandHandler<,>));
            services.AddTransient<IPipelineBehavior<CommandContext<DummyCommand, DummyResponse>, CommandResult<DummyResponse>>, TestCommandHandler>();`

**Comment by jbogard** [comment]
And the exception?

**Comment by t11omas** [comment]
Its ok, it was just me being stupid :)
