### ISSUE TITLE
Mediator pipeline with notifications

### ISSUE THREAD

**Issue by afgallo** [jbogard/MediatR#31]
Hi @jbogard 

This isn't really an issue, it's more like a question.

I'd like to have my MediatorPipeline to publish notifications. I think the're a couple of different ways to achieve that and I thought of:

1. Publish notifications from my post request handlers.The advantage is I leave my Pipeline pretty lean with only request type of objects (pre, actual and post) and also validators. Example here: https://gist.github.com/afgallo/5fc2464ff4f15dd19bd3

2. Extend the pipeline to decorate with an object of type NotificationHandler. However, I'd have to change their contract so it obeys the generic variance and am not that familiar with it to be honest.

How would you do this? Is my example OK or have I completely missed the point here?

By the way, this is a fantastic library. It solves so many day-to-day problems that any consulting firms would charge you $$$$$ for it !

Thanks
Andre

**Comment by jbogard** [comment]
Lol well it seems too simple to charge for. I'd probably stick with post-request handlers I think. Another option is to have command handlers return some sort of Result object where you return a list of events along with the Result something like:

```
public class CommandResult<T> {
    public T Result { get; set; }
    public IList<object> DomainEvents { get; set; }
}
```

**Comment by afgallo** [comment]
Thanks Jimmy. I think I'll probably stick to the basics and inside my controller do:

    var result = _mediator.Send(command);
    _mediator.Publish(notification)
