### ISSUE TITLE
How do you create a lifetime scope per request?

### ISSUE THREAD

**Issue by ayoung** [jbogard/MediatR#313]
In the Autofac examples, we are told to register `Mediator` using `InstancePerLifetimeScope()`.

Is it ok to create to create a lifetime scope (for example per request or message) and then resolve the `Mediator` before sending the message?

```c#
using(var scope = container.BeginLifetimeScope())
{
  var mediator = scope.Resolve<IMediator>();
  await mediator.Send(request);
}
```

I have a situation where I would like to create a scope per request. Would this be the correct way to do it?

**Comment by jbogard** [comment]
Looks correct? I’m not an Autofac user though.

**Comment by jbogard** [comment]
Oh well if it’s ASP.NET Core it does this for you anyway.

**Comment by bartosz6** [comment]
There should not be any noticable performance drops. Handlers cache is static concurrent dictionary, so it should be shared anyway.
