### ISSUE TITLE
No AsyncRequestHandler<TRequest, TResponse>

### ISSUE THREAD

**Issue by lilasquared** [jbogard/MediatR#314]
Working through upgrading our application to v5 and noticed the abstract classes that our handlers could inherit from.  Wondering why there is no AsyncRequestHandler that allows returning something other than Unit.Value?  I can easily make my own, just curious why it's not included in the project.

**Comment by lilasquared** [comment]
nvm that's a dumb question

**Comment by thomaslevesque** [comment]
Well, if this class existed, it wouldn't do anything useful, but still, I think it would make sense to have it, if only to provide symmetry with `AsyncRequestHandler<TRequest>`. It's a bit puzzling at first when you realize it's not there.
