### ISSUE TITLE
Question: Implement a Business Logic before the Handler is called

### ISSUE THREAD

**Issue by coderabsolute** [jbogard/MediatR#315]
My handler is starting to get messy due to the complicated business logic I implement. Where is the best place to implement the business logic, any pattern is worth to consider?

I have also separated out the business logic to another service (other classes - where the business checks happen) but this delegation is currently being done from the Handler.

Am thinking the `Handler` shouldn't even be called unless all the business logic cases succeed, any thoughts? Between, am using ASP.NET Core API 2.0 with MediatR 5.1.0

**Comment by lilasquared** [comment]
@coderabsolute have you thought about or tried using a pipeline?  The pipelines can implement specific business logic based on the request data and then decide to or to not call the next handler in the pipeline.

**Comment by coderabsolute** [comment]
@lilasquared Yes - as a matter of fact am using a `IPipelineBehavior` for a generic logging. But again, not sure how to implement using a clean approach for the specific business logic using, for an example I want the Business Logic to get triggered before the CustomerAddHandler, SupplierAddHandler, etc is called. Maybe, am missing something obvious, a hint or an example would be extremely helpful.

**Comment by lilasquared** [comment]
Sure,  `IPipelineBehavior` can be scoped to particular types of requests.  For example:
```csharp
public class CustomerBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> 
    where TRequest : CustomerAddRequest
{
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        // perform some business logic using the request data
        if (businessLogic == true)
        {
            return await next();
        }
        return new FailureResult();
    }
}
```

the code might be a little off but something like that is what we use.

In one application that I work on all requests return a type of `IResult<T>` which is implemented by `SuccessResult<T>` and `FailureResult<T>`.  This way the calling code can then made decisions based on if the request failed or not.

**Comment by coderabsolute** [comment]
@lilasquared Thanks for the example, I managed to implement the PipelineBehavior and it works like a charm! Closing the issue. Cheers!
