### ISSUE TITLE
Cannot access method 'Handle' here due to its protection level

### ISSUE THREAD

**Issue by lilasquared** [jbogard/MediatR#316]
I've been working on upgrading to 5.1.0 and i wanted to use the abstract `RequestHandler` classes provided for our handlers that are not async, but I've hit a little snag.  I can't tell if it is just Visual Studio bugging out or something else going on.

Here is the code:
```csharp
public class SomeHandler : RequestHandler<SomeRequest, SomeResponse>
{
    protected override SomeResponse Handle(SomeRequest, request)
    {
        ...
    }
}
```
And this seems to work fine no problem.  Now here is the unit test.
```csharp
private SomeHandler _sut;
...
var response = await _sut.Handle(new SomeRequest(), CancellationToken.None);
```
This won't build, throwing the error in the title.  However, if I change this test to the following:
```csharp
private IRequestHandler<SomeRequest, SomeResponse> _sut;
...
var response = await _sut.Handle(new SomeRequest(), CancellationToken.None);
```
Then it works just fine.  Also, if I create my own implementation of RequstHandler like this:
```csharp
public abstract class QueryHandler<TRequest, TResponse> : IRequestHandler<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    public Task<TResponse> Handle(TRequest request,
                                    CancellationToken cancellationToken)
        => Task.FromResult(Handle(request));

    protected abstract TResponse Handle(TRequest request);
}
```
It works.  

So the question is: Is my test flawed; should I be testing against the interface, is the `RequestHandler` class flawed, OR is my Visual Studio just bunked and this should work just fine?

**Comment by bartosz6** [comment]
This behavior is correct. 

On 1st example you use protected (synchronous btw., await is incorrect here) method from your handler.
On 2nd example you use public wrapper from base class that wraps your protected sync handler with Task.FromResult. 

Here is the source -> https://github.com/jbogard/MediatR/blob/b3b819f05bed0da789791fec1d8b8a0168a85606/src/MediatR/IRequestHandler.cs#L63

**Comment by lilasquared** [comment]
The protected implementation is just where I’ve put my synchronous logic.  The public method on `RequestHandler` is still async and requires await. From a unit test perspective I thought I would still be testing the public method, but it doesn’t appear to be available.

**Comment by bartosz6** [comment]
It is not reachable from SomeHandler perspective because it is explicitly implemented from interface IRequestHandler<TRequest, TResponse>

**Comment by lilasquared** [comment]
Got it.  I haven't seen that syntax before so I didn't know that was the behavior.  Thanks for that info.  What is the benefit of doing it that way?
