### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type while attempting to activate 

### ISSUE THREAD

**Issue by dipak10** [jbogard/MediatR#322]
I am trying to implement MediarR in asp.net core i have created Request, Handler, Service, Interface but i am getting above mention error

Controller

```
 public async Task<IActionResult> Index()
 {
            var response = await mediator.Send(new DemoRequest());
            var viewModel = mapper.Map<DemoViewModel>(response);
            return View(viewModel);
 }
```

Request

`public class DemoRequest : IRequest<string>
    {
    }`

Handler

```
public class DemoRequestHandler : IRequestHandler<DemoRequest,string>
{
        private DemoService _demoservice;

        public DemoRequestHandler(DemoService demoservice)
        {
            _demoservice = demoservice;
        }

        public Task<string> Handle(DemoRequest request, CancellationToken cancellationToken)
        {
            return _demoservice.ReturnMessage();
        }
}
```

And here is my stack trace

MediatR.Internal.RequestHandlerBase.GetHandler<THandler>(ServiceFactory factory)
MediatR.Internal.RequestHandlerWrapperImpl<TRequest, TResponse>+<>c__DisplayClass0_0.<Handle>g__Handler|0()
MediatR.Internal.RequestHandlerWrapperImpl<TRequest, TResponse>.Handle(IRequest<TResponse> request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
MediatR.Mediator.Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken)
DemoApp.Controllers.DemoController.Index() in DemoController.cs
+
            var response = await mediator.Send(new DemoRequest());
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by lilasquared** [comment]
What are you using for registration?

**Comment by dipak10** [comment]
@lilasquared Unity for asp.net core
