### ISSUE TITLE
Should MediatR Create a Scope Per Handler?

### ISSUE THREAD

**Issue by heymega** [jbogard/MediatR#324]
I have an EventBusPublisher which is registered as a Singleton. I'm creating a scoped service in my EventBusPublisher to publish events like this...

           using (var scope = _serviceProvider.CreateScope())
            {
                // Deserialize event
                var dispatcher = scope.ServiceProvider.GetRequiredService<IMediator>();

                await dispatcher.Publish(@event, token);
            }

My NotificationHandlers that handle the Event contain a UnitOfWork which needs to be registered in as a scope (I don't want the unit of work being shared amongst my handlers). 

I've registered this via Microsoft.Extensions.DependencyInjection like so `services.AddScoped<IUnitOfWork, DocumentUnitOfWork>()`

The problem is that my Mediator Handler doesn't receive a scoped dependency. In fact, they are shared amongst all the other Mediator Handlers :(

I can't tell the `IServiceScope` to give me an `IUnitOfWork` because `MediatR` doesn't take this as an argument. Instead, I'm assuming, internally, `MediatR` uses `IServiceProvider` to resolve the dependencies of the Handler.

Should `Mediatr` not also create a scope per notification handler?

Thanks in advance.

**Comment by bartosz6** [comment]
Can you provide us more detailed info about your container registrations? MediatR does not use IServiceProvider explicitly, it uses ServiceFactory which you register in your startup.

**Comment by jbogard** [comment]
No, MediatR has no knowledge of `IServiceProvider`, you should create a scope yourself. Or, you can override the `Mediator` method to invoke a notification handler to wrap things in a scope.
