### ISSUE TITLE
No DI is registering the handlers, Interfaces have numbers appeneded to them

### ISSUE THREAD

**Issue by MercedeX** [jbogard/MediatR#325]
I'm trying to implement the IRequestHandler<> but when registering with DI container, none of them getting registered. Here's a snap of what I'm getting

![image](https://user-images.githubusercontent.com/13726779/48217467-4025d700-e3a9-11e8-8138-c9ad5a197a49.png)

due to these extra `1 `2 no DI container is registering them. I'm not sure why these numbers are appened to these interfaces, can you please help?

**Comment by lilasquared** [comment]
those numbers just mean that they are dynamic typed interfaces.  can you share your DI code?  There are many examples here as well https://github.com/jbogard/MediatR/tree/master/samples

**Comment by jbogard** [comment]
What DI container?
