### ISSUE TITLE
NotifcationHandler not firing

### ISSUE THREAD

**Issue by pnsullivan78** [jbogard/MediatR#336]
Cannot seem to get my notifcationHandler to fire.
Am I doing something stupid here?

public class TestNotificationHandler : INotificationHandler < TestNotification >
    {
        public async Task Handle(TestNotification notification, CancellationToken cancellationToken)
        {
            var name = notification.Name;

            Debug.Write("Notification");
        }
    }

public class TestCommandHandler : IRequestHandler<TestCommand, int>, IRequestHandler<TestCommand2, int>
    {
        private readonly IMediator _mediator;

        public TestCommandHandler(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<int> Handle(TestCommand request, CancellationToken cancellationToken)
        {
            var name = request.Name;

            _mediator.Publish(new TestNotification { Name = name }, cancellationToken).GetAwaiter().GetResult();

            Debug.WriteLine("From CommandHandler TestCommand");

            return 1;
        }

        public async Task<int> Handle(TestCommand2 request, CancellationToken cancellationToken)
        {
            Debug.WriteLine("From CommandHandler TestCommand2");

            return 2;
        }
    }

Container
private static void BuildMediator(TinyIoCContainer container)
        {
            var assemblies = GetAssemblies();
            container.Register<IMediator, Mediator>();

            container.Register(typeof(IRequestHandler<,>), typeof(TestCommandHandler)).AsMultiInstance();
            container.Register(typeof(INotificationHandler<>), typeof(TestNotificationHandler)).AsMultiInstance();

            container.Register<ServiceFactory>((ioc, p) => (ioc.Resolve));
        }

**Comment by pnsullivan78** [comment]
Thanks for reply.  Have tried that but same result.

await _mediator.Publish(new TestNotification {Name = name}, cancellationToken);

I'm raising the notification from a IRequestHandler which inturn fires no problems. Baffled.

**Comment by jbogard** [comment]
What does your container registration show? Does your container support
resolving directly from IEnumerable or does it have a special method for
enumerables that isn’t compatible with the regular resolution method?

**Comment by pnsullivan78** [comment]
Thanks for rely jimmy. Using TinyIoC. Regardless I tried the following no joy
var assemblies = GetAssemblies();
container.AutoRegister(assemblies, t => RegisterTypes.Any(it => it(t)));

 public static IEnumerable<Func<Type, bool>> RegisterTypes = new Func<Type, bool>[]
        {
            typ => typ.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(INotificationHandler<>)) && typ.IsClass
        };

but this works
container.RegisterMultiple<INotificationHandler<SendEjBekraftadNotification>>(new[] {typeof(EjBekraftadNotificationHandler)}).AsMultiInstance();

It will do.  Thanks for you help guys.
