### ISSUE TITLE
Feature request: Publishing asynchronous

### ISSUE THREAD

**Issue by thomai-d** [jbogard/MediatR#340]
Thanks for sharing your great and simple implementation.
Just one thing that makes me curious:

Why is the `Mediator.Publish()` implementation awaiting all handlers in a loop?

I'd suggest changing it to:

        protected virtual async Task PublishCore(IEnumerable<Func<Task>> allHandlers)
        {
            var tasks = allHandlers
                        .Select(h => h())
                        .ToArray();

            await Task.WhenAll(tasks);
        }

(Unit tests pass of course).

**Comment by jbogard** [comment]
Because most folks using MediatR on the web can't do parallel tasks. You can override this behavior, however, as that method is virtual.

**Comment by thomai-d** [comment]
What do you mean with "**can't do** parallel tasks"?

The current implementation uses `ConfigureAwait(false)`, so thread affinity might not the problem.

**Comment by jbogard** [comment]
Most folks use this in conjunction with something like EF6 or EF Core, and DbContext's aren't thread safe.
