### ISSUE TITLE
Sample to Xamarin with Prism/DryIoc

### ISSUE THREAD

**Issue by Wivison** [jbogard/MediatR#341]
Does anyone have any examples of how to register dependencies using Xaramin with Prism and DryIoc? I looked at the DryIoc example available here, but it's different in Prism with DryIoc.

I tried to register the types there, but the application simply stops working and gives NullReference. I do not think I know how to do it properly.

Thank you in advance!

**Comment by Argent78** [comment]
I'm currently using mediator with Xamarin, Prism & DryIoC. Here's what works for me:

In App.xaml.cs:

	protected override void RegisterTypes(IContainerRegistry containerRegistry)
	{
		var container = containerRegistry.GetContainer();

		container.RegisterDelegate<ServiceFactory>(r => r.Resolve);
		container.RegisterMany(new[] { typeof(IMediator).GetAssembly() }, Registrator.Interfaces);
		container.RegisterMany(typeof(MyMediatorHandler).GetAssembly().GetTypes().Where(t => t.IsMediatorHandler()));

		container.Register(typeof(IPipelineBehavior<,>), typeof(RequestPreProcessorBehavior<,>)); 
		container.Register(typeof(IPipelineBehavior<,>), typeof(RequestPostProcessorBehavior<,>)); 

		containerRegistry.RegisterForNavigation<NavigationPage>();
		// more view registrations here
	}

		
	public static class ContainerExtensions 
	{
        public static bool IsMediatorHandler(this Type arg)
        {
            //Ugly hack to limit assembly registration to request handlers only
            return arg.GetInterfaces().Where(i => i.Name.StartsWith("IRequestHandler")).Any();
        }
    }

**Comment by Wivison** [comment]
@Argent78 Thank you very much. I'll test now.

**Comment by Wivison** [comment]
@Argent78  Worked perfectly! Thank you again!

**Comment by cocowalla** [comment]
@Argent78 I'm interested in how Mediatr can be used with Xamarin and Prism, with the aim of having "clean" view models, so that everything testable is in mediatr handlers that don't depend on any framework (i.e. Xamarin).

I don't support you have any code online that demonstrates this?

**Comment by cocowalla** [comment]
@Argent78 I'm interested in how Mediatr can be used with Xamarin and Prism, with the aim of having "clean" view models, so that everything testable is in mediatr handlers that don't depend on any framework (i.e. Xamarin).

I don't support you have any code online that demonstrates this?

**Comment by Argent78** [comment]
@cocowalla I don't have any public code that demonstrates this, but the principles are fairly straight-forward:

`    

    public class MediatorViewModel
    {
        private readonly IMediator _mediator;
        public DelegateCommand ImageTappedCommand { get; set; }

        protected MediatorViewModel(IMediator mediator)
        {
            _mediator = mediator;
            ImageTappedCommand = new DelegateCommand(async () => await SelectImage());
        }

        private async Task SelectImage()
        {
            var imageStream = await _mediator.Send(new SelectImageRequest());
            Image = ImageSource.FromStream(() => imageStream);
        }
 
    }

    public class SelectImageRequest : IRequest<Stream>
    {

    }

    public class SelectImageRequestHandler : IRequestHandler<SelectImageRequest, Stream>
    {
        public async Task<PhotoResponse> Handle(SelectImageRequest request, CancellationToken cancellationToken)
        {
            var image = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
            {
                CompressionQuality = 50,
                ModalPresentationStyle = MediaPickerModalPresentationStyle.OverFullScreen
                SaveMetaData = false,
                RotateImage = true,
            });             
            return image.GetStream();
        }
    }

`


I haven't compiled the above snippets, but it does give the general idea. Typically I would encapsulate any framework-specific code behind an interface that is injected into the request handler, and mocked out when under test (not shown above for the sake of brevity).
