### ISSUE TITLE
Not FUnciona in Windows 2016 Server

### ISSUE THREAD

**Issue by borisgr04** [jbogard/MediatR#342]
I have a project In Windows 2012, Windows 10 Funciona OK. 

In Windows 2016 => 

Error constructing handler for request of type MediatR.IRequestHandler.

**Comment by davidrevoledo** [comment]
@borisgr04 I think this is irrelevant of the operative system did you checked that you registred the assemblies for the resquest handlers ? ?

**Comment by borisgr04** [comment]
El problema era en el connection string.
Autofac no daba para resolver la inyección completa por el error que habia.

El 16 dic. 2018 2:42 p. m., "David Revoledo" <notifications@github.com>
escribió:

@borisgr04 <https://github.com/borisgr04> I think this is irrelevant of the
operative system did you checked that you registred the assemblies for the
resquest handlers ? ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jbogard/MediatR/issues/342#issuecomment-447669957>, or mute
the thread

**Comment by borisgr04** [comment]
Yes.

El 16 dic. 2018 3:25 p. m., David Revoledo <notifications@github.com> escribió:

Awesome so it's solved right ? @borisgr04<https://github.com/borisgr04>
