### ISSUE TITLE
Unable to install new 6.0.0 nuget package

### ISSUE THREAD

**Issue by TraGicCode** [jbogard/MediatR#345]
Hey @jbogard ,

When i'm trying to reference the 6.0.0 release visual studio is failing to install the package and providing me with the following erorr:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'MediatR 6.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

```

Can you check if you have a faulty release that needs to be pulled?

Thanks

**Comment by TraGicCode** [comment]
I cracked open the nuget package and it looks like you dropped support for .net framework 4.5.  I suggest you do the following:

1. If possible update the release notes on github for 6.0.0 to indicate .net framework 4.5 was dropped and the library is compiled for 4.6 now
2. Update the nuspec for mediatr to have a dependency on .net framework 4.6 so that visual studio provides a friendlier error message.

Thanks!

**Comment by jbogard** [comment]
Nope, I don’t target 4.5 anymore. Just 4.6.1 and above.

**Comment by jbogard** [comment]
Well really netstandard2.0 only.

**Comment by jbogard** [comment]
Updated release notes. The package targets `net461` and `netstandard2.0`.
