### ISSUE TITLE
Pipeline Behaviors are auto triggered without explicit registration in v6.0.0

### ISSUE THREAD

**Issue by ilimansky** [jbogard/MediatR#346]
Not sure this is a feature or a bug or tbd but in the latest version (v6.0.0) I don't even have to register a pipeline behavior in Startup.cs (using the built-in DI with .NET Core 2.2) and it gets triggered. Tested with 5.x and 6.0.

In 5.x I had to at least do the following, with 6.0 it will hit the behavior twice
services.AddMediatR(typeof(Startup));
services.AddScoped(typeof(IPipelineBehavior<,>), typeof(RequestPreProcessorBehavior<,>));

With 6.0 it triggers the behavior with only 
services.AddMediatR(typeof(Startup));

Thanks!

**Comment by jbogard** [comment]
Those pre/post processor behaviors are automatically registered now.

**Comment by ilimansky** [comment]
Understood, thanks for the quick reply!

So is the new approach/best practices not to register behaviors in Startup at all and only constrain them via **where** within the custom behavior classes? e.g.

public class LogBehaviorPre<TRequest> : IRequestPreProcessor<TRequest> **where** TRequest: Pages.Xyz.Edit.Query

**Comment by jbogard** [comment]
No, MEDI (Microsoft.Extensions.DI) does not support constrained open generics, see https://github.com/aspnet/Extensions/pull/536. I only use generic constraints for cross-cutting behaviors, like `IRequireCurrentUserContext`.

**Comment by jbogard** [comment]
And if you go generic constraints, you'll need to use a 3rd party container.

**Comment by ilimansky** [comment]
Got it, I'm migrating to AutoFac as we speak. As you said this doesn't work with MEDI but works with AutoFac. Using an Interface so all I have to do is implement it anywhere I need the behavior to kick in (for cross cutting behaviors only).

`public class LogBehaviorPre<TRequest> : IRequestPreProcessor<TRequest> where TRequest: ILogBehaviorPre`

`public class Query : IRequest<Command>, ILogBehaviorPre
        {
            public int Id { get; set; }
        }`

**Comment by jbogard** [comment]
Exactly! And even then - it's only when you want to constrain behaviors to only certain requests.

 - Closed generic type -> apply to single type
 - Open generics -> apply to all types
 - Constrained open generic -> apply to some types
