### ISSUE TITLE
generic asp.net core , not registered

### ISSUE THREAD

**Issue by moataz1991** [jbogard/MediatR#348]
Hello

i tried to register generic request and handlers but i couldn't
im using AspNetCore 2.1

here is my code

`
 
    public interface IDbRespone
    {
        string Message { get; }
        DbResponeTypes ResponeType { get; }
    }

    public class DbResponse : IDbRespone
    {
        string _message;
        DbResponeTypes _responseType;

        public string Message => _message;
        public DbResponeTypes ResponeType => _responseType;

        public DbResponse(string message, DbResponeTypes responeType)
        {
            _message = message;
            _responseType = responeType;
        }
    }

    public interface IDbRequest<T>: IRequest<IDbRespone> where T : class
    {
        ICollection<DbCommand> Commands { get; }
        T Model { get; }
    }

    public class DbRequest<T> : IDbRequest<T> where T : class
    {
        T _entity;
        ICollection<DbCommand> _dbCommands;

        public T Model => _entity;
        public ICollection<DbCommand> Commands => _dbCommands;

        public DbRequest(T entity,ICollection<DbCommand> dbCommands)
        {
            _entity = entity;
            _dbCommands = dbCommands;
        }
    }
    
    public class DbRequestHandler<T,TRequest> : RequestHandler<TRequest, IDbRespone> where TRequest : IDbRequest<T> where T : class
    {
        protected readonly IRepository<T> _repository;
        public DbRequestHandler(IRepository<T> repository)
        {
            _repository = repository;
        }

        protected override IDbRespone Handle(TRequest request)
        {
            throw new NotImplementedException();
        }
    }

    public class DbCommandsRequestHandler<T> : DbRequestHandler<T, IDbRequest<T>> where T : class
    {

        public DbCommandsRequestHandler(IRepository<T> repository) : base(repository)
        {
        }
        protected override IDbRespone Handle(IDbRequest<T> request)
        {
            string _message = "";
            DbResponse dbResponse;
            try
            {
                foreach (var c in request.Commands)
                {
                    _repository.GetType().GetMethod(c.TargetMethodName).MakeGenericMethod(typeof(T)).Invoke(_repository, c.CommandParams);
                }
                //_repository.AddEntity(request.Model);
                
            }
            catch(Exception e) {

            }

            return new DbResponse("", DbResponeTypes.ERROR);
        }
    }`

can you please help me ?
with a good Startup class :)

Thanks

EDIT:
i added a reference to similar issue but still couldn't do it
if it helps explaining my issue

**Comment by moataz1991** [comment]
what i want is how to get this registered , and sorry for wrong method signature in the first post
i modified the TRequest
it's now like this
```
public class DbCommandsRequestHandler<T> : RequestHandler<T, IDbRespone> where T : IRequest<IDbRespone>
    {
        protected override IDbRespone Handle(T request)
        {
            throw new NotImplementedException();
        }
    }
```

and to use mediatR like this

```
            IDbRequest<Move> request = new DbRequest<Move>(new Move(), commands);
            var _dbResponse = await _mediatR.Send(request);
```
and this is my IDbRequest<T> that inherits IRequest<IDbRespone>

```
public interface IDbRequest<T>: IRequest<IDbRespone>
    {
        ICollection<DbCommand> Commands { get; }
        T Model { get; }
    }

    public class DbRequest<T> : IDbRequest<T>
    {
        T _entity;
        ICollection<DbCommand> _dbCommands;

        public T Model => _entity;
        public ICollection<DbCommand> Commands => _dbCommands;

        public DbRequest(T entity,ICollection<DbCommand> dbCommands)
        {
            _entity = entity;
            _dbCommands = dbCommands;
        }
    }
```
and is it ok to make my handler accepting DI like this : 

```
public class DbCommandsRequestHandler<M,T> : RequestHandler<T, IDbRespone> where T : IRequest<IDbRespone> where M : class
    {
        IRepository<M> _repository;

        public DbCommandsRequestHandler(IRepository<M> repository)
        {
            _repository = repository;
        }

        protected override IDbRespone Handle(T request)
        {
            throw new NotImplementedException();
        }
    }
```

i'm learning new staffs , sorry i making any non-sense code :) 
hope you answer my question
thanks

**Comment by jbogard** [comment]
Are you using the built-in DI stuff from ASP.NET Core? If so, I think you can register an open generic handler. The scanner I have for MediatR (`services.AddMediatR`) does not register open generic handlers.

But I don't think this will work anyway - you have to flow all generic types down, and you'd need to have the request type, the model type, and the response type.

I'd try to make this work without MediatR - that is, just get the basic registration and resolution working with the container before you introduce MediatR into the mix. And you'll likely be looking towards generic constraints instead of hard-coding the request/response types in your class. Good luck!
