### ISSUE TITLE
Opt-out from processors, behaviors

### ISSUE THREAD

**Issue by abatishchev** [jbogard/MediatR#350]
It would nice to be able to opt-out from processors, behaviors. Purpose: to simplify the DI container registration process and make the whole pipeline more lightweight in case when. Scenario: user don't have any processors or behaviors but still have to register them all.

Here's how it'd look in Simple Injector syntax:

```c#
var options = new MediatorOptions
{
    OptOutPreProcessorBehavior = true,
    OptOutPostProcessorBehavior = true,
    OptOutRequestPreProcessor = true,
    OptOutRequestPostProcessor = true
};
container.RegisterInstance<MediatorOptions>(options);

// Mediator ctor accepts MediatorOptions now, or has it as read-write property
container.RegisterSingleton<IMediator, Mediator>();
```

Another implementation option:

```c#
[Flags]
public enum MediatorFeatures
{
    All = PreProcessorBehavior | PostProcessorBehavior | RequestPreProcessor | RequestPostProcessor,
    PreProcessorBehavior,
    PostProcessorBehavior,
    RequestPreProcessor,
    RequestPostProcessor,
    None
}

public class MediatorOptions
{
    public MediatorOptions()
        : this(MediatorOptions.All) { }

    public MediatorOptions(MediatorFeatures features) =>
        _features = features;
}

// or

var options = new MediatorOptions
{
    Features = MediatorFeatures.None
};
```

So none of these would be needed:

```c#
container.Collection.Register(typeof(IPipelineBehavior<,>), new[]
{
    typeof(RequestPreProcessorBehavior<,>),
    typeof(RequestPostProcessorBehavior<,>),
    typeof(EmptyPipelineBehavior<,>)
});
container.Collection.Register(typeof(IRequestPreProcessor<>), new[]
{
    typeof(EmptyRequestPreProcessor<>)
});
container.Collection.Register(typeof(IRequestPostProcessor<,>), new[]
{
    typeof(EmptyRequestPostProcessor<,>)
});
```

This would basically bring my code back to the MediatR 2.x times but allow the users of the new features to continue using them without any changes from their side.

This also would allow to fine-tune which processors and/or behaviors user wants and which doesn't.

The overhead of checking enum flag shouldn't be bigger than returning `Task.CompletedTask` from each of my "empty" processor/behavior.

**Comment by abatishchev** [comment]
MediatR is a glue between layers and I'd like:

- Minimize the performance overhead by using it
- Minimize the configuration overhead by using it

**Comment by jbogard** [comment]
What configuration overhead exactly? Is this issue in the wrong repo? You're not forced to register pre/post processors today. Those are just extra behaviors.

**Comment by abatishchev** [comment]
Wrong repo? I though this is the repo for MediatR :)

I don't want to have this:

```c#
container.Collection.Register(typeof(IPipelineBehavior<,>), new Type[0]);
container.Collection.Register(typeof(IRequestPreProcessor<>), new Type[0]);
container.Collection.Register(typeof(IRequestPostProcessor<,>), new Type[0]);
```

But first of all I want to opt-out from them completely, not even being attempted to be resolved in the first place.

**Comment by jbogard** [comment]
I don't know what container you're using, but for example the one built in to ASP.NET Core does not require you to register empty enumerables. And the pre/post processors would *only* be necessary if you also registered the pre/post processor behaviors. At the very least you have 2 extra registrations.

As for the first registration, that seems like a problem with the container.

**Comment by abatishchev** [comment]
Simple Injector. I'll check with Steven. But I'm definite it does require, by design.
