### ISSUE TITLE
INotification with IPipelineBehavior

### ISSUE THREAD

**Issue by kl1mm** [jbogard/MediatR#353]
Hi guys,
is it possible to run a pipeline while publishing a notification?

`Mediator.Send (new MyRequest());`
will go through my PipelineBehaviors

`Mediator.Publish (new MyNotification());`
will not go through my PipelineBehaviors  :(

Can I control that?
greetings

**Comment by jbogard** [comment]
No, the pipeline behaviors were explicitly design for requests. If you want something like a pipeline for notifications, you can override the `PublishCore` method in the `Mediator` class, or you can register decorators for notification handlers in your container of choice.

**Comment by kl1mm** [comment]
Ok, thanks for the quick response :)
