### ISSUE TITLE
netstandard2.0

### ISSUE THREAD

**Issue by GibSral** [jbogard/MediatR#354]
Hi,
are there any particular reasons why mediatr targets netstandard2.0.
I would like to use Mediatr in an UWP app but at the moment we are stuck with the last LTS verision of Windows which means, that we can not use netstandard2.0.

i tried compiling the code against netstandard1.3 and it compiled without error.

Thx in advance

Lars

**Comment by jbogard** [comment]
I don't want to support the platforms `netstandard1.3` supports nor do I want to continue to support the tests against that platform.
