### ISSUE TITLE
Pre/Post Request handler to control only for specific commands

### ISSUE THREAD

**Issue by NaveenKumar2303** [jbogard/MediatR#355]
Hello guys ,

May be this query has been sorted out but wanted to have concrete implementation for it .

The query is as Asp.net core Di provides default injection for pre and post request handler and this will be executing for all the commands , i need to get it executed only for specific commands how do i do it with default DI provided by Core? 

If it is not really possible with default DI then what is the way forward Autofac ? Any reason why this is forbidden with default DI ?

**Comment by jbogard** [comment]
You can’t. The best you can do is put a conditional inside your pre/post
handlers.

**Comment by IAm-Naveen** [comment]
Then if the number of pre/post request class increases then application tends to hit all those. 

Rather than that what is the best way to tackle this? Use other injection

**Comment by jbogard** [comment]
Why would you have many pre and post request handlers? Even for large
applications we’d only see a few.

**Comment by IAm-Naveen** [comment]
For example,
1.based on user details need to have logger and log into different db. 
2.have to send out mail to different admins and this depends on users asssoicated under him 

Like this sort we might end up with more than expected,  yes true that we can control number of pre post handlers and all the time our request keeps on hitting that handlers

**Comment by jbogard** [comment]
Ultimately, the built in container cannot handle these scenarios. I usually
use generic constraints, but you can also just have a concrete pre/post
handler. You just won’t be able to have anything depend on the specific
request type.

**Comment by IAm-Naveen** [comment]
Understood then I will have a pre post handlers to have a generic purpose usage rather than specific types. 
Thanks a ton for quick reply this helps a lot.

**Comment by IAm-Naveen** [comment]
And even for a concrete pre post handlers for specific type, still all the request goes through all the pre post handlers right we can't just skip handlers even if I provide concrete implementation

**Comment by IAm-Naveen** [comment]
Or even if I have a generic types implemented for the pre post handler as 

public class SomePreProcessor<response> : IRequestPreProcessor<response> where response : mycommand 
{

This will shoot up error during executing of other command handlers

**Comment by jbogard** [comment]
Why not something like:

```c#
public class SomePreProcessor : IRequestPreProcessor<ISomeCommand> 
{
}
```

For that generic constraint, making a concrete implementation? The default DI does not support generic constraints (see https://github.com/aspnet/Extensions/pull/536)

**Comment by robjackstewart** [comment]
I am currently hitting this issue and I ended up implementing @jbogard implementation

> Why not something like:
> 
> ```cs
> public class SomePreProcessor : IRequestPreProcessor<ISomeCommand> 
> {
> }
> ```
> 
> For that generic constraint, making a concrete implementation? The default DI does not support generic constraints (see [aspnet/Extensions#536](https://github.com/aspnet/Extensions/pull/536))

I have implemented this solution, and it does solve one of the problems (the throwing of the generic type constraint error), however, it then results in only one of the specified IRequestPreProcessCommands being injected into the relevant RequestPreProcessBehaviour.

So if we have the below Preprocess Behaviour
`
private readonly IEnumerable<IRequestPreProcessor<TRequest>> _preProcessors;
public RequestPreProcessBehaviour(IEnumerable<IRequestPreProcessor<TRequest>> preProcessors)
        {
            _preProcessors = preProcessors;
        }

public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            foreach (var processor in _preProcessors)
            {
                await processor.Process(request, cancellationToken).ConfigureAwait(false);
            }
            return await next().ConfigureAwait(false);
        }`

Then we Implement two IRequestPreprocessor classes which specifiy a particular request type:
`
public class PreProcessorOne : IRequestPreProcessor<SomeCommand> 
{
}

public class PreProcessorTwo : IRequestPreProcessor<SomeCommand> 
{
}
`

The RequestPreProcessBehaviour will only receive PreProcessorOne.

Any ideas?

**Comment by robjackstewart** [comment]
I managed to get a collection of the preprocessor commands which run for a specific implementation of IRequest as follows:

```cs
public class RequestPreProcessValidationBehaviour<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : IRequest<TResponse>
    {
        private readonly IEnumerable<IRequestPreProcessor<TRequest>> _preProcessors;
        private readonly IValidatorFactory _validatorFactory;

        public RequestPreProcessValidationBehaviour(IValidatorFactory validatorFactory,)
        {
            _validatorFactory = validatorFactory

            var TRequestAssemblyQualifiedName= typeof(TRequest).AssemblyQualifiedName;
            _preProcessors = Assembly.GetExecutingAssembly().GetTypes()
                .Where(x => x.GetInterfaces().Any(y => y.IsGenericType && y.FullName == $"MediatR.Pipeline.IRequestPreProcessor`1[[{TRequestAssemblyQualifiedName}]]")).ToList();
        }

        public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            List<ValidationFailure> validationFailures = new List<ValidationFailure>();

            foreach (var processor in _preProcessors)
            {
                var validator = _validatorFactory.GetValidator(processor.GetType());
                await processor.Process(request, cancellationToken).ConfigureAwait(false);
                if (validator != null)
                {
                    var validationContext = new ValidationContext(processor);
                    validationFailures.AddRange(validator
                        .Validate(validationContext)
                        .Errors
                        .Where(f => f != null)
                        .ToList());
                }
            }

            if (validationFailures.Count > 0)
            {
                throw new Exceptions.ValidationException(validationFailures);
            }

            return await next().ConfigureAwait(false);
        }


    }````

However, this does have a limitation in that it will not instantiate IPreProcessorRequest's which apply to all e.g.

```cs
public class RequestLogger<TRequest> : IRequestPreProcessor<TRequest>
    {
        private readonly ILogger _logger;

        public RequestLogger(ILogger<TRequest> logger)
        {
            _logger = logger;
        }

        public Task Process(TRequest request, CancellationToken cancellationToken)
        {
            var name = typeof(TRequest).Name;

            _logger.LogInformation("LenovoFlexit Request: {Name}, {@Request}", name, request);

            return Task.CompletedTask;
        }
    }
```

This will not be caught, so still some mroe working out to be done but I hope this helps for now
