### ISSUE TITLE
[Question ] Why IRequestPostProcessor does not have generic constraints?

### ISSUE THREAD

**Issue by HesamKashefi** [jbogard/MediatR#357]
Hi, It may be a silly question but i'm new to MediatR and I'm facing this question that how can I wrap my Requests' Result into some kind of Envelope for pagination and I'm confused.
I see that `IRequestPostProcessor` is defined this way : 
`public interface IRequestPostProcessor<in TRequest, in TResponse>
    {
        Task Process(TRequest request, TResponse response);
    }`
but is there a way for a request with a response type defined in it such as IRequest<int> end up returning a different type other than int ? if so, how? but if it can't woudln't be better to define  `IRequestPostProcessor` this way : 
`public interface IRequestPostProcessor<in TRequest, in TResponse> where TRequest : IRequest<TResponse>
    {
        Task Process(TRequest request, TResponse response);
    }`

**Comment by jbogard** [comment]
I don’t remember tbqh

**Comment by StevenTCramer** [comment]
@HesamKashefi your where clause makes sense to me.  Given the output of the pipeline has to be what was expected at the start of the pipeline.  And in general we like constraints that keep us from shooting ourselves in the foot.

Making the change cascades down into other things. But with those changes **all tests still pass**.

Here are the changes required in my fork. @jbogard can review and see if he would want to implement this.  It would be a breaking change as all the pipeline classes have to all add this constraint.

https://github.com/StevenTCramer/MediatR/commit/f2666254781fc7cc7871bacf420d2c5217453765

**Comment by HesamKashefi** [comment]
@jbogard I think this may have something to do with the lack of generic constraints support by Microsoft.Extensions.DependencyInjection Package! am I right?! 
I was moving all my codes to CQRS styled codes, and slowly migrating my codes from asp.net web api to asp.net core and my codes were working fine until I started to test the .net core version and booooom! error came up saying that it does not support generic constraints!
now I have to change my IOC Container 😢
