### ISSUE TITLE
[Question] Execute PipelineBehavior only to specific types of request

### ISSUE THREAD

**Issue by thiagoteles** [jbogard/MediatR#358]
Can I execute pipeline matching a specific Interface to avoid the test like this?

https://gist.github.com/thiagoteles/4f6776e23660e5eba168fb9a1916683e

**Comment by thiagoteles** [comment]
Can I execute pipeline matching a specific Interface to avoid the test like this?

`
public class TestBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
       where TRequest : IRequest<TResponse>
{
	private readonly IMediator _mediator;
	public TestBehavior(IMediator mediator)
	{
		_mediator = mediator;
	}

	public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
	{
		if (request is ITestReadContext request)
		{
			request.Container = await _mediator.Send(new TestQuery() { Name = request.Name });
		}

		return await next();
	}
}
`

**Comment by lilasquared** [comment]
instead of `where TRequest : IRequest` you should be able to say `where TRequest : ITestReadContext`

**Comment by thiagoteles** [comment]
> instead of `where TRequest : IRequest` you should be able to say `where TRequest : ITestReadContext`

I registered the type with generic sintax like that:

`
services.AddTransient(typeof(IPipelineBehavior<,>), typeof(LoadCurrentIdentityBehavior<,>));
`

When I change the generic constraint to 

`
where TRequest : ITestReadContext
`

I receive a violation constraint in runtime

**Comment by lilasquared** [comment]
when starting the app up or when trying to execute a command?

**Comment by thiagoteles** [comment]
> when starting the app up or when trying to execute a command?

When trying to execute some behaviors including the ITestReadContext

**Comment by lilasquared** [comment]
It most likely has to do with the dependency resolver you are using, I use structuremap and it has no issue with the generic constraints.  What are you using?

**Comment by lilasquared** [comment]
I'm pretty sure that one doesn't support open generic registration.  

jimmy has a pr open to that end https://github.com/aspnet/Extensions/pull/536

**Comment by thiagoteles** [comment]
> I'm pretty sure that one doesn't support constrained open generic registration.
> 
> jimmy has a pr open to that end [aspnet/Extensions#536](https://github.com/aspnet/Extensions/pull/536)

Sad story ;(

**Comment by ZNS** [comment]
You could do

`where TRequest : IRequest<TResponse>`

and then inside Handle(...)

`if (request is ITestReadContext) {.. do stuff ..} return next();`

not as nice but should work?
