### ISSUE TITLE
Sharing data between pipeline behaviors

### ISSUE THREAD

**Issue by huysentruitw** [jbogard/MediatR#361]
The pipeline behaviors look very interesting for what we're trying to achieve. However, we are having the need to pass information from one behavior to the other. Any idea how we can do this? Or is this considered bad practice?

**Comment by jbogard** [comment]
You can use dependencies to share information from one to the next, or you can put things on the request objects themselves. The only other alternative is to put an additional parameter on the pipeline/handler classes for a context object (like filters in ASP.NET Core), but I'm not sure it's worth the breaking change.

**Comment by jbogard** [comment]
Also, the pre/post processors are a special kind of built-in behavior. You can do something similar where you make up your own "pre/post processor" that passes around a context object.
