### ISSUE TITLE
Unity DI Container sample code RegisterType method not working with Unity v5.9.x

### ISSUE THREAD

**Issue by OculiViridi** [jbogard/MediatR#364]
After updating **Unity DI Container**  from v5.8.x to v5.9.x, the configuration used to register `Mediator` object suggested [here](https://github.com/jbogard/MediatR/tree/master/samples/MediatR.Examples.Unity) is not working anymore. 

The problem is an error about `RegisterType` method arguments:

> Cannot convert from 'Unity.Lifetime.LifetimeManager' to 'Unity.Injection.InjectionMember'

This is my actual code taken from the sampe code:

```csharp
public static IUnityContainer RegisterMediator(this IUnityContainer container, LifetimeManager lifetimeManager)
{
    return container.RegisterType<IMediator, Mediator>(lifetimeManager)
        .RegisterInstance<ServiceFactory>(type =>
        {
            var enumerableType = type
                .GetInterfaces()
                .Concat(new[] { type })
                .FirstOrDefault(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable<>));

            return enumerableType != null
                ? container.ResolveAll(enumerableType.GetGenericArguments()[0])
                : container.IsRegistered(type)
                    ? container.Resolve(type)
                    : null;
        });
}
```

I've also take a look [here](https://github.com/unitycontainer/unity/wiki/Upgrading-to-Release-5.9.x) but nothing about this change is mentioned.

Is it already available a new version of the registration code?
What have I to do to update my code?

**Comment by OculiViridi** [comment]
The solution seems very easy!
The `RegisterType` method is now taking an `ITypeLifetimeManager` parameter instead of `LifetimeManager`.

Please see [here](https://stackoverflow.com/questions/54664959/unity-di-container-registertype-method-breaking-changes-from-v5-8-x-to-v5-9-x/) on SO.

**Comment by jbogard** [comment]
Happy to take a PR if you get it fixed! I don't really update the samples *too* often unless someone sends me a PR, since I don't really use any of these containers.
