### ISSUE TITLE
Multiple Event in one Handler(Listener)

### ISSUE THREAD

**Issue by aimprogman** [jbogard/MediatR#365]
How can I create multiple Event in one EventHandler . 

For example: 
### Event1: 
```
public class UserAutorizeEvent: INotification
    { }
```
### Event2
```
public class UserLogoutEvent: INotification
    { }
```
### EventHandler
```
public class SaveTrackHandler : INotificationHandler<UserAutorizeEvent,UserLogoutEvent>
    { }
```

I can`t put two events in one EventHandler as INotificationHandler<UserAutorizeEvent,UserLogoutEvent>

**Comment by stiankroknes** [comment]
You have to implement them both, but you can have it in the same handler class and delegate to common handle logic if that is the goal. 
Handler : INotificationHandler<UserAutorizeEvent>,
INotificationHandler<UserLogoutEvent>

**Comment by aimprogman** [comment]
Thanks @stiankroknes , it solved my problem.
