### ISSUE TITLE
Match handler by method signature instead of interface

### ISSUE THREAD

**Issue by xperiandri** [jbogard/MediatR#367]
I wonder why we need a handler interface if we can just match handler method by its signature having a command parameter in it and returing a type as command requires. All the other parameters will be filled from DI.
This is what I miss to use MediatR in F#.

**Comment by jbogard** [comment]
Yeah....no this isn't going to happen. We don't have this kind of pattern matching in C#, so we have to use types. Sorry!

**Comment by xperiandri** [comment]
You can use both approaches giving choice to developer. Why not?

**Comment by jbogard** [comment]
That's developing a completely new MediatR project. Nothing could be kept from the existing codebase, nothing at all. I don't want to do that, someone else can if they like.

**Comment by xperiandri** [comment]
I started a prototype. I will send a pull request when ready
