### ISSUE TITLE
Mediatr dependency release policy

### ISSUE THREAD

**Issue by EdwinVanVliet** [jbogard/MediatR#369]
I have been using Mediatr (5.1.0) for a couple of months now, and it has been a great help in simplifying lot's of concerns. However I'm running into an issue in combination with Castle.Windsor I can't seem to get solution for I'm really content with.

In the application I'm working on we have an in-memory queue with all sorts of events being raised. For some events multiple handlers are interested in those events, and thus I'm using the IMediator.Publish(INotification notification) api. Events are published as expected and not much trouble in here. However some of the notification handlers are having dependencies injected into their constructors using Castle.Windsor. This also works as expected.

However when Mediator is done handling the requests, Windsor is not being informed that the notification handlers are not needed anymore because the Release function on the container is not being invoked. Therefore garbage collection can't do his job of cleaning up the notification handlers. 

I configured my Windsor container as follows (based on the sample project on this GitHub)
```
container.Register(Component.For<IMediator>().ImplementedBy<Mediator>());
container.Register(Classes.FromAssemblyInThisApplication().BasedOn(typeof(INotificationHandler<>)).WithServiceAllInterfaces()
                .LifestyleTransient());
container.Register(Component.For<ServiceFactory>().UsingFactoryMethod<ServiceFactory>(k => type =>
            {
                var enumerableType = type
                    .GetInterfaces()
                    .Concat(new[] { type })
                    .FirstOrDefault(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable<>));

                return enumerableType != null ? k.ResolveAll(enumerableType.GetGenericArguments()[0]) : k.Resolve(type);

            }).LifestyleTransient());
```

I'm a bit of struggling on how to approach this with the Mediatr package, I could recompile the source myself and build this in, but I would also like to benefit of the work the maintainers are doing. So don't really prefer to do this.

What might be some nice solutions to this project;

1. Having an option to override the part that handles the resolving in Mediator. So I can execute the publish, and then invoke the release on my container myself.

2. Have a post step which gets the handler(s) injected, so I can do some additional cleanup myself.

Any advice how to approach this issue?

**Comment by jbogard** [comment]
I'm not really familiar with Castle Windsor - but typically I use Mediator in a scoped manner, so that the instance is tied with some sort of context and everything goes away together, like in ASP.NET Core's DI.

**Comment by EdwinVanVliet** [comment]
> I'm not really familiar with Castle Windsor - but typically I use Mediator in a scoped manner, so that the instance is tied with some sort of context and everything goes away together, like in ASP.NET Core's DI.

For now I created a decorator, which takes the IMediatr and my Windsor container as an argument, and wraps everything into a scope of Windsor. Also registered all request and notification handlers as LifeStyleScoped.

This way I can just use the IMediatr interface as before, and don't have to pay attention to cleanup of resources everywhere.
