### ISSUE TITLE
MediatR breaks or stops responding when given derived classes

### ISSUE THREAD

**Issue by madks13** [jbogard/MediatR#370]
Hello, i'm working on a project that has a bit of complex architecture. I have 2 web APIs both using MediatR. So far so good. Except both need to communicate between them using RabbitMQ. Sending RMQ messages between them is easy. Deserializing queries and using MediatR to not have to know what type of query it is not. Let me give you examples of the classes i have.

First the base model for view models. This ensures the business side always sends back a message, even if only to say it failed.

```cs
public class BaseViewModel
{
    public bool QueryResult { get; set; }
    public string Message { get; set; }
}
```

Then a test view model, for testing

```cs
public class TestViewModel : BaseViewModel
{
    public int Status { get; set; }
}
```

Here's the query.

```cs
public class GetTestResultQuery : IRequest<TestViewModel>
{
    public string SubService { get; set; }
}
```

As for the handlers...well there is some abstraction.
First the base for all handlers.
As you can see, it simply adds a few protected fields so derivated classes can have everything ready.

```cs
public abstract class BaseQueryHandler<TRequest, TResponse, TDbContext> : IRequestHandler<TRequest, TResponse> 
        where TRequest : IRequest<TResponse>
        where TDbContext : DbContext
    {
        protected readonly TDbContext _context;
        protected readonly IMapper _mapper;

        public BaseQueryHandler(TDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public abstract Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken);
    }
```

Then another abstract layer for those using RMQ.
Also very simple.

```cs
public abstract class MessagerQueryHandler<TRequest, TResponse, TDbContext> : BaseQueryHandler<TRequest, TResponse, TDbContext>, IDisposable
        where TRequest : IRequest<TResponse>
        where TDbContext : DbContext
    {
        private bool _disposed = false;
        private RMQClient _messager;

        public RMQClient Messager => _messager;
        public abstract RMQConfig MessengerSettings { get; }

        public MessagerQueryHandler(TDbContext context, IMapper mapper) : base(context, mapper)
        {
            _messager = RMQClient.Instance;
            _messager.Initialize(MessengerSettings);
        }

        ~MessagerQueryHandler()
        {
            Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        // Protected implementation of Dispose pattern.
        protected virtual void Dispose(bool disposing)
        {
            if (_disposed)
                return;

            if (disposing)
            {
                _messager.Dispose();
            }

            _disposed = true;
        }
    }
```

Then finally the concrete class.

```cs
public class GetTestResultQueryHandler : MessagerQueryHandler<GetTestResultQuery, TestViewModel, DiscountOnlineCloudDbContext>
    {
        public override RMQConfig MessengerSettings => SettingsHelper.RMQConfig;

        public GetTestResultQueryHandler(DiscountOnlineCloudDbContext context, IMapper mapper) : base(context, mapper)
        {
        }

        public async override Task<TestViewModel> Handle(GetTestResultQuery request, CancellationToken cancellationToken)
        {
            var data = DataSerializer.Deserialize(Messager.SendMessageWithAnswer("Test", DataSerializer.Serialize(request))) as TestViewModel;

            return data;
        }
    }
```

I'm initializing the MediatR service by giving it an assembly.

```cs
services.AddMediatR(typeof(GetClientByIdQueryHandler).GetTypeInfo().Assembly);
```

And finally, the part where i'm testing the deserialized object.

```cs
                   var testQuery = new GetTestResultQuery
                    {
                        SubService = @"test-sub"
                    };

                    var serialized = DataSerializer.Serialize(testQuery);
                    var deserialized = DataSerializer.Deserialize(serialized);

                    IRequest<BaseViewModel> cast = (IRequest<BaseViewModel>)deserialized;
                    IRequest<TestViewModel> castDirect = (IRequest<TestViewModel>)deserialized;
                    GetTestResultQuery uncast = (GetTestResultQuery)deserialized;

                    var response = await Mediator.Send(cast);
```

I've tried to cast in 3 different ways without using "as" just to be sure it can be cast without problems.
I'm having problems only when sending "cast".
The ideal would be to be able to use "cast", since i don't know what type the message is of, but i'm getting exceptions in this case :

=> Handler was not found for request of type MediatR.IRequestHandler`2[DiscountOnline.Application.Common.Test.Queries.GetTestResultQuery,DiscountOnline.Application.Common.Infrastructure.BaseViewModel]. Register your handlers with the container. See the samples in GitHub for examples.

I've checked the code for MediatR, and the problem seem to stem from typeof(TResponse) being used instead of checking the actual type of the object.

Another problem i'm having is that when i try this with a non messager handler (only implementing BaseQueryHandler), it sends back a cast exception:

=> Unable to cast object of type 'MediatR.Internal.RequestHandlerWrapperImpl`2[DiscountOnline.Application.Common.Client.Queries.GetClientByIdQuery,DiscountOnline.Application.Common.Client.Models.ClientViewModel]' to type 'MediatR.Internal.RequestHandlerWrapper`1[DiscountOnline.Application.Common.Infrastructure.BaseViewModel]'.

I know that the interfaces use "in" and "out", so it should work fine when down/up casting.

Another problem i encountered is that i cloned MediatR and MediatR.Extensions repos, so i can step into the code and see what is happening. The weird thing is that ServiceCollectionExtensions found correctly my 2 handlers, and called Add on the service, but once i stepped into MediatR's Send, the handlers list was empty.

I did change the references of MediatR to the cloned repo in every project using it, including the Extensions repo, and i also switched to the cloned extensions repo in my web app.

I'm not sure why i'm having these problems since using the cloned repos adds more question while answering only a few.

Lastly, is there a better way of doing this?

**Comment by stiankroknes** [comment]
Have you tried with dynamic?

**Comment by lilasquared** [comment]
@madks13 we use mediatr to send messages to a queue as well.  Our serialization just includes the type in the data so that when we deserialize dotnet knows exactly what type it is.  Then we deserialize as IRequest and send to mediatR which handles it just fine.  Not sure if that helps solve your problem but it sounds similar.

**Comment by madks13** [comment]
@lilasquared  I think IRequest is not inherited by IRequest<>. Can you give me an example fo how i would do that?
@stiankroknes Sorry, i don't understand what you meant by dynamic. I do know about the dynamic objects, but i don't see how i would use that with mediator. Can you give me an example of what you mean? Just in case, the deserialization is not the problem, it's calling Send once i got my deserialized object.

**Comment by jbogard** [comment]
Oh my. There is a base request interface. But offhand, I'd say get rid of your base classes altogether, they don't seem to be providing any tangible value.

**Comment by jbogard** [comment]
I'm not being flippant here either - I tried this many years ago but really, it's not worth it. You're better choosing composition over inheritance. Instead of having a base class with the RMQ stuff, create a class that manages that for you.

**Comment by madks13** [comment]
@jbogard well, i was testing how to best implement genericity with automation. I can replace the base classes, however, does that mean it will solve the problem of casting?

That said, i'm curious about why when i use the source code i got by cloning, i get an empty handlers list.
