### ISSUE TITLE
Async method naming conventions

### ISSUE THREAD

**Issue by jamesharling** [jbogard/MediatR#371]
Apologies if this has been asked before, I couldn't find an issue about it.

C#/.NET design docs recommend the use of the `Async` suffix for async methods, and I think this is a well-established convention. The MediatR interfaces however don't use this suffix - e.g. `Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken)`.

Is there any plan to align with this convention?

**Comment by jbogard** [comment]
No. Otherwise every single method would have Async in its name. So I opted for what some other, pure-async libraries do:

https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

**Comment by mwarrier** [comment]
Disagree with this, but accept the answer. For the .NET library I think having Async makes perfect sense.
