### ISSUE TITLE
Testing the "registrations" - matching request to handler

### ISSUE THREAD

**Issue by matthiaslischka** [jbogard/MediatR#374]
So yesterday I wrote [a quick unittest](https://matthiaslischka.at/2019/02/25/Testing-MediatR-Registrations/) to verify that I have a request handler for every request. I like to do such tests for reflection stuff because it moves the fail time from runtime to at least unit test execution time.

I use `IBaseRequest` and `IRequestHandler<,>` for the lookup.

Just now I was wondering if you, who know the framework in and out, could think of a cleaner/better way? Maybe one that uses the actual code of the mediator to list its handlers or shtg. like that.

Or probably that is already solved somewhere and I could just not find it?

Would love to hear your ideas on that.

BR,
Matthias

p.s.: an idea that popped up while writing this: Maybe it would be cool to register not only the handler assembly but also the request assembly and mediatR would fail at startup if those do not match up. Not thought this through yet :/

**Comment by jbogard** [comment]
You might want to look at the MS.Ext.DI package - it already does assembly scanning to wire everything up.

**Comment by matthiaslischka** [comment]
Do you mean the `MediatR.Extensions.Microsoft.DependencyInjection` package? I use this to register my handlers: 

```csharp
services.AddMediatR(typeof(AllCustomersQueryHandler).Assembly);
```
But the mediatR still does not know anything about the possible requests.

**Comment by jbogard** [comment]
Ah, yeah, you'd just need to write a test yourself that uses reflection.
