### ISSUE TITLE
Ability to filter notification handlers before executing them

### ISSUE THREAD

**Issue by tdamir** [jbogard/MediatR#375]
Hi,

I would like to be able to exclude/include the notification handlers based on interface they are implementing. For example: 
```
public class SomeNotification : INotification { }
public class SomeNotificationHandler : INotificationHandler<SomeNotification>, IHandleBeforeCommit {}
public class SomeNotificationHandler2 : INotificationHandler<SomeNotification>, IHandleAfterCommit {}
```
I tried to implement this in the way similar to MediatR.Examples.PublishStrategies (eg: Publisher.PublishBeforeCommit(), Publisher.PublishAfterCommit()) but it looks like there is no an easy way to accomplish this. I tried to override the PublishCore but I don't have enough info to decide if handler implements the specific interface. 

Any suggestions?

Thanks

**Comment by jbogard** [comment]
This looks like you want to have an order to handlers?

**Comment by lilasquared** [comment]
It might be a bit of overhead but if the work is truly separate (before vs. after) would it make sense to publish a before notification and an after notification separately?

**Comment by tdamir** [comment]
The ordering is not important in my case. I would like to dispatch events two times. Like this:
```
DispatchDomainEvents() // these events would be handled only by handlers implementing IHandleBeforeSaveChanges
SaveChanges()
DispatchDomainEvents() // these events would be handled only by handlers implementing IHandleAfterSaveChanges
``` 
I need this feature because there are some events which need the domain to be saved (to get the id of the entity back and use it). There could also be a need that the same event needs to be handled before SaveChanges and also after SaveChanges. Let me know if you need more clarification.

**Comment by jbogard** [comment]
I don't know of a great way to do this - since you're looking for *handlers* that implement an interface, you can't easily use generic constraints.

If I were you, I'd just skip `Mediator` and create my own thing to do this. The notification stuff is barely any code anyway.

**Comment by tdamir** [comment]
You are probably right about my own implementation. It would need a rewrite of current implementation of Mediator to support this scenario. To support this scenario, the NotificationHandlerWrapperImpl.Handle method should somehow accept the type of interface to filter collected handlers before executing them (publishing IEnumerable<Func<Task>>). Then the Mediator.PublishNotification (which should be overridable) could pass the concrete handler interface to the NotificationHandlerWrapperImpl.Handle (eg: handler.Handle<IHandleAfterSafeChanges>(notification, cancellationToken, _serviceFactory, PublishCore);)

Since NotificationHandlerWrapperImpl is internal and Mediator.PublishNotification is private I would need to implement my own IMediator which does exactly that.

Thanks

**Comment by SharpNoiZy** [comment]
We also need that Feature, in a different way.
We decorate our NotificationHandlers with FilterAttributes, they execute logic on some data to decide if the handler should be executed.

Because we have realy large enterprise application that works through millions of handlers a day, we want to do that before the handler is instantiated.

But there is no good point to hook up Mediatr to do that, can you maybe consider that feature again for your next version.

**Comment by SymboLinker** [comment]
For scenarios that require such custom logic you can use [IGet](https://www.nuget.org/packages/iget).

```csharp
public class NotificationPublisher
{
    private IGet i;

    public NotificationPublisher(IGet iget)
    {
        i = iget;
    }

    public async Task PublishAsync(Notification notification)
    {
        try
        {
            await i.Get<FirstHandler>().HandleAsync(notification);
        }
        catch { }
        if (notification.ShouldInvokeSecondHandler())
        {
            try
            {
                await i.Get<SecondHandler>().HandleAsync(notification);
            }
            catch { }
        }
        try
        {
            i.Get<ThirdHandler>().Handle(notification);
        }
        catch { }
    }
}
```
Note:
- The `SecondHandler` only gets instantiated if `ShouldInvokeSecondHandler()` is true.
- You can decide the order in which the (notification) handlers are executed.

At startup, do
```csharp
serviceCollection.AddIGet();
```
and get the `IGet` instance `i` from your services. There is no need to register any of the handlers.

Now you can use your `NotificationPublisher` like this:
```csharp
await i.Get<NotificationPublisher>().PublishAsync(notification);
```
