### ISSUE TITLE
Registration Exception Only when Publish site on IIS

### ISSUE THREAD

**Issue by axanth** [jbogard/MediatR#376]
Hi There!
I am getting the Exception : 
{"error":["Error constructing handler for request of type MediatR.IRequestHandler`2[Wateration.Application.UseCases.Customers.Queries.GetCustomerDetailsQuery,Wateration.Application.UseCases.Customers.Models.CustomerOutputModel]. Register your handlers with the container. See the samples in GitHub for examples."],"stackTrace":"   ........

But this happens only when the site is published on IIS. On the IISExpress and on the IIS published on the development machine it works fine!! I Have checked SDK and Run-time versions as well as any versioning conflicts and there is no problem there! Any Help????

**Comment by axanth** [comment]
Nevermind figured out and solved it.

**Comment by syska** [comment]
Please post the solution to the problem, if others should have the same issue in the future.

**Comment by jbogard** [comment]
Could be that you're not explicitly passing in the types to scan?

**Comment by ppatel514** [comment]
Hello - I am facing exactly same issues. can you please advise the solution. Thanks in advance.
