### ISSUE TITLE
Scoped MediatR dependencies not available when switching thread

### ISSUE THREAD

**Issue by kevin93w** [jbogard/MediatR#379]
Hi there!

Currently working on a project that contains a console application. That console app subscribes and listens to a SignalR feed, and whenever a message comes in it is handled by the appropriate event handler.

Whenever the application is started, MediatR and all it's necessary dependencies are registered on the main thread (startup thread). And after that, my SignalR connection is configured adding the necessary event handlers and starting the connection. In the background, SignalR will process incoming messages on seperate threads and let the event handler process the messages.

This is where I get into trouble, because in one of my event handlers I implement IMediator to do some commands and queries. However, I get the following error message:

`Cannot access a disposed object. Object name: 'IServiceProvider'.`

This is because IMediator uses scoped dependencies which, in the separate thread that has now been created, are not available anymore.

Is there any way to change the lifetime of the dependencies registered by MediatR?

**UPDATE**
If I inject the command handlers into my event handler directly, in stead of using IMediator, it works like a charm.

**Comment by jbogard** [comment]
Yeah - don't call `Mediator` from inside a handler, things get weird.

**Comment by mviegas** [comment]
Hey @jbogard, I just ran into this same issue yesterday when calling `IMediator` from inside a handler. Do you have any alternative suggestions when such need happens?!

**Comment by bobbyangers** [comment]
Hi,
I ran into that issue also.

Is it ok to publish an event from inside a handler ?

**Comment by Sulexa** [comment]
Same issue here.
Do you have any solution, or should i not user mediator at all in this case ?

**Comment by campelo** [comment]
Hi @jbogard, what should we do instead of calling a mediator from inside a handler? For some reasons I have to keep my mediator with scoped lifetime. There's a mediator that send 4 parallel commands and from inside of some handlers we'll call others mediator commands. So we have the same issues telling that  IServiceProvider is disposed.

**Comment by jbogard** [comment]
> Hi,
> 
> I ran into that issue also.
> 
> 
> 
> Is it ok to publish an event from inside a handler ?

Yes.

**Comment by jbogard** [comment]
> Hi @jbogard, what should we do instead of calling a mediator from inside a handler? For some reasons I have to keep my mediator with scoped lifetime. There's a mediator that send 4 parallel commands and from inside of some handlers we'll call others mediator commands. So we have the same issues telling that  IServiceProvider is disposed.

Create your own abstraction here instead. You don't want nested behavior pipelines.
