### ISSUE TITLE
When using the publish mode, does not need to wait for the end of the execution of each notification Handler

### ISSUE THREAD

**Issue by swpudp** [jbogard/MediatR#382]
`public class TestNotify : INotification`
` {`
` }`

`public class TestNotify : INotification`
   ` {`
    `}`
   ` public class NotifyHandlerA : INotificationHandler<TestNotify>`
    `{`
   &#8194;     `    public async Task Handle(TestNotify notification, CancellationToken cancellationToken)`
   &#8194;  `   {`
   &#8194; &#8194;  `      await Task.Delay(2000);`
 &#8194;   `    }`
   ` }`
   ` public class NotifyHandlerB : INotificationHandler<TestNotify>`
  `  {`
  &#8194;`      public async Task Handle(TestNotify notification, CancellationToken cancellationToken)`
  &#8194; `     {`
  &#8194;&#8194;  `        await Task.Delay(2000);`
   &#8194;  `   }`
 `   }`
 `   public class NotifyHandlerC : INotificationHandler<TestNotify>`
   ` {`
 &#8194;  `     public async Task Handle(TestNotify notification, CancellationToken cancellationToken)`
 &#8194;  `     {`
 &#8194;&#8194;  `         await Task.Delay(2000);`
 &#8194;  `     }`
    }`

in valuescontroller:
`        [HttpGet("TestNotify")]`
   `      public async Task<IActionResult> TestNotify()`
 `        {`
 &#8194; `             TestNotify testNotify = new TestNotify();`
 &#8194;   `           await _mediator.Publish(testNotify);`
 &#8194;   `           return Ok("ok");`
 `        }`

The execution time is about 6 seconds.

**Comment by nixonad** [comment]
The default strategy for Publish loops through the notification handlers and awaits each one. You can change the publish strategy if you have different requirements.

From the github wiki (https://github.com/jbogard/MediatR/wiki)
"**Publish strategies**
The default implementation of Publish, loops through the notification handlers and awaits each one. This makes sure each handler is run after one another, while each call to 'Handle' is run asynchronously.

Depending on your use-case for publishing notifications, you might need a different strategy for handling the notifications. Maybe you want to publish all notifications in parallel, or wrap each notification handler with your own exception handling logic.

A few example implementations can be found in MediatR.Examples.PublishStrategies. This shows four different strategies documented on the PublishStrategy enum."

**Comment by kbamarnath** [comment]
hello there
Is there a way to find out if the publish event has been handled by any of the subscriber?
I want to log an error if the incoming event doesnt have a handler? Can someone kindly suggest on how to acheive this?


protected async Task HandleMessage(string message)
        {
            try
            {
                    if (!(JsonConvert.DeserializeObject(message, new JsonSerializerSettings()
                {
                    TypeNameHandling = TypeNameHandling.Objects
                }) is INotification e)
                )
                {
                    throw new Exception("Cannot deserialize JSON as INotification.");
                }

                try
                {
                    Logger.LogInformation($"Incoming event {message}.");
                    var notificationType = e.GetType();
                     // Mediator requires a scoped instance
                    // to be able to work with DbContext and other scoped services.
                    using var scope = ServicesScopeFactory.CreateScope();
                    await scope.ServiceProvider.GetRequiredService<IMediator>().Publish(e);
                    
                }
                catch (Exception ex)
                {
                    Logger.LogError(ex, $"A {ex.GetType()} exception occurred when handling the event.\n{message}");
                    throw;
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, $"A {ex.GetType()} exception occurred when handling the event.\n{message}");
                throw;
            }
        }
Regards

**Comment by frkn2076** [comment]
builder.Services.AddMediatR(x => 
{
    // other configs
    x.NotificationPublisher = new TaskWhenAllPublisher(); // default: new ForeachAwaitPublisher()
});
