### ISSUE TITLE
Send common command (query) object and get object response

### ISSUE THREAD

**Issue by megafetis** [jbogard/MediatR#385]
Pleace add such functionality:

```
object query  = Activator.CreateInstance(requestType);
object response = Mediator.Send(query);
if(response is SomeType resp) 
{
 //...
}
```

**Comment by jbogard** [comment]
Why? What's your use case here?

**Comment by megafetis** [comment]
For sending all requests from frontend and automatic detect Requests and send them.
Then to send a response.

I want to a send all requests from one place (action) without expanding web API controllers, but in busines logic.
In controllers 2 actions: for Queries, and for Commands

**Comment by megafetis** [comment]
For example in Nhibernate ORM (or EF) to get any entity i must know only its id and entityName:
```
object id='1234';
string entityName = 'SomeEntityClass';
object entity = dbSession.get(entityName,id);
```
I want something like this, but not in databases, but in business logic

**Comment by jbogard** [comment]
How would the single controller know how what request type to use, and how would fill it with data? Would the data in the requests come from HTTP request information?

**Comment by megafetis** [comment]
Its simple. From json
The query class will create using Nson.Net lib or manually
```
//js
var httpPayload= {
  __type:'SomeDataQuery',
  id:'1234'
}
axios.get('url',httpPayload).then(resp=>console.log(resp))

```

**Comment by jbogard** [comment]
That's how you instantiate it - but where will the properties on the request come from? JSON.Net? So you'd deserialize from JSON.NET into a request object?

**Comment by megafetis** [comment]
yes using JSON.Net in this case.

**Comment by jbogard** [comment]
I'm not sure about your use case - it sounds a bit like gRPC, and I'm not sure that it's worth all that just to avoid controllers.

But, Publish has an overload that is object-based for a different use case, so it would make sense to create one for `Send`. I'll take a pull request if you want to give this a shot.

**Comment by megafetis** [comment]
Ok Thanks.

**Comment by lilasquared** [comment]
@megafetis we do this today without needing a object based send method.  Change if you change your json object that is deserialized to something like this:

```csharp
public class QueryWrapper
{
    public IRequest Query { get; set; }
}
```

then your json would just look like this: 
```json
{
    "Query": { "__type": "SomeDataQuery", "id": 1234
}
```

since you are using the __type property it will retain the correct type and the object will know it is an IRequest and `.Send(...)` will work just fine.  You may even be able to remove the wrapper layer and simply have your controller accept an IRequest parameter instead of an object.

**Comment by megafetis** [comment]
> @megafetis we do this today without needing a object based send method. If you change your json object that is deserialized to something like this:
> 
> ```cs
> public class QueryWrapper
> {
>     public IRequest Query { get; set; }
> }
> ```
> 
> then your json would just look like this:
> 
> ```json
> {
>     "Query": { "__type": "SomeDataQuery", "id": 1234
> }
> ```
> 
> since you are using the __type property it will retain the correct type and the object will know it is an IRequest and `.Send(...)` will work just fine. You may even be able to remove the wrapper layer and simply have your controller accept an IRequest parameter instead of an object.

What about a response of request ? ``Unit`` or ``object``, or another Type 
```cs

var resp = _mediator.Send(query as IRequest);

```
Thank you, I'll try to do the same

**Comment by lilasquared** [comment]
Hmm now that I think of it we might have done this only for commands and not queries so everything had a return type of `Unit`.  Even with a `Send` method that takes `object` how will you know what the response is?  Or will it just be `object` as well?

**Comment by megafetis** [comment]
> Hmm now that I think of it we might have done this only for commands and not queries so everything had a return type of `Unit`. Even with a `Send` method that takes `object` how will you know what the response is? Or will it just be `object` as well?

I want just serialize `object` resp to http response in this case.
In other cases we can handle response if it implements some interfaces for example.. Or do other logic

**Comment by jbogard** [comment]
It would be:

```c#
Task<object> Send(object request, CancellationToken cancellationToken = default);
```

**Comment by megafetis** [comment]
Yes

**Comment by twadrianlis** [comment]
@jbogard are you still accepting PR for the non-generic Send? I would use such a functionality and it is always better to have it officialy supported than to maintain a fork. I did however had a small problem and I am not sure if it will be a decent enough solution. I can prepare a PR and open it up for further discussion/guides on how to proceed with this.

I must warn you though, my main field is C++ not C# 😂

**Comment by megafetis** [comment]
@jbogard pleace apply non-generic Send, suggested above from @twadrianlis  =)

**Comment by jbogard** [comment]
Oh, I was waiting for a PR. @twadrianlis go ahead and open one!

**Comment by vip32** [comment]
the extension in the PR works nice though
```
public static class MediatorExtensions
    {
        public static async Task<object> Send(this IMediator mediator, object request, CancellationToken cancellationToken = default)
        {
            return await mediator.Send((dynamic)request, cancellationToken);
        }
    }
```

**Comment by remcoros** [comment]
> the extension in the PR works nice though
> 
> ```
> public static class MediatorExtensions
>     {
>         public static async Task<object> Send(this IMediator mediator, object request, CancellationToken cancellationToken = default)
>         {
>             return await mediator.Send((dynamic)request, cancellationToken);
>         }
>     }
> ```

I have been doing this for years in one of our (plugin extendable) webservices.

- Have a registry of command names + .NET types. (plugins can register new command names + their type)
- on http request of a command, lookup it's .NET type by command name
- use JSON deserializer to deserialize to that type
- because it's all runtime, you get back an 'object' from the serializer,
- using that MediatR extension I send the command (object) to mediatr

Works like a charm

**Comment by vip32** [comment]
Yes, have the same case (command from json deserialization) glad I found
this thread ✌️
