### ISSUE TITLE
Pipeline are being called before than expected

### ISSUE THREAD

**Issue by Guilh3rme3Soar3es** [jbogard/MediatR#386]
First of all, sorry me about language mistakes. I'm brazilian and I've started study english recently...

I have a doubt about a problem that found in a project that I'm working. It's used ASP.NET Core, FluentValidation and MediatR in this project.

It's used a light implementation of CQRS too. The commands and queries implement IRequest interface. Inside of each one, it's exists a public inner class that contains the validations of FluentValidation (it extends AbstractValidator).

These inner classes was private. However it required testing it and my team decided to make public it. After this change, the pipeline behavior that validate the command and queries, it's called before of the execution of my end point in the controller.

If the inner class is private or isn't a inner class, the call doesn't occur before.

I would like to know if my implementation is an anti-pattern or it can be a problem with MediatR.

Can someone help me?
Thanks!

This is an example of my implementation:

` public class DeviceAddPrinter
    {
        public class Command : IRequest<Result<Exception, Unit>>
        {
            public int DeviceId { get; set; }
            public string Name { get; set; }
            public string SerialNumber { get; set; }
            public string IpAddress { get; set; }
            public int CurrentDeviceId { get; set; }

            public ValidationResult Validate()
            {
                return new Validator().Validate(this);
            }

            protected class Validator : AbstractValidator<Command>
            {
                public Validator()
                {
                    RuleFor(m => m.DeviceId).NotNull().NotEqual(0);
                    RuleFor(m => m.Name).NotNull().NotEmpty().Length(1, 100);
                    RuleFor(m => m.SerialNumber).NotNull().NotEmpty().Length(1, 100);
                    RuleFor(m => m.IpAddress).NotNull().NotEmpty();
                }
            }
        }
}`

**Comment by nixonad** [comment]
@Guilh3rme3Soar3es If your web project is using the FluentValidation.AspNetCore package and registering itself using something like this: `services.AddMvc()
  .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<PersonValidator>());` (as per the fluentvalidation documentation, then it will insert itself into the MVC pipeline and execute before your controller actions are executed. 
If you've also registered your validators in a MediatR pipeline then they will execute again there.
I got around this in my project by registering the validators with the DI container but not using the 'AddFluentValidation' extension method (which is what injects the validation into the mvc pipeline)
hth
