### ISSUE TITLE
can i run multi-prepost handler in parallel ? 

### ISSUE THREAD

**Issue by bigken** [jbogard/MediatR#387]
now i have about 15 IRequestPreProcessor, and in each one they all have a long process, i think now they are processed one by one in `single thread`,  for me this take too long time, can you please support parallel run those pre-post handlers?  thank you .

maybe likes this:
```
task.waitAll(PreRequestHandlers).continue(handler).continue(postRequestHandlers)~~
```

**Comment by bartosz6** [comment]
https://github.com/jbogard/MediatR/blob/8e0c349ff720dcf8d63cbb560d3718fd229076ae/src/MediatR/Mediator.cs#L68

**Comment by bartosz6** [comment]
Unfortunately it is not possible. This is how pipelines work - one belongs on the result of the other.

**Comment by jbogard** [comment]
Yep if you want to do something different, you can create your own pipeline step with its own "pre/post handlers". In fact, pre/post handlers are really only a single pipeline step. You can look to that as a guide about how to create your own.
