### ISSUE TITLE
When using the publish mode（asp.net core webapi）,each Handler being executed twice

### ISSUE THREAD

**Issue by swpudp** [jbogard/MediatR#389]
![QQ截图20190403095319](https://user-images.githubusercontent.com/11451713/55447457-6d904d00-55f6-11e9-924a-be30fef2366c.png)

![QQ截图20190403100007](https://user-images.githubusercontent.com/11451713/55447706-6584dd00-55f7-11e9-9373-aa97161a08bf.png)

![QQ截图20190403095605](https://user-images.githubusercontent.com/11451713/55447571-d5469800-55f6-11e9-8ac2-10591158f84f.png)

**Comment by syska** [comment]
@swpudp 

Can you recreate this issue in a Console app for .NET Core 2.x?

What IOC container are you using here? What version of Mediatr?

**Comment by swpudp** [comment]
@syska The IOC container is Autofac of version 4.9.2,MediatR version is 6.0.0

**Comment by RDalziel** [comment]
I think i'm getting the same - don't seem to get the problem with Microsoft DI

**Comment by RDalziel** [comment]
> I think i'm getting the same (From a console app) - haven't confirmed whether it's specific to Autofac yet!

Odd coincidence we got the same issue at roughly the same time. But my problem was daft - i had called AddMediator accidently which caused 2 instances of the notification handler to be in the container which results in them both being called.

**Comment by remcoros** [comment]
Looks like a dependency registration issue. This can happen when you do scanning for types and (by accident) add multiple instances of the same handler to the container.

Without sample code it's hard to tell, but double check if you don't do any duplicate registrations.

you could check this quickly by resolving a handler manually. E.g.

    var handlers = container.Resolve<INotificationHandler<TestNotification>>(); // use whatever method your container uses for resolving.

check 'handlers', it probably has double the amount of instances you expect.
