### ISSUE TITLE
Can't install nuget package in project targeting .NET 4.5.2

### ISSUE THREAD

**Issue by ellern** [jbogard/MediatR#39]
When I try to install MediatR in a project that targets .NET Framework 4.5.2 it fails. I'm using VS 2015 RC.

```
PM> Install-Package MediatR -Pre

Attempting to gather dependencies information for package 'MediatR.2.0.0-beta-004' with respect to project targeting '.NETFramework, Version=v4.5.2'
Attempting to resolve dependencies for package 'MediatR.2.0.0-beta-004' with DependencyBehavior 'Lowest'
Resolving actions to install package 'MediatR.2.0.0-beta-004'
Resolved actions to install package 'MediatR.2.0.0-beta-004'
Adding package 'MediatR 2.0.0-beta-004' to folder 'C:\Users\Dev\Documents\Visual Studio 2015\Projects\App\packages'
Added package 'MediatR 2.0.0-beta-004' to folder 'C:\Users\Dev\Documents\Visual Studio 2015\Projects\App\packages'
Install failed. Rolling back...
Package 'MediatR 2.0.0-beta-004' does not exist in project 'App.Core'
Removing package 'MediatR 2.0.0-beta-004' from folder 'C:\Users\Dev\Documents\Visual Studio 2015\Projects\App\packages'
Removed package 'MediatR 2.0.0-beta-004' from folder 'C:\Users\Dev\Documents\Visual Studio 2015\Projects\App\packages'
Install-Package : Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ Install-Package MediatR -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by jbogard** [comment]
Do other targets work for you?

**Comment by ellern** [comment]
4.5.1 does also fail with message `Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache`

I'm using latest NuGet 3.0 RC 2.

BTW. AutoMapper installed without any problems in same project.

**Comment by ellern** [comment]
Could it be because "System.Runtime" is missing from dnxcore50 dependencies inside project.son?

**Comment by nojaf** [comment]
Having the same issue here.

**Comment by tlycken** [comment]
I'm seeing this too.

Is there anything I can do to fix/test this locally? (I've never worked with NuGet packaging before...) The CSL dependency in earlier versions is a dealbreaker in our project, but if we can get this version to install that would be really sweet :)

**Comment by jbogard** [comment]
Can you make sure you uncheck the V3 NuGet API in the NuGet settings?

**Comment by tlycken** [comment]
It was already unchecked.

**Comment by jbogard** [comment]
I think what I can do is not target 4.5.2 and just target 4.5?

**Comment by tlycken** [comment]
Maybe)...? :P  (As I said, I've never published a nuget package, so not sure how dependencies and such are handled...)

If you can give some build instructions, I could probably build a package against 4.5 and try referencing that in our solution - or try any other fixes we can conceive.

**Comment by ellern** [comment]
FYI I've installed the package in a .xproj without any issue.

**Comment by jbogard** [comment]
Can you try the beta5 package? I've included explicit TFN releases.

**Comment by ellern** [comment]
It seems to work fine with VS2015RC and regular .NET 4.5.2 project.

**Comment by jbogard** [comment]
Nice! Can we close this?

**Comment by ellern** [comment]
It works on my machine.
I've just updated another project to beta5 without issues, so closing this.

**Comment by tlycken** [comment]
Yeah, this works for me too now. Thanks a lot for the speedy fix!
