### ISSUE TITLE
Async NotificationHandler with IOC lose scope

### ISSUE THREAD

**Issue by bernardo-bruning** [jbogard/MediatR#392]
My project has a news handler waiting to be sent to an api, and after sending it saves some information in the database.

When using the database context the system throws an exception saying that my database is already discarded.

I believe that may be the question of the scope of my dependency injection.

Should not publish create a new scope of dependency injection?

Code for simulate situation:

```
public async Task Handle(RegisteredCompanyNotification notification, CancellationToken cancellationToken)
{
    await Task.Delay(10000);
    disposibleObject.GetValue(); // My exception is raised why object is removed in memory with interface Dispose
}
```

**Comment by jbogard** [comment]
No, I don't think so, and in any case, MediatR doesn't know about any "scope". You can create a scope though if you override `PublishCore`.
