### ISSUE TITLE
AspnetCore DI and contravariant fun

### ISSUE THREAD

**Issue by NinoFloris** [jbogard/MediatR#393]
This line is the bane of my existence ;)
https://github.com/jbogard/MediatR/blob/master/src/MediatR/Mediator.cs#L35

Could we not do another major version bump and update IMediator.Send to be 
```cs
        Task<TResponse> Send<TRequest, TResponse>(
            TRequest request,
            CancellationToken cancellationToken = default (CancellationToken))
            where TRequest : IRequest<TResponse>;
```
In that case we at least have some way of forcing MediatR to fetch the correct type from the container by casting it beforehand.

**Comment by MarkusEischeid** [comment]
With this change you would have to define the type arguments explicitly when calling Send():
```csharp
mediator.Send<IRequest<Message>, bool>()
```
otherwise you would get a compiler error:
```
The type arguments for method
'CustomMediator.Send<TRequest, TResponse>(TRequest, CancellationToken)'
cannot be inferred from the usage.
```

Here is my solution for this:

ITypedRequest.cs (new Interface)
```csharp
    public interface ITypedRequest<TRequest, TResponse> : IRequest<TResponse>
    {

    }
```

Mediator.cs (and according signatures for Send() in IMediator.cs)
```csharp
        ...
        public Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (request == null)
            {
                throw new ArgumentNullException(nameof(request));
            }

            return this.Send(request, request.GetType(), cancellationToken);
        }

        public Task<TResponse> Send<TResponse>(IRequest<TResponse> request, Type requestType, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (request == null)
            {
                throw new ArgumentNullException(nameof(request));
            }

            if (requestType == null)
            {
                throw new ArgumentNullException(nameof(requestType));
            }

            var handler = (RequestHandlerWrapper<TResponse>)_requestHandlers.GetOrAdd(requestType,
            t => Activator.CreateInstance(typeof(RequestHandlerWrapperImpl<,>).MakeGenericType(requestType, typeof(TResponse))));
            return handler.Handle(request, cancellationToken, _serviceFactory);
        }

        public Task<TResponse> Send<TRequest, TResponse>(Lan.Cloud.Accounts.Queries.ITypedRequest<TRequest, TResponse> request, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (request == null)
            {
                throw new ArgumentNullException(nameof(request));
            }

            return this.Send(request, typeof(TRequest), cancellationToken);
        }
        ...
```

So can create a generic IRequestHandler like this:
```csharp
    public interface IMessage : ITypedRequest<IMessage, bool>
    {
    }

    public class Message1 : IMessage
    {
    }

    public class Message2 : IMessage
    {
    }

    public class MessageRequestHandler : IRequestHandler<IMessage, bool>
    {
        public async Task<bool> Handle(IMessage request, CancellationToken cancellationToken)
        {
            // logic here
            return true;
        }
    }
```

**Comment by NinoFloris** [comment]
I keep forgetting C# generic argument inference is so much worse than that of F# (no offence meant with it).

Yeah it might be a good overload candidate then? 
I don't mind specifying the generic arguments when it's the only way to fix a problem ;)

**Comment by jbogard** [comment]
Can you provide an example that shows the problem you're seeing?

**Comment by jbogard** [comment]
And years and years ago I think either me or @khellang opened an issue with the C# team to have better generic inference for exactly this scenario, but I can't find it.

**Comment by khellang** [comment]
There are tons of them. You can start off [this PR](https://github.com/dotnet/roslyn/pull/7850) and dig your way through all the linked issues 😄

**Comment by NinoFloris** [comment]
So right now I've just created my own version of IMediator with these Send methods

```cs
   public interface IMediator
    {
        Task<TResponse> SendDynamic<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default);
        Task<TResponse> Send<TRequest, TResponse>(TRequest request, CancellationToken cancellationToken = default)
            where TRequest: IRequest<TResponse>;

        ...
    }


``` 

This works well for both C# and F#. 
F# has simpler overload selection rules so having both methods be called `Send` instead means having to call `Send<_>` or `Send<_,_>` everywhere to disambiguate, even with inference it's no fun.

For C# having both be called `Send` works and currently picks the `IRequest<TResponse>` overload, however in that case we're basically creating the scenario that LDM is afraid of, why they call it a breaking change to have constraints influence generic method inference, currently it would pick `IRequest...`, but with better inference it'll pick the `TRequest` overload, subtly changing semantics.

Having these two methods would work for all cases and keeps the option open of deprecating `SendDynamic` once/if C# gets inference improvements, who knows, there may actually be some good use for it :)

<details><summary>Implementation</summary>

```cs
// InvokeHandler would be GetHandler + running pipeline with it.

   private static readonly MethodInfo InvokeHandlerMethodInfo =
        typeof(Mediator).GetMethod(nameof(InvokeHandler), BindingFlags.NonPublic | BindingFlags.Static);

    private delegate Task<TResponse> InvokeHandlerFunc<in TRequest, TResponse>(ServiceFactory serviceFactory, TRequest request, CancellationToken cancellationToken = default)
        where TRequest: IRequest<TResponse>;

    public Task<TResponse> SendDynamic<TResponse>(IRequest<TResponse> request,
        CancellationToken cancellationToken = default)
    {
        if (request == null) { throw new ArgumentNullException(nameof(request)); }

        // Contravariant cast because we don't statically know the requestType
        var handler = (InvokeHandlerFunc<IRequest<TResponse>, TResponse>)_mediatorCache.RequestHandlers.GetOrAdd(request.GetType(),
            t => Delegate.CreateDelegate(typeof(InvokeHandlerFunc<,>).MakeGenericType(t, typeof(TResponse)), InvokeHandlerMethodInfo));

        return handler.Invoke(_serviceFactory, request, cancellationToken);
    }

    public Task<TResponse> Send<TRequest, TResponse>(TRequest request, CancellationToken cancellationToken = default) where TRequest : IRequest<TResponse>
    {
        if (request == null) { throw new ArgumentNullException(nameof(request)); }

        var handler = (InvokeHandlerFunc<TRequest, TResponse>)_mediatorCache.RequestHandlers.GetOrAdd(typeof(TRequest),
            _ => (InvokeHandlerFunc<TRequest, TResponse>)InvokeHandler<TRequest,TResponse>);

        return handler.Invoke(_serviceFactory, request, cancellationToken);
    }
```

Using `Delegate.CreateDelegate` for the slow case with a method backing it is much easier than having wrapper types.
Also, I have pulled out the caches into a new type `MediatorCache` as instance members, such that they can be switched out (say container per tenant scenarios).
</details>

I'm happy to make a PR

**Comment by jbogard** [comment]
What issue are you running into that makes that line the bane of your existence?

**Comment by NinoFloris** [comment]
Aspnet DI won't resolve a contravariant service. It'll treat it as invariant. I have a request type that's extended (say `class B : A`) in our webhost project with extra attributes for query param converters. So I pass in `B` that should be resolved to a handler that takes A. I cannot achieve that as I cannot go around value.GetType

**Comment by jbogard** [comment]
Why not open a PR to fix that? They're suuuuuuuper receptive about adding valuable features to core DI.

Or use a container that does support variance?

**Comment by khellang** [comment]
> They're suuuuuuuper receptive about adding valuable features to core DI.

😂

**Comment by NinoFloris** [comment]
So I'm being laughed out of the room for proposing to do the work? 

Aspnet DI won't change, there are enough issues around variance on the basis that they want to be a lowest common denominator container.

MediatR regardless of container choice should allow you to statically pass in the request type you want to retrieve a handler for, not offer just this runtime resolution.

**Comment by jbogard** [comment]
My hesitance comes from adding more to the public API. I know it won't break anyone, but it's a bit ugly to use.

**Comment by jbogard** [comment]
I'll take a PR for it, can you include a test that shows the issue?

**Comment by NinoFloris** [comment]
@jbogard would this be something to add with it right away?
https://github.com/jbogard/MediatR/issues/385#issuecomment-476272304

Proposed interface is a bit bloated if we can't remove anything, but it works...
```cs
public interface IMediator
{
    Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default);

    // Start of new methods
    Task<object> Send(object request, CancellationToken cancellationToken = default);
    
    // Naming open for suggestions
    Task<TResponse> SendExact<TRequest, TResponse>(TRequest request, CancellationToken cancellationToken = default) where TRequest: IRequest<TResponse>;

   // ... Publish methods, do they need an extra method for 'Exact' dispatch too?
}
```

My ideal interface would have been:
But that ship has sailed I guess. (unless we would define a new IMediator in another namespace?)

```cs
public interface IMediator
{
    Task<TResponse> Send<TRequest, TResponse>(TRequest request, CancellationToken cancellationToken = default) where TRequest: IRequest<TResponse>;
}
```

@jbogard @khellang thoughts?

On top of that ideal interface you could easily define some extension methods for the dynamic things.

```cs
    public static class MediatorExtensions
    {
        private static readonly ConcurrentDictionary<Type, InvocationHelper> InvocationHelpers = new ConcurrentDictionary<Type, InvocationHelper>();

        private abstract class InvocationHelper
        {
            public abstract Task<object> InvokeDynamic(IMediator mediator, object request, CancellationToken cancellationToken);

            public class Impl<TRequest, TResponse> : InvocationHelper where TRequest : IRequest<TResponse>
            {
                public override async Task<object> InvokeDynamic(IMediator mediator, object request, CancellationToken cancellationToken)
                {
                    return await mediator.Send<TRequest, TResponse>((TRequest)request, cancellationToken);
                }
            }

        }

        // Public but not defined as an extension member
        public static Task<object> SendDynamic(IMediator mediator, Type requestType, object request, CancellationToken cancellationToken = default)
        {
            var handler = InvocationHelpers.GetOrAdd(
                requestType,
                rType =>
                {
                    Type responseType = null;
                    if (typeof(IRequest).IsAssignableFrom(rType))
                    {
                        responseType = typeof(Unit);
                    }
                    else
                    {
                        foreach (var i in rType.GetInterfaces())
                        {
                            if (i.IsConstructedGenericType && i.GetGenericTypeDefinition() == typeof(IRequest<>))
                            {
                                responseType = i.GenericTypeArguments[0];
                            }
                        }
                    }

                    if (responseType == null)
                    {
                        throw new ArgumentException("Invalid argument, request should implement IRequest<TResponse> or IRequest.", nameof(request));
                    }

                    return (InvocationHelper) Activator.CreateInstance(
                        typeof(InvocationHelper.Impl<,>).MakeGenericType(rType, responseType), true);
                }
            );

            // This may blow up once InvokeDynamic.Impl tries to cast the request value to requestType, caller beware.
            return handler.InvokeDynamic(mediator, request, cancellationToken);
        }

        public static Task<object> SendDynamic(this IMediator mediator, object request, CancellationToken cancellationToken = default)
            => SendDynamic(mediator, request.GetType(), request, cancellationToken);

        public static async Task<TResponse> SendDynamic<TResponse>(this IMediator mediator, IRequest<TResponse> request, CancellationToken cancellationToken = default)
            => (TResponse)await SendDynamic(mediator, request.GetType(), request, cancellationToken);
    }
```

**Comment by NinoFloris** [comment]
Any preference? 

Both will be a breaking change anyway. I'd rather do the second option and possibly let the PR wait a bit until you feel happy pushing a new major version into the world.

But it's your call in the end.

**Comment by jbogard** [comment]
Why is it a breaking change?

**Comment by NinoFloris** [comment]
Changing interfaces is a breaking change until we have default interface implementations

**Comment by jbogard** [comment]
Derp. Of course

**Comment by jbogard** [comment]
I would prefer an overload instead of a new method - that shouldn't break anyone (existing callsites would use the existing method, no?)

**Comment by NinoFloris** [comment]
Adding it as an overload could change method overload choice in future C# and it breaks inference in current F#. It really should be to be a new method. 

Regarding adding that method to IMediator.
If people implemented their own IMediator we have binary and source breaks. If people only called Send on IMediator we should have neither as the original interface slot is still there. Would need to actually test this to be absolutely sure though.

In any case you're not going to make those implementers of custom IMediator instances happy if you don't do a semver major bump

**Comment by jbogard** [comment]
Yeah of course, if we break the interface then we'll need to bump major
versions.

A new method though is...weird.

**Comment by NinoFloris** [comment]
If we do major bump we don't have to care about binary compatibility. We should then optimize for largest group of users. 

Change IMediator by removing the old `Send<TResponse>` and introduce new `SendRequest<TRequest, TResponse>` or some name like it.

Then to keep source compatibility have an extension method to keep the old Send method signature intact. It'll make the interface less pretty but keeps mostly everything going.

**Comment by NinoFloris** [comment]
Could also add a new focussed interface for Send ...

```
IRequestMediator 
{
    TResponse Send<Request, Response>(...)
}
```
Just this method and then again adding the dynamic parts via extension methods.

Would be very non breaking and not too confusing.

**Comment by jbogard** [comment]
Extension method possible?

**Comment by NinoFloris** [comment]
Not for the generic one, it needs a type argument so we can lock in the exact type of the request

**Comment by jbogard** [comment]
No I mean can you accomplish it with an extension method instead of
changing the interface?

**Comment by NinoFloris** [comment]
Yeah not really, like I said we need an exact type and we need to pass that exact type to the servicefactory which is private instance state :/

**Comment by NinoFloris** [comment]
I get if you don't want to go through with it, any option is really a bit suboptimal from this starting point. No hard feelings either, much of this work was also super useful for our own internal version!

**Comment by jbogard** [comment]
Yeah, I think I'll put this in the back burner for now. Maybe in C# 42?
