### ISSUE TITLE
Some handlers cannot be resolved when code is running in a docker image on linux

### ISSUE THREAD

**Issue by lnaie** [jbogard/MediatR#394]
Hello,

I'm using MediatR 6.0 with aspnet core 2.2.0 and core runtime 2.2.3.

I have a very curious issue with an API that works fine when the code is running in a docker image on windows but it breaks on linux only for PUT and PATCH requests. It works for the GET request. The API is using a self contained Application tier where all my MediatR  features are implemented in ContosoUniversityCore style.

I keep getting this:
```Error constructing handler for request of type MediatR.IRequestHandler`2[Application.Features.Feature1.PutFeature1+Request,MediatR.Unit]. Register your handlers with the container. See the samples in GitHub for examples.. Stack trace:    at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory)\n   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass0_0.<Handle>g__Handler|0()\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\n   at Api.Controllers.[...] ```

The features code is written in this style:
```
namespace Application.Features.Feature1
{
    public class PatchFeature1
    {
        public class Request : IRequest
        {
            // Properties
        }

        public class RequestHandler : IRequestHandler<Request>
        {
            // Private types injected
            //

            public RequestHandler(/* injected types */)
            {
            }

            public async Task<Unit> Handle(Request request, CancellationToken cancellationToken)
            {
                // await calls
                //
                return Unit.Value;
            }
        }
    }
}
```

Did anyone have this before?
Any help about how to debug this is greatly appreciated. 

Thanks!

**Comment by lnaie** [comment]
Eventually it was an exception thrown in the handler's constructor, obscured by a custom global exception handler.

**Comment by neoxack** [comment]
same issue only on linux
