### ISSUE TITLE
MediatR.Examples.DryIoc doesn't work with DryIoc release 4.x.x+

### ISSUE THREAD

**Issue by sm-framerelay** [jbogard/MediatR#396]
Thanks for great library and samples provided!

While trying different integration samples I've just noticed that MediatR.Examples.DryIoc doesn't work with any non-preview versions of DryIoc. Attempt to update 4.0.0-preview-01 to 4.0.0+ release causes runtime issue with DryIoc container:

![dryioc-mediatr400](https://user-images.githubusercontent.com/3810834/56475558-8cb22a00-6492-11e9-9c72-745fd5e2c100.PNG)

`System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at DryIoc.Container.GetConstantExpression(Object item, Type itemType, Boolean throwIfStateRequired) in \.nuget\packages\dryioc\4.0.3\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 1388`

Unfortunate I haven't found the root of issue, but seem DryIoc Container.cs logic at line 1384:

`public Expression GetConstantExpression(object item, Type itemType = null, bool throwIfStateRequired = false)
        {
            // Check for UsedForExpressionGeneration, and if not set just short-circuit to Expression.Constant
            if (!throwIfStateRequired && !Rules.ThrowIfRuntimeStateRequired && !Rules.UsedForExpressionGeneration)
                return Constant(item, itemType);`

fails to return ConstantExpression Constant(object value, Type type) for case when Type is null

**Comment by dadhi** [comment]
@sm-framerelay, I will check.

**Comment by jbogard** [comment]
Anything we need to update here? Just the package reference?
