### ISSUE TITLE
Handler was not found for request of type MyClass+Command. Container or service locator not configured properly or handlers not registered with your container

### ISSUE THREAD

**Issue by robertlongstreth** [jbogard/MediatR#397]
My web api is working properly when i run it in VS2019, this issue only happens when I have deployed it to an on prem server.  This appears to be happening when i try to inject a dbcontext into my handler.

Here is the pertinent code from my configure services method:
````
	services.AddCors()
		.AddDbContext<PricingContext>(
			options => options.UseSqlServer(Configuration.GetConnectionString("someConnectionString"),
				sqloptions => sqloptions.CommandTimeout(150)))
		.AddMediatR(typeof(BusinessLogic.Loader).Assembly)
````
Here is the code from my RequestHandler:
````
  internal class LogRequestResponsHandler : IRequestHandler<LogRequestResponse>
    {
        private readonly PricingContext context;
        public LogRequestResponsHandler(PricingContext context)
        {
            this.context = context;
        }
        public async Task<Unit> Handle(LogRequestResponse request, CancellationToken cancellationToken)
        {
            var logger = new DataAccess.Entities.PricingLog
            {
                User = context.Users.FirstOrDefault(x => x.UserID == request.userID),
                SecurityID = request.configurationID,
                claimSubmitted = request.pricingTool.ClaimSubmitted,
                claimResponse = request.pricingTool.ClaimResponse,
                JSONReceived = Newtonsoft.Json.JsonConvert.SerializeObject(request.pricingRequest)
            };
            await context.PricingLogs.AddAsync(logger);
            await context.SaveChangesAsync();
            return Unit.Value;
        }
    }
````
this is running under .net core 2.2 using Mediatr 6.0.0

**Comment by syska** [comment]
What version of Windows Server? 
Though IIS? 
What if you run it on the server with "dotnet run"
What if you run it on IIS locally?
What Windows version?

Can you make a replica of this?

**Comment by robertlongstreth** [comment]
I found the issue.  I was building in release mode, and deploying to my dev system.  I did not have my connection strings in the proper config file.  I found the error when i ran it using kestrel.  I wish that it gave me a better error message in swagger when i ran it.

@syska, thanks for the heads up about running it from the kestrel
