### ISSUE TITLE
Ideas to implement Handlers for multi-tenant scenario?

### ISSUE THREAD

**Issue by coderabsolute** [jbogard/MediatR#398]
Am writing the multi-tenant application which has a typical Request, Response, and Handlers to handle the standard business scenario.

Now, I have a requirement to handle the business logic for some specific tenants separately due to their different business process.

I wonder how others are handling this type of requirement? Can someone please shed a light on this topic.

Thanks in advance!

**Comment by lilasquared** [comment]
One possible solution would be to have a different request type for the tenants that have different logic.  

```csharp
switch (tenant.type) {
    case A:
        await mediator.send(new RequestA(tenant));
        break;
    case B:
        await mediator.send(new RequestB(tenant));
        break;
    case default:
        await mediator.send(new NormalRequest(tenant));
        break;
}
```

if you have hundreds or thousands of different tenants with different logic then you can use a container to scan for the different types and construct a request provider that creates the right request for the right tenant.

**Comment by jbogard** [comment]
I would add - don't lean on the container *too* much for these scenarios. You might be better off creating your own custom pipeline behavior "container" and then manually deciding which request to send off.

You can create plugins based on their existence or not, or some other conditional that you wrap before calling them.

**Comment by JosephWoodward** [comment]
@lilasquared What solution did you come up with in the end for your requirement?

> You can create plugins based on their existence or not, or some other conditional that you wrap before calling them.

Do you happen to have any examples of what this might look like? Thanks.

**Comment by lilasquared** [comment]
I didn't have this requirement i was just giving a suggested approach.  Might want to ask @coderabsolute
