### ISSUE TITLE
Pipeline behaviors execution order / constrained behaviors

### ISSUE THREAD

**Issue by AleRoe** [jbogard/MediatR#399]
Hi there,

this is not really an issue and I assume that what I'm experiencing is by design, but I wanted to make sure:

I'm making extensive use of pipeline behaviors along my request path, whereby I have a number of generic behaviors which apply to all requests and some more specific requests which only apply to certain request types.

I thought I could achieve the latter by implementing IPipelineBehavior<MyType, Unit> and then registering this specific behavior. But it turns out that pipeline behaviors implementing a more specific type than IRequest (registered using open generics) get executed before any of the more generic IPipelineBehavior<TRequest, TResponse> behaviors.

The "workaround" is to use constraints when implementing IPipelineBehavior which results in all handlers being executed in the order they were registered.

Nevertheless, it makes behavior definition and registration a bit more cumbersome and forces me to register my constrained behaviors as open generics as well, despite them being closed.

Is there any way to influence the execution order of the behaviors or is this just by design that more specific behaviors are executed prior to more generic ones?

Any comments welcome!

Cheers
Alexander

**Comment by jbogard** [comment]
Depends on the container, really

**Comment by AleRoe** [comment]
Unity

**Comment by jbogard** [comment]
No idea tbqh. Some containers guarantee the order executed is the order registered, some don't.
