### ISSUE TITLE
`INotification` restriction

### ISSUE THREAD

**Issue by MiloszKrajewski** [jbogard/MediatR#402]
Hi,

This is not a bug, it is more like a question or feature request.

I like to keep my DTOs in assembly with no dependencies at all - pure data. In such case though I cannot use them as MediatR requests/commands or notifications/events as it would require referencing MediatR from pure DTO assembly.

As I understand need for `IRequest<TResponse>` interface (declaring response type) the requirement to implement empty `INotification` interface on notifications feels a little bit artificial.

I guess I could use my DTOs as notification by making completely identical class and use... AutoMapper :-) I could also add `MyDTOWrapper<T>: INotification` which I could use to wrap any DTO as MediatR monitification. Thing become a little bit hairy with `IRequest`, of course.

I would like you to consider:
1. Dropping `INotification` restriction
2. Moving interfaces to separate assembly `MediatR.Annotations` (`Abstraction`? `Interfaces`?). The dependency would be still there, of course, but now assembly dragged along would be like 5k maybe.

Regards,
Milosz Krajewski

**Comment by jbogard** [comment]
Why do you keep them without dependencies?

**Comment by MiloszKrajewski** [comment]
Kind of the "banana" case:
"Because the problem with object-oriented languages is they’ve got all this implicit environment that they carry around with them. You wanted a banana but what you got was a gorilla holding the banana and the entire jungle."

I guess not having dependencies is a generally a good thing and enable reuse in some other context. Splitting libraries by dependencies feels to me like good idea. It is equivalent at all but for example, we are running Hangfire on MySql but because of how Hangfire is release (on assembly) it drags all the Microsoft SQL dlls even though they are not used at all.

I liked the idea that `IObservable<T>` is in `System` while "the whole rest of it" is in `System.Reactive`.
I also really welcomed approach used in .NET core with Microsoft.Extensions.Logging` and `Microsoft.Extensions.Logging.Abstractions`, `Microsoft.Extensions.DependencyInjection` and `Microsoft.Extensions.DependencyInjection.Abstractions`. 
Also `Microsoft.Orleans.Client`, `Microsoft.Orleans.Server` and `Microsoft.Orleans.Core.Abstractions` belong to different areas, so get distributed as 3 assemblies rather than `Orleans`, even if there would be functional different if it was.

I feel like, we should always try to put Interfaces (and attrbiutes) in separate assemblies.

**Comment by jbogard** [comment]
Do you have other consumers of these DTOs that would force you to remove
dependencies?

**Comment by MiloszKrajewski** [comment]
In short: yes.
This issue was the situation where we had some external messages which were handled by some other mechanism. There also was some code review comment: "Why not announce this message with MediatR?".
After 5 minutes we found out that "Oh.. It would add MediatR dependency to all those other assemblies which do not need it at all and this is relatively big change for Friday afternoon,". So it didn't happen.

It would also affect producer (of events) and persistence (of these events). Both absolutely agnostic about actual "announcement" (or handling) mechanism.

My question would be: why not do it?

**Comment by jbogard** [comment]
Typically if I have external consumers, I create a different message. I
don’t want external consumers to receive internal messages. I’ll translate
my internal message to the external one. Anti-corruption layer and all that.

**Comment by MiloszKrajewski** [comment]
My case was opposite: handling external message handled by internal consumer. 
You argument about anti-corruption layer valid but splitting MediatR into two assemblies would not prevent that.
What it prevents is to handle external messages internally, straight from the queue (for example) like:
```
queue.Subscribe(mediator.Publish)
```
and have message validation in notification handler decorator (as there are no pipeline behaviors for notifications).

I'm thinking of messages as contracts, like protobuf defintions, for example, It would feel weird to add MediatoR to assembly dedicated to contain protobuf messages (.proto files and generated .cs files).
It just doesn't feel right. They can be handled by MediatR but they don't require MediatR.

**Comment by jbogard** [comment]
The way I see it, anything consuming MediatR messages is intentionally
coupled, so the reference is immaterial. If I want to decouple, I’d
republish or translate to a different, external message.

Or just not use MediatR. The pattern for publishing is very simple.

**Comment by MiloszKrajewski** [comment]
You are absolutely right what you say although you are not really addressing what I'm saying:

* "I don’t want *external consumers* to receive *internal messages*" while in fact my case is "*internal consumer* processing *external messages*".
* "anything consuming *MediatR messages*" while in fact my case is about *non-MediatR* messages.

It doesn't make this case any stronger and I guess I'm not going to convince you (well, I'm not even convince myself). I don't feel very strong about it, I just had a hunch that `Mediator.Annotations` might be a good idea. You don't like it and it is absolutely fine. Inability to handle external messages by MediatR consumers make a good case for AutoMapper, after all ;-)
