### ISSUE TITLE
Running app using dotnet run throws System.InvalidOperationException: Unable to resolve service for type 

### ISSUE THREAD

**Issue by sameerkattel** [jbogard/MediatR#403]
Running app from **commandline using dotnet run** throws System.InvalidOperationException: Unable to resolve service for type 

but if i debug the **app through visual studio in iis.express** it runs fine.

` System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[Command,System.Collections.Generic.List`1[Result]]. Register your handlers with the container. See the samples in GitHub for examples. -`

**Using MediatR Version="7.0.0"**

**Comment by joro550** [comment]
Could you post a gist of some of your code? from this small example it's quite difficult to know what technologies you are using i.e. what di framework are you using? Is this a console app or asp app? 

Could you create a repository that can replicate the issue?

**Comment by MaikuMori** [comment]
Had the same problem in Core 3.1 project using `PublishSingleFile`, `PublishTrimmed`, `PublishReadyToRun` set to `true`. Runtime was `linux-x64`.

Reverting to running `.dll` fixed the problem.

**Comment by sameerkattel** [comment]
> Could you post a gist of some of your code? from this small example it's quite difficult to know what technologies you are using i.e. what di framework are you using? Is this a console app or asp app?
> 
> Could you create a repository that can replicate the issue?

Sorry, I can't recreate this issue any longer. I think i reordered mediatr service registration line to get around this - but not sure as it has already been sometime since i faced this issue. btw,  I was using asp.net core inbuilt di framework and it was asp.net core app
will create a gist if I face this issue again. Thanks!
