### ISSUE TITLE
Question about ValueTask for IRequestHandler

### ISSUE THREAD

**Issue by DenisTsapelnikov** [jbogard/MediatR#404]
May it be ValueTask instead of Task for synchronous requests for a more generic way of doing things?

**Comment by bartosz6** [comment]
ValueTask is not to be replacement for Task. Even if, this would be a breaking change, which would require every consumer of MediatR to change every single handler.
From MediatoRs point of view we cannot say which requests will be executed synchronously.

[Why not to use valueTask by default](http://dotnetapis.com/pkg/System.Threading.Tasks.Extensions/4.3.0/netstandard1.0/doc/System.Threading.Tasks.ValueTask'1)

**Comment by DenisTsapelnikov** [comment]
Thanks for clarification

**Comment by christophedemey** [comment]
I would like to use ValueTask also in some scenario's, maybe MediatR could support both ?

**Comment by christophedemey** [comment]
@DenisTsapelnikov 

Another solution would be to add a function or class with function that returns valuetask and then await it in the IRequestHandler interface implementation.

For example, in your requesthandler : 
```
public async Task<RealestateObject> Handle(RealEstatePushRequestModel request, CancellationToken cancellationToken)
{
    return await GetValue();
}

public ValueTask<RealestateObject> GetValue()
{
    if (!cacheActive)
    {
        //Fetch data
        return new ValueTask<RealestateObject>(GetDataFromEndpointAsync());
    }
    else
        return new ValueTask<RealestateObject>(new RealestateObject() { ObjectKey = "cached data" });
}
```
