### ISSUE TITLE
Ninject MVC Binding issue

### ISSUE THREAD

**Issue by alexandermlharris** [jbogard/MediatR#407]
MediatR v=5.1.0
Ninject v=3.2.0.0
.Net Framework v=4.5.2
Microsoft.AspNet.Mvc v=5.2.3
VisualStudio = 2019

Adding MediatR into an existing MVC web project. Steps so far:

1) Install nuget package
2) Bindings (alongside my existing Ninject bindings):

~~~
kernel.Bind(scan => scan.FromAssemblyContaining<IMediator>().SelectAllClasses().BindDefaultInterface().Configure(x => x.InRequestScope()));
kernel.Bind<ServiceFactory>().ToMethod(ctx => t => ctx.Kernel.TryGet(t));
kernel.Bind<IRequestHandler<MyNewCommand>>().To<MyNewCommandHandler>().InRequestScope();
~~~

3) Code:

~~~
public class MyNewCommand: IRequest
{
    // Properties
}

public class MyNewCommandHandler : IRequestHandler<MyNewCommand>{
     public async Task<Unit> Handle(MyNewCommand request, CancellationToken cancellationToken)
     {
            // do some stuff
            return Unit.Value
     }
}
~~~

4) Usage (MVC Controller)

~~~
await _mediator.Send(new MyNewCommand{ });
~~~

What I'm getting is:

* `_mediator` is activated by the kernel and passed to my constructor
* `.Send()` is called and throws and exception:

>Value cannot be null.
>Parameter name: source

~~~
   at System.Linq.Enumerable.Reverse[TSource](IEnumerable`1 source)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at MyProject.Namespace.Controllers.MyController.<MyAction>d__17.MoveNext()
~~~

I've tried:

* Binding by convention
* Binding explicately (as above)
* Implementing the `ContravariantBindingResolver` and adding it to the kernel as per the samples

Nothing seems to change this.

While looking at `ctx.Kernel.TryGet(t)` I can see that:

* The type being activated is: 
~~~
System.Collections.Generic.IEnumerable`1[[MediatR.IPipelineBehavior`2[[MyProject.MyNewCommand, MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MediatR.Unit, MediatR, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null]], MediatR, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null]]
~~~

Inspecting the kernel bindings, there is a matching binding for:

~~~
System.Collections.Generic.IEnumerable`1[[MediatR.IPipelineBehavior`2[MyProject.MyNewCommand, MyAssembly, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MediatR.Unit, MediatR, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null]], MediatR, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
~~~

Of note there is that the binding has a the PublicKeyToken set whereas the type to be bound doesn't....

I'm out of ideas for this, is this
* My project setup
* My ninject setup being incorrect
* My MedatR setup being incorrect / incomplete
* Something else?

Many thanks!

**Comment by jbogard** [comment]
I have no idea, I'm not a Ninject user. Might I suggest StackOverflow?

**Comment by alexandermlharris** [comment]
Understood - apologies. Solved this by down-grading to MediatR 4 (or 3) and making the tweaks to binding required (moving from ServiceFactory to Single/Multi Instance Factory bindings etc).

Now works like a charm, so I suspect that the Ninject version wasn't happy with the v5 MediatR version. If I have time to move back to v5 and fix the problem (probably via a Ninject version bump) I'll post what worked for me.

The joys of back-porting into old code ;)

@jbogard - fantastic library which I've been wanting to use for ages and finally had the chance to get my hands dirty. So much nicer than those ever expanding constructor calls passing in endless Query / Command Handlers etc.

Many thanks!

**Comment by alexandermlharris** [comment]
@VinitaHotwani - sadly never had a chance to go back to this to try for a better solution.
