### ISSUE TITLE
Can TMediatR.publish() have a return value?

### ISSUE THREAD

**Issue by tobecon** [jbogard/MediatR#409]

**Comment by henkmollema** [comment]
`Publish()` is used for notifications and publishes to multiple notification handlers. Because there would be multiple return values, returning a value from `Publish()` doesn't really make sense.

**Comment by tobecon** [comment]
> `Publish()` is used for notifications and publishes to multiple notification handlers. Because there would be multiple return values, returning a value from `Publish()` doesn't really make sense.

well , may be it can return a ```Task<TResult[]>``` ? just like ```Task.WhenAll()``` Or should I deal with 
Business logic in Handler ?

**Comment by jbogard** [comment]
What exactly are you trying to do? What's your use case?

The point of notifications is fire-and-forget. The point of request/response is to get a request and response. It sounds like you're trying to implement a different pattern than these two.

**Comment by tobecon** [comment]
> What exactly are you trying to do? What's your use case?
> 
> The point of notifications is fire-and-forget. The point of request/response is to get a request and response. It sounds like you're trying to implement a different pattern than these two.

Thanks! You're right. I was misunderstand the request/response. 
My use case is 

- First:  There is a  request which have a task list 
- Second: I fire a Task Handler list for each task in the list
- Third: Then return the value from every Task handler (Task handler have different logic inside itself , but they have same return value) 

So it is neither the pattern of  fire-and-forget and request/response. 
My solution is create a object that contains the return value list. 
Finally It may be match the pattern of request/response. and It works well now.
