### ISSUE TITLE
Publish overload with notification of type object

### ISSUE THREAD

**Issue by oliverhanappi** [jbogard/MediatR#410]
The `IMediator` interface contains the following method:

```csharp
Task Publish(object notification, CancellationToken cancellationToken = default);
```

In its implementation `Mediator` there is however a runtime type check if the argument `notification` implements `INotification`. Why does the interface allow `object` if callers are supposed to only pass instances which implement `INotification`?

**Comment by jbogard** [comment]
Because that’s a constraint on the handler interface.

**Comment by jbogard** [comment]
And it supports scenarios where you may not know the type at compile time.

**Comment by oliverhanappi** [comment]
Maybe I am missing something: Why is the method on the interface not defined as follows?

```csharp
Task Publish(INotification notification, CancellationToken cancellationToken = default);
```

**Comment by lilasquared** [comment]
If at compile time you can't confirm that your object is of type INotification then you wouldn't be able to use publish.  Without the constraint you can

**Comment by oliverhanappi** [comment]
Is there any reason why I should not use one of the following?

```csharp
if (message is INotification notification)
  await _mediator.Publish(notification);
```

or

```csharp
await _mediator.Publish((INotification) message);
```
