### ISSUE TITLE
can't use IServiceCollection.AddMediatR() in .NET core Preview 6

### ISSUE THREAD

**Issue by xubb1988** [jbogard/MediatR#412]
i user MediatR in .net core p6 ,their no ServiceCollection Extensions function AddMediatR,
my os is win10, VS2019,MediatR 6.0  and 7.0 not work both  
and 6.0 not worked   on .net core 2.2 in a project
by the way  my other project use 6.0   but is work
![TIM截图20190620233900](https://user-images.githubusercontent.com/17037219/59862079-abf70600-93b4-11e9-8758-15f2669e75eb.png)

thanks

**Comment by gemcloud** [comment]
I met with the issue either, I fixed it by add Nuget
Install-Package MediatR.Extensions.Microsoft.DependencyInjection
and We just install "MediatR.Extensions.Microsoft.DependencyInjection" which including "MediatR".
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
