### ISSUE TITLE
Validating handler existence

### ISSUE THREAD

**Issue by vhe1** [jbogard/MediatR#413]
This is probably not an issue, more a question:
I'm worried about missing or too many handlers for a command.
Another package, AutoMapper comes with its own validation function that I can run as a unit test that validates that all required mapper profiles exist

Is there a similar (or other) way to validate that each command showing up in a Send call has exactly one handler registered?

**Comment by jbogard** [comment]
This is usually covered via an integration test around the handler that
actually calls into startup. See my contoso university repos for examples.
