### ISSUE TITLE
Question: Is it possible to use the same object type for the Request and Response objects when using IRequestHandler 

### ISSUE THREAD

**Issue by stephenpatten** [jbogard/MediatR#414]
Due to constraints out of my control (ACORD)  I have to use the same High-Level object as a container for both the request and responses. It's called a TXLife_Type object when you gen out the xsd, but when serialized to and from XML it will be a TXLife root node. Anyways, I  now am facing this issue when trying to create a handler:

public class MyHandler : IRequestHandler<TXLife_Type, TXLife_Type>

The compiler is complaining that "The type 'TXLife_Type' cannot be used as type parameter 'TRequest' in the generic type or method 'IRequestHandler<TRequest, TResponse>'. There is no implicit reference conversion from 'TXLife_Type' to 'MediatR.IRequest<TXLife_Type>'."

What a PITA!

Any suggestions are welcome.

Thank you,
Stephen

**Comment by lilasquared** [comment]
I’m not sure I understand what is forcing you to use the generated type as the mediator request and response. But a request does have to implement IRequest as indicated by the error message. Would wrapping the Generated type in request message where that type is a property not be sufficient?

**Comment by stephenpatten** [comment]
The signature of the WCF SOAP call is

TXLife DoSomething(TXLife request)

This is how the signature needs to look in order to pass Acord validation
with business partners

**Comment by lilasquared** [comment]
MediatR doesn't have that method signature anyway as the handlers accept a cancellation token and return tasks (they are async).  Wouldn't something like this be better as a translation layer from what you are required to conform to (Acord) and what you are using (MediatR)?

```csharp
public class MyClass 
{
    private IMediator _mediator;
    public MyClass(IMediator mediator)
    {
        _mediator = mediator;
    }

    public TXLife DoSomething(TXLife request)
    {
        var myRequest = new MyRequest
        {
            Payload = request
        };

        var result = _mediator.Send(myRequest, CancellationToken.None).Result;

        return result;
    }
}
```

**Comment by stephenpatten** [comment]
I believe that will work.

What I thought had to happen was reuse of the request and response
signature all through the pipeline.

 Ahhh, the handler can be different, thanks for showing me something new
Aaron! FYI, my code is fully async, I just forget to write it up that way

-Stephen
