### ISSUE TITLE
Mediatr tutorials / more samples

### ISSUE THREAD

**Issue by andrewduffy77** [jbogard/MediatR#416]
I'm a Mediatr yellow belt, and have been through all Contoso samples they were great. I'm now looking for more sample code written by anyone with more Mediatr experience than me.

In particular some of the techniques Jimmy mentioned in https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/ eg using Domain services (as was its original purpose in the DDD book)

I guess I'm looking for a more complicated sample with a more complex domain, can just be someones demo project etc.

Thanks!

**Comment by no1melman** [comment]
Do you want something more complex - I kinda like the simplicity that mediatr brings - I've found the most complex thing I've had to do is create session object from http and pass that into mediatr... which was really straightforward

**Comment by remcoros** [comment]
eShopOnContainer from Microsoft

Can't remember if they used Mediatr, but it has quiet a few patterns implemented (unit of work, messaging, publish/subscribe, etc.)

**Comment by jbogard** [comment]
You can also check out my Contoso University projects, with full working examples.
