### ISSUE TITLE
MediatR.Examples.Windsor registers components as Singleton

### ISSUE THREAD

**Issue by nallejacobsson** [jbogard/MediatR#418]
MediatR.Examples.Windsor does not specify the lifestyle when registering IMediator and the handlers, which means the [default lifestyle (Singleton)](https://github.com/castleproject/Windsor/blob/master/docs/lifestyles.md) is used. But I gather from https://github.com/jbogard/MediatR/issues/257 and https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/issues/63#issuecomment-486225133 this is not recommended.

**Comment by jbogard** [comment]
PR?

**Comment by nallejacobsson** [comment]
What?

**Comment by jbogard** [comment]
Pull Request?

**Comment by nallejacobsson** [comment]
Sorry, Git newbie, not familiar with the lingo 😁
