### ISSUE TITLE
Type implementing INotificationHandler and IRequestHandler is called more than once on Notification

### ISSUE THREAD

**Issue by jehof** [jbogard/MediatR#420]
I have a type `MySuperHandler` that implements an `INotificationHandler<SomethingHappened>` and also an `IRequestHandler<ShouldItHappen, true>`. 

The type is registered through MediatR.Extensions.Autofac.DependencyInjection (3.0.0) once at startup using `builder.AddMediatR(typeof(Program).Assembly);`

When I publish the Notification `SomethingHappened` using

`await _mediator.Publish(new SomethingHappened());`

the Handle method for `SomethingHappened` of `MySuperHandler` gets called twice. 

Implementing multiple different INotificationHandler on a type is no problem. The Handle will only be called once.

Removing the interface IRequestHandler<ShouldItHappen,true> from the type, solves the problem and the method gets only called once.

Is this a bug within Mediatr? Is it not allow to implement an INoficationHandler and IRequestHandler on the same type?

    public class MySuperHander : INotificationHandler<SomethingHappened>, IRequestHandler<ShouldItHappen,bool>    {

        public async Task Handle(SomethingHappened notification, CancellationToken cancellationToken)   {
            Console.WriteLine("It has happened");
        }

        public async Task<bool> Handle(ShouldItHappen request, CancellationToken cancellationToken)    {
            return true;
        }
    }

    public class ShouldItHappen : IRequest<bool>    {    }

    public class SomethingHappened : INotification    {    }

This will print out "It has happened" twice. when calling `await _mediator.Publish(new SomethingHappened());`

**Comment by lilasquared** [comment]
Since notification handlers are one to many my guess is that due to the IRequestHandler being picked up by the dependency scan, and it also implements INotificationHandler your registration has two copies of your implementation of INotificationHandler.  Some containers will let you log out what they scanned and what implementations they have.  If you were to check that my guess is you would have two copies of MySuperHandler as registered implementations of INotifciationHandler

**Comment by jehof** [comment]
Looking through IMediatr while debugging it says the type is registered once as INotificationHandler and once as IRequestHandler

![image](https://user-images.githubusercontent.com/1583129/61141589-34f1f080-a4ce-11e9-9379-5512ce5a3b8c.png)

**Comment by lilasquared** [comment]
That collection is used simply to store the type map between INotifications and INotificationHandlers.  Internally the NotificationHandlerWrapperImpl still uses the service factory to construct all instances that match that type and then iterates them.  You need to see if there is more than one in the registry / module / whatever it is called for autofac.

```csharp
internal class NotificationHandlerWrapperImpl<TNotification> : NotificationHandlerWrapper
        where TNotification : INotification
    {
        public override Task Handle(INotification notification, CancellationToken cancellationToken, ServiceFactory serviceFactory, Func<IEnumerable<Func<Task>>, Task> publish)
        {
            var handlers = serviceFactory
                .GetInstances<INotificationHandler<TNotification>>()
                .Select(x => new Func<Task>(() => x.Handle((TNotification)notification, cancellationToken)));

            return publish(handlers);
        }
    }
```

**Comment by jehof** [comment]
I think you are right. Currently dumping autofac registrations and I think I saw MySuperHandler registered more than once for INotificationHandler. Let me check that

**Comment by jehof** [comment]
Then it may be more a problem with the MediatR.Extensions.Autofac.DependencyInjection, that should ensure that the type is not registered multiple times with the interface

**Comment by lilasquared** [comment]
It may be working as intended.  I would question the use case of having a single class implementing both the INotificationHandler and IRequestHandler.  I would also suggest testing it out with another DI container to see if the behavior is the same.  If not then it might be something unique to Autofac

**Comment by jehof** [comment]
AutoFac and MediatR might work as intended, cause they do what they got telled. For me this is a bug in the registration component, that I use, so I head over to this. 

But I think this is a bad (implementation) restriction, to avoid implementing INotificationHandler and IRequestHandler on the same type. Is it also recommended to only implemented one INotificationHandler on a type (and not multiple times for different notifications)?

**Comment by lilasquared** [comment]
I would say in general when keeping SOLID in mind you would want to isolate responsibility of the notification handlers to their own classes.  Any shared functionality between them could be offloaded to an injected dependent service if necessary.
