### ISSUE TITLE
make registering IPipelineBehavior not required.

### ISSUE THREAD

**Issue by ofirgeller** [jbogard/MediatR#421]
I gave this framework a try (with simple injector) and found that this feature which is not basic requires one more setup step to get a minimal example working. 

Working back from the sample I was able to avoid adding actual IPipelineBehavior(s)  but I still needed to register an empty collection of them to avoid the exception.

I think "baking in" a do nothing IPipelineBehavior  might get some up and running faster. unless I am missing something and this is a inalienable part of the library.

**Comment by jbogard** [comment]
It may be an inalienable part of SimpleInjector, not MediatR. MediatR just makes requests to the container, it's entirely up to the feature set of the container to provide registration and resolution.

Compare that with StructureMap/Lamar for example:

https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.Lamar/Program.cs#L33

With my MS DI extensions, however, I *don't* automatically add all pipeline behaviors. This is because people may want a specific ordering of behaviors, so I leave it up to the container's registration to provide that.

**Comment by lilasquared** [comment]
@jbogard would changing these lines to avoid the exception make sense or is the exception indicative of improper registration configuration?

https://github.com/jbogard/MediatR/blob/8e0c349ff720dcf8d63cbb560d3718fd229076ae/src/MediatR/Internal/RequestHandlerWrapper.cs#L46-L49

to
```csharp
            var behaviors = serviceFactory
                .GetInstances<IPipelineBehavior<TRequest, TResponse>>() 
                    ?? Enumerable.Empty<IPipelineBehavior<TRequest, TResponse>>();
            
            return behaviors
                .Reverse()
                .Aggregate((RequestHandlerDelegate<TResponse>) Handler, (next, pipeline) => () => pipeline.Handle((TRequest)request, cancellationToken, next))();
```

If an exception is expected maybe a function similar to `GetHandler` on `RequestHandlerBase` that throws an invalid operation exception would make sense.

```csharp
protected static IEnumerable<IPipelineBehavior<TRequest, TResponse>>> GetPipelineBehaviors<TRequest, TResponse>(ServiceFactory factory)
{
    var behaviors = factory..GetInstances<IPipelineBehavior<TRequest, TResponse>>();

    if (behaviors == null)
    {
        throw new InvalidOperationException($"Some message that I can't think of right now.");
    }

    return behaviors;
}
```

**Comment by jbogard** [comment]
Registering behaviors shouldn’t be required, but I don’t know if this kind of change would mask problems or not.

It would be odd if a container returned null, though. I’d treat returning null enumerables as a bug.

**Comment by lilasquared** [comment]
Ah I thought the exception @ofirgeller was referring to was because the container returned null.  but it looks like this is just expected behavior for SimpleInjector

> Warning: Simple Injector requires a call to Collection.Register to be made, even in the absence of any instances. Without a call to Collection.Register, Simple Injector will throw an exception.
