### ISSUE TITLE
Register conrete PipelineBehaviour

### ISSUE THREAD

**Issue by LaterStart** [jbogard/MediatR#422]
Hi,

Is it possible to use concrete implementation of IPipelineBehaviour?

**For example:**
```
public class CommandValidationBehavior : IPipelineBehavior<ICommand, Guid>
{
}
```

**which would be registered as service:**
`services.AddTransient(typeof(IPipelineBehavior<ICommand,Guid>), typeof(CommandValidationBehavior));`

I am asking because I couldn't manage to register such behavior. It only works for <,> generic use cases.

**Comment by jbogard** [comment]
Which container are you using?

**Comment by LaterStart** [comment]
Built in .NET Core

**Comment by jbogard** [comment]
Ah then it doesn’t support this. This is contravariance. I have a PR open:

https://github.com/aspnet/Extensions/pull/536

But won’t be merged any time soon.

**Comment by LaterStart** [comment]
Oh ok, until then its the if statements :)
