### ISSUE TITLE
Best Practices - should calls to mediatr command/queries be atomic?

### ISSUE THREAD

**Issue by larkydoo** [jbogard/MediatR#425]

**Comment by larkydoo** [comment]
To clarify, if I am creating, say, a user, and that user has an address in a separate table, should I make two command classes - one to create the user and one to create the address - or is it okay to do this in a single command?

**Comment by jbogard** [comment]
I'm sorry, what question? I think something messed up in your first post, I don't see anything but a title of "atomic".

**Comment by larkydoo** [comment]
Doh! Sorry, forgot to save the title change. Should be visible now.

**Comment by jbogard** [comment]
I do everything in a single command - to me, commands are mapped to requests, and requests are the atomic user action being performed.

**Comment by larkydoo** [comment]
Thanks!
