### ISSUE TITLE
Best Practice - Usage of CultureInfo in  IRequestHandler Handle

### ISSUE THREAD

**Issue by BartHuls** [jbogard/MediatR#428]
Hi,

In the handle method of the IRequestHandler I want to be sure that the 
                    Thread.CurrentThread.CurrentCulture = culture;
                    Thread.CurrentThread.CurrentUICulture = culture;
are set to the "users" culture.

Now I'm setting the in the IApplicationBuilder.Use handler, but it seems that the Handle method is handled on a other thread (so it's not taken over the culture settings).
What is the best way to solve this.

**Comment by jbogard** [comment]
No idea! Try StackOverflow.

**Comment by jbogard** [comment]
FYI if you're in ASP.NET Core, there are other ways of setting the culture:
