### ISSUE TITLE
Samples work differently for AspNetCore and Autofac

### ISSUE THREAD

**Issue by vyacheslav-mikhaylov** [jbogard/MediatR#430]
## asp net core di sample output
Sending Ping...
- Starting Up
- Starting Up
-- Handling Request
- Starting Up
- Starting Up
-- Handling Request
--- Handled Ping: Ping
-- Finished Request
- All Done
- All Done with Ping
- All Done
-- Finished Request
- All Done
- All Done with Ping
- All Done

## Autofact output
Sending Ping...
- Starting Up
-- Handling Request
--- Handled Ping: Ping
-- Finished Request
- All Done
- All Done with Ping

**Comment by jbogard** [comment]
That’s to be expected. They’re different containers with different
available features.

**Comment by vyacheslav-mikhaylov** [comment]
Do you know how to make aspnetcore work the same way as autofac?

**Comment by jbogard** [comment]
Nope.

**Comment by vyacheslav-mikhaylov** [comment]
Well, it is the case when aspnetcore di acts correctly. In the samples you have registration for 5 open generics and then you scan assemblies. The scan apparently doubles the registrations.
