### ISSUE TITLE
Building on a Mac - Consideration

### ISSUE THREAD

**Issue by no1melman** [jbogard/MediatR#435]
I've tried to just do straight up `dotnet build` on a mac... obviously that throws a single error of 461 not available - to be expected.

I've just changed the csproj slightly ( based on [this blog](https://dev.to/davidwengier/targeting-builds-for-multiple-frameworks-and-machines-5h22) )

```
<TargetFrameworks>netstandard2.0</TargetFrameworks>
<TargetFrameworks Condition="'$(OS)' != 'Unix'">net46;netstandard2.0</TargetFrameworks>
```

I run this with `dotnet build` and it works without any errors. This becomes more prevalent when you run `dotnet pack` (it won't work unless the above)

It might not be a necessary - just thought I would share.

**Comment by JosephWoodward** [comment]
@no1melman There are a few ways to do this. [This PR](https://github.com/jbogard/MediatR/pull/436) adds support for compiling on Mac/Linux and is generally the preferred approach.

**Comment by no1melman** [comment]
Sweet
