### ISSUE TITLE
when i throw an exception, the mediaR can still run next step

### ISSUE THREAD

**Issue by liugt34** [jbogard/MediatR#437]
The CommandHandler
```
public virtual Task<Unit> Handle(AddFileAuthorizeCommand cmd, CancellationToken cancellationToken)
{
        try{
               .......
          }
         catch (Exception ex)
            {
                _logger.LogError(ex, "新增授权失败");
                throw new DivideByZeroException(ex.Message);
            }
}
```
![image](https://user-images.githubusercontent.com/8056013/64248571-10514c80-cf44-11e9-974a-34998a4604b1.png)
when it throw the exception, it still run to the  next step,
![image](https://user-images.githubusercontent.com/8056013/64248591-1e9f6880-cf44-11e9-93e0-ba32488e2f2d.png)

i had an gloable exception filter ,but it can not enter in,because the exception has been eat

```
services.AddMvcCore(options =>
            {
                options.Filters.Add<GlobalExceptionFilter>(99);
            })
```

so, any one met this problem,and how resolve it,need help!

**Comment by jbogard** [comment]
It doesn’t look like you’re awaiting the Task there. If you don’t await
tasks any exception will happen later.

**Comment by liugt34** [comment]
@jbogard  thanks for your reply, 
but when i add an await before
`return  await _bus.SendCommandAsync(fileAuthCommand);`
all the program cracked!

**Comment by liugt34** [comment]
i resolved it by both add the "async" before the Controller.Action
public async Task<IActionResult> Post([FromBody]AddFileAuthorizeViewModel addModel);
and first await in the action
`await _fileAuthorizeService.InsertAsync(model);`
and then await in the service layer

```
public async Task InsertAsync(FileAuthorizeViewModel viewModel)
        {
            var fileAuthCommand = _mapper.Map<AddFileAuthorizeCommand>(viewModel);
            await _bus.SendCommandAsync(fileAuthCommand);
        }
```
it worked! but i still don't know why!

**Comment by jbogard** [comment]
Because you never awaited the task - tasks that aren't awaited have exceptions that aren't caught.
