### ISSUE TITLE
Question about IPipelineBehavior only for certain types of requests (marked by interface))

### ISSUE THREAD

**Issue by zap93** [jbogard/MediatR#441]
I would like to register an IPipelineBehavior in a way that it gets executed only for certain types of requests (using a marker interface).

Let me post an example:

`
public class ElaborateCommand : ICommittableRequest
{
 
public DateTime From { get; set; }
public DateTime To { get; set; }

 }

`

ICommittableRequest already implements IRequest<Unit>.

How can I register a PipelineBehavior that is executed only for the ICommittableRequests?

This is the way I registered the behaviors with the default Asp.Net Core container:

`
services.AddTransient(typeof(IPipelineBehavior<,>), typeof(LoggingPipelineBehavior<,>));

services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationPipelineBehavior<,>));

services.AddTransient(typeof(IPipelineBehavior<ICommittableRequest,Unit>),typeof(CommitPipelineBehavior));
 
services.AddTransient(typeof(IPipelineBehavior<ElaborateCommand,Unit>),typeof(ElaborateCommandPipelineBehavior));
`

I have also a custom behavior for some requests (for example the ElaborateCommand request).

The CommitPipelineBehavior is implemented this way: 

`public class CommitPipelineBehavior : IPipelineBehavior<ICommittableRequest, Unit>`

At the moment the CommitPipelineBehavior  is never executed.

Is there a way to achieve this kind of specification?

Thanks in advance

**Comment by andreortigao** [comment]
I don't know if it would be feasible to add a behavior to specific commands like you proposed.  but you can execute a pipeline behavior for a specific interface with a poor man checking:

```
class MyPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
{
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        if(request is ICommittableRequest commitableRequest)
        {
            /* commitableRequest.Foo = "Bar"; */
        }
        return await next();
    }
} 
```

**Comment by nixonad** [comment]
I'm not 100% sure this will solve your scenario, but I use something similar for validation and adding a constraint on TRequest seems to work for me.
Something like:
```public class MyPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : IRequest<TResponse>, ICommittableRequest { ... }```

**Comment by zap93** [comment]
I will surely check if this will solve my issue.

Thanks for your help, I will post my code if everything works correctly maybe someone else will find this usefull.

**Comment by KostaMadorsky** [comment]
> I'm not 100% sure this will solve your scenario, but I use something similar for validation and adding a constraint on TRequest seems to work for me.
> Something like:
> `public class MyPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : IRequest<TResponse>, ICommittableRequest { ... }`

@nixonad How do you register your pipeline? I was going to use the same approach, but it throws when I execute some other commons that do not implement the interface: "violates the constraint of type 'TRequest'."

**Comment by KostaMadorsky** [comment]
@nixonad As per https://github.com/jbogard/MediatR/issues/305, this should be fixed in .Net Core 3.1.
Still waiting for AWS Lambda support for it...

**Comment by tradercentric** [comment]
There is no need to register ICommitableRequest.  The ICommitableRequest will have the following:

public interface ICommitableRequest: IRequest<Unit> { properties }
, and the implementation: 
public CommitableRequest: ICommitableRequest { public properties }

Then you can use the MyPipelineBehavior from KostaMadorsky.

I had the same question and able to resolve it by above.  So, now I can get rid of type checking code like:

public Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next) {

   var myRequest = request as CreateTestSequenceCommand
     if (myRequest == null)
       throw new ArgumentNullException(nameof(myRequest));

**Comment by sigridbra** [comment]
@zap93 @KostaMadorsky Did any of you succeed in doing it the way @nixonad proposed ? I am struggling with the same type of issue now, and also getting the same error as @KostaMadorsky.

**Comment by lilasquared** [comment]
Constrained generics are not supported by the default DI for dotnet core (until 5.0).  If you need this functionality from the DI you will need to use a 3rd party DI like Lamar.

**Comment by KostaMadorsky** [comment]
@sigridbra you would need to upgrade to .NET 5 in order to make it work nicely with the default DI:
https://jimmybogard.com/constrained-open-generics-support-merged-in-net-core-di-container/amp/

**Comment by koncewiczbartosz** [comment]
i would do it like that:

class MyPipelineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : ICommittableRequest
{
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        // business logic
        return await next();
    }
}
