### ISSUE TITLE
Add support for Simple Requests to keep number of request classes low

### ISSUE THREAD

**Issue by starx207** [jbogard/MediatR#442]
I started using this library in an ASP.NET Core web api and I started to find that I was creating a lot of request classes with only a single property (for operations such as GetById or DeleteById) since I can't send a request of a primitive type (int, string, bool, etc). I came up with a solution that I think others may benefit from. 

It involves creating a generic request class:
``` c#
public class SimpleRequest<TRequest, TResponse> : IRequest<TResponse> {

    public TRequest Request { get; }

    public SimpleRequest(TRequest request) => Request = request;
}
```

And also an abstract request handler (based on `RequestHandler`):
``` c#
public abstract class SimpleRequestHandler<TRequest, TResponse> : RequestHandler<SimpleRequest<TRequest, TResponse>, TResponse> {
   
    protected abstract TResponse Handle(TRequest request);

    protected override TResponse Handle(SimpleRequest<TRequest, TResponse> request)
        => Handle(request.Request);
}
```

**Usage**
So if I have a controller with a GetById method, I could use the simple request like this:
``` c#
public class FooController : ControllerBase {

    public Task<Foo> GetById(int id) 
        => _mediator.Send(new SimpleRequest<int, Foo>(id));
}
```

And my handler would look like this:
``` c#
public class FooHandler : SimpleRequestHandler<int, Foo> {
    protected override Foo Handle(int request) {
        // code to get Foo and return it
    }
}
```

I'd be happy to work on adding this if you think it would be helpful to other users of the library. I also thought of adding a `SimpleAsyncRequestHandler<TRequest, TResponse>` in much the same way.

**Comment by jbogard** [comment]
That's an interesting idea! I'm a little worried about adding too many helpers I don't use though - we don't have primitive requests like this, so I wouldn't know if the feature needed any changes or not.
