### ISSUE TITLE
Registration Exception Only when Publish site on IIS

### ISSUE THREAD

**Issue by ppatel514** [jbogard/MediatR#443]
Hi There!
I am getting the Exception :
{"error":["Error constructing handler for request of type MediatR.IRequestHandler`2[Wateration.Application.UseCases.Customers.Queries.GetCustomerDetailsQuery,Wateration.Application.UseCases.Customers.Models.CustomerOutputModel]. Register your handlers with the container. See the samples in GitHub for examples."],"stackTrace":" ........

But this happens only when the site is published on IIS. On the IISExpress and on the IIS published on the development machine it works fine!! I Have checked SDK and Run-time versions as well as any versioning conflicts and there is no problem there! Any Help????

**Comment by syska** [comment]
* What container?
* What version?
* What SDK? 
* How do you register the handlers?
* How do you use it?
* Can you show the code for the smallest possible recreation of the issue?

And all other relevant information would be awesome ...

**Comment by ppatel514** [comment]
Version/SDK - .NET Core 2.2

Here is the exact solution I am trying to implement. https://github.com/JasonGT/NorthwindTraders

The solution works locally with IISExpress but it does not when publishing to IIS.

**Startup Class snippet**

            // Add MediatR
            services.AddMediatR(typeof(GetProductQueryHandler).GetTypeInfo().Assembly);


**Controller snippet**

public class ProductsController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult<ProductsListViewModel>> GetAll()
        {
            return Ok(await Mediator.Send(new GetAllProductsQuery()));
        }
   }

**GetProductQueryHandler**

namespace Northwind.Application.Products.Queries.GetProduct
{
    public class GetProductQueryHandler : MediatR.IRequestHandler<GetProductQuery, ProductViewModel>
    {
        private readonly INorthwindDbContext _context;
        private readonly IMapper _mapper;

        public GetProductQueryHandler(INorthwindDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public async Task<ProductViewModel> Handle(GetProductQuery request, CancellationToken cancellationToken)
        {
            var product = _mapper.Map<ProductViewModel>(await _context
                .Products.Where(p => p.ProductId == request.Id)
                .SingleOrDefaultAsync(cancellationToken));

            if (product == null)
            {
                throw new NotFoundException(nameof(Product), request.Id);
            }

            // TODO: Set view model state based on user permissions.
            product.EditEnabled = true;
            product.DeleteEnabled = false;

            return product;
        }
    }
}

**Comment by ppatel514** [comment]
any luck with this issue? do you more details to recreate?

**Comment by acheriya** [comment]
Can you post the exception details. I had fixed similar issue,  I missed connectionString but the exception was same, But the inner exception helped
