### ISSUE TITLE
Mediatr throws exception when invoked in Parallel

### ISSUE THREAD

**Issue by Beczka** [jbogard/MediatR#444]
Hi, 
I'm not sure if this is na error but https://github.com/jbogard/MediatR/blob/master/src/MediatR/Mediator.cs#L38 this will throw an exception when invoked like this (at least for few starting threats) :

`Parallel.ForEach(someList, (someElement) =>
 {
      _mediator.Send(new Request() { Element = someElement})
 });`

Method GetOrAdd of ConcurrentDictionary is not atomic. But I'm not sure if this is by design and I should not use mediator like this.

**Comment by jbogard** [comment]
Typically not - we usually scope the `IMediator` instance per request, so in the above code you'd create the instance inside the `Parallel.ForEach`.

How are you hosting this? What is running MediatR?

**Comment by Beczka** [comment]
Thanks for promp response. I thought I'm using this wrong (it was just simple to reuse what I've got in code)  :) Regarding hosting it is inside hangfire task and _mediator it is injected there as singelton.

**Comment by Beczka** [comment]
But when you think about it [_requestHandlers  ](https://github.com/jbogard/MediatR/blob/master/src/MediatR/Mediator.cs#L17 ) is static field so no matter how many instances of mediator I will create they all will point to the same dictionary. So in the context of a web application, there could  be a situation where two requests (for the same handler) will hit serwer at the same time (like one in a million cases but it could happen) and we can get en exception inside GetOrAdd right ?

**Comment by jbogard** [comment]
Ah you’re right!

**Comment by remcoros** [comment]
GetOrAdd is not atomic, but it ís thread-safe.

See Remarks on https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=netframework-4.8#System_Collections_Concurrent_ConcurrentDictionary_2_GetOrAdd__0_System_Func__0__1__

Because it is not atomic, You COULD get the value back which was inserted by another thread, and your value is discared. But since it is a cache, it doesn't matter here.

**Comment by matercha** [comment]
@remcoros Could you share why you vote for removal of static?

**Comment by remcoros** [comment]
There is no control over the lifetime of the cache.

I was playing around with dynamic assembly loading/unloading and type generation, and there was no way for me to clear the static cache, so MediatR would hold on to the types in that assembly. And (from what I remember), when I load two times the same assembly (trough Assembly.LoadFrom(byte[]), it still holds references to the types in the first assembly.

It's very much an edge case. But I'd like to have some control.

e.g. trough a IHandlersTypeCache, with a default implementation like it is now (using static).

Haven't given it much thought though.

**Comment by Beczka** [comment]
@remcoros ehh you are right :) problem was with how I set up IoC :) Thanks for a clear response with GetOrAdd

**Comment by jbogard** [comment]
@remcoros if you can figure a way to add it without affecting existing users, I'm open to a PR. I don't want to make DI registration more complicated.

**Comment by remcoros** [comment]
> @remcoros if you can figure a way to add it without affecting existing users, I'm open to a PR. I don't want to make DI registration more complicated.

Yea figured that. It's so edge casy, that it's probably not worth the trouble. And if anyone still needs to get rid of that dictionary, they can fork (that's what I did back then).

This issue can be closed.

**Comment by jbogard** [comment]
Another option would be to allow you to subclass and override like we did with the `Publish` options.
