### ISSUE TITLE
INotification in PublishCore

### ISSUE THREAD

**Issue by jacobrabjohns** [jbogard/MediatR#445]
Hi,

I notice a PR has been accepted to pass the INotification into publish core.  This is a change Ill be needing (until you guys get around to adding notification pipelines) as it facilitates my caching model.

How would be best to go about getting these changes? Is there any chance of a release fairly soon including them? Or should I fork the repo and create my own packages, in which case I may as well go the whole hog and add pipelines as well?

**Comment by jbogard** [comment]
The master builds are on MyGet, check the readme for a link.

I wait about 6-9 months between major releases to allow the API to stabilize.

**Comment by jacobrabjohns** [comment]
Thanks mate, much appreciated! <3 

Love the library, onto my 7th project using it.
