### ISSUE TITLE
Preoblems using Scrutor + MeadiatR to decorate RequestHandlers

### ISSUE THREAD

**Issue by lurumad** [jbogard/MediatR#447]
Hi @jbogard 

I have an scenario where I need to decorate some RequestHandlers in order to add cache. For this reason I decided to use Scrutor.

I've created an CachePingHandler in your TestApp

```csharp
public class CachePingHandler : IRequestHandler<Ping, Pong>
{
    private readonly PingHandler handler;

    public CachePingHandler(PingHandler handler)
    {
        this.handler = handler;
    }

    public Task<Pong> Handle(Ping request, CancellationToken cancellationToken)
    {
        return handler.Handle(request, cancellationToken);
    }

}
public class PingHandler : IRequestHandler<Ping, Pong>
{
    private readonly TextWriter _writer;

    public PingHandler(TextWriter writer)
    {
        _writer = writer;
    }

    public Task<Pong> Handle(Ping request, CancellationToken cancellationToken)
    {
        return Task.FromResult(new Pong { Message = request.Message + " Pong" });
    }
}
```

I've added Scrutor to the solution and I've added the decorator:

```csharp
private static IMediator BuildMediator(WrappingWriter writer)
{
    var services = new ServiceCollection();

    services.AddSingleton<TextWriter>(writer);
    services.AddMediatR(typeof(Ping));

    foreach (var service in services)
    {
        Console.WriteLine(service.ServiceType + " - " + service.ImplementationType);
    }

    services.Decorate<IRequestHandler<Ping, Pong>, CachePingHandler>();

    var provider = services.BuildServiceProvider();

    return provider.GetRequiredService<IMediator>();
}
```

If I run the application:

![image](https://user-images.githubusercontent.com/1729519/66316213-89fba200-e917-11e9-8a0a-6c3fa1e2d72a.png)

If I change the order in the file, works:

```csharp
public class PingHandler : IRequestHandler<Ping, Pong>
{

}

public class CachePingHandler : IRequestHandler<Ping, Pong>
{

}
```

Digging into the source code of MediatR.Extensions.Microsoft.DependencyInjection, I've seen that when you register the services you are using **TryAddTransient**:

https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/blob/ab26360b20ad813f9c3876179aba650ea2fb776c/src/MediatR.Extensions.Microsoft.DependencyInjection/Registration/ServiceRegistrar.cs#L95

For that reason It's obvious that if the class of the cache is find first it's not able to create the instance of the decorated handler.

My questions is: 

Is there any way to do this regardless the order of the handlers?

Kind regards!

**Comment by jbogard** [comment]
Don't use decorators - they're too problematic in relying on DI magic. Instead, I added [Behaviors](https://github.com/jbogard/MediatR/wiki/Behaviors) to address these kinds of cross-cutting concerns.

**Comment by lurumad** [comment]
Thanks for your reply @jbogard!

With behaviors, Can I decided which handlers should cache? Because only a wnat to cache Query handlers and nor Commands.

Kind regards!
