### ISSUE TITLE
Handler executing multiple times

### ISSUE THREAD

**Issue by julipur** [jbogard/MediatR#448]
I am using MediatR with a .net core 3.0 application and registering my handlers via the MediatR extension. My notification handler is being executed multiple times (8 times or so). My code is very simple (gist: https://gist.github.com/julipur/032ce2b512100586b1750280ea9ca627). Am I using something incorrectly here?

I have used similar approach before with success and am wondering if there any known issues with .net core 3.0 (DI maybe)?

**Comment by jbogard** [comment]
This is almost always because the handlers are registered multiple times. Check the `IServiceCollection` object to make sure you don't see multiple entries.

I haven't tested with Core 3.0 yet, but there weren't many (if any) changes made to the core DI stuff.

**Comment by julipur** [comment]
All my command handlers and query handlers working registered the same way and working. This the first notification handler I added and registered it, and it has the issue. I do see it multiple times in the collection even if I remove my line that explicitly adds it to DI (from my startup.cs file in the gist)

**Comment by julipur** [comment]
I replaced all my explicit handler registrations with this line 

    services.AddMediatR(typeof(Startup).GetTypeInfo().Assembly);

and it worked. 

Thanks @jbogard  for responding.

**Comment by jbogard** [comment]
Ohhhhhhh yes those other ones use the type as a marker type to grab the
assembly. You don’t register individual handlers.

**Comment by ge022** [comment]
All of my pipeline behaviors are running twice. Registering the services, I tried Assembly.GetExecutingAssembly(), typeof(Startup).Assembly, and typeof(Startup).GetTypeInfo().Assembly.
I am on version 8.1.0. Any ideas what could be going on?

**Comment by lilasquared** [comment]
Pipeline behaviors are not registered using the extension method discussed above.  You have to register them manually.  Can you show what service registration code you are using?

**Comment by ge022** [comment]
@lilasquared Turns out one of the behavior handler is calling _mediator.Send, which sends that through the handler itself and through the other pipelines.

**Comment by lilasquared** [comment]
ah yes that can be problematic.  It is highly recommended to not use the IMediator from within any hander or pipeline.  as of 9.0 that interface was split into IPublisher and ISender to help mitigate those mistakes.
