### ISSUE TITLE
Custom Route Parameters

### ISSUE THREAD

**Issue by TDK1964** [jbogard/MediatR#450]
Hi Jimmy,

My controller class is decorated with this route specification
```
[ApiController]
[Route("api/portfolios/{Code}/[controller]")]
public class MyController : ControllerBase { ... }

[HttpGet]
public async Task<IActionResult> Get(string parentCode) { ... }
```
And my Query looks like this
```
[HttpGet]
public class Query : IRequest<IEnumerable<Command>>
{
     public string ParentCode { get; set; }
     public string Code { get; set; }
}
...
```

The problem is {Code} defined in the route is not being picked up by the Query. 
What have I missed?

**Comment by jbogard** [comment]
Don’t you need FromQuery, not HttpGet?

**Comment by no1melman** [comment]
Or maybe FromRoute if that is still a thing
