### ISSUE TITLE
Revise the request handler API

### ISSUE THREAD

**Issue by vanillajonathan** [jbogard/MediatR#456]
The current API is confusing.

- For some request handlers you implement an interface, for other request handlers you inherit from an abstract base class.
- The `AsyncRequestHandler` (with the word "async") is used for asynchronous handlers, but `IRequestHandler` (without the word "async") is also used for asynchronous handlers.
- There is a unconventional `Unit` struct to represent `void`.

## Current API
The current API uses a mix of both interfaces and abstract base classes.

| Description | Type | Name
|-|-|-
| Asyncronous with response | Interface | `IRequestHandler<TRequest, TResponse>`
| Asyncronous without response | Abstract | `AsyncRequestHandler<TRequest>`
| Syncronous | Abstract | `RequestHandler<TRequest, TResponse>`

Uhm, this is confusing and I am probably wrong here about something.

## Proposal
| Description | Type | Name
|-|-|-
| Asyncronous with response | Interface | `IAsyncRequestHandler<TRequest, TResponse>`
| Asyncronous without response | Interface | `IAsyncRequestHandler<TRequest>`
| Syncronous with response | Interface | `IRequestHandler<TRequest, TResponse>`
| Syncronous without response | Interface | `IRequestHandler<TRequest>`

- Unify usage by always and consistently using interfaces for both sync and async, as well as for both with and without response.
- Drop the abstract base classes.
- Drop the `Unit` struct.

**Comment by khellang** [comment]
The abstract classes are just convenience classes that hide some cruft if you need your handlers to be sync-only (wraps result in a `Task<T>`) or you don't want to return a response (implicitly returns a throwaway `Unit`). This makes the implementation very simple by only having to care about a single interface, `IRequestHandler<TRequest, TResponse>`. There's nothing forcing you to use any of the abstract base classes.

**Comment by vanillajonathan** [comment]
Well the abstract classes (in the case of `AsyncRequestHandler`) are not only used for sync-only, they are also used for asynchronous handlers without messages.

They are supposed to be convenient, but I think they are a bit confusing when some are interfaces, some are abstract base classes, and some are named with "Async", even though there is an interface without "Async" that can be used for async too.

Maybe it would be better to clean up the API as proposed and rewrite the implementation to inspect the return type to determine if it is a `Task`, a `Task<>` or something else. Not sure how much that would complicate the internals.

Compare with ASP.NET Core, in a controller you can return `IActionResult`, `Task<IActionResult>` or just a class, a collection of classes (to be serialized) or data type such as `string`.
https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types

**Comment by khellang** [comment]
> Well the abstract classes (in the case of `AsyncRequestHandler`) are not only used for sync-only, they are also used for asynchronous handlers without messages.

Yes, that's why I said "or you don't want to return a response (implicitly returns a throwaway `Unit`)"

> Maybe it would be better to clean up the API as proposed and rewrite the implementation to inspect the return type to determine if it is a Task, a Task<> or something else.

Are you saying drop the interfaces altogether? Or include `Task` in the generic parameter and inspect the return type at runtime?

> Not sure how much that would complicate the internals.

Pretty substantially. It would probably increase the code size by 2-3x. Not to mention the potential performance hit. Sure, it's possible, but is it worth it just so you can use an interface instead of an abstract class? Why does interface vs class even matter? Just aesthetics?

> Compare with ASP.NET Core, in a controller you can return `IActionResult`, `Task<IActionResult>` or just a class, a collection of classes (to be serialized) or data type such as `string`.
> [docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types)

Yes, or `ActionResult` or `Task<ActionResult>` or `ActionResult<T>` or `Task<ActionResult<T>`. How is that less confusing? I think this just underlines the point; you have to know what you're doing and why you're doing it.

**Comment by vanillajonathan** [comment]
> Are you saying drop the interfaces altogether? Or include Task in the generic parameter and inspect the return type at runtime?
To drop the abstract base classes and just use interfaces as is shown on the table above under the proposed header.

Yeah there would be a need to inspect the return type of the request handler to know if it is a `Task`, a `Task<>` or some other non-awaitable object.

> Sure, it's possible, but is it worth it just so you can use an interface instead of an abstract class? Why does interface vs class even matter? Just aesthetics?

My desire is for simplicity, predictability and comprehension. Using abstract classes classes would be fine too, I just find it undesirable to have a mix of both interfaces and abstract classes, as well as the inconsistent naming where you use an abstract base class with the word "async" in the name to implement some async handlers, while using a interface that does not contain the word "async" in the name to also implement async handlers. It makes it unpredictable.

Compare this so the [IAuthorizationFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iauthorizationfilter) and [IAsyncAuthorizationFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iasyncauthorizationfilter) interfaces which are very logically named and predictable.

**Comment by lilasquared** [comment]
The move to a single interface (async first) was an explicit move for MediatR v4.0 - you can check out the release notes here https://github.com/jbogard/MediatR/releases/tag/v4.0.1

I agree with @khellang that the classes are simply convenience classes and are not part of public API / Interface of the library, they are simply implementations of the interface to reduce boilerplate code on the users part.  Use them, or don't.  The public api for MediatR Handlers is simply 

| Description  | type   |Name   |
|---|---|---|
| Asyncronous with response | Interface | `IRequestHandler<TRequest, TResponse> `|
| Asyncronous without response | Interface | `IRequestHandler<TRequest>` |
| Asyncronous without response | Interface | `INotificationHandler<TNotification>` |

**Comment by khellang** [comment]
> inconsistent naming where you use an abstract base class with the word "async" in the name to implement some async handlers, while using a interface that does not contain the word "async" in the name to also implement async handlers

Right, it's unfortunate that one contains `Async` while the other doesn't, when it's not asynchrony that differentiates them. Ideally, one would be called `NoResponseRequestHandler<TRequest>`, but that's a bit of a mouthful as well 😝

> Using abstract classes classes would be fine too, I just find it undesirable to have a mix of both interfaces and abstract classes

If you're fine with abstract base classes and really want consistency, it's pretty easy to roll your own set of abstract base classes if you want to:

```csharp
public abstract class RequestHandler<TRequest, TResponse> : IRequestHandler<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    public abstract Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken);
}

public abstract class NoResponseRequestHandler<TRequest> : IRequestHandler<TRequest, Unit>
    where TRequest : IRequest
{
    async Task<Unit> IRequestHandler<TRequest, Unit>.Handle(TRequest request, CancellationToken cancellationToken)
    {
        await Handle(request, cancellationToken);
        return Unit.Value;
    }

    public abstract Task Handle(TRequest request, CancellationToken cancellationToken);
}

public abstract class SyncRequestHandler<TRequest, TResponse> : IRequestHandler<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    Task<TResponse> IRequestHandler<TRequest, TResponse>.Handle(TRequest request, CancellationToken cancellationToken)
    {
        return Task.FromResult(Handle(request));
    }

    public abstract TResponse Handle(TRequest request);
}

public abstract class SyncNoResponseRequestHandler<TRequest> : IRequestHandler<TRequest, Unit>
    where TRequest : IRequest
{
    Task<Unit> IRequestHandler<TRequest, Unit>.Handle(TRequest request, CancellationToken cancellationToken)
    {
        Handle(request);
        return Unit.Task;
    }

    public abstract void Handle(TRequest request);
}
```

Which ends up looking like this:

Description | type | Name
-- | -- | --
Asynchronous with response | Abstract | RequestHandler<TRequest, TResponse>
Asynchronous without response | Abstract | NoResponseRequestHandler<TRequest>
Synchronous with response | Abstract | SyncRequestHandler<TRequest, TResponse>
Synchronous without response | Abstract | SyncNoResponseRequestHandler<TRequest>

> Compare this so the [IAuthorizationFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iauthorizationfilter) and [IAsyncAuthorizationFilter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.iasyncauthorizationfilter) interfaces which are very logically named and predictable.

The only reason those exist is because of legacy MVC, which introduced `IAuthorizationFilter` long before there was an async counterpart. The same goes for

- `IResourceFilter` and `IAsyncResourceFilter`
- `IPageFilter` and `IAsyncPageFilter`
- `IActionFilter` and `IAsyncActionFilter`
- `IResultFilter` and `IAsyncResultFilter`

If you also include `ActionFilterAttribute`, which mplements both the sync and async interfaces, things really start to get hairy.

If you take a look at the MVC internals, you'll the crazy amount of hoops they have to jump through to support both interfaces.

**Comment by vanillajonathan** [comment]
Oh now you made it much more clearer and easier for me to understand. When you present it this way, it looks very simple and easy, and not confusing at all.

Now if I want an synchronous request handler without a response, I can just implement `IRequestHandler<TRequest>` without declaring a return statement. If I want a synchronous request handler with a response I can just return `await Task.FromResult("Pong");`.

But then the abstract base classes doesn't really serve any purpose. I can just use the interface and either not return or return with [`Task.FromResult`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.fromresult). Right?

So then I would like to propose the removal of the abstract base classes – they serve no purpose and their existence is just a source of confusion.

**Comment by khellang** [comment]
> But then the abstract base classes doesn't really serve any purpose. I can just use the interface and either not return or return with `Task.FromResult`.
> So then I would like to propose the removal of the abstract base classes – they serve no purpose and their existence is just a source of confusion.

Yes and no. As I said in my first comment; they're convenience classes to save you from writing some cruft, like wrapping results in a `Task` if your handler is synchronous, or returning `Unit` if you don't care about the result. That's it.

**Comment by vanillajonathan** [comment]
> Yes and no. As I said in my first comment; they're convenience classes to save you from writing some cruft, like wrapping results in a Task if your handler is synchronous, or returning Unit if you don't care about the result. That's it.

Well wrapping the result in a Task is rather simple, and I would say its easier than to figure out which of all those base classes to use. As for when not caring about the result, isn't there the `IRequestHandler<TRequest>` interface for that?

I feel these base classes cause more confusion than convenience.
