### ISSUE TITLE
Provide a RequestHandler interface that returns IAsyncEnumerable

### ISSUE THREAD

**Issue by adnang** [jbogard/MediatR#458]
Now that we have C# 8.0, it would be nice if we had an interface such as `IStreamRequestHandler<TRequest, TResponse>` with method 
```
public async IAsyncEnumerable<TResponse> Handle(TRequest, CancellationToken)
{
}
```
Instead of needing another allocation for a `Task<IAsyncEnumerble<TResponse>>` using the existing `IRequestHandler<TRequest, IAsyncEnumerable<TResponse>>`.

**Comment by lilasquared** [comment]
Is this really something that should be part of the base library?  It would be quite simple to have a seperate library `MediatR.AsyncEnumerable` or something of that nature with these types of simplified interfaces.

**Comment by Shumigaj** [comment]
IAsyncEnumerable<T> interface is part of .NET Standard 2.1. If library migrates to 2.1 version it won't be possible to use it in the .NET Framework projects [.NET implementation support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

**Comment by wazzamatazz** [comment]
> 
> 
> IAsyncEnumerable interface is part of .NET Standard 2.1. If library migrates to 2.1 version it won't be possible to use it in the .NET Framework projects (read more [.NET implementation support](https://docs.microsoft.com/en-us/dotnet/standard/net-standard))

`IAsyncEnumerable` is available via the [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/) package for projects targeting .NET Framework or .NET Standard 2.0. MediatR wouldn't need to use C# 8 language features to be able to add a request handler that returned `IAsyncEnumerable<T>`. 

Alternatively, it would be possible to include the idea proposed by @adnang using multi-targeting and only including it when targeting .NET Standard 2.1.

**Comment by ThomasSkyldahl** [comment]
how should this be implemented if your are interested in a pull request?

I'm thinking of doing a Stream() method instead of Send() on the Mediator to handle the IAsyncEnumerable requests

Would that be a viable route?

**Comment by jbogard** [comment]
Another route would be to only target `netstandard2.1`, that would be OK with me too, especially given the `net5.0` direction.

**Comment by ThomasSkyldahl** [comment]
How would you handle the difference in signature with the single Send 

Should we do  IStreamRequest and IStreamRequestHandler and stick to the Send() method for both IRequest and IStreamRequest both interfaces could inherit IBaseRequest but IMediator with have a method for both request types

as on Returns Task<T> and the other returns IAsyncEnumerable<T>

**Comment by jbogard** [comment]
There would be a separate interface and overload.

**Comment by mrUlrik** [comment]
It appears @driekus77 made enormous progress with #574. Is there any chance of introducing this into master?

**Comment by jbogard** [comment]
Yeah I'd like to open it up to feedback on the API and approach. It's a big change :)
