### ISSUE TITLE
MediatR not finding Handlers on IIS

### ISSUE THREAD

**Issue by MrTheremy** [jbogard/MediatR#459]
I am writing a simple application in .NET Core 3.0 with different layers and using MediatR to make my code clean. I have 5 different layers: API, Application, Application.IO, Domain and Infrastructure with my IRequestHandler in Application and my IRequest in Application.IO and registering my handlers happens in the Startup class in the API layer.

When running this locally I have no issues but when I deployed this to an IIS server I keep getting the error:

Error constructing handler for request of type MediatR.IRequestHandler`2[WerfRegistratie.Application.IO.Queries.GetPersonQuery,WerfRegistratie.Application.IO.Queries.GetPersonQueryResponse]. Register your handlers with the container. See the samples in GitHub for examples.

**Comment by khellang** [comment]
And what is the inner exception?

**Comment by MrTheremy** [comment]
Since I posted this I have since found the solution. The problem was that I injected a repository class in the handler which had a faulty connection string after deployment and the error made it seem like I had done something wrong with the handler registration.
