### ISSUE TITLE
MediatR FAILS to resolve IRequestHandler when IRequest was created by reflection.

### ISSUE THREAD

**Issue by jcrowegitHu8** [jbogard/MediatR#460]
I have a business need to maintain year specific logic for a few years then it can just be removed.  The application is already setup with IRequest and IRequestHandler for the year specific logic.

However the issue is that mediatR can't resolve any IRequestHandler based on an IRequest object created by Activator.CreateInstance(type).

I have created a code example that shows the issue if you could please review this on [github](https://github.com/jcrowegitHu8/MultiYear.MediatR.Example/blob/master/README.md)  and provide feedback as to why it happens and how to fix it.  I'm also open to any other implementation, provided its not reworking these very large projects away from the MediatR pattern.

I appreciate your help.

Code shows a result of

```csharp
{
  "coreInstance": "Core Handler Executed",
  "year1Instance": "Year1 Handler Executed",
  "year1ReflectionInstance": "Error constructing handler for request of type MediatR.IRequestHandler'2[BusinessLogic.Year1.Application.DoSomething1Request,System.String]. Register your handlers with the container. See the samples in GitHub for examples."
}
```

**Comment by jbogard** [comment]
I see you're using AppDomains to load assemblies - I'm not sure that's supported in .NET Core. That uses the whole `AssemblyLoadContext` stuff.

**Comment by jbogard** [comment]
Yep, that's it. If you change the library projects to `netstandard2.0` and the main app to `net461` then it works just fine:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp2.2\MultiYear.MediatR.Example.WebApi.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="3.0.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessLogic.Core\BusinessLogic.Core.csproj" />
    <ProjectReference Include="..\BusinessLogic.Year1\BusinessLogic.Year1.csproj" />
    <ProjectReference Include="..\BusinessLogic.Year2\BusinessLogic.Year2.csproj" />
  </ItemGroup>

</Project>
```

![image](https://user-images.githubusercontent.com/104498/69580684-a6709e00-0f9a-11ea-877e-60559cd45c5f.png)

**Comment by jcrowegitHu8** [comment]
> Yep, that's it. If you change the library projects to `netstandard2.0` and the main app to `net461` then it works just fine:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>net461</TargetFramework>
>   </PropertyGroup>
> 
>   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
>     <DocumentationFile>bin\Debug\netcoreapp2.2\MultiYear.MediatR.Example.WebApi.xml</DocumentationFile>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <Folder Include="wwwroot\" />
>   </ItemGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="5.0.1" />
>     <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="3.0.1" />
>     <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
>     <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.2.0" />
>     <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
>     <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
>   </ItemGroup>
> 
>   <ItemGroup>
>     <ProjectReference Include="..\BusinessLogic.Core\BusinessLogic.Core.csproj" />
>     <ProjectReference Include="..\BusinessLogic.Year1\BusinessLogic.Year1.csproj" />
>     <ProjectReference Include="..\BusinessLogic.Year2\BusinessLogic.Year2.csproj" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> ![image](https://user-images.githubusercontent.com/104498/69580684-a6709e00-0f9a-11ea-877e-60559cd45c5f.png)

Thanks for pointing that out.  Just to share full info.  I implemented the correct usage of AssemblyLoadContext that is supported by net core.  I updated my code on github to show it working now.  This was needed for my business case because we run in docker Linux containers.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-2.2

**Comment by jbogard** [comment]
Nice! I'll bookmark this - I've not played much with the AssemblyLoadContext stuff and would have done exactly what you did
