### ISSUE TITLE
Support inheritance for error handlers

### ISSUE THREAD

**Issue by Shumigaj** [jbogard/MediatR#461]
Sometimes it is convenient to declare base type for Requests (e.g. application has different modules that can process the same request, so developer can move all common properties to the base Request and just inherit from it). 

The second situation when base type can possibly reduce code duplication when we want to create error handler to handle specific exceptions (e.g. TaskCanceledException).

I think that it would be useful to search error handlers not only for Request+Response pair but also for all Request base types+Ressponse in situation when we haven't found handlers for original pair (maybe even when error wasn't handled - point for discussion).

If you find it useful I will implement that change so it will be in the same release with error handler functionality.

**Comment by jbogard** [comment]
Sure!

**Comment by Shumigaj** [comment]
Implementation can be found in the #468
