### ISSUE TITLE
New release or pre-release soon? 

### ISSUE THREAD

**Issue by eskaufel** [jbogard/MediatR#463]
Just curious…

**Comment by Shumigaj** [comment]
I'm working right now on some changes to error handler. If release the current code, then the potential changes from my side will be considered as breaking changes and requires new major version. More information: [Support inheritance for error handlers](https://github.com/jbogard/MediatR/issues/461)

**Comment by Shumigaj** [comment]
Some new thoughts on upcoming release with new exception handler functionality [Exception handler improvements](https://github.com/jbogard/MediatR/issues/464)

**Comment by lilasquared** [comment]
i think the actual releases are all posted to https://myget.org/users/jbogard under the mediatr-ci feed.  He has stated a bunch of times that not every release will make it to nuget automatically due to documentation and reasons.  So if you want the latest you can use the myget feed

**Comment by eskaufel** [comment]
@Shumigaj Sorry for the late reply. I noticed the new pull request #468. I will check it out
