### ISSUE TITLE
Exception handler improvements

### ISSUE THREAD

**Issue by Shumigaj** [jbogard/MediatR#464]
All this week I have been thinking about how to make the exception handler more powerful and change it to behave more like try / catch statement, and here are some points that I would like to highlight:

1.  Remove 'exceptionHandlers' parameter from 'RequestExceptionProcessorBehavior' constructor.

    This will positively affect the performance of the library because we don't need a list of handlers until an exception occurs during the execution of the request.

2. Handlers from the Request Assembly (or namespace if it doable) must be preferable and override the inherited handlers.

    Let's imagine that a developer created general ExceptionHandler to handle some exception that might be thrown from the base request. Then he created request that inherits the base request and also wants to make some changes to exception handler (override ExceptionHandler from base request). As a result, library should't call an inherited ExceptionHandler.

3. General interface for request exception handler should be changed to abstract class.
  
    I can be wrong here. Let me know if I missed some ideas from introducing this interface.

    That's why i think so:
  
    - IRequestExceptionHandler<TRequest, TResponse>inherits IRequestExceptionHandler<TRequest, TResponse, Exception> and will be used to catch all Exceptions from the request. That type of handlers must be called when application haven't found other appropriate handlers (like catch (Exception e) always goes last);
    - Those handlers will be requested in the last step in RequestExceptionProcessorBehavior to search for available handlers by using IRequestExceptionHandler<,,> (not IRequestExceptionHandler<,>);
    - During automatic registration IRequestExceptionHandler<,> handlers will be registered twice (search implementations for IRequestExceptionHandler<,> and IRequestExceptionHandler<,,> interfaces). Otherwise some DI containers (e.g. SimpleInjector) will throw exception for unregistered collection;
    - Abstract class will look consistent to existing library structure (e.g. AsyncRequestHandler and RequestHandler classes).

    Source code that calls IRequestExceptionHandler<,>handler in the last iteration:
```
    do
    {
        var exceptionHandlerInterfaceType = typeof(IRequestExceptionHandler<,,>).MakeGenericType(typeof(TRequest), typeof(TResponse), exceptionType);
        exceptionType = exceptionType.BaseType; // will set exceptionType to System.Exception before the last iteration
    } while (exceptionType != typeof(Exception).BaseType);
```

4. Code duplication from RequestExceptionProcessorBehavior must be removed.

    Code below repeats last step from do / while loop. More information in the previous point.

```
    foreach (var exceptionHandler in _exceptionHandlers)
    {
        await exceptionHandler.Handle(request, exception, state, cancellationToken).ConfigureAwait(false);
    }
```

5. Library should exit the loop with process of searching handlers when handler has changed state to handled. 

    +:
    - exit faster (fail fast concept);
    - application state won't be damaged by calling basic handlers;
    - it will be similar to try / catch behavior. 

6. Contravariant keyword must be removed from IRequestExceptionHandler (~~in~~ TException)

    I'll refer to SimpleInjector behavior for such configuration.

    Developers can create a hierarchical structure of handlers:

        public class ExceptionHandler1 : IRequestExceptionHandler<int, int, ArgumentException>{}
        public class ExceptionHandler2 : IRequestExceptionHandler<int, int>{}

    Developer expects that ExceptionHandler2 will executed after ExceptionHandler1 but for SimpleInjector (during automatic registration and using contravariant keyword) ExceptionHandler2 as good as ExceptionHandler1 to handle ArgumentException because it inherits Exception. 

    As a result SimpleInjector returns handlers collection with ExceptionHandler1 and ExceptionHandler2  after requesting handlers with IRequestExceptionHandler<int, int, ArgumentException>. So, ExceptionHandler2 will be called on the fist iteration of ArgumentException exception handling.

   The RequestExceptionProcessorBehavior was written the way to call handlers from more specific exceptions to more generic by using do / while loop and check BaseType during the next iteration.

    Library handle hierarchy manually without need of using contravariant keyword.

I need a feedback on the proposed changes.

Best regards, Pavel

**Comment by Shumigaj** [comment]
# #468

**Comment by jbogard** [comment]
Merged.
