### ISSUE TITLE
Error when using MediatR with NetCore's new Worker service

### ISSUE THREAD

**Issue by mattkrebs** [jbogard/MediatR#465]
I am currently using MediatR successfully with my .net core web project.  But unfortunately when using a Worker service the DI breaks and can not find my Handlers.   Worker Services require an Environment Var of `"DOTNET_ENVIRONMENT" : "Development"`  and my web project uses `"ASPNETCORE_ENVIRONMENT" : "Development"`  when i switch my worker service to use the later of the two EV vars, there are no problems with my worker services finding the Handlers, but the worker services picks up the wrong `appsettings.[ENV].json`  (Production instead of Development).  

Thanks

**Comment by lilasquared** [comment]
Is there something that is changing the DI registration based on those environment variables in your code?  Are you using both set to development at the same time?

**Comment by mattkrebs** [comment]
No, not that I am aware of.  
Everything is pretty basic.    Here is where i wire up all my DI.    Like i said, what is weird is that when I change to ASPNETCORE_ENVIROMENT the DI works but grabs the incorrect appsettings.json file.
```
{
  "profiles": {
    "Rypen.Worker": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"  //Breaks DI but picks up correct appsettings.json
      }
    },
    "Docker": {
      "commandName": "Docker",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }

  }
}
```


```
 public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)            
                .ConfigureServices((hostContext, services) =>
                { 
                    services.AddTransient<IServiceAuth, ServiceAuth>();
                    
                   
                    services.AddPersistence(hostContext.Configuration);
                    services.AddApplication();

                    services.AddHostedService<Worker>();

                });
    }
```

```
  public static class DependencyInjection
    {
        public static IServiceCollection AddApplication(this IServiceCollection services)
        {
            services.AddSingleton<ITestDependancy, TestDependancy>();
            services.AddAutoMapper(Assembly.GetExecutingAssembly());
            services.AddMediatR(Assembly.GetExecutingAssembly());
          
            return services;
        }
    }
```

**Comment by lilasquared** [comment]
in the profiles section what if you use both ENV vars set to development?

**Comment by mattkrebs** [comment]
Yeah, tried that.   Still breaks the DI.  
Here is the error message.
```
Error constructing handler for request of type MediatR.IRequestHandler`2[MyProject.Reporting.Application.Proposal.Query.GetProposalListQuery,MyProject.Reporting.Application.Proposal.Query.ProposalListModel]. Register your handlers with the container. See the samples in GitHub for examples.
```

**Comment by mattkrebs** [comment]
Ok, I have narrowed it down to where I inject my dependency for my DbContext.

`Unhandled exception. System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[MyProject.Reporting.Application.Inventory.GetInventoryListQuery,MyProject.Reporting.Application.Inventory.InventoryListModel]. Register your handlers with the container. See the samples in GitHub for examples.
 ---> System.InvalidOperationException: Cannot resolve 'MediatR.IRequestHandler`2[MyProject.Reporting.Application.Inventory.GetInventoryListQuery,MyProject.Reporting.Application.Inventory.InventoryListModel]' from root provider because it requires scoped service 'MyProject.Reporting.Data.IMyContext'.`

My DI wireup for my DbContext
```
public static class DependencyInjection
    {
        public static IServiceCollection AddPersistence(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddDbContext<RypenContext>(options =>
                  options.UseSqlServer(configuration.GetConnectionString("RypenDatabase")));

            services.AddScoped<IRypenContext>(provider => provider.GetService<RypenContext>());

            return services;
        }
    }

```

**Comment by lilasquared** [comment]
yeah, that makes sense.  A scoped service can't be injected into the Worker Service directly since it doesn't have a scope - you'll need to follow the directions that I linked for "Consuming a scoped service in a background task"

**Comment by mattkrebs** [comment]
Yeah, What blows my mind is that I get no errors and data returns fine when I use `ASPNETCORE_ENVIRONMENT`

**Comment by lilasquared** [comment]
yeah that is definitely super weird.  I have no idea how those are used under the hood, or why it would cause different registration behavior in the scoped worker service.  What is the worker service doing exactly?  Do you not have a web api environment at all?

**Comment by mattkrebs** [comment]
I created a sample app that closely resembles my project.  If you want to can clone and see what I am talking about.  
https://github.com/mattkrebs/WorkerServiceWithMediatR_EFCore

I do have a web api, and am thinking about ditching EF Core and just talking to the WebApi to do all the "WORK"

**Comment by mattkrebs** [comment]
Also, Thanks for all your help!!! Much appreciated!!

**Comment by lilasquared** [comment]
i'm trying to understand to purpose of the worker service then - you can use efcore with your web api right?

**Comment by lilasquared** [comment]
I'm definitely seeing the same strange behavior that you are seeing with it working but using PROD configuration for the non-scoped service when you use the ASPNETCORE environment variables.  Thats definitely strange behavior.  Even changing the DOTNET_ENVIRONMENT to "Production" causes the mediator handlers to suddenly resolve and work without the scope.

**Comment by jbogard** [comment]
There are different behaviors for dev vs production for verifying scopes
and lifetimes.

**Comment by jbogard** [comment]
In the MS DI container that is. What you have is some resolutions expecting
scopes and you’re not creating a scope (like a DbContext).

**Comment by lilasquared** [comment]
It makes sense why it wouldn't work, but why would that behavior be so drastically different to where it suddenly does work in production?  Or is there something different about how the background services are registered between the two?  Either way a scope should be created its just strange that switching to production causes it to work.

**Comment by mattkrebs** [comment]
Seems like this is not the right thread for all this and it is obviously more of a MS question/issue.  I appreciate you both chiming in.   I do have it working with creating the scopes "on the fly". 

@lilasquared As to your question about why we need a worker service.  There are just some tasks that need to be done when items expire or email need to be sent if say a shopping cart becomes out dated.  Things like that.
