### ISSUE TITLE
Request for Collaborator permissions

### ISSUE THREAD

**Issue by Shumigaj** [jbogard/MediatR#467]
I want to push changes according to [Support inheritance for error handlers](https://github.com/jbogard/MediatR/issues/461) and [Exception handler improvements](https://github.com/jbogard/MediatR/issues/464) but I don't have permissions to create new branches in this repository.

Could you add necessary permissions to share my work with you?

**Comment by jbogard** [comment]
You can fork and open a PR.

**Comment by Shumigaj** [comment]
Thank for help
