### ISSUE TITLE
Unable to resolve service for type 'System.Object' while attempting to activate 'MediatR.ServiceFactory'

### ISSUE THREAD

**Issue by FanrayMedia** [jbogard/MediatR#469]
I have an Asp.net Core 2.2 app that I'm upgrading to 3.0. I'm using Mediatr 7.0.0 and now I got this error after the upgrade

> Error while validating the service descriptor 'ServiceType: System.ICloneable Lifetime: Transient ImplementationType: MediatR.ServiceFactory': Unable to resolve service for type 'System.Object' while attempting to activate 'MediatR.ServiceFactory'.

Here is my code in the Startup.cs

    services.AddMediatR(typeof(BlogPost));

and I'm using Scrutor to scan `IMediator`

    services.Scan(scan => scan
              .FromAssembliesOf(typeof(ISettingService), typeof(IMediator), typeof(BlogPost), typeof(IHomeHelper))
              .AddClasses()
              .UsingRegistrationStrategy(RegistrationStrategy.Skip) 
              .AsImplementedInterfaces()
              .WithScopedLifetime());
     
The above code works in 2.2, but now I cannot get the program to even launch due to the error.  Could someone point out what is going wrong please? Thanks.

**Comment by h-bahrami** [comment]
I had the same error but it was because of visual studio, 
I ran successfully via dotnet run ... command
now updating visual studio, may not be related but
