### ISSUE TITLE
Add "channels" or blacklists to IPipelineBehaviour when sending

### ISSUE THREAD

**Issue by hypervtechnics** [jbogard/MediatR#472]
Background: 
CQRS in ASP.NET Core

I got to know pipeline behaviours through this project: https://github.com/JasonGT/CleanArchitecture. I tried to adapt it to a use case I have, but the following problems occured:

1. Anonymous requests where blocked as the pb relied on having user information given.
2. Internal send's of commands/queries were blocked too as there was no http context available during execution from the inner application.

Am I getting something wrong with the pattern? If yes: I should head over to the CA-Repo - I know.

But maybe when can be MediatR more flexible at this point. By adding something like a flow system the request will go through - a channel. A channel would be all or only a subset of the defined behaviours. This could be implemented as a simple IChannel defining which pipelines to omit or include (black- or whitelist mode). Then the IChannel implementation could be passed as a generic parameter or something similar.

What do you think?

**Comment by jbogard** [comment]
I don't really want to do pipes and filters with MediatR, it's supposed to be simple. However, you can do that with your own behaviors, if you like.

**Comment by hypervtechnics** [comment]
Okay thank you for your response :blush:
