### ISSUE TITLE
Is it OK for Handler to Send/Publish

### ISSUE THREAD

**Issue by slimshader** [jbogard/MediatR#473]
Hi,

Is is OK from design PoV for Handlers to Send() or Notify() more Commands / Queries. If not, what would be the alternative to Handler needing to notify of some event or access a service that is normally accessed by Send()ing a query?

**Comment by lilasquared** [comment]
We do it but jimmy has indicated that it can get messy and is not ideal.  Shared functionality between handlers can still be abstracted as you normally would with an interface and shared service.  This may end up that a mediator query or command simply passes through to the shared service, but you still are tied into the shared pipeline behaviors that you don't get by calling the service directly.

**Comment by lilasquared** [comment]
here is another issue where it is discussed https://github.com/jbogard/MediatR/issues/434

**Comment by TorbjornHoltmon** [comment]
I am implementing caching and I was wondering about the same thing.
Id like to notify multiple re-caching notifications in my command handler when updating, deleting or adding something to the database.

But seeing as it is not recommended I am not sure how to approach this.

**Comment by remcoros** [comment]
I wouldn't say it is "not recommended". As Jimmy points out in the linked thread, his personal experience with nested handlers was not too good. (note: I think he's talking about nested request handlers, not a Request handler sending out notification).

My advice would be to go with what you (or the team) feel most comfortable with. In your caching use-case, I personally would go that route. (Controller sends a request, request handler does the main work and sends a "invalidate cache" notification).

This is pretty simple structure and if you and your colleagues feel good about it, go with it!

**Comment by jbogard** [comment]
Yes - this is nested request handlers. Notifications are fine inside a request handler.
