### ISSUE TITLE
Question: Name convention for async methods.

### ISSUE THREAD

**Issue by sq735** [jbogard/MediatR#479]
Why methods return **Task** or **Task\<T>**  do not end with the suffix "Async"? Msdn [say](https://docs.microsoft.com/en-gb/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model) "_The name of an async method, by convention, ends with an "Async" suffix._" For example in interfaces [IMediator](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IMediator.cs), [IRequestHandler](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequestHandler.cs), [INotificationHandler](https://github.com/jbogard/MediatR/blob/master/src/MediatR/INotificationHandler.cs) etс .

**Comment by f1ana** [comment]
I've seen `Async` suffixes within libraries that offer both sync and async versions of a given operation.  EF/EF Core is one such example.  For a library such as this, IMO such a convention is redundant.

**Comment by sq735** [comment]
Yes, but when we call the **Send** method, we usually want to wait for the completion of the corresponding handler. To do this, we use the keyword **await**. In addition, the handler itself often contains asynchronous operations. Therefore, the suffix "**Async**" is appropriate.

**Comment by jbogard** [comment]
https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix
