### ISSUE TITLE
Invoking SendAsync with reflection is broken

### ISSUE THREAD

**Issue by lcamlibel** [jbogard/MediatR#48]
Hello
i have the following code. it has been working so far including v2.0 beta 5.
i started getting error of ambiguous match found because you have created overloaded method of SendAsync with cancelation token. could you tell me how to fix the following code

 var requestInterface = requestType.GetInterface("IAsyncRequest`1");
            var sendMethod = mediator.GetType().GetMethod("SendAsync");
            var method = sendMethod.MakeGenericMethod(requestInterface.GetGenericArguments());
            var task=  (Task)method.Invoke(mediator, new[] {instance});
            await task;
            return task.GetType().GetProperty("Result").GetValue(task);

**Comment by kappy** [comment]
a blind (non-tested) hint:

passing the parameters on the GetMethod doesn't do the trick?

`var sendMethod = mediator.GetType().GetMethod("SendAsync", typeof(IAsyncRequest<>));`

**Comment by khellang** [comment]
@kappy It doesn't support open generics :cry: 

@lcamlibel Since you already have a closed generic type (from `GetInterface`), try passing `requestInterface` to the `GetMethod` call :smile:

**Comment by kappy** [comment]
I tried both 

    var sendMethod = mediator.GetType().GetMethod("SendAsync", new [] { requestInterface })

and
 
    var sendMethod = mediator.GetType().GetMethod("SendAsync", new[] { typeof(IAsyncRequest<>) });

both return null.. I think there is some limitation on the generics using reflection.
This worked for me:

            var parameterTypes = new[] {typeof (IAsyncRequest<>)};
            var sendMethod = (from m in mediator.GetType().GetMethods()
                where m.Name == "SendAsync"
                where parameterTypes.SequenceEqual(m.GetParameters().Select(p => p.ParameterType.GetGenericTypeDefinition()))
                select m).SingleOrDefault();

based on Jon Skeet comment on http://stackoverflow.com/a/269992/4634243

**Comment by lcamlibel** [comment]
thanks guys
