### ISSUE TITLE
Remove built-in pre/post processors

### ISSUE THREAD

**Issue by Neuroglia** [jbogard/MediatR#482]
Hello everyone!

I have an issue with the built-in pre/post processors that are now intercepting exceptions. I would like to intercept those myself with an IPipelineBehavior such as the following, in order to return specific responses:

        public virtual async Task<TResponse> Handle(TCommand request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            try
            {
                return await next();
            }
            catch (DomainArgumentException ex)
            {
                TResponse response = (TResponse)Activator.CreateInstance(typeof(TResponse), new object[] { ResponseCode.Invalid, new Error[] { new Error(ex.ArgumentName, ex.Message) } });
                return response;
            }
            catch (DomainException ex)
            {
                TResponse response = (TResponse)Activator.CreateInstance(typeof(TResponse), new object[] { ResponseCode.Invalid, new Error[] { new Error(string.Empty, ex.Message) } });
                return response;
            }
            catch (Exception ex)
            {
                this.Logger.LogError($"An exception occured while handling a command of type '{request.GetType().Name}':{Environment.NewLine}{ex.ToString()}");
                TResponse response = (TResponse)Activator.CreateInstance(typeof(TResponse), new object[] { ResponseCode.InternalError });
                return response;
            }
        }

That behavior is being skipped and the built-in RequestExceptionProcessorBehavior is being called as soon as an exception is being thrown.

How can I achieve this in the current version?

Thanks in advance!

**Comment by lilasquared** [comment]
I think you'll need to implement an `IRequestExceptionHandler`, not a pipeline behavior to achieve this.

**Comment by Neuroglia** [comment]
@lilasquared Yes, thank you! I was not aware of those new services!
