### ISSUE TITLE
Q: Best practice MediatR in a console application?

### ISSUE THREAD

**Issue by Pyrobolser** [jbogard/MediatR#485]
Hello,

It is my understanding that it is not straight forward to go from ASP.NET Core to a Console application as ASP.NET Core handles the scope creation, for example, to use a DbContext in MediatR.
I have read about MediatR and Dependency Injection in .NET Core and I am trying to figure out how to properly implement the following in a console application.
_"A small menu and a request to MediatR for every option to execute queries in a DbContext."_  

Here is what I have working for now. I am just wondering if it is considered best practices or if there is a better way to do it?

**Program.cs**
```csharp
public static class Program
{
    public static async Task Main(string[] args)
    {
        var hostBuilder = CreateHostBuilder(args);

        await hostBuilder.RunConsoleAsync();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureServices((hostingContext, services) =>
            {
                services.AddDbContext<MyDbContext>(options =>
                    options.UseSqlServer(configuration.GetConnectionString("MyDatabase")));

                services.AddScoped<IMyDbContext>(provider => provider.GetService<MyDbContext>());
                services.AddMediatR(Assembly.GetExecutingAssembly());
                services.AddSingleton<IHostedService, ConsoleApp>();
            });
}
```

**ConsoleApp.cs**
```csharp
public class ConsoleApp : IHostedService
{
    private readonly ILogger _logger;
    private readonly IServiceScopeFactory _serviceScopeFactory;
    public ConsoleApp(ILogger<ConsoleApp> logger, IServiceScopeFactory serviceScopeFactory)
    {
        _logger = logger;
        _serviceScopeFactory = serviceScopeFactory;
    }
    
    public async Task StartAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Starting application");
        int choice = -1;
        while (choice != 0)
        {
            WriteLine("Please choose one of the following options:");
            WriteLine("0. Exit");
            WriteLine("1. Extract receipts");
            WriteLine("2. Upload receipts");

            try
            {
                choice = int.Parse(ReadLine());
            }
            catch (FormatException)
            {
                choice = -1;
            }

            switch (choice)
            {
                case 0:
                    WriteLine("Bye...");
                    break;
                case 1:
                    using (var scope = _serviceScopeFactory.CreateScope())
                    {
                        var _mediator = scope.ServiceProvider.GetRequiredService<IMediator>();
                       
                        await _mediator.Send(new ExtractReceiptsCommand(), cancellationToken);
                    }
                    break;
                case 2:
                    using (var scope = _serviceScopeFactory.CreateScope())
                    {
                        var _mediator = scope.ServiceProvider.GetRequiredService<IMediator>();

                        await _mediator.Send(new UploadReceiptsCommand(), cancellationToken);
                    }
                    break;
                default:
                    WriteLine("Invalid choice! Please try again.");
                    break;
            }
        }
    }
}
```

Then I inject _IMyDbContext_ inside the request handler constructor and everything looks like it is working properly.
Thank you for your suggestions.

**Comment by lilasquared** [comment]
MediatR shouldn't care whether you're in a web context or a console context so long as the DI is all hooked up which it looks like you have done here.

**Comment by Pyrobolser** [comment]
Thanks for your comment and sorry if this was confusing. 
I don't think it is a MediatR specific issue. I was just wondering if the way I am solving this issue here, by using _IServiceScopeFactory_, is the proper way when using MediatR, or if there is another way to do this that I should consider.

If I inject IMediator directly into ConsoleApp, I get the following error when constructing the Handler for the Request type.

> Cannot resolve 'MediatR.IRequestHandler`2 from root provider because it requires scoped service IMyDbContext.

**Comment by lilasquared** [comment]
Using the service scope factory is ideal if you want each time a user picks a menu option to have a nested scope and essentially new set of scoped dependencies.  Since you set up `IMyDbContext` as scoped `services.AddScoped<IMyDbContext>(provider => provider.GetService<MyDbContext>());` that is why you are receiving the error when trying to resolve a handler with the regularly injected IMediator.  You could add the context as a singleton in which case it will exist for the lifetime of the console application, it just depends on how you want to handle the lifecycle of that db context.  If each action is truly independent and you can think of them the same as making an http request to an api server, then scoped service collections seem to be the way to go.

**Comment by jbogard** [comment]
EF has a configuration value to let you change that too FYI. For Console apps I have to be more explicit about lifecycles.

**Comment by Pyrobolser** [comment]
@lilasquared That's exactly what I'm trying to do.

@jbogard I'll try to look into it, let me know if you know of an example that lies somewhere that I could look at. If you happen to add some details about Console app I'll be sure to check it out too.

Thank you both for your help.
