### ISSUE TITLE
Documentation in NuGet package is missing

### ISSUE THREAD

**Issue by Fitch24** [jbogard/MediatR#492]
The source code is documented. But when installing the MediatR via NuGet, it does not have any documentation (at least for .NET Standard platform). Tried on MediatR v7 and v8.
![2020-02-09 205005](https://user-images.githubusercontent.com/42736888/74103340-e7ca2000-4b7d-11ea-96db-654a8bb606d7.png)
On screenshot is "Object Explorer" (MS VS v16.4) with empty class description (right bottom panel).

**Comment by jbogard** [comment]
Fixed!
