### ISSUE TITLE
Handle interface from command in IRequestHandler

### ISSUE THREAD

**Issue by mvdiemen** [jbogard/MediatR#493]
Is it possible to handle a generic interface/abstract class as command?

So for example I can define something like this:
```
    internal class DemoHandler : IRequestHandler<IDemoCommand>
    {
        public Task<Unit> Handle(IDemoCommand request, CancellationToken cancellationToken)
        {
             return Task.FromResult(Unit.Value);
        }
    }
```

For which the command looks like the following:
```
    class DemoCommand : IDemoCommand
    {
    }

    interface IDemoCommand : IRequest
    {
    }
```

When I use it in combination with MediatR.Extensions.Microsoft.DependencyInjection it gives me the error that the Handler registration can't be found.

Registrated the following way:
```
       new ServiceCollection()
                .AddMediatR(typeof(Startup).Assembly)
                .BuildServiceProvider();
```

**Comment by lilasquared** [comment]
It's possible to do this with constrained generics (I think) but refer to this issue https://github.com/jbogard/MediatR/issues/305.  aspnet core DI out of the box does not support constrained generics.

**Comment by TommyBlasta** [comment]
Hi, don't want to necro this issue but is this available behaviour now? I saw that the related PR was merged but I do still get:

`No service for type <HandlerWithInterfaceRequest> has been registered.` errors.

Is there an option to enable this somehow or a plan to implement it?

Thanks

**Comment by nzcoward** [comment]
> 

Yes, but you need it to be an open type handler:

`internal class DemoHandler<TDemoCommand> : IRequestHandler<TDemoCommand> where TDemoCommand : IDemoCommand`
