### ISSUE TITLE
Error constructing handler for request of type MediatR.IRequestHandler

### ISSUE THREAD

**Issue by robominesgithub** [jbogard/MediatR#497]
```
{
  "error": [
    "Error constructing handler for request of type MediatR.IRequestHandler`2[NPPDPayment.Application.Payment.Command.DuplicatePaymentCheckCommand,NPPDPayment.Application.Common.ApiResponse`1[NPPDPayment.Application.Common.DuplicatePaymentResponse]]. Register your handlers with the container. See the samples in GitHub for examples."
  ],
  "stackTrace": "   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory)\r\n   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at NPPDPayment.Application.Infrastructure.RequestPerformanceBehaviour`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)\r\n   at NPPDPayment.WebAPI.Controllers.PaymentController.DuplicatePayment(DuplicatePaymentCheckCommand command)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()"
}
```

**Comment by lilasquared** [comment]
Sweet stack trace

**Comment by neoxack** [comment]
same issue

**Comment by jbogard** [comment]
Yikes. I can't read that at all. Please update with something I can parse.

And just a stack trace won't allow me to reproduce. Please update with a minimal repro

**Comment by Junicus** [comment]
I think I'm having the same issue will try to give all the information I can to help you reproduce it

Exception Information
``` code
System.InvalidOperationException
  HResult=0x80131509
  Message=Error constructing handler for request of type MediatR.IRequestHandler`2[IrsiAccounting.Application.Concepts.Queries.GetConceptsQuery,IrsiAccounting.Application.Concepts.Queries.ConceptsViewModel]. Register your handlers with the container. See the samples in GitHub for examples.
  Source=MediatR
  StackTrace:
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IrsiAccounting.WebUI.Controllers.ConceptsController.<Get>d__0.MoveNext() in C:\Code\irsi-dev\IrsiAccounting\src\IrsiAccounting.WebUI\Controllers\ConceptsController.cs:line 18

  This exception was originally thrown at this call stack:
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(System.Type, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, System.Reflection.ParameterInfo[], bool)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ResultCache, System.Type, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Microsoft.Extensions.DependencyInjection.ServiceDescriptor, System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain, int)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite.AnonymousMethod__0(System.Type)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteChain)
	Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(System.Type)
    ...
    [Call Stack Truncated]
Inner Exception 1:
InvalidOperationException: Unable to resolve service for type 'IrsiAccounting.Application.Common.Interfaces.IApplicationDbContext' while attempting to activate 'IrsiAccounting.Application.Concepts.Queries.GetConceptsQueryHandler'.
```

Controller Code
```
namespace IrsiAccounting.WebUI.Controllers
{
    public class ConceptsController : ApiController
    {
        [HttpGet]
        [ProducesResponseType((int)StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(typeof(ConceptsViewModel), (int)StatusCodes.Status200OK)]
        public async Task<ActionResult<ConceptsViewModel>> Get()
        {
            return await Mediator.Send(new GetConceptsQuery()).ConfigureAwait(true);
        }
    }
}
```

Way I'm registering MediatR
```
namespace IrsiAccounting.Application
{
    public static class DependencyInjection
    {
        public static IServiceCollection AddApplication(this IServiceCollection services)
        {
            services.AddAutoMapper(Assembly.GetExecutingAssembly());
            services.AddMediatR(Assembly.GetExecutingAssembly());

            return services;
        }
    }
}
```

Handler Code
```
namespace IrsiAccounting.Application.Concepts.Queries
{
    public class GetConceptsQuery : IRequest<ConceptsViewModel>
    {
    }

    public class GetConceptsQueryHandler : IRequestHandler<GetConceptsQuery, ConceptsViewModel>
    {
        private readonly IApplicationDbContext _context;
        private readonly IMapper _mapper;

        public GetConceptsQueryHandler(IApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public async Task<ConceptsViewModel> Handle(GetConceptsQuery request, CancellationToken cancellationToken)
        {
            var vm = new ConceptsViewModel
            {
                Concepts = await _context.Concepts
                    .ProjectTo<ConceptDto>(_mapper.ConfigurationProvider)
                    .OrderBy(t => t.Name)
                    .ToListAsync(cancellationToken)
                    .ConfigureAwait(false)
            };
            return vm;
        }
    }
}
```

Packages referenced
```
    <PackageReference Include="MediatR" Version="8.0.1" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="8.0.0" />
```

Hope this will help you reproducing the problem, seems that the handler is registered in the container but can't resolve the handler.

**Comment by Junicus** [comment]
Yeah, not it at all :) sorry for that

**Comment by timdows** [comment]
Had the same issue
In my code I had 
```services.AddOptions();``` 
before
```services.AddMediatR(typeof(myAssemblyStuff).GetTypeInfo().Assembly);```

Changed it and it worked again

**Comment by fujunYang123** [comment]
Has the problem been solved？

**Comment by fujunYang123** [comment]
I had a similar problem，The exception information is
System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[CRM.Allspark.Service.Commands.CustomerHandles.SendBlindSmsCommand,MediatR.Unit]. Register your handlers with the container. See the samples in GitHub for examples.

**Comment by seyfside** [comment]
I think the reason for this error is somewhere else. in my case wrong migration code.

**Comment by KostaMadorsky** [comment]
Is my case was an issue with the connection string in one of the repositories the handler depends on. Better logging in the app helps.

**Comment by abcox** [comment]
I realize this is closed, but in case someone else comes here with my case, then make sure you don't forgot to register something.  Like my repository that I was attempting to have implemented via a controller.

**Comment by kennydust** [comment]
@jbogard 

just an FYI. i just recently came across this, and this was because i mixed automapper's mappingprofilebase with my commands.

public class EnrollWithEmailTokenCommand : MappingProfileBase<EnrollWithEmailTokenCommand>, IRequest<Unit>{ 
...
}

commented this out and it all started working.

**Comment by Zodt** [comment]
This exception will be made if the parameters of your SQL connection are not added to the DI or added, but you are not connected to a VPN to connect to the database.
How can I handle this exception so that there is no such error?

**Comment by fidelflorian** [comment]
I had the same problem but the error was an enviroment configuration, I did not have the connection to the database,

**Comment by Zodt** [comment]
I [found](https://gist.github.com/Zodt/12e5fd474fa01c7026a29e01f081c143) the solution of that problem

**Comment by ArouaChaouch** [comment]
> I had a similar problem，The exception information is System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[CRM.Allspark.Service.Commands.CustomerHandles.SendBlindSmsCommand,MediatR.Unit]. Register your handlers with the container. See the samples in GitHub for examples.

hey i have the same error did u figure it out ?

**Comment by kanwulf01** [comment]
Hello i had the same problem, the solution, verify you conecctionString is fine in every part where was reference, and everything works

**Comment by isra-rar** [comment]
Hello, I solved using this alternative 

`services.AddMediatR(AppDomain.CurrentDomain.GetAssemblies());`

**Comment by assueromoraisfinxapp** [comment]
Hello, i had the same problem, with a Azure Functions Project, and it was due to the lack of the connection string in the file local.settings.json.
To solved it, I included the "ConnectionStrings" tag into local.settings.json, after "Values" tag. Like bellow:
![image](https://user-images.githubusercontent.com/85592954/154131399-73be8363-9ce0-4530-ad1f-421a6041a945.png)

**Comment by MisinformedDNA** [comment]
Unfortunately, the exception message points us to look at handlers, when the issue isn't with the handlers themselves.

**Comment by AL-CHALABEE** [comment]
Without **.IncludeMembers** the apps works, using **.IncludeMembers** in one of the CreateMap I got the error _Error constructing handler for request of type MediatR.IRequestHandler`2_ etc...

**Comment by askrinnik** [comment]
Hello, I have the same problem.
But I have the exception ONLY when my test executes in GitHub action.
In my development environment, all tests passed.
Any thoughts?

**Comment by checherry20** [comment]
I was stuck in this error as well. And I found out that there is just unregistered constructor in my command handler.

**Comment by remcoros** [comment]
@jbogard see: https://github.com/jbogard/MediatR/blob/master/src/MediatR/Wrappers/HandlerBase.cs#L15

how about just removing the catch entirely or use ExceptionDispatchInfo.Capture().Throw to the point the underlying exception is just bubbled up to the user. I've seen a lot of issues opened here like this and it's never MediatR. Just letting the underlying exception be thrown would make that more obvious.
the handler == null case can stay as is.

**Comment by remcoros** [comment]
@mehzan07 See my previous comment. It 100% is not MediatR, but can be a bit tricky to debug.

Look at or log the "InnerException" of the thrown Exception and it will show the underlying exception which caused this

**Comment by mehzan07** [comment]
Hi Remocoros,
Thank you for answering my question
the strange thing  is that it is working with Debug configuration in Visual Studio, BUT not in Release (production ) Configuration. What make this strange ?????


I have taken All information fram the exception and it is 

System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[ProductMicroservice.CQRS.Queries.GetProductLisQuery,System.Collections.Generic.List`1[ProductMicroservice.Models.Product]]. Register your handlers with the container. See the samples in GitHub for examples. ---> System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString') at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName) at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction) at ProductMicroservice.Startup.b__4_0(DbContextOptionsBuilder options) in C:\src\ProductMicroservice\ProductMicroservice\Startup.cs:line 45 at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument) at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.b__0(ServiceProviderEngineScope scope) at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType) at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) at MediatR.ServiceFactoryExtensions.GetInstance[T](ServiceFactory factory) at MediatR.Wrappers.HandlerBase.GetHandler[THandler](ServiceFactory factory) --- End of inner exception stack trace --- at MediatR.Wrappers.HandlerBase.GetHandler[THandler](ServiceFactory factory) at MediatR.Wrappers.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.g__Handler|0() at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) at ProductMicroservice.Controllers.ProductController.Get() in C:\src\ProductMicroservice\ProductMicroservice\Controllers\ProductController.cs:line 53

Thanks in advance.
Mehrdad

**Comment by remcoros** [comment]
@mehzan07 

It's right there in the logs:

    System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString') at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName) at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action1 sqlServerOptionsAction) at ProductMicroservice.Startup.b__4_0(DbContextOptionsBuilder options) in C:\src\ProductMicroservice\ProductMicroservice\Startup.cs:line 45 at**

You probably have a different configution for release/debug or Development/Production and missing the connectiong string in your config

**Comment by mehzan07** [comment]
Hi remcoros,
Thanks for response:
I have same connectiontring for both Release and Debug please look to the following in the appsetting.json:
"ConnectionStrings": {
 
    "ProductsDBConString": "Data Source=192.168.1.220,1433; Database=ProductsDB; User ID=sa; Password=xxxxxxxx; MultipleActiveResultSets=true;Persist Security Info=True"
  },

and my startup.cs class is as follow:
public void ConfigureServices(IServiceCollection services)
        {
services.AddDbContext<ProductContext>(options => options.UseSqlServer(Configuration.GetConnectionString("ProductsDBConString")));

services.AddMediatR(Assembly.GetExecutingAssembly());
 services.AddAutoMapper(typeof(Startup));
}

 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {

            
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c =>
                {
                    c.SwaggerEndpoint("/swagger/v1/swagger.json", "Product API V1");
                    c.RoutePrefix = string.Empty;
                });
            }
            app.UseHttpsRedirection();
            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }

many thanks in advance
Please help me to solve this problem.
I have triied many ways but problem still exits

**Comment by mehzan07** [comment]
Hi Remcoros,
Any solution for mig problem as i have descirbed as above?
I have tried with many ways but couldn't find any solution.
the strange is that it is happening only in Release mode not debug mode 

thanks

**Comment by MisinformedDNA** [comment]
@mehzan07 It's difficult to determine based on the current code, but it is also outside the scope of this thread/project. I recommend creating a small repro and posting to SO. Good luck.

**Comment by IceBears** [comment]
我的也出现了同样的问题，搜索发现，是Autofac 与 MediatR 共用的问题， 虽然我不太明白，
但是我通过在  autofac 的注册中添加 
builder.RegisterType(typeof(CustomerCommandHandler))
                    .As<IRequestHandler<RegisterCustomerCommand, bool>>()
                    .AsImplementedInterfaces();
此代码解决了问题
Autofac 与 MediatR 在 Program中配置代码
//Autofac注入
builder.Host
    .UseServiceProviderFactory(new AutofacServiceProviderFactory())
    .ConfigureContainer<ContainerBuilder>(builder =>
    {
        builder.RegisterModule(new ConfigureAutofac());
        builder.RegisterType(typeof(CustomerCommandHandler))
                    .As<IRequestHandler<RegisterCustomerCommand, bool>>()
                    .AsImplementedInterfaces();
    });
希望对你们有用

**Comment by mehzan07** [comment]
Hi jbogard,I didn't understand your resolutoin,Please write clear what shoujld I add and in which file/class should be changed /added
Thanks in advance
 Med vänlig hälsningar /Kind RegardsMehrdad Zandiwebsite: https://softsolutionsahand.comEmail: ***@***.*** 
Mobile: +46 (0) 730 31 86 25
Skype ID: mehzan          

    On Monday, August 8, 2022 at 10:20:05 AM GMT+2, IceBears ***@***.***> wrote:  
 
 


我的也出现了同样的问题，搜索发现，是Autofac 与 MediatR 共用的问题， 虽然我不太明白，
但是我通过在 autofac 的注册中添加
builder.RegisterType(typeof(CustomerCommandHandler))
.As<IRequestHandler<RegisterCustomerCommand, bool>>()
.AsImplementedInterfaces();
此代码解决了问题
Autofac 与 MediatR 在 Program中配置代码
//Autofac注入
builder.Host
.UseServiceProviderFactory(new AutofacServiceProviderFactory())
.ConfigureContainer(builder =>
{
builder.RegisterModule(new ConfigureAutofac());
builder.RegisterType(typeof(CustomerCommandHandler))
.As<IRequestHandler<RegisterCustomerCommand, bool>>()
.AsImplementedInterfaces();
});
希望对你们有用

**Comment by jeff-eastman** [comment]
Hello, I found a simple solution to this (in my case), hope it works for others...

In my case the problem was due to the order or which I registered my services. I had registered an interface and service as a scoped service, before adding and HttpClient, which subsequently caused a error with iMediator.

The fix that that this:

builder.Services.AddScoped<IMyService, MyService>();

builder.Services.AddHttpClient<IMyService, MyService>(c =>
{
    c.BaseAddress = new Uri("https://mytestwebapi.com");
});


had to become this:

builder.Services.AddHttpClient<IMyService, MyService>(c =>
{
    c.BaseAddress = new Uri("https://mytestwebapi.com");
});


builder.Services.AddScoped<IMyService, MyService>();

**Comment by birhannega** [comment]
```
//services.AddMediatR(Assembly.GetExecutingAssembly());  wrong
services.AddMediatR(AppDomain.CurrentDomain.GetAssemblies()); Perfect solution
```

**Comment by arigatory** [comment]
The problem might be because "No parameterless constructor defined" for e.g. `MappingProfiles` class inherited from `Profile `class. And it must be `public`, not `protected`. You might not see this exception if your custom middleware hides inner exceptions.

**Comment by GrapeJuice787** [comment]
Had the same issue when leveraging multiple DBContext objects without typing the DBContextOptions in the constructor for the DBContext instances.

**Comment by mahdignb** [comment]
> ```
> //services.AddMediatR(Assembly.GetExecutingAssembly());  wrong
> services.AddMediatR(AppDomain.CurrentDomain.GetAssemblies()); Perfect solution
> ```

This worked for me. Thanks.

**Comment by samuelhenshaw2020** [comment]
In my own case, i used `... Mediator mediator` instead of the interface `IMediator mediator` .

**Comment by paulonev** [comment]
I had this problem when trying to inject object of type specified in another dll. 
Using `new` operator helped in my case.

**Comment by campui** [comment]
**This can resolve your issue, it works for me**
builder.Services.AddMediatR(typeof(MyQuery).GetTypeInfo().Assembly);
