### ISSUE TITLE
.NET Core 3.1 Support

### ISSUE THREAD

**Issue by gt-downunder** [jbogard/MediatR#498]
Are there plans to implement support for .NET Core 3.1?  MediatR is an awesome library and a critical piece to our platforms.  With our recent upgrade to 3.1, MediatR is the only library unable to be built.

![image](https://user-images.githubusercontent.com/12604549/75301233-1804f600-57ef-11ea-864c-06dafb495315.png)

**Comment by jbogard** [comment]
? MediatR targets netstandard2.0. That targets .NET Core 2.0 and later. Any
netstandard2.0 library supports .NET Core 3.1. Most MS libraries target 2.0.

What exactly are you trying to do? What does your dockerfile look like?

**Comment by gt-downunder** [comment]
Actually, sorry, this particular issue is "not" Docker.  It's simply running a "nuget restore" as part of our Azure DevOps Pipeline and the above fails when it tries to pull down MediatR.  Any clues?

**Comment by gt-downunder** [comment]
Ok, seems it is a problem with Azure DevOps Pipelines and not using the latest hosted agent.  I apolgize for raising this issue.

For anyone that comes across this, the solution is to install at least NuGet 5.0+, ensure your build is using at least VS2019, and the hosted agent is one that supports MSBuild 16+.  Moving to Docker will fix this problem too :)
