### ISSUE TITLE
Creating a second notification handler in MediatR.Examples

### ISSUE THREAD

**Issue by andygithub** [jbogard/MediatR#5]
Nice library.

I was taking the library for a spin and attempted to create a second notification handler in MediatR.Examples like below just pasting and renaming the existing class:

```
public class PingedDubHandler : INotificationHandler<Pinged>
{
    private readonly TextWriter _writer;

    public PingedDubHandler(TextWriter writer)
    {
        _writer = writer;
    }

    public void Handle(Pinged notification)
    {
        _writer.WriteLine("Got pingedDub.");
    }
}
```

I then attempted to rerun the MediatR.Examples.Unity example and it broke on this line 
container.RegisterTypes(AllClasses.FromAssemblies(typeof (Ping).Assembly), WithMappings.FromAllInterfaces);
with this exception: An unhandled exception of type 'Microsoft.Practices.Unity.DuplicateTypeMappingException' occurred in Microsoft.Practices.Unity.RegistrationByConvention.dll

Additional information: An attempt to override an existing mapping was detected for type MediatR.INotificationHandler`1[MediatR.Examples.Pinged] with name "", currently mapped to type MediatR.Examples.PingedHandler, to type MediatR.Examples.PingedDubHandler.

So to resolve that issue I changed the registration for that line to include the type name so that multiple types with the interface can be registered.

However now when running the example the send is broken because all types now have names:
An unhandled exception of type 'Microsoft.Practices.ServiceLocation.ActivationException' occurred in Microsoft.Practices.ServiceLocation.dll

Additional information: Activation error occurred while trying to get instance of type IRequestHandler`2, key ""

Is this the expected behavior with unity or am I trying to create a second notification handler in the incorrect way?

**Comment by sale42** [comment]
Maybe I missing something, but I tried to add another INotification and INotificationHandler in unity example and got same error from above.
