### ISSUE TITLE
Small change: Really async for PublishAsync

### ISSUE THREAD

**Issue by ignatandrei** [jbogard/MediatR#50]
In the code for  PublishAsync(IAsyncNotification notification) it is
public async Task PublishAsync(IAsyncNotification notification)
        {
            var notificationHandlers = GetNotificationHandlers(notification);
           
            foreach (var handler in notificationHandlers)
            {
                await handler.Handle(notification));
            }
        }
This manner the PublishAsync waits for each handler to execute.
( put 
await Task.Delay(2000);
in PingedAsyncHandler 
and
 await Task.Delay(5000);
in PingedAlsoAsyncHandler  
and you will see that total await time is 2000 + 5000)
 
It will be real async if executed in parallel.
The code will be:

public async Task PublishAsync(IAsyncNotification notification)
        {
            var notificationHandlers = GetNotificationHandlers(notification);
            var tasks =new List<Task>();
            foreach (var handler in notificationHandlers)
            {
                tasks.Add( handler.Handle(notification));
            }
            await Task.WhenAll(tasks);
        }

What do you think ?

**Comment by ignatandrei** [comment]
Now I see that is the same think as the https://github.com/monnster/MediatR/commit/4050a254fc63369d4cca73d824d47d2b5e5953bd

**Comment by jbogard** [comment]
Yep, this is in!
