### ISSUE TITLE
Add T4 samples to the wiki

### ISSUE THREAD

**Issue by ErenForce** [jbogard/MediatR#500]
It would be nice to have some T4 samples that can take request classes in a namespace and produce request handlers in new namespace and to have a place in the wiki that explains how to use them. This would be very helpful especially for those that are just starting to learn T4 templates like myself.

**Comment by jbogard** [comment]
I've never used T4 templates. I think you may want to look at ReSharper file templates or Roslyn generators too. The wiki is editable by anyone, so if someone wants to add this they certainly can.
