### ISSUE TITLE
IRequestPostProcessor and IPipelineBehavior with transactions and different DB Contexts in EF Core

### ISSUE THREAD

**Issue by velchev** [jbogard/MediatR#502]
I am using MediatR and I have Behaviour:

```
public class TransactionBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
	{
		/// <inheritdoc/>
		public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
		{
			var transactionOptions = new TransactionOptions
			{
				IsolationLevel = IsolationLevel.ReadCommitted,
				Timeout = TransactionManager.MaximumTimeout,
			};

			using (var transaction = new TransactionScope(
				TransactionScopeOption.Required,
				transactionOptions,
				TransactionScopeAsyncFlowOption.Enabled))
			{
				// handle request handler
				var response = await next();

				// complete database transaction
				transaction.Complete();

				return response;
			}
		}
	}
```
 which creates transaction for some requests. I have also post processing code which access different DB context and this breaks the transactions. In EF Code you get this exception: "this platform does not support distributed transactions while opening connection object"

Do you know if I can do transactions for specific contexts - commit it before postprocessing (IRequestPostProcessor) and where?  Is it possible not to use PostProcessor in this case but something else. My postprocessor is taking care of Audit operation - captures what is changed in the DB.

**Comment by joaomatossilva** [comment]
I think your problem is not really related to MediatR but to the fact you're using TransactionScope, which is very specific to Microsoft Distributed Transaction Coordinator (MSDTC) and that is not supported on the platform you are compiling. 

Maybe you need to switch to full .Net Framework (and Entity Framework)?

**Comment by velchev** [comment]
@joaomatossilva This is how it seems, but will not be possible to switch to full .NET Framework and fill EF. 
I have integration tested the transactions for specific Requests and work very well with IPipelineBehavior. Seems the post-processing part need to be triggered after the transaction is completed, but will be ugly in the code where I have call to Handler to do after another call to another handler which deals with post-processing. That is a solution still as both Requests will have different transactions, but I will not take advantage of the post-processing. There should be more elegant way. Will do more research and see if someone has a solution to this.

**Comment by joaomatossilva** [comment]
Do that post-processing need to be on the same transaction? if not, then you can can envolve it on a scope like this `new TransactionScope(TransactionScopeOption.Suppress)` in order to not enlist on same transaction

If it does need to the be on the same transaction then I think you're out of luck.
You can see here: https://github.com/dotnet/EntityFramework.Docs/issues/1686 .Net core does not support MSDTC

**Comment by velchev** [comment]
One solution I found is to do the post-processing in its own transaction.
```
	using (var transaction = new TransactionScope(
					TransactionScopeOption.Suppress,
					new TransactionOptions
					{
						IsolationLevel = IsolationLevel.ReadCommitted,
						Timeout = TransactionManager.MaximumTimeout,
					},
					TransactionScopeAsyncFlowOption.Enabled))
				{
```
It is hard limitation on the way .NET core works. I created a prove of concept project [https://github.com/velchev/MediatRTransactions](https://github.com/velchev/MediatRTransactions)
Which proves that you can have different contexts in one transaction only if the contexts are pointing to one and the same DB, if they are not pointing to the same DB  `This platform does not support distributed transactions.` exception is thrown. 
So for now if you want distributed transactions - you can't you can just make transaction for specific DB.

**Comment by joaomatossilva** [comment]
Yes, hence what I've said about
> which is very specific to Microsoft Distributed Transaction Coordinator (MSDTC) and that is not supported on the platform you are compiling

Dot net core does not support Distributed transactions

**Comment by joaomatossilva** [comment]
I think this issue can be close as it's not really related to MediatR
