### ISSUE TITLE
[Question] Use of request interfaces in handlers 

### ISSUE THREAD

**Issue by rtjandrews** [jbogard/MediatR#506]
Hi, I am playing about with a greenfield project architecture at the moment and I thought it would be good to separate out the concerns of requests by assembly. For example...

`MyProject.Data` - contains handlers and public interfaces for requests and returned data models
`MyProject.Services` - contains handlers and public interfaces and returned service models as well as concrete implementations of data request interfaces.
`MyProject.Api` - contains controllers etc and concrete implementations of the service request interfaces

This feels to be a better separation of layers than having the concrete requests in the same assembly as the handlers.

It currently isnt possible to have a `IRequestHandler<IMyRequest, IEnumerable<IMyServiceModel>>` is this something you would consider adding?

I have an example of the kind of change that would be required here...
````
public Task<TResponse> Send<TResponse>(IRequest<TResponse> request, CancellationToken cancellationToken = default)
        {
            if (request == null)
            {
                throw new ArgumentNullException(nameof(request));
            }

            var requestType = request.GetType();
          
            var requestDirectInterfaceType = this.GetRequestDirectInterfaceType(requestType);
           
            var handler = (RequestHandlerWrapper<TResponse>) _requestHandlers.GetOrAdd(requestDirectInterfaceType ?? requestType,
                t => Activator.CreateInstance(typeof(RequestHandlerWrapperImpl<,>).MakeGenericType(requestDirectInterfaceType ?? requestType, typeof(TResponse))));

            return handler.Handle(request, cancellationToken, _serviceFactory);
        }

private Type GetRequestDirectInterfaceType(Type requestType)
        {
            return requestType
                .GetInterfaces().Where(i => !requestType.GetInterfaces().Any(i2 => i2.GetInterfaces().Contains(i)))
                .FirstOrDefault(i => typeof(Mediator).Assembly.GetType(i.FullName) == null);
        }
````

What are your thoughts on this idea? In my use case I only need to check for a single interface on the request object.

**Comment by lucasluizss** [comment]
Maybe use reflection like this can make your software slower. You can just use dependency injection with all your classes typed, if you are doing this with .Net Core. There are many ways to register a service in your container, including registering for each of your assemblies. You must prefer interfaces than inheritance, if you want to handle many request types.
About your return type, you can handle this in your application layer, [AutoMapper](https://automapper.org/) support that kind of idea.

Sample how to solve it with IoC:
```
bool IsRequestHandlers(Type type) => type.Is(typeof(IRequestHandler<,>)) || type.Is(typeof(IRequestHandler<>));

void AddRequestHandlers(this IServiceCollection services, Type type) => type.Assembly
            .GetTypes()
            .Where(type => type.GetInterfaces().Any(IsRequestHandlers)).ToList()
            .ForEach(type => type.GetInterfaces().Where(IsRequestHandlers).ToList().ForEach(@interface => services.TryAddScoped(@interface, type)));
```

**PS:** there is some add-ons in my code, but I think you can understand it.
