### ISSUE TITLE
[Feature Request]: Unobtrusive/Convention-based Command/Event/Message configuration

### ISSUE THREAD

**Issue by fourpastmidnight** [jbogard/MediatR#507]
Is it possible to introduce some sort of unobstrusive/conventions-based command and event registration mechanism, similar to what NServiceBus provides?

Many people (not all, but many) feel that Commands and Events are part of the application domain model in terms of the Onion (or hexagonal) architecture. Command and event handlers, meanwhile, are part of the application layer. In order to minimize application concerns bleeding into the domain model, it would be nice to not have to decorate command and event classes with marker interfaces, since this means that a library containing the domain model would necessarily need to reference a library which deals with purely application concerns: MediatR in this case.

**Comment by joaomatossilva** [comment]
Two questions:

* Without any knowledge of the MediatR how would the commands or event be executed? Wouldn't it need access to the `IMediator` instance the same?
* A similar case would be repositories. Wouldn't the repository interfaces be known to the domain?

If for the latter question the answer is yes, then think about the `IMediator` like if it was a `DbContext` (if using EF). It' possible to acheive that, but you'll be creating an abstracion layer on top of MediatR (similar how you create Repositories on top of the EF).

Honestly I don't think you do have anything to gain by abstracting MediatR away. Only a lot of plumbing code everytime you need to add something.

Yes, it does make it pretty... on the cost of over complicating things and future effort... It's like a design where adding a feauture as the cost of the feature plus all the design decisions.

**Comment by fourpastmidnight** [comment]
If you implement the domain with persistence ignorance (since persistence is an application concern and not a domain concern), then your domain has no knowledge of a DbContext or Session. And it does not require the use of repositories. This is quite simple to achieve and is quite common in CQRS/Event-sourced systems.

Since command and event handlers are an application concern and not a domain concern, in the same way then, it would be nice to have "messaging-handling ignorance" within the domain, too.

And I'm not suggesting that "unobtrusive"/convention-based configuration necessarily _replace_ the use of marker interfaces. Indeed, you can still use such interfaces in NServiceBus.

**Comment by joaomatossilva** [comment]
When I was making the parallel against Entity Framework, I was talking about Repositories, and having the domain layer knowledge if the `IRepository` interfaces as the point of contact between layers.

In this case, the repositories are just kinda of an abstraction layer between your Domain layer and the Data layer that is the implementation of those and the `DbContext` access.

You could in theory create your own event dispachers that would in turn just connect with the `IMediator`. But again, to me that would just extra plumbing without much gain.

**Comment by fourpastmidnight** [comment]
I think you and I are coming at this from two different angles. I'm not proposing a useless abstraction at all. I'm proposing a different way of MediatR being able to discover messages and understand how handlers are associated with their commands and events using an unobtrusive/convention-based setup mechanism similar to NServiceBus. [Here's their documentation on using a convention-based approach to discovering commands/events/messages instead of using marker interfaces.](https://docs.particular.net/nservicebus/messaging/conventions) Again, you _can_ still use marker interfaces with NServiceBus&mdash;as an implementor, you have a choice of whether to use marker interfaces or convention-based configuration.

Come to think of it, my use of the word _registration_ in the title of this issue may be causing the confusion. I apologize for the potential misuse of that word because of the overloaded nature of what that _could_ mean.

**Comment by joaomatossilva** [comment]
Ok. Got it.

I would say that it would be possible for the MediatR Notifications to be configured like that (the `INotification` derivations) because the handler only needs the type of the Notification.
It would be a rather simple, and even possible to do without changing the code base, only by doing some assembly scanning and registering the types on startup.

The Request types (the `IRequest<TResponse>` derivations) would be harder. Because you need to have the type of the response. But I guess you left those out of the issue title on purpose.

I would say it's possible to achieve for the first part, the notifications. You just need to ignore the registration setup and roll your own.

**Comment by fourpastmidnight** [comment]
Oh shoot. You make a good point about commands implementing IRequest{T}. I forgot about that interface, and others like it.

That sort of takes most of the wind out of the sails on this request. As any command returning a value would still need to implement that marker interface and your domain library still needs to take an application dependency.

This isn’t the worst thing. I was just hoping to avoid it, if possible.

Thank you for your patience in trying to understand my request.

Sent from my Windows 10 phone

**Comment by jbogard** [comment]
There was a request a few years ago on the C# team to better infer the generic arguments based on the assignment type. We need the `TRequest` because C# otherwise can't figure that out. If the argument doesn't implement something that describes `TRequest`, then it must be provided some other way in the assignment.

Your other option is to force an argument for `TRequest`:

```csharp
Task<TResponse> Send<TResponse>(object request);
```

Then you can do:

```csharp
var response = await _mediator.Send<MyResponse>(request);
```

C# also can't do partial generic argument inference, so if you do this:

```csharp
Task<TResponse> Send<TRequest, TResponse>(TRequest request);
```

Then your usage would be:

```csharp
var request = new Request();
var response = await _mediator.Send<Request, Response>(request);
```

My overall design goal with MediatR's `IMediator` methods was to avoid *any* generic arguments and do what I can with inference. The interface you see now is the end result of that.

**Comment by fourpastmidnight** [comment]
Makes sense, Jimmy. Yeah, I simply forgot about the result returning commands, coming from an NServiceBus background which has no such thing. And I can appreciate your desire for minimizing “generic soup” on method calls to MediatR.

Thanks for responding and providing your thought process behind the design of MediatR.

Seeing as how that is a core feature of MediatR, while it might be nice to have convention-based configuration, it appears that for many use-cases, this wouldn't be possible anyway, thereby adding little value to MediatR while increasing the maintenance burden.

I’ll close this issue later today.

Again, thank you all for your kind consideration and remarks.

Sent from my Windows 10 phone
