### ISSUE TITLE
Mocking MediatR with generics fails

### ISSUE THREAD

**Issue by fjod** [jbogard/MediatR#508]
Hello, I'm trying to write integration tests for webapi with Moq. I want to test if controller method calls mediator, and mediator does it job correctly. So working test look like this:
```
   Mock<IMediator> mediatrMock = new Mock<IMediator>();
            var moqResult = "FooTest";

            mediatrMock.Setup(m =>
                m.Send(It.IsAny<Foo.Query>(),
                    It.IsAny<CancellationToken>())).ReturnsAsync(() => moqResult);


            var sut = new HomeController(mediatrMock.Object);
            var ret = await sut.TestFoo();
            Assert.Equal(moqResult, ret.Value);

            mediatrMock.Verify(x => x.Send(It.IsAny<Foo.Query>(),
                It.IsAny<CancellationToken>()));
```

But I will have many duplicate code if I use this approach. I thought that I can use generics, because I change only Query type and set operation result each time. So :
```

async Task Generic<TK,K>(TK expectedResult,Func<Task<ActionResult<TK>>> callControllerMethod)
        {

            mediatrMock.Setup(m =>
                m.Send(It.IsAny<K>(),
                    It.IsAny<CancellationToken>())).ReturnsAsync(() => expectedResult);
            
            var ret = await callControllerMethod();

            Assert.Equal(expectedResult, ret.Value);

            mediatrMock.Verify(x => x.Send(It.IsAny<K>(),
                It.IsAny<CancellationToken>()));

        }
```

And I should be able to call it simply as:

```
  var moqResult = "BarTest";
            
            await Generic<string, BarQuery>(moqResult, () => sut.TestBar());

```
But mediatr fails to register it :/

I created a repo on github to demostrate it: https://github.com/fjod/MediatrMoq
please check it. May be I dont really understand what I am doing here xD

**Comment by jbogard** [comment]
Why would you try to mock the mediator?

**Comment by fjod** [comment]
Well, how do I test Controller then? I have Mediator injected in controller, so I must provide instance. If I try to do straightforward:

```
 public class NoMocking_Mediatr
    {
        public NoMocking_Mediatr(IMediator mediator)
        {           
            Mediator = mediator;
        }

        public IMediator Mediator { get; }


        [Fact]
        public async void Test()
        {
            var moqResult = "FooTest";

            var sut = new HomeController(Mediator);
            var ret = await sut.TestFoo();
            Assert.Equal(moqResult, ret.Value);           
        }

    }
```
It fails with "The following constructor parameters did not have matching fixture data: IMediator mediator"

And google said that I need to use mocks here https://stackoverflow.com/questions/55443201/how-to-instanciate-mediatr-as-part-of-a-unit-test

**Comment by jbogard** [comment]
I don't think this test provides any value. I never write these tests, the logic has been pushed down into the handler instead.

**Comment by lilasquared** [comment]
Maybe not as an integration test but as a unit test ensuring that the right controller method sends the right command / query with the properties populated correctly should provide some value?

**Comment by fjod** [comment]
> I don't think this test provides any value. I never write these tests, the logic has been pushed down into the handler instead.

This is very true, I'm not sure if I even should write them at all. Anyway, I still can test them, just without generics.
