### ISSUE TITLE
Unable to resolve service for type 'System.Object' while attempting to activate 'MediatR.ServiceFactory'

### ISSUE THREAD

**Issue by ngruson** [jbogard/MediatR#511]
Hi,

I'm upgrading my web app from ASP.NET Core 2.0 to ASP.NET Core 3.1.
Also, I upgraded to Mediatr 8.0.1 and Mediatr.Extensions.Microsoft.DependencyInjection 8.0.0.

On startup, this exception is thrown:

**Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: System.ICloneable Lifetime: Transient ImplementationType: MediatR.ServiceFactory': Unable to resolve service for type 'System.Object' while attempting to activate 'MediatR.ServiceFactory'.) (Error while validating the service descriptor 'ServiceType: System.Runtime.Serialization.ISerializable Lifetime: Transient ImplementationType: MediatR.ServiceFactory': Unable to resolve service for type 'System.Object' while attempting to activate 'MediatR.ServiceFactory'.)**

I used to have this in Startup.cs to add Mediatr to dependency injection:
```csharp
services.AddScoped<ServiceFactory>(p => p.GetService);
```

I also tried
```csharp
services.AddMediatR(Assembly.GetExecutingAssembly());
```
but the exception still occurs.

Any idea why DI is not registering the ServiceFactory type correctly?
How should I do this in ASP.NET Core 3.1?
Downgrading again to Mediatr 7.0.0 didn't help.

**Comment by lilasquared** [comment]
It looks like it is registering ServiceFactory as ICloneable and ISerializable, is there anything else from your Startup.cs you can share?

**Comment by ngruson** [comment]
Problem solved.
I used to scan assemblies using the Scrutor package to register my Mediatr handlers.

Now I'm doing:
```csharp
services.AddMediatR(Assembly.GetExecutingAssembly());
services.AddMediatR(typeof(MyCommandHandler).Assembly);
```

**Comment by aliChavoshi** [comment]
what is the MyCommandHandler ???

**Comment by aliChavoshi** [comment]
i have this problem :(

**Comment by aliChavoshi** [comment]
yes, I solved this problem. check all DI in the project, my problem in the UnitOfWork
