### ISSUE TITLE
Call Multiple handle into one handler

### ISSUE THREAD

**Issue by shrutigoyal123** [jbogard/MediatR#517]
@jbogard @lilasquared 

I am using MediatR in my project. and I want to fetch records form Handler1 and acording to Handler1's result I can call handler2 and according to handler2's result I can call handler3.

And at last I can return a combined data from my handler1 to my view.

Is it possible and yes then how?

**Comment by joskoanicic** [comment]
What is stopping you from calling mediator.Send(...) multiple times?

```

var handler1Result = await mediator.Send(new Handler1Command());

if(hanhandler1Result) //some condition {
var handler2Result = await mediator.Send(new Handler2Command());

if(hanhandler2Result) //some condition {
  var handler3Result = await mediator.Send(new Handler3Command());
 }
} 
```
Or you could inject mediator into your Handler1 and Handler2 and send commands directly from Handler1 and Handler2 depending on the business logic you are implementing.

**Comment by shrutigoyal123** [comment]
@joskoanicic 

Thanks, I was looking for injecting mediator.

So big thanks to you.

**Comment by jbogard** [comment]
Just don't do this from inside a handler, calling handlers from other handlers generally ends badly.

**Comment by joaomatossilva** [comment]
> Just don't do this from inside a handler, calling handlers from other handlers generally ends badly.

Do you also include on the rationale raising a notification after a request is completed?

**Comment by jbogard** [comment]
Ah, I should clarify - you can raise notifications, since those are different pipelines. Just multiple Send really.
