### ISSUE TITLE
Send Message without response

### ISSUE THREAD

**Issue by cirrusone** [jbogard/MediatR#520]
Hello,

I'm trying to follow the example in the wiki to send a message with no response, the example starting from _In the case your message does not require a response, use the AsyncRequestHandler<TRequest> base class:_

But I get the following error 
`Error	CS0161	'MainWindowViewModel.OneWayHandlerWithBaseClass.Handle(OneWay, CancellationToken)': not all code paths return a value`

How do I fix this? I'm using netcore 3.1. 
I may have mis-interpreted what this does as I thought there should be nothing returned, do I actually still need to return 'something'  such as return Task.FromResult(0); ? If it's a long running task before the return is there a delay on the await _mediator.Send...?

App.xaml.cs:
```
protected override void RegisterTypes(IContainerRegistry containerRegistry)
{
    // MediatR DI
    var container = containerRegistry.GetContainer();
    container.RegisterDelegate<ServiceFactory>(r => r.Resolve);
    container.RegisterMany(new[] { typeof(IMediator).GetAssembly(), typeof(OneWay).GetAssembly() }, Registrator.Interfaces);
}
```

BlankCoreApp1.Events:
```
namespace BlankCoreApp1.Events
{
    // Event to trigger event with no message and return string response
    public class Ping : IRequest<string>
    {
    }

    // Event to trigger event with string Message and return string response
    public class PingWithVariable : IRequest<string>
    {
        public string Message { get; set; }
    }

    //// Event to trigger event with string Message and no response (one way)
    //public class PingNoResponse : IRequest
    //{
    //    public string Message { get; set; }
    //}

    public class OneWay : IRequest { }
}
```

MainWindowViewModel.cs:
```
...
        public class OneWayHandlerWithBaseClass : AsyncRequestHandler<OneWay>
        {
            protected override Task Handle(OneWay request, CancellationToken cancellationToken)
            {
                // Twiddle thumbs
            }
        }
...
```

**Comment by jbogard** [comment]
`Task` represents an asynchronous activity that has no result. It looks like you're getting tripped up by the difference between async and sync handlers. If your async handler does not return a result, you'd simply await whatever action you're performing:

```csharp
        public class OneWayHandlerWithBaseClass : AsyncRequestHandler<OneWay>
        {
            protected override async Task Handle(OneWay request, CancellationToken cancellationToken)
            {
                await doSomethingAsync();
                await doDomethingElseAsync();
            }
        }
```

No result returned. However, you do have the Task thing because you're in async-land. However, the Task does not have a result.

If you are synchronous AND don't return a value, you may use the `RequestHandler` base class:

```csharp
public class MyHandler : RequestHandler<MyRequest> {
   protected override void Handle(MyRequest request) {
       // twiddle thumbs
   } 
}
```

I tend to not use these though, I find them a bit confusing. Instead I just use the interface and return an appropriate value.

- `Task.CompletedTask` - notification handler with no async work
- `Unit.Task` - command handler with no async work and no return value

**Comment by cirrusone** [comment]
Excellent, thank you.

One final question... If I have 2 viewmodels is it possible to have the have a handler inside the viewmodel? At the moment the Handler's are classes so unclear how a viewmodel would consume a message. For example,

```
public class MessengerPingHandler : IRequestHandler<MessengerPing, string>
{
    public Task<string> Handle(MessengerPing request, CancellationToken cancellationToken)
    {
        // Access MainViewModel data here?
        return Task.FromResult($"Complete");
    }
}
```
Viewmodel2:
```
private async void LaunchWindow()
{
     string result = await _mediator.Send(new MessengerPing() { Message = "PassSomeDataToMainViewModelAndReturnValue" });
}
```

MainViewModel:
How do I consume MessengerPingHandler inside the MainViewModel?

**Comment by cirrusone** [comment]
I managed to figure it out... the viewmodel inherits the `IRequestHandler` rather than it being a separate class.

```
public class MainWindowViewModel : BindableBase, IRequestHandler<MessengerPing, string>
{
        public Task<string> Handle(MessengerPing request, CancellationToken cancellationToken)
        {
            return Task.FromResult($"Complete");
        }
}
```

Thanks for your help again. This is an excellent tool.
