### ISSUE TITLE
SendAsync inside handler of another sendAsync = System.AggregateException ?

### ISSUE THREAD

**Issue by bossen2k** [jbogard/MediatR#53]
at MediatR.Examples.PingAsyncHandler.<Handle>d__1.MoveNext() 

And the innerException is of type System.Exception{System.NullReferenceException}
Should it be posible to use SendAsync from within another SendAsync ?

**Comment by jbogard** [comment]
It might be possible, we do that occasionally. But it might not work if the container etc is not configured properly.

**Comment by bossen2k** [comment]
So if we took the example and copied ping to ping2 and pinghandler to ping2handler and called mediator.send(new ping2{ message = "Ping 2"}); from within pinghandler.handle, what changes in the container configuration should i make ?

**Comment by jbogard** [comment]
I'm not sure what container you're using now, for us it just works with StructureMap and the example config in the repo.
