### ISSUE TITLE
Assembly version is 8.0.0.0 for release 8.0.2

### ISSUE THREAD

**Issue by dsteinweg** [jbogard/MediatR#531]
Hi, I went to upgrade MediatR today in my application and got assembly version errors.  It appears the 8.0.2 release was published with assembly version(s) 8.0.0.0, while the 8.0.1 release had assembly version(s) 8.0.1.0.

**Comment by jbogard** [comment]
Oof, I'll double-check

**Comment by jbogard** [comment]
Ah, I switched to a different versioning library, which now follows the MS guidance around assembly versions:

https://docs.microsoft.com/dotnet/standard/library-guidance/versioning#version-numbers

What error are you getting now?

**Comment by dsteinweg** [comment]
Does this mean MediatR will now be following this guidance, from that link?
CONSIDER only including a major version in the AssemblyVersion.

My error was due to a dependency graph: App (MediatR 8.0.2, assembly 8.0.0.0) -> app class library (MediatR 8.0.1, assembly 8.0.1.0).
Since the class library had MediatR 8.0.1 installed, upgrading the app to MediatR 8.0.2 resulted in the assembly version errors.

If 8.0.0.0 is going to be the go-forward assembly version for 8.x.x releases, that's fine.  I will simply update all my class libraries to 8.0.2.  Thanks!

**Comment by davidroth** [comment]
@jbogard Afaik this guidance is no longer valid because binding redirects don`t exist in .NET Core. (Deps.json FTW :-) 
Would be interested what made you think this change is still worth it? For the existing NetFX Consumers?

**Comment by jbogard** [comment]
What change? I just added `MinVer`, the assembly version was unintentional.

**Comment by davidroth** [comment]
> What change? I just added `MinVer`, the assembly version was unintentional.

The assembly version change.  (keeping the major version number of the AssemblyVersion and the NuGet package version in sync.)

**Comment by davidroth** [comment]
> What change? I just added `MinVer`, the assembly version was unintentional.

The assembly version change.  (Including only including a major version in the AssemblyVersion.)

**Comment by jbogard** [comment]
Right that was just an accident with moving to MinVer from manual versioning
