### ISSUE TITLE
Support for generic IRequest and IRequestHandler pairs

### ISSUE THREAD

**Issue by jasonycw** [jbogard/MediatR#534]
I are writing an event store application and found some use cases where I would want a generic `IRequest` and `IRequestHandler` to minimize the number of duplicate Handlers.

But it seems that `IMediator` cannot resolve a generic handler like `IRequestHandler<TestGenericRequest<T>, string>`

I pushed an example here: https://github.com/jasonycw/TestMediatR
Under [TestController.cs](https://github.com/jasonycw/TestMediatR/blob/master/TestMediatR/Controllers/TestController.cs)
``` C#
return await _mediator.Send(new TestGenericRequest<int>(1024));
```
This will throw an exception where it cannot resolve the handler that inherit `IRequestHandler<TestGenericRequest<T>, string>`.

However,
``` C#
await _mediator.Publish(new TestGenericNotification<int>(1024));
```
This will work and can find the handler that inherit `INotificationHandler<TestGenericNotification<T>>`

I looked into [`MediatR.Extensions.Microsoft.DependencyInjection`](https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection) and found that under [`ServiceRegistrar.cs`](https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/blob/bb576723d48b0a35b5f1a3c54b24cd68403def4a/src/MediatR.Extensions.Microsoft.DependencyInjection/Registration/ServiceRegistrar.cs#L48-L78)

``` C#
        private static void ConnectImplementationsToTypesClosing(Type openRequestInterface,
            IServiceCollection services,
            IEnumerable<Assembly> assembliesToScan,
            bool addIfAlreadyExists)
        {
            var concretions = new List<Type>();
            var interfaces = new List<Type>();
            foreach (var type in assembliesToScan.SelectMany(a => a.DefinedTypes).Where(t => !t.IsOpenGeneric()))
            {
                var interfaceTypes = type.FindInterfacesThatClose(openRequestInterface).ToArray();
                if (!interfaceTypes.Any()) continue;

                if (type.IsConcrete())
                {
                    concretions.Add(type);
                }

                foreach (var interfaceType in interfaceTypes)
                {
                    interfaces.Fill(interfaceType);
                }
            }
```
 `IRequestHandler<TestGenericRequest<T>, string>` will be filtered out during `assembliesToScan.SelectMany(a => a.DefinedTypes).Where(t => !t.IsOpenGeneric())`

Is this behavior expected? Or will generic `IRequest` be supported in the future like `INotification`?

**Comment by jbogard** [comment]
Yes, this is expected, as what you're trying to create is a partially closed generic type, where the open parameter is far down the generic type path. I don't try to recursively find the open generic parameter (look at both pairs, look for any generic parameter, if none, keep looking). It's just too complicated.

It's not just registration, but resolving as well. You'd have to get that type registered, AND during resolution find the right `T` parameter to fill in.

**Comment by jasonycw** [comment]
@jbogard thanks for the quick response.

I have one follow up question, if partially closed generic `IRequest` is not supported, why partially closed generic `INotification` can work?
The 2 generic `INotificationHandler` in [TestGenericNotification.cs](https://github.com/jasonycw/TestMediatR/blob/master/TestMediatR/Features/TestGenericNotification.cs) 
``` C#
    public class TestGenericNotification<T> : INotification
    {
     ...
    }

    public class TestGenericNotificationHandler<T> : INotificationHandler<TestGenericNotification<T>>
    {
     ...
    }

    public class AnotherTestGenericNotificationHandler<T> : INotificationHandler<TestGenericNotification<T>>
    {
     ...
    }
```

Can properly handle the generic `INotification` when I call

``` C#
await _mediator.Publish(new TestGenericNotification<int>(1024));
```
