### ISSUE TITLE
 error CS0305: Using the generic type 'ValidationContext<T>' requires 1 type arguments

### ISSUE THREAD

**Issue by PAMALSAHAN** [jbogard/MediatR#535]
when using ValidationBehavior  class cause an error
 because of below code 
 var context = new ValidationContext(request);

**Comment by Ignlek** [comment]
Hi, I think you are using  FluentApi 9.0 and code that you pasted is from  8.0 there was some changes try using 
`var context = new ValidationContext<TRequest>(request);`
it worked for me, good luck

**Comment by parasparmar** [comment]
@Ignlek - And yes sir, it absolutely does resolve the problem. Thank you and God bless.
