### ISSUE TITLE
remove need for invocation using Handle() method

### ISSUE THREAD

**Issue by eskensberg** [jbogard/MediatR#539]
This is not an issue, but a request.

Is it possible to design the behaviour of the handlers in a way, that the handling is done by the constructor (similar how the fluent validation uses ctor for validation) ?

At the moment, I have to type alot of boilerplate just to inject dbContext and etc, and create fields to pass on to Handle() method, when in reality I want to avoid that boilerplate.

I appologise if that was discussed somewhere else alrady previously 😅 

Thanks for the great library guys ❗ 

Elvis

**Comment by jbogard** [comment]
No, constructors can't be async so that seveeeeerely limits things.

The other option is currying and partial application, which is super annoying in C#

Or have a "context" object passed in that you resolve services from. None of those are great, so here we are!
