### ISSUE TITLE
Need some help on DecorateAllWith in WebApi

### ISSUE THREAD

**Issue by ThisNoName** [jbogard/MediatR#54]
I'm testing a simple ping request with a decorator.

```
public class ValidatorHandler<TRequest, TResponse> : IRequestHandler<TRequest, TResponse>
   where TRequest : IRequest<TResponse> { ... }
```

In a console application, the ValidatorHandler works.

```
       var container = new Container(cfg =>
        {
            cfg.Scan(scanner =>
            {
                scanner.AssemblyContainingType<PingRequest>();
                scanner.AssemblyContainingType<IMediator>();
                scanner.WithDefaultConventions();
                scanner.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>));
            });
            cfg.For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
            cfg.For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));

            var handlerType = cfg.For(typeof(IRequestHandler<,>));
            handlerType.DecorateAllWith(typeof(ValidatorHandler<,>));
        });

        var mediator = container.GetInstance<IMediator>();
        mediator.Send(new PingRequest { Message = "Ping"});
```

But when trying the same in a WebApi project, the ValidationHandler never wired up.  I know the rest of the IoC works, because I can inject IDatabase and retrieve data.  Did I miss something?  Maybe need to decorate from a different place?  Thanks

```
    public DefaultRegistry()
    {
        Scan(
            scan =>
            {
                scan.TheCallingAssembly();
                scan.AssemblyContainingType<PingHandler>();
                scan.WithDefaultConventions();
                //scan.With(new ControllerConvention());
                scan.AddAllTypesOf(typeof(IRequestHandler<,>));
            });

        var handlerType = For(typeof(IRequestHandler<,>));
        handlerType.DecorateAllWith(typeof(ValidatorHandler<,>));

        For<IMediator>().Use<Mediator>();
        For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
        For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));

        For<IDatabase>().Use(new Database("DefaultDb"));
    }
```

**Comment by ChrisMissal** [comment]
I encountered something similar with this. The decoration was happening in two places for me. The first being what you have above, the second being within an instance of `IDependencyResolver`. Inside `BeginScope()` the app creates a child/nested container, which only lives for the request, but also registers the decoration.

Sorry I can't be too specific right now, but hopefully that will point you in the right direction.

**Comment by whoever123** [comment]
Thanks.  Changed the default BeginScope to the following and it works, not sure if it's the right way though, and seems like you don't have to do it in DefaultRegistry.

        public IDependencyScope BeginScope()
        {
            //IContainer child = this.Container.GetNestedContainer();
            //return new StructureMapWebApiDependencyResolver(child);
            var resolver = new StructureMapWebApiDependencyResolver(CurrentNestedContainer);

            ServiceLocatorProvider provider = () => resolver;

            CurrentNestedContainer.Configure(cfg =>
            {
                cfg.For<ServiceLocatorProvider>().Use(provider);
                cfg.For(typeof(IRequestHandler<,>)).DecorateAllWith(typeof(ValidatorHandler<,>));
            });
            return resolver;
        }

Now look back, turned out SimpleInjector can do it simpler without the extra step.  Yesterday I was actually stuck on a different issue, trying to build decorator with a different signature.  It was the IValidator<TRequest>[] blow up.

    public class ValidationRequestHandler<TRequest, TResponse> : IRequestHandler<TRequest, TResponse> 
        where TRequest : IRequest<TResponse>
    {
        private readonly IRequestHandler<TRequest, TResponse> _innerHander;
        private readonly IValidator<TRequest>[] _validators;

        public ValidationRequestHandler(IRequestHandler<TRequest, TResponse> innerHandler,
              IValidator<TRequest>[] validators)
        {
            _validators = validators;
            _innerHander = innerHandler;
        }

This was copied from bernos' MediatR.Extensions.  He has some MediatorBuilderExtensions to wire things up, but I still not sure how to use it.  Let me know in case you tried that one too.  Thanks.

https://github.com/bernos/MediatR.Extensions/tree/master/MediatR.Extensions.FluentValidation
