### ISSUE TITLE
mediatr console application sample

### ISSUE THREAD

**Issue by sadeghhp** [jbogard/MediatR#540]
please add a console app sample

**Comment by lilasquared** [comment]
There are a ton of samples in the “samples” folder.

**Comment by sadeghhp** [comment]
I want a very simple sample without injector ! is it possible?

**Comment by lilasquared** [comment]
Its simpler WITH dependency injection. Otherwise you’d have to write your own service factory.

**Comment by JohnSheppard** [comment]
I am a noob. I too was looking for the same thing (an example with out injection). I am not all that comfortable with DI as yet. Wondered why all the examples on the web used DI... It's a problem.... That's all I have to say though. So now, I'm off to figure out DI, which is a solution to a problem for a problem for a problem lol...oh wells... thanks everyone for your hard work.

**Comment by jbogard** [comment]
MediatR is built *on top of* dependency injection. You cannot separate MediatR from DI, it's a fundamental component of its design. In fact, it's a fundamental component of the mediator pattern for OO languages.
