### ISSUE TITLE
MediatR.Extensions.Microsoft.DependencyInjection version 8.0.1 does not reference MediatR version 8.0.2

### ISSUE THREAD

**Issue by mohammed-fuad** [jbogard/MediatR#541]
Runtime exception is thrown `Could not load file or assembly 'MediatR, Version=8.0.1.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'. The system cannot find the file specified.`  this is caused when Domain layer project have `MediatR version 8.0.2` while application layer reference `MediatR.Extensions.Microsoft.DependencyInjection version 8.0.1`

**Comment by mohammed-fuad** [comment]
@jbogard Any idea for this issue?

**Comment by joaomatossilva** [comment]
Can't you use the same version on both? Do you need different versions?

**Comment by mohammed-fuad** [comment]
> Can't you use the same version on both? Do you need different versions?

@joaomatossilva Sure can do which has no problem, issue is happening because of mismatching of dependencies in MediatR.Extensions.Microsoft.DependencyInjection

**Comment by jbogard** [comment]
I think the best option here is to bump the versions.

**Comment by jbogard** [comment]
I just released 8.1.0 which *should* fix things?

**Comment by mohammed-fuad** [comment]
> I just released 8.1.0 which _should_ fix things?

Yes, it's working

Appreciate it.
