### ISSUE TITLE
Integration Testing NotificatonHandlers

### ISSUE THREAD

**Issue by ebrim** [jbogard/MediatR#544]
Using Jimmy's vertical slice test fixture how do you integration test INotificationHandlers when you have multiple handlers that handle the same event? Only thing I can come up with is testing each handler individually using mocks but at that point it becomes a unit test.

**Comment by lilasquared** [comment]
What roadblocks are you hitting testing multiple? If you had one handler that say logged to the db and one that logged to a file, after the test I would assume you could just check both the db and the file to ensure both were hit.  I don't think having multiple would affect that outcome.

**Comment by ebrim** [comment]
The only issue I have testing multiple is that if I fire off an event, and there are five handlers, then that could become quite a bit to test in one integrations test. I was looking for a cleaner way to isolate one piece of the integration.

**Comment by lilasquared** [comment]
So with the integration tests I've made I was constructing a container and such to use in the tests.  If you wanted you could probably introduce some sort of filtering option or test configuration to override what implementations are picked up by whatever IoC you are using.  So for your situation for testing Notification Handler A could say, only add that handler to the dependency graph and then when you send the notification only that one would be picked up.  It would limit the scope of the test a bit but would not represent a true integration test of the full application.

**Comment by ebrim** [comment]
Looks like I will just need to test the entirety of the event.
