### ISSUE TITLE
Publishstrategy not working as intended

### ISSUE THREAD

**Issue by iammelvin** [jbogard/MediatR#549]
I have implemented the publish strategy as given in the publish strategies example. I am trying to use parallel no wait strategy for my notification handler. Inside the handle method of notification I have multiple awaits which fetches data from repository for report generation. Since this is using no wait publish strategy I am able to send response to the user even before the report has been generated but my reports which is supposed to be generated in the background tasks never completes. Any help would be really appreciated. But when I use parallel when all strategy it is working but response is returned to the user only when the entire process is completed which is taking so much time.

**Comment by no1melman** [comment]
I feel like this lacks examples

**Comment by iammelvin** [comment]
Also want to know how to pass object from main thread to new thread in case of using publish strategy. Now I am getting dispose error.
