### ISSUE TITLE
LightInject sample incorrect LifeTime

### ISSUE THREAD

**Issue by ArnaudB88** [jbogard/MediatR#550]
Hi,
I think that the pipeline behaviors in the LightInject sample are registered with the incorrect lifetime. Let me explain how I come to this...

In our project, we have simple pipeline:
- Validation preprocessor: inherits from IRequestPreProcessor and executes fluentValidation validators ([similar example](https://stackoverflow.com/questions/42283011/add-validation-to-a-mediatr-behavior-pipeline))
- Transaction behavior: inherits from IPipelineBehavior and simply saves database changes after the 'await next()'

I our validator classes, database calls are made using a 'UnitOfWork'/dbcontext wrapper.
With the current example code for LightInject, we get the following exception when executing multiple unit tests for one mediatR command:
```
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
    Object name: 'EntityFrameworkEntitiesDbContext'.
  Stack Trace: 
    DbContext.CheckDisposed()
```
**Reason**
The first unit test using a 'FooValidator' instance, works correctly. But a second, third, ... unit test will use the same 'FooValidator' instance. Know that the dbContext is registered scoped and each unit test runs within its own scope. So each unit test uses the same 'FooValidator' instance containing the same dbContext, which is disposed after the first unit test.

How is it possible that the same validator instances are used for different unit tests?
The IPipelineBehavior registrations in the sample code are done with a PerContainerLifetime, giving the following situation:
- mediatR.Send(FooRequest)
- mediatR requests the pipeline from the LighInject container: "IEnumerable<IPipelineBehavior< FooRequest >>"
- FooValidator instance created (needed for validation preprocessor constructor parameter below)
- Validation preprocessor instance created
- Transaction behavior instance created
- Validation preprocessor executes Process(), this executes FooValidator fluent validation code
- Transaction behavior executes Handle()
- Handler is executed

For a second unit test, the same situation as above occurs except instance creation for validation preprocessor and FooValidator (steps 3 and 4). The same preprocessor instance and FooValidator instance are used (so also FooValidator.UnitOfWork).

**Solution**
Register IPipelineBehaviors with a transient lifetime (= a null returning function):
```
serviceContainer.RegisterOrdered(typeof(IPipelineBehavior<,>),
new[]
{
     typeof(RequestPreProcessorBehavior<,>),
     typeof(RequestPostProcessorBehavior<,>),
     typeof(GenericPipelineBehavior<,>)
}, type => null);
```
Note 1: you can verify that sample code for other DI libraries, default LT = transient is used (StructureMap, Autofac, unity)
Note 2: registering the IRequestPostProcessors with a transient lifetime could solve similar problems

**Comment by lilasquared** [comment]
I think each mediator request should be using a nested or sub container, which is why the behaviors are registered as per container.  In a web api scenario each request constructs a nested container to handle the DI for the request.  If you are using the same instance of a container for all of your unit tests then that is different behavior than what a web api application would be doing.  If you aren't using a web api then yeah maybe registering them as transient would be better for your use case.

**Comment by ArnaudB88** [comment]
> 
> 
> I think each mediator request should be using a nested or sub container, which is why the behaviors are registered as per container. In a web api scenario each request constructs a nested container to handle the DI for the request. If you are using the same instance of a container for all of your unit tests then that is different behavior than what a web api application would be doing. If you aren't using a web api then yeah maybe registering them as transient would be better for your use case.

@lilasquared You are correct that for each unit test and for each web api request a 'different container' should be used. LightInject works with 'scopes' instead of nested/sub container, but results in the same behavior. In my project both unit tests and web api requests work with scopes.
The PerContainerLifetime used in the sample code is a singleton lifetime (aka container controlled lifetime). So the same instance for the container, for all scopes.
See https://www.lightinject.net/#percontainerlifetime

The lifetime should be changed to not-singleton lifetime to solve this problem described above.
Note that a PerScopeLifetime or PerRequestLifetime could also be a solution, BUT when running the same code from an application which doesn't uses scopes (eg. console app), that will result in an exception (see https://www.lightinject.net/#perscopelifetime).
Therefor my proposition of a transient lifetime.

**Comment by lilasquared** [comment]
Ah ok so those are equivalent to singleton, that makes sense.  In that case I think the sample could be updated.  Feel free to open a PR to address it
