### ISSUE TITLE
Send Mediatr request from Middleware

### ISSUE THREAD

**Issue by stan-solovyov** [jbogard/MediatR#565]
Hi,

We use custom middleware for logging requests in our project  and wanted to send Mediatr request to save some data from request/response.
Unfortunately we get an error:
`
System.InvalidOperationException: Cannot resolve System.Collections.Generic.IEnumerable1[MediatR.IPipelineBehavior2[Psms.Domain.Command.CreateInboundActivityCommand,Psms.Domain.InboundActivityDto]] from root provider because it requires scoped service MediatR.IPipelineBehavior2[Psms.Domain.Command.CreateInboundActivityCommand,Psms.Domain.InboundActivityDto].
` 

Here is the code how we register IPipelineBehavior in our project:
`services.AddScoped(typeof(IPipelineBehavior<,>), typeof(ValidationBehavior<,>));`

If the request is sent from controller, then there is no error and command is recieved successfully by corresponding handler.
Therefore it seems that the registration is correct.

Just to check i tried to send another already working command from inside middleware and got the same error.

I haven't found any restrictions that we cannot send mediatr requests from inside middleware.
It seems that the process of using mediatr inside middleware is different from controller actions.

Software details:
MediatR - 8.1.0
.Net Core - 3.1

**Comment by jbogard** [comment]
Change your pipeline behavior lifetime to `Transient`. Scoped services are intended to only be used inside a scope, which I doubt is the case for your validation behavior.

Alternatively, if there is something inside your behavior that is also scoped (say, a DbContext), then check out your options here:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#scoped

**Comment by stan-solovyov** [comment]
Thank you for your quick response!

Indeed, the issue was not related to Mediatr at all, but rather how i registered middleware with scoped service.
