### ISSUE TITLE
Suggestion: Improve Exception Message for `Unable to resolve service for type 'MediatR.Mediator'`

### ISSUE THREAD

**Issue by MisterJames** [jbogard/MediatR#573]
I would like to propose a PR that would improve the message in the exception for `Unable to resolve service for type 'MediatR.Mediator'`. This is an exception that is called not only when the service registration isn't completed, but also if someone tries to inject `Mediator` instead of `IMediator`.

I propose that the message include the suggestion includes to check the type that is being injected through DI where the exception is thrown.

**Comment by jbogard** [comment]
That's not an exception that MediatR throws though. I think that's the MS DI package?

**Comment by MisterJames** [comment]
Good point...which isn't really a good place to clarify that particular problem.
