### ISSUE TITLE
Do request/notification handlers require locking?

### ISSUE THREAD

**Issue by AZ1904** [jbogard/MediatR#578]
I have a request handler that is invoked by an asp.net core controller method. If there are multiple parallel calls made to this controller, is the request handler also executed in parallel? I.e. do i need to lock my handlers?

**Comment by jbogard** [comment]
Your request handlers will be handled in parallel. As far as locking, you don't lock handlers. You look at concurrency controls for whatever work is being done. This work may or may not have contention. As far as how you should approach that problem, there are a lot of great resources out there, this book is my favorite:

https://www.amazon.com/Designing-Data-Intensive-Applications-Reliable-Maintainable/dp/1449373321

Although if you're using SQL, the docs on concurrency are great too. In short - no, do not lock your handlers, that's almost certainly the wrong thing to do. Instead, look at concurrency controls on whatever resource the handler is working with.

**Comment by AZ1904** [comment]
Thank you so much for the response! (and the excellent library too!)
That book has been in my reading list for a while now. Will check it out
Thanks again
