### ISSUE TITLE
RequestExceptionHandler way to set another error

### ISSUE THREAD

**Issue by radenkozec** [jbogard/MediatR#579]
I am using `RequestExceptionHandler<TRequest, TResponse, TException>` to log errors in my API.
After error is logged I want to return 500 response from API without any error detail.

How can I in Handle method clean previous error so that users does not receive real error message?

**Comment by jbogard** [comment]
Swallow the exception and rethrow something more generic. Or use the various ways ASP.NET Core does this, that'll almost certainly be easier. I don't use MediatR to affect the HTTP result, ASP.NET Core is easier/more appropriate seam to do so.
