### ISSUE TITLE
[Request/Discussion] Using Microsoft-recommended "Async" suffixes in MediatR classes

### ISSUE THREAD

**Issue by julealgon** [jbogard/MediatR#582]
Just wanted to double check if this was intentional or not. Most `async` methods in MediatR don't have the `Async` suffix on their names: for example:
- `IMediator`
 `Task<TResponse> Send<TResponse>(IRequest<TResponse>, CancellationToken)`

- `IRequestHandler`
 `Task<TResponse> Handle(TRequest, CancellationToken)`

Microsoft recommends adding the "Async" suffix to all `async` methods. Is there a chance this will be implemented in MediatR in the future?

I think seeing every other async member with the `Async` suffix and just MediatR types not having them is actually a bit confusing.

**Comment by lilasquared** [comment]
This has already been discussed here #371

**Comment by julealgon** [comment]
> This has already been discussed here #371

Thanks @lilasquared . Tried to search but for some reason that didn't come up for me. Looks like MediatR is part of a "rebel group" of libraries not using the recommendation :D. I guess that's fine though, looks like it was a very conscious decision.

Closing this. Apologies for the spam.

**Comment by remcoros** [comment]
@julealgon You might find this an interesting read about "Async" suffixes https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

**Comment by julealgon** [comment]
> @julealgon You might find this an interesting read about "Async" suffixes https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix

Thanks @remcoros . I had already seen that article from NServiceBus before replying earlier.
