### ISSUE TITLE
Generic notification handler in Asp.net core not handling notifications 

### ISSUE THREAD

**Issue by michaelboke** [jbogard/MediatR#584]
Hi, I am having a problem understanding how the generic Notification handler works. 
I was trying to create a generic notification handler to log and store all the events that are happening in my application. (An ASP.Net Core 3 application). Unfortunately, all the events that do not have a specific handler registered for their type are not picked up by the generic notification handler.

This is how my generic Notification handler is defined:
```
public class EventLogHandler : INotificationHandler<INotification>
    {
        public Task Handle(INotification notification, CancellationToken cancellationToken)
        {
            Debug.WriteLine($"Received notification ${notification} in eventLogHandler");
            return Task.CompletedTask;
        }
    }
```

There are no other notification handlers in my project registered at this point. and when I call publish `mediatr.Publish(new Test1())`. No event is handled in the generic EventLogHandler.

But as soon as I add a 2nd handler that is specific to that type `Test1`. Both handlers get called.

This is the 2nd specific handler: 
```
public class ExampleHandler : INotificationHandler<Events.Test1>
    {
        public Task Handle(Events.Test1 notification, CancellationToken cancellationToken)
        {
            Debug.WriteLine($"Received notification ${notification} in exampleHandler");
            return Task.CompletedTask;
        }
    }
```

And now when I call to publish the event, the result is
```
Received notification $Test1 in  exampleHandler
Received notification $Test1 in  eventLogHandler
```

I do not understand why the generic handler is working this way?
And all new notifications/events that I publish that do not have a notification handler are ignored by the generic EventLogHandler. 

I did come up with a workaround by registering all my events explicitly in the container. (But not sure if this is the right way)
```
Assembly.GetAssembly(typeof(Events.Test1)).GetTypes()
                .Where(t => t.IsClass && t.IsAssignableTo(typeof(INotification)))
                .ToList()
                .ForEach(t =>
                {
                    Type[] typeArgs = {t};
                    services.TryAddTransient(
                        typeof(INotificationHandler<>).MakeGenericType(typeArgs),
                        typeof(EventLogHandler)
                    );
                });
```

I hope someone can explain to me what concept I am missing here and how it comes that once a handler is registered for a specific type, it will be handled automatically by the generic handler.

Thanks

**Comment by lilasquared** [comment]
What you have here isn’t a generic notification handler. You have a notification handler that is typed to `INotification`. I can’t give you an explanation as to why it works once you add a second explicit handler, but in order to get it to work generally I believe you just need to make it actually generic

```
public class EventLogHandler<TNotification> : INotificationHandler<TNotification>
    {
        public Task Handle(TNotification notification, CancellationToken cancellationToken)
        {
            Debug.WriteLine($"Received notification ${notification} in eventLogHandler");
            return Task.CompletedTask;
        }
    }
```

Keep in mind that if you need a generic handler with specific constraints that is not supported with the built in aspnet core DI unless you are running the 5.0 preview.

**Comment by michaelboke** [comment]
I see I just choose a bit of the wrong words here (Generics or general). I agree this is not a generic handler. I should have said that I created a Notification handler that (should) catch-all notifications that implement the `INotification` interface. 

Thanks.

**Comment by maulik-modi** [comment]
@michaelboke , would you please request closure of the issue?

**Comment by michaelboke** [comment]
@maulik-modi although my question is not answered, I would love to close it as I have the workaround as also posted in my question
