### ISSUE TITLE
Notification handler causing autofac singleton class to get resolved twice

### ISSUE THREAD

**Issue by fbd-ss** [jbogard/MediatR#588]
Hi Jimmy,
Im using your MediatR and Autofac in a Xamarin project.  I have a class that is registered with autofac as single instance, and it has always been resolved as a singleton, until i included a notification handler in it.

The class was defined as MyClass : IMyClass { }
then with the handler it became MyClass : IMyClass, INotificationHandler<notification>{ }

from that point on it has been getting resolved twice by Autofac, once from the container and then from somewhere else, from what it seems it getting resolved again just before the handler is invoked.

I have set using the mediatR extension to scan the assemblies, ie builder.AddMediatR( typeof( xassembly ) ).

Have you come across something like this before?

Regards Steve.

**Comment by lilasquared** [comment]
Mediator handlers are always registered as transient. They should not be coupled with singleton classes. If you need to share functionality between a singleton and the handlers a dependency of both should encapsulate that functionality

**Comment by gmkado** [comment]
Sorry to resurrect this @lilasquared, but wouldn't that solution require exposing functionality from the singleton class that could otherwise be private?

```cs
public class MySingleton:INotificationHandler<MyNotification>
{
    private readonly int _privateState;
    public Task Handle(MyNotification notification)
   {
        _privateState = notification.State;
        return Task.CompletedTask;
    }
}
```
Are you suggesting doing this instead?

```cs
public class MyHandler:INotificationHandler<MyNotification>
{
    private readonly MySingleton _singleton;
    public MyHandler(MySingleton singleton)
    {
        _singleton = singleton;
    }

    public Task Handle(MyNotification notification)
   {
        _singleton.State = notification.State;  // <-- Now needs to be  accessible
        return Task.CompletedTask;
    }
}
```

**Comment by gmkado** [comment]
FWIW I stumbed across this package:  https://github.com/KuraiAndras/MediatR.Courier
Which seems to do what `SharedSingletonDependency` above does
