### ISSUE TITLE
send heavy task command in fire and forget mode

### ISSUE THREAD

**Issue by freetison** [jbogard/MediatR#589]
To avoid nested command chain I´m trying  to send command sequentially

var order = await Mediator.Send(orderCommand);
await Mediator.Publish(new OrderPlacedEvent(order));

// Now  create contract  command  (heavy task) depend on order response
//.. some mapper
 var contract = await Mediator.Send(createContractPublicCommand;
**await** Mediator.Publish(new ContratCreatedEvent(contract));

is there some strategy to send the second command in fire and forget mode in order to response only the order as soon as possible? ...

**Comment by MPapst** [comment]
You simply should not await the call. That will have it running in background.

**Comment by sk-shahnawaz** [comment]
@MPapst, can it also be done by using `await Task.Yield();` as the first statement inside the notification handler? because not awaiting inside an async method just invites compiler warning.

**Comment by MPapst** [comment]
That has been 4 years ago.

Have a look into the documentation, there are new possibilities involving Custom Notification Publishers.
