### ISSUE TITLE
CoreCLR

### ISSUE THREAD

**Issue by jchannon** [jbogard/MediatR#59]
Is this supposed to work on coreclr? I've tried to get it to build but no joy :cry:

**Comment by jbogard** [comment]
The project or something using MediatR? I need to get MediatR targeting dotnet5.1, but "dotnet" should work (allegedly)

**Comment by jchannon** [comment]
Sorry, I meant MediatR :smile: 

With the dotnet moniker does that need the new dotnet/cli tools?
