### ISSUE TITLE
Dependency Injection failure with handlers for both INotificationHandler<T> and INotificationHandler<InterfaceT>

### ISSUE THREAD

**Issue by LewisDean** [jbogard/MediatR#591]
I've run into an issue with an azure function app solution using the default DI framework in Microsoft.Extensions.DependencyInjection.

This issue occurs when having an `INotificationHandler<TDomainEvent>` (TDomainEvent implements IDomainEvent) and an `INotificationHandler<IDomainEvent>` in the same solution.

This causes a dependency injection exception to be thrown:
` A host error has occurred during startup operation 'b23181d7-f9e5-4590-bf53-69ad632bfeb1'.
[2020-12-01T10:04:59.365Z] Microsoft.Azure.WebJobs.Script.WebHost: Registering implementation type Domain.DoSomethingElseBecauseISomethingHappenedDomainEventHandler is not assignable to service type MediatR.INotificationHandler<Domain.SomethingHappenedDomainEvent>.`

The intention in our actual project is to have TDomainEvent1, TDomainEvent2, TDomainEvent3 all implement IDomainEvent, so we can have handlers of the concrete types for specific behaviour, and a handler for the interface for generic behaviour.

I've created an example project to demonstrate this issue which can be found here: https://github.com/LewisDean/MediatorOrDependencyInjectionIssueDemo

Error occurs on startup.

**Comment by jbogard** [comment]
FYI, you can reference the 5.0 version of the DI package and it should start working.

**Comment by LewisDean** [comment]
Thank you for the responses! Appreciate your help @lilasquared, @jbogard
