### ISSUE TITLE
[Exception] - Method not found  MediatR.IMediator.Publish(!!0, System.Threading.CancellationToken)

### ISSUE THREAD

**Issue by damikun** [jbogard/MediatR#594]
After update to last release I'm getting following exception..

- It happened only with debugger attached under VS-Code debugger..
- If i run app as `release ` or using `dotnet run`, **all works**

Exception:

The place where it happened is standard notification push... fired on UserRefreshed under _OnValidatePrincipal..._

```
await _mediator.Publish(new UserRefreshedNotifi() { UserID = parsed_user_id },cancellationToken);
```

```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task MediatR.IMediator.Publish(!!0, System.Threading.CancellationToken)'.
   at Aplication.Services.UserAutenticateService.Refresh(String current_access_token, String current_refresh_token, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Aplication.Services.UserAutenticateService.Refresh(String current_access_token, String current_refresh_token, CancellationToken cancellationToken)
   at WebApi.ServiceExtension.OnValidatePrincipal(CookieValidatePrincipalContext context) in 

```

![image](https://user-images.githubusercontent.com/54806834/101778953-e39bc580-3af4-11eb-8fe7-93f9e23d40fe.png)

**Comment by dheerajawale** [comment]
Is there any solution for this ?

**Comment by damikun** [comment]
@jbogard  Any idea what fire this exception on debug mode ?

**Comment by aKzenT** [comment]
I have the same problem. Did you find any solution?

**Comment by samon11** [comment]
May not work for everyone but in my case this error cleared when I manually installed the MediatR package
`dotnet add package MediatR `

**Comment by laimis** [comment]
It started happening to me as well and after some digging the cause appears to be referencing different versions of the library in the same solution. I had one project referencing version 9 and another project referencing version 8. Updating it to the same version everywhere took care of the issue.

**Comment by ammard2u** [comment]
got it, just need to ensure all the projects using it, installed the package as well 👍👍
