### ISSUE TITLE
Nested IRequest leads to InvalidCastException

### ISSUE THREAD

**Issue by v-echo** [jbogard/MediatR#595]
Scenario:
I have a base IRequest that works on its own, structured like this:
```csharp
public class SearchQuery : IRequest<IElasticResponse<IPagedCollection<IElasticSearchResult>>>
{
    // properties
}
public class SearchQueryHandler : IRequestHandler<SearchQuery, IElasticResponse<IPagedCollection<IElasticSearchResult>>>
{
    // handle logic
}
```

I need to re-use this same query in another one, and would have preferred to avoid duplicating its properties and internal logic.
Therefore I created the following:
```csharp
public class SearchAsMatchQuery : SearchQuery, IRequest<MatchResult>
{
}
public class SearchAsMatchQueryHandler : IRequestHandler<SearchAsMatchQuery, MatchResult>
{
    IMediator Mediator { get; }

    public SearchAsMatchQueryHandler(IMediator mediator//,...)
    {
        Mediator = mediator;
        //...
    }

    public async Task<MatchResult> Handle(SearchAsMatchQuery request, CancellationToken token)
    {
        var search = await Mediator.Send<IElasticResponse<IPagedCollection<IElasticSearchResult>>>(request, token);
        // handle logic
    }
}
```

The initial call is:
```csharp
await mediator.Send<MatchResult>(query)
```
which correctly leads to the top-level IRequestHandler, but that's when things start to break.

The exception I'm getting is [using source link]:
![mediator_err](https://user-images.githubusercontent.com/6671776/101903444-9717bf00-3bb4-11eb-997c-c89809e9211c.PNG)

It triggers on this line in the above handler: 
```csharp
var search = await Mediator.Send<IElasticResponse<IPagedCollection<IElasticSearchResult>>>(request, token);
```

According my knowledge, it should be able to cast it. Is this kind of scenario unsupported?

Edit: Forgot to mention, this was on the latest version of MediatR (9.0).

**Comment by lilasquared** [comment]
Generally is it not recommended to use nested requests, due to duplication of the pipeline behavior logic and the unexpected side effects of that. Mediator is designed to be used as top level actions and the IMediator shouldn’t be injected into a handler.

With that being said the reason you are getting this exception is because Mediator is using the IRequest<MatchResult> as the interface for the query you are sending, which doesn’t align with the return type you have provided to Send. I believe if you cast your derived class to its base then you should get the desired behavior.  You also shouldn’t have to provide the return type to send, which is a red flag that something is wrong.

**Comment by v-echo** [comment]
Casting doesn't really change the internal type. I have the following: 
```csharp
var search = await Mediator.Send((SearchQuery)request, token);
```
However still get the exception, and its message implies that it still considers it a IRequest<MatchResult>.
The reason I had the return type was to differentiate between the 2 different type resolutions for .Send.

**Comment by lilasquared** [comment]
Ah alright it was worth a shot. In that case then what I would do is create an abstract base class that has all the properties, and inherit from that for both requests with the interface and return type being only on the derived classes. But keep in mind that the recommended approach to sharing functionality across handlers is to create a shared dependency that encapsulates the logic.

**Comment by v-echo** [comment]
Yes. that would work, and it's probably what I'm going to do. I'm just curious is this is considered a bug or working as intended.
For now, I'll leave it to @jbogard to close at his discretion.

**Comment by remcoros** [comment]
Mediator does a "request.GetType()" on the request object, so it always ends up resolving the handler using the most concrete request type.

Casting the request parameter of 'Send' to a base type doesn't do anything, as the 'actual' type of the request is used.

In general, only use inheritance for behavior overloading, not for the sake of data, or saving a few keystrokes. Favor composition over inheritance like @lilasquared describes.

**Comment by lilasquared** [comment]
Jimmy also gives the same advice here #270

**Comment by jbogard** [comment]
There are some times where inheritance is OK, but the key here is your base object cannot be another request with another *concrete* handler. Instead, you can use some abstract/generic constraint goodness to ensure your base request and handler are never considered to be candidates for concrete request/response/handler resolution.

First, declare your "base" request abstract with generic constraints:

```csharp
public abstract class SearchQuery<TResponse>
    : IRequest<IElasticResponse<IPagedCollection<TResponse>>>
    where TResponse : IElasticSearchResult
{
    // Common junk here
}
```

And next, figure out how you want to compose your handler behavior but make this one abstract with generic constraints, too:

```csharp
public abstract class SearchQueryHandler<TRequest, TResponse>
    : IRequestHandler<TRequest, IElasticResponse<IPagedCollection<TResponse>>>
    where TRequest : SearchQuery<TResponse> 
    where TResponse : IElasticSearchResult
{
    // handle logic
    public async Task<IElasticResponse<IPagedCollection<TResponse>>> Handle(
        TRequest request, 
        CancellationToken cancellationToken)
    {
        // do normal logic with response
        
        // var response = FunTimes(request);

        // now that we have a response, call the abstract method
        await HandleCore(request, response);

        return response;
    }

    protected abstract Task HandleCore(
        TRequest request, 
        IElasticResponse<IPagedCollection<TResponse>> response);
}
```

Now you've provided a seam for concrete implementations to add their little bit of spice to the mix here. How you design the main `Handle` method and `HandleCore` is up to your specific logic. This handler will NEVER be resolved. Instead, we'll have our concrete implementation:

```csharp
public class SearchAsMatchQuery : SearchQuery<MatchResult>
{
    // More junk
}

public class MatchResult : IElasticSearchResult
{
}

public class SearchAsMatchQueryHandler 
    : SearchQueryHandler<SearchAsMatchQuery, MatchResult>
{
    protected override Task HandleCore(
        SearchAsMatchQuery request, 
        IElasticResponse<IPagedCollection<MatchResult>> response)
    {
        // do whatever extra junk

        return Task.CompletedTask;
    }
}
```

The generic constraints mean in the abstract class we get access to all of those members. Then in the concrete implementation you get the extra members. The constraints also mean you can't accidentally use the wrong request/response pairs, nor will MediatR/the container ever be able to resolve the base handler (nor will it be registered in the container).

**Comment by v-echo** [comment]
I appreciate the code snippets, thank you. Indeed, this approach looks pretty good. It might be worth adding it as an optional pattern to the official documentation.

Since I have a resolution, I'm closing this issue.
