### ISSUE TITLE
About Notification

### ISSUE THREAD

**Issue by jt4000** [jbogard/MediatR#596]
Hello,
What is the main purpose to use notification instead of using Iquery and Command??
Do you have a concrete example of using notification in your application?

Thank you!

**Comment by lilasquared** [comment]
INotifications can have many handlers where IRequests must be 1:1. This allows you to add features to an application when an event occurs by simply adding another notification handler. An example I have used is when a user registers. At the end of the creation process for the user publish a UserCreated notification. Now any side effects you want to happen after that can be done in notification handlers. Each with their own single responsibility. Maybe sending an confirmation email, posting a message to the users messages welcoming them, etc.
