### ISSUE TITLE
Better Error Handling On Failed DI

### ISSUE THREAD

**Issue by ehennis** [jbogard/MediatR#599]
I have a system that is referencing a nuget package. One of those classes threw an exception in the constructor and MediatR suppressed it and gave the generic error handler message.

Is there a way to bubble that up or at least write out the exception to the debug log?

To recreate:
public class1{
  public class1(SomeClass cls){}
}

public SomeClass{
  public SomeClass(){
    throw new Exception("Show Me");
  }
}

**Comment by remcoros** [comment]
You can inspect the InnerException property, it contains the original exception that was thrown from the DI container.

**Comment by ehennis** [comment]
How do you get access to it? I am debugging but my code isn't calling the
constructor it is generated through DI. I have a try/catch around the Send.

This is my first project with MediatR so I am sure I could be missing
something.

**Comment by mxmissile** [comment]
If I understand correctly, you can do something like this:

```
try
{
  var result = await _mediator.Send(query);
}
catch (Exception ex)
{
  //  ex.InnerException should be your Exception("Show Me")
}
```

**Comment by ehennis** [comment]
I do that but it just says that the class couldn't be created. It is a
general error message. Also, the error happens in the constructor and that
is outside my code.

**Comment by remcoros** [comment]
What are the error and stacktraces you get?

**Comment by ehennis** [comment]
Nothing. That is the problem. Because the exception happens during the
constructor it just prints the default error to the window. You can't catch
it because DI is used to created the object.

**Comment by remcoros** [comment]
Catch the exception like @mxmissile shows and print out the InnerException (using ToString for example)

**Comment by ehennis** [comment]
That doesn't work because the exception is in the constructor and not the
Send method.

**Comment by remcoros** [comment]
The constructor of what? Your handler? Then you cán capture it from the send method, since that method will find the correct handler trough DI.

Just debug and break on wherever you get the error in your app and inspect the exception, inner exception and stacktrace and paste it here

**Comment by ehennis** [comment]
So, the actual issue that caused my bug was that an internal nuget package
contained a library that required an appsettings setting. I didn't have it
so it threw an exception but Mediatr suppressed it and I couldn't find the
bug. The only way I found it out was finding the actual source code and
stepping through it.

**Comment by ehennis** [comment]
After the holidays I will get a small application spun up that shows my
issue. Really, I just wanted a way to see the root issue in my code get
displayed some place.

**Comment by remcoros** [comment]
If you can, please do. I may have an idea to improve this and (looking at previous issues) this is something others have struggled with as well. Especially in more complex DI scenarios.

**Comment by ehennis** [comment]
Honestly, I don't know either because you don't always want to bubble up
errors all the way to the UI.

**Comment by remcoros** [comment]
```csharp
        [Fact]
        public async Task What_is_in_the_stacktrace()
        {
            var serviceFactory = new ServiceFactory(type =>
                typeof(IEnumerable).IsAssignableFrom(type)
                    ? Array.CreateInstance(type.GetGenericArguments().First(), 0)
                    : throw new ArgumentException("some error while constructing object graph"));

            var mediator = new Mediator(serviceFactory);

            try
            {
                await mediator.Send(new Ping());
            }
            catch (Exception ex)
            {
                _output.WriteLine(ex.ToString());
            }
        }
```

prints:

```
System.InvalidOperationException: Error constructing handler for request of type MediatR.IRequestHandler`2[MediatR.Tests.ServiceFactoryTests+Ping,MediatR.Tests.ServiceFactoryTests+Pong]. Register your handlers with the container. See the samples in GitHub for examples. 
---> System.ArgumentException: some error while constructing object graph
   at MediatR.Tests.ServiceFactoryTests.<>c.<What_is_in_the_stacktrace>b__5_0(Type type) in C:\Projects\MediatR\test\MediatR.Tests\ServiceFactoryTests.cs:line 51
   at MediatR.ServiceFactoryExtensions.GetInstance[T](ServiceFactory factory) in C:\Projects\MediatR\src\MediatR\ServiceFactory.cs:line 16
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory) in C:\Projects\MediatR\src\MediatR\Internal\RequestHandlerWrapper.cs:line 20
   --- End of inner exception stack trace ---
   at MediatR.Internal.RequestHandlerBase.GetHandler[THandler](ServiceFactory factory) in C:\Projects\MediatR\src\MediatR\Internal\RequestHandlerWrapper.cs:line 24
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler|0() in C:\Projects\MediatR\src\MediatR\Internal\RequestHandlerWrapper.cs:line 62
   at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory) in C:\Projects\MediatR\src\MediatR\Internal\RequestHandlerWrapper.cs:line 64
   at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken) in C:\Projects\MediatR\src\MediatR\Mediator.cs:line 41
   at MediatR.Tests.ServiceFactoryTests.<What_is_in_the_stacktrace>d__5.MoveNext() in C:\Projects\MediatR\test\MediatR.Tests\ServiceFactoryTests.cs:line 59
```

This clearly shows "System.ArgumentException: some error while constructing object graph" (my own error thrown from within ServiceFactory, which simulates an exception from DI).

So I'm really unsure what's up with your code.

Did you miss an 'await' before Send (in case the exception never bubbles up, hence is never caught by a catch?)

**Comment by ehennis** [comment]
I will have to check my code when I get back to work on Monday. I wonder if
I am doing something that is suppressing the inner exception of ignoring it
because I don't get that exception text.

**Comment by ke4vtw** [comment]
Exceptions in constructors are a royal pain in .NET. The best solution I've found when I've encountered problems like this is to add a temporary try...catch block around the contents of the offending constructor and then *set a breakpoint in the catch*. 

Debug the code, and when you hit the breakpoint, examine the exception there.
