### ISSUE TITLE
[Question] : Separate Pipelines

### ISSUE THREAD

**Issue by mayoatte** [jbogard/MediatR#604]
Thanks for all the great work on Mediatr.

Is there a way to create multiple, separate mediatr pipelines? I am building a ddd modular monolith and i was thinking of using a separate pipeline for domain and integration events. This would allow me to have completely different behaviors and also enforce the difference between the two long term (e.g. swapping out the integration pipeline for a message queue).

Thoughts?

**Comment by jbogard** [comment]
Pipelines don't apply to notifications, only requests.

**Comment by mayoatte** [comment]
Thanks for the quick response. That's my bad on the pipelines (i'm new to Mediatr). In any case, is there a way to restrict usage of notifications to certain subsets of handlers? I am building a ddd style modular monolith and don't have a good feel for how to delineate uses of Mediatr within a bounded context and across bounded contexts.

**Comment by jbogard** [comment]
I mean, not really, the constraining is really the design of the notification itself. Don't let other BCs reference other BCs notifications and they won't be able to write handlers for them

**Comment by mayoatte** [comment]
That makes sense. I think i tripped myself up when I tried to write an orchestration style saga which needed to issue commands to / read events from multiple bounded contexts  which led to references and the question "separation." Will rework.

Thanks for the fast and helpful resonses.
