### ISSUE TITLE
no await for response when send command issued

### ISSUE THREAD

**Issue by vlapenkov** [jbogard/MediatR#611]
I need to send command for ef dbContext to update records from asp.net core controller. But i don't need to wait when SaveChanges works.
Is it proper to call `mediator.Send(new UpdateMessageStatusesCommand { Id = 1 });` without await?
I see that controller returns result and then handler writes in console:
```
async Task<bool> IRequestHandler<UpdateMessageStatusesCommand, bool>.Handle(UpdateMessageStatusesCommand command, CancellationToken cancellationToken)
        {
            await Task.Delay(5000);
            Console.WriteLine("UpdateMessageStatusesCommandHandler: " + command.Id);
          using (var scope = _scopeFactory.CreateScope())
            {
                var dbContext = scope.ServiceProvider.GetRequiredService<MessagesDbContext>();
                var message = dbContext.Messages.First(p => p.Id == command.Id);
                message.IsRead = true;
                dbContext.SaveChanges();
            }
        }
```
and i need to create scope of dbContext as it's disposed. But record updated successfully.

**Comment by GabrielHSFerreira** [comment]
Hi @vlapenkov.
Can't you register your DbContext as lifestyle scoped and inject it on your handler(s)? Assuming that your handlers are application code, and not infrastructure, they should not have access to your DI Container.
About the await question: I advise you always await Task methods. I had seen cases where the components tree was disposed before the methods ended to run.

**Comment by KurogamiLight3303** [comment]
I recommend U to use a library like **HangFire** to Run the Task in the background
