### ISSUE TITLE
Create Command then Read Query

### ISSUE THREAD

**Issue by TDK1964** [jbogard/MediatR#612]
Hi,

Is it okay to call a create command and then the read to get the newly created record?
(I have some loosely coupled objects which require some additional mapping to get the related entities)
```
public async Task<IActionResult> Post([FromBody] Create.Command command)
{
    if (!ModelState.IsValid) return BadRequest(ModelState);
    var result = await _mediator.Send(command);
    return Ok(_mediator.Send(new GetById.Query {Id = result.Id}));
}
```

**Comment by GabrielHSFerreira** [comment]
I guess it have no problem since both calls are being made on your application entry point. What you should avoid is call Mediator.Send inside a Handler that responds to a previous Mediator.Send.

**Comment by johnfabian** [comment]
I agree this needs to be on the server side since it's poor design to have to make 2 web api calls for every insert or update since you want the new or updated item back in the UI. I think the examples need to be updated with the pattern above since you are sending a command up and expect the full object back.

**Comment by TDK1964** [comment]
Often the model returned to the UI is different than the model posted for create or update, especially if returning foreign key lookups is required. So I don’t consider this a poor design at all.

**Comment by johnfabian** [comment]
> Often the model returned to the UI is different than the model posted for create or update, especially if returning foreign key lookups is required. So I don’t consider this a poor design at all.

Well if calling insert item from say an angular application then getting back an id then turning around and calling GetById is doing 2 api calls so I would have an event, ItemCreated and put the item as in-processing and notify the client via signalr or web sockets. I don't really see crud applications needing CQRS. I see the repository pattern being better for those types of apps IMO or return Id from CreateCommand and Call another Command GetById but then all you are basically doing is the repository pattern. NserviceBus I've used and it worked for a workflow type application which worked really good but I don't think most apps need to use the Mediator pattern unless doing microservices and having a some type of real time connection to notify the client via notification.

**Comment by OculiViridi** [comment]
@TDK1964 
"RESTful-ly" speaking, a Controller method that creates an entity should return the created entity's Id. And also, the corresponding HTTP status response should be [201 Created](https://httpstatuses.com/201).
Why not changing the implementation of your `Create.Command`, to persist the entity and then return the corresponding Id? so, you can avoid the "ugly" 2 calls to Mediator.
