### ISSUE TITLE
How to inspect Commands in Pipeline Behaviour using Asp.Net 5

### ISSUE THREAD

**Issue by umar-ulabs** [jbogard/MediatR#615]
My commands return either CommandResult or CommandResult<T> from my command handlers. I have an Audit Pipeline Behaviour where I want to inspect the return types which will be either CommandResult or CommandResult<T>. 
The follow code works with the CommandResult

 ```
public class AuditPipelineBehaviour<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : IRequest<TResponse>, IRequest<CommandResult>
    { 
        public AuditPipelineBehaviour()
        {           
            
        }
        public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        { 
            var response = await next();
            
            if(response is CommandResult command)
            {
                
            }        
            return response;
        }
    }
```
I read somewhere constrained generic handlers where not supported before in built-in DI (I am using Autofac). How can I handle/capture/intercept both result types

**Comment by jbogard** [comment]
Actually they are supported in .NET 5! My PR was finally accepted.

**Comment by umar-ulabs** [comment]
Yey, and thank you MediatR. It make code flow the poetry.
