### ISSUE TITLE
source code syntax error

### ISSUE THREAD

**Issue by gaoyangcaiji** [jbogard/MediatR#616]
I want to read the  mediatR source code,but i can not build them.my dotnet runtime and sdk is 3.1.4.I don‘t know how to fix this.
thanks for your help.
![image](https://user-images.githubusercontent.com/26948255/108696641-ca73b400-753c-11eb-9a8f-9e7bbcfff806.png)

**Comment by jbogard** [comment]
You need to use VS 2019 and .NET 5.
