### ISSUE TITLE
Is there a way to centrally determine & log the impl classes which will handle notifications?

### ISSUE THREAD

**Issue by craigfowler** [jbogard/MediatR#621]
What I'm looking to do is to centralise logging for "when Mediatr sends a notification to a notification handler".  The information I want to be able to log is:
* Some information about the notification instance itself (it's type would be sufficient)
* Which notification handler classes that notification instance is being sent to (again, just their type names would be sufficient)

The kind of logging I am thinking of would likely be at TRACE level (or equivalent _highest level of verbosity_).  It would not be used in production, but would be enabled when trying to diagnose problems.  Essentially it'd be used to determine "Are notifications of type X being sent to all of the handlers I expected them to be?".  I'd like to be able to do that centrally within Mediatr instead of implementing (largely duplicated) logging throughout all of my handler classes.

## What I've looked into so far
I was reading [this example about creating centralised logging] for request handlers and I noted that immediately after it advises that you can't use this technique for notification handlers, only request/response handlers.

I also looked into [this example for subclassing the `Mediator` itself] and overriding `PublishCore`.  Rather than doing that to change the synchronicity of dispatching notifications, instead add logging as each notification is dispatched.  The issue I ran into there is that `PublishCore` only receives each notification as a `Func<INotification, CancellationToken, Task>`.  From some tinkering I can also tell that this delegate is not actually a reference to the original method on the actual notification handler implementation class.  [The `Target` and `Method` properties] of the delegate suggest that the delegate was created as a lambda somewhere else, because they point to a compiler-generated `xyz__DisplayClass__xyz` type.

[this example about creating centralised logging]: https://github.com/jbogard/MediatR/wiki/Behaviors
[this example for subclassing the `Mediator` itself]: https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.PublishStrategies/CustomMediator.cs
[The `Target` and `Method` properties]: https://docs.microsoft.com/en-us/dotnet/api/system.delegate?view=net-5.0#properties

## Is there a good way to do this at the moment?
So my question, really, is: "Is there a good way to achieve what I've described above?".  Perhaps something I have missed or didn't know to look for?

## If not, could there be?
I appreciate that it's reasonable for a notification handler _to only be a delegate_ and not necessarily an actual method of an instance of a type which implements the notification handler interface.  So, the method signature of `PublishCore` is understandable.  On the other hand, when the notification handler _really is a concrete method on a concrete class_ (which I imagine is the most common use-case), it would be quite helpful if the delegate really were a direct reference to that method and not a lambda.

That would enable me to write the desired logging logic by inspecting the `Target` and `Method` properties of that delegate, in order to determine where the code is going to go next.

**Comment by jbogard** [comment]
Have you thought of using a container that supports decorators? That's what folks did for the pipeline decorators before I made it a thing. You could decorate your notification handlers and do all that logging stuff.

**Comment by craigfowler** [comment]
That's a good answer _when I have control over the container implementation_.  Unfortunately I ran into this when working on something which is itself a container-neutral library.  So I can only count on having some kind of `IServiceProvider` and not a specific container.

I agree, that in an actual app I would have immediately used Autofac to slap a decorator on my notification handlers and accomplished it that way.
