### ISSUE TITLE
send notification in background queue cannot resolve scope

### ISSUE THREAD

**Issue by 7amou3** [jbogard/MediatR#622]
Hello there
Im sending notifications in [ background queue](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#queued-background-tasks) like this:
```
public async Task<someResult> Handle(AddUserCommand request, CancellationToken cancellationToken) 
{
...
// Queue notification task
_backgroundTaskQueue.QueueBackgroundWorkItem((cancellationToken) => _mediator.Publish(new UserCreatedNotification(User)));

}
```
In the notification handler, I resolve my scoped services like:
```
public async Task Handle(UserNotification request, CancellationToken cancellationToken)
{
            using (IServiceScope scope = _serviceProvider.CreateScope())
            {
                IUnitOfWork unitOfWork = scope.ServiceProvider.GetService<IUnitOfWork>();
                ....
             }
}
```
But sometimes the DI framework can not create the scope, and generate exception of type:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType 
...
``` 
this error is random, in most cases the scope is resolved but it fails let say 1/10, I don't know why
is sending notification in background a bad idea?
thanks

**Comment by elementh** [comment]
Are you directly injecting the IServiceProvider into the handler?

The correct way of doing this usually involves using [IServiceScopeFactory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.iservicescopefactory?view=dotnet-plat-ext-5.0). Let me give you an example:


```csharp
public class ExampleHandler : INotificationHandler<ExampleNotification>
{
    private readonly IServiceScopeFactory _scopeFactory;

    public ExampleHandler( IServiceScopeFactory scopeFactory)
    {
        _scopeFactory = scopeFactory;
    }

    public async Task Handle(ExampleNotification request, CancellationToken cancellationToken)
    {
        using var scope = _scopeFactory.CreateScope();

        var uow = scope.ServiceProvider.GetRequiredService<IUnitOfWork>();
       
       //...
    }
}
```


Try this and if still fails, please upload an example project :)
