### ISSUE TITLE
Handling OAuth2 Token Introspection within Pipeline Behaviors

### ISSUE THREAD

**Issue by joemar12** [jbogard/MediatR#625]
the Web API I'm building can handle JWT Bearer and Reference Tokens but I want to move the authorization to MediatR Pipeline Behavior so the authorization is closer to the logic. Is there an existing way to handle reference tokens there, or shall I write it myself?

**Comment by elementh** [comment]
I think you'll have to handle that yourself. If I were to do something like that I may hook up a [IHttpContextAccessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-5.0) on the pipeline and let aspnet core handle all the hard logic of auth itself. 

I'll also try to have that pipeline behavior defined in the api layer or a common project to not populate domain with unnecessary aspnet core classes and abstractions.

**Comment by joemar12** [comment]
thanks for the response @elementh... that is kind of what I came up with, through an IHttpContextAccessor. And yes it's true that the application layer gets a bunch of references to aspnet core classes (I felt that's kind of hacky but it works haha) so I may have to try your suggestion regarding that. Anyway, I'll close this issue now.
