### ISSUE TITLE
Ordered behaviours with MS.Ex.DI

### ISSUE THREAD

**Issue by andyblack19** [jbogard/MediatR#629]
The wiki page [Container Feature Support](https://github.com/jbogard/MediatR/wiki/Container-Feature-Support) suggests that ordered behaviours are _not supported_ with ASP.NET Core DI.

As I need ordered behaviour execution I thought I'd give it a quick test in an Azure Functions app `netcoreapp3.1`. This showed that the behaviours were executed in the expected order that I registered them in. (B,A,C, in the repro below).

Digging a little, I noticed the pipeline behaviour instances are [fetched from the ServiceFactory](https://github.com/jbogard/MediatR/blob/master/src/MediatR/Wrappers/RequestHandlerWrapper.cs#L55), which [resolves them](https://github.com/jbogard/MediatR/blob/master/src/MediatR/ServiceFactory.cs#L19) as an `IEnumerable<T>`.

With the [MS DI docs](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection) quoting: "Services appear in the order they were registered when resolved via IEnumerable<{SERVICE}>", does this get the green tick now? Or am I missing something about Ordered Behaviours?

Repro:
```
public class Startup : IWebJobsStartup
{
    public void Configure(IWebJobsBuilder builder)
    {
        builder.Services.AddMediatR(Assembly.GetExecutingAssembly());
        builder.Services.AddTransient(typeof(IPipelineBehavior<,>), typeof(BehaviourB<,>));
        builder.Services.AddTransient(typeof(IPipelineBehavior<,>), typeof(BehaviourA<,>)); 
        builder.Services.AddTransient(typeof(IPipelineBehavior<,>), typeof(BehaviourC<,>));
    }
}

public class BehaviourA<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
{
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next) => await next();
}

public class BehaviourB<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
{
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next) => await next();
}

public class BehaviourC<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
{
    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next) => await next();
}

public class Function
{
    private readonly IMediator _mediator;

    public Function(IMediator mediator) => _mediator = mediator;

    [FunctionName("Test")]
    public async Task<string> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "Test")] object req)
        => await _mediator.Send(new TestRequest());
}

public class TestRequest : IRequest<string> {}

public class TestRequestHandler : IRequestHandler<TestRequest, string>
{
    public Task<string> Handle(TestRequest request, CancellationToken cancellationToken)
        => Task.FromResult("ok");
}
```

**Comment by elementh** [comment]
Never thought this was an issue, I've always arranged them in the way I wanted and they stay ordered; and that is still true since I moved over to [@JasperFx/lamar](Jhttps://github.com/JasperFx/lamar).

**Comment by jbogard** [comment]
Fixed! I just checked the latest build output that runs these checks. I should automate the whole output I guess...
