### ISSUE TITLE
Mediatr Validation Pipline when using with views?

### ISSUE THREAD

**Issue by aloksharma1** [jbogard/MediatR#630]
Hello,
i have an application which uses both views and apicontrollers, as long its api response i am ok with validation pipeline to return json results. but in case of views which require back modelstate and all to show validation errors (using with fluent validator) i am unable to find a good use case. so i am wondering:

1. if its not suitable with views [with model state validation pipeline]
2. or do i need to change my approach and put model validation somewhere else instead of pipeline in case of working with views.

asking this here because i am unable to find any good examples with razor views, almost all the examples and sample codes i found were related to API and CQRS.

**Comment by elementh** [comment]
As everything while coding, it's a matter of trade-offs, you can totally populate the modelstate with fluent validation errors if you want and I guess that will solve your problem, but it will require some work (not much tho, I remember doing that before).

Personally I think using validation inside a pipeline is something you have to really think about. validation on requests should be fail-fast when possible, in my case I use FluentValidation to hook on the validation pipeline of aspnet core and do some static validations there, then if everything is fine I'll launch the request and have heavy validation (like finding duplicates) directly on the pipeline.
