### ISSUE TITLE
Can I use your Logo for a Visual Studio integration project?

### ISSUE THREAD

**Issue by nils-a** [jbogard/MediatR#648]
I'm currently working on an integration for Visual Studio.

The main feature I was thinking about was "Find Handlers" to be used on Notification and Requests. As an easy start into the topic I began by showing a tool window that currently simply lists all Notifications, Requests and Handlers..

I was wondering whether it would be ok if used some variant of your logo as the logo for the project and vsix?

**Comment by jbogard** [comment]
Sure, no problem
On 7/4/2021 7:50:06 AM, Nils Andresen ***@***.***> wrote:
I'm currently working on an integration for Visual Studio.
The main feature I was thinking about was "Find Handlers" to be used on Notification and Requests. As an easy start into the topic I began by showing a tool window that currently simply lists all Notifications, Requests and Handlers..
I was wondering whether it would be ok if used some variant of your logo as the logo for the project and vsix?

**Comment by nils-a** [comment]
Thanks!

For anyone interested, the latest build version is available at https://www.vsixgallery.com/extension/3a8c8d1d-7dd3-43ff-ac42-df24457b78fd 
Currently it "only" lists all Notifications, Requests and Handlers in a dedicated tool window but there's more to come.
