### ISSUE TITLE
How to fit MediatR into a Modular Monolith?

### ISSUE THREAD

**Issue by codefactorydevelopment** [jbogard/MediatR#661]
We're starting with a new project and we've decided to build it as a modular monolith.

Since we want to use MediatR in some of our modules (probably most, but not in all) we're looking in different ways of setting it up having on mind module encapsulation in particular.

In particular, is there a way that each module sets up its own handlers/queries registration through service? Something like:

```
public static class ServiceCollectionExtensions
  {
    public static IServiceCollection AddModuleAApplicationInfrastructure(this IServiceCollection services, IConfiguration config)
    {
      services.AddMediatR(thisModuleAssembly);
      return services;
    }
  }
```

Would multiple calls to `AddMediatR()` from each module cause some trouble, duplicates, etc?

Reason for this is to keep registrations as close to handlers as possible.

**Comment by remcoros** [comment]
You can call AddMediatR() multiple times with different assemblies.

The base services (like IMedatior) are only added once.

Note that if you use the overload with the configure options delegate, the last one wins.

**Comment by andre-wells** [comment]
@codefactorydevelopment , I've had no trouble using multiple `AddMediatR()` calls for different modules.

Assuming modules are defined in `Application` and `Infrastructure` class libraries:

Define an empty class in the namespace (it's only purpose is to serve MediatR dependency injection)
```c#
namespace MyNameSpace.ModuleOne.Application
{
    public class ModuleOneApplicationAssembly { }
}
```

In the host application (WebApi, CLI etc) reference the `Application` and setup Dependency Injection for `Infrastructure`.
Setup `IServiceCollection` extensions to make adding modules clean and easy to maintain:

```c#
    // Dedicated extension to setup Application and Infrastructure
    public static class ModuleOneModuleExtension
    {
        public static IServiceCollection AddModuleOneModule(this IServiceCollection services)
        {
            services.ConfigureModuleOneInfrastructure(); // Extension method defined in Infrastructure Class Lib
            services.AddMediatR(typeof(ModuleOneApplicationAssembly ).GetTypeInfo().Assembly);

            return services;
        }
    }
```

```c#
    public static class ModulesExtension
    {
        public static IServiceCollection AddModules(this IServiceCollection services)
        {
            services.AddModuleOne();
            services.AddModuleTwo();
            services.AddModuleThree();
            return services;
        }
    }
```

Then `Startup.ConfigureServices()` just has a single line of `services.AddModules()`.

**Comment by FrankAlberto** [comment]
@codefactorydevelopment I've doing that way until I need a IRequestPostProcessor to notify/log each handler execution, because this makes a PostProcessor triggers fore each `services.AddMediatR` call.
