### ISSUE TITLE
Sync methods

### ISSUE THREAD

**Issue by petrkasnal** [jbogard/MediatR#662]
Hello, is it possible to add sync method to mediatr? I don't want use only async method... Thank you very much

**Comment by andre-wells** [comment]
Do you have a specific scenario in mind?  Most of my calls make use of `async` routines and the _small_ handful that cannot I return `Task.CompletedTask` or `Task.FromResult(_result)`.

**Comment by jbogard** [comment]
Supporting both sync and async pipelines was a...nightmare to say the least. I made it sync-only because behavior pipelines for both sync and async is impossible to maintain from both a library and consumer perspective. So the compromise is creating handlers with abstract sync methods 🤷‍♂️
