### ISSUE TITLE
Passing string parameter using Mediatr

### ISSUE THREAD

**Issue by smartaquarius10** [jbogard/MediatR#666]
Team,

I am a pretty beginner with Mediatr and have situation where I need to send a json string to handler for blindly upload that to a storage.

I have read the wiki and found that with Mediatr we need to send an IRequest. Now, for sending the request we have to pass the request in the form of a class object to the Handler. But in my case I just have to send the string request without any update so making objects of classes, deserializing, unboxing etc. will be an extra effort. 

Could you please suggest any possible solution to handle this situation. 

Thank you

**Comment by andre-wells** [comment]
@smartaquarius10, a request needs to map to a handler.  We handle scenarios like this with a dedicated `IRequest` object:

```c#
    public class MyJsonRequest: IRequest
    {
        public string JsonPayload { get; set; }
        //public Stream JsonPayloadStream { get; set; } My preferred way
    }

    public class MyJsonHandler: IRequestHandler<MyJsonRequest>
    {
        // Implementation here ...
    }
```

In this way you can can support different handles for different JSON content or streams. Would this not work for you?

**Comment by smartaquarius10** [comment]
@andre-wells , Thanks for sharing. But at least we have to include this part right
JsonConvert.Deserializeobject<MyJsonRequest>(body).

**Comment by andre-wells** [comment]
Yup, essentially reading the stream like

```c#
    var content = await responseMessage.Content.ReadAsStringAsync().ConfigureAwait(false);
    return JsonConvert.DeserializeObject<Out>(content);
```

But in Net6, you have an option of [deserializing directly from a stream](https://twitter.com/okyrylchuk/status/1450917428796473349), releasing this week.
