### ISSUE TITLE
RequestExceptionHandler does not work in case of class throwing exception by which is inheriting TRequest, TResponse and Exception 

### ISSUE THREAD

**Issue by Dheerajcode2016** [jbogard/MediatR#676]
Hello , 

Scenario 
I have 

- BaseQuery
- BaseDTO
- NotFoundException inheriting Exception

Now 

- GetItemByIdQuery inherits BaseQuery
- ItemDTO inherits BaseDTO

i have implemented the Exception Handler  while inheriting IRequestExceptionHandler<BaseQuery,BaseResponse<BaseDTO>,NotFoundException>

but when i throw exception "NotFoundException" then its not caught by this handler 

same time if i use derived class like 
IRequestExceptionHandler<GetItemByIdQuery ,BaseResponse<ItemDTO >,NotFoundException>

it works , please help and if possible then update an example with same

**Comment by BGajda13** [comment]
Maybe try writing a constraint? RequestExceptionHandler<TRequest, TResponse, TException> :
where TRequest: BaseQuery
where TResponse: BaseResponse
where TException: NotFoundException

See Polimorphic dispatch in documentation

**Comment by Dheerajcode2016** [comment]
Will look at it later
