### ISSUE TITLE
Version 10 breaking changes

### ISSUE THREAD

**Issue by steveoh** [jbogard/MediatR#688]
It appeared the only breaking change was net 2.1 support. However when I just upgraded some pipeline behaviors stopped working with the following error

> The type 'TRequest' cannot be used as type parameter 'TRequest' in the generic type or method 'IPipelineBehavior<TRequest, TResponse>'. There is no boxing conversion or type parameter conversion from 'TRequest' to 'MediatR.IRequest<TResponse>'

Is this expected?

**Comment by jbogard** [comment]
Good call. This is an additional breaking change, I created a migration to help:

https://github.com/jbogard/MediatR/wiki/Migration-Guide-9.x-to-10.0

**Comment by steveoh** [comment]
Will you put that link in the release notes?

**Comment by jbogard** [comment]
Done! And I'll update the blog post too

**Comment by Sandeep7OnShell** [comment]
@jbogard 
Getting below errors after upgrade to MediatR 10.0.1

1. Reference to type 'IBaseRequest' claims it is defined in 'MediatR', but it could not be found
2. Reference to type 'IRequest<>' claims it is defined in 'MediatR', but it could not be found
3. Reference to type 'IRequest' claims it is defined in 'MediatR', but it could not be found

Any clues?

**Comment by erica-teixeira** [comment]
no answers on this??

**Comment by khellang** [comment]
> no answers on this??

@erica-teixeira You're commenting on an issue that was resolved 3 years ago 😅

**Comment by erica-teixeira** [comment]
True but I was commenting on the last post that was never answered. My issue was that we had another custom package that had an older mediatR version and when trying to use v10.0.1 it was throwing this error:

Could not load type 'MediatR.IRequest 1' from assembly 'MediatR, Version=10.0.0.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'

I just updated the version in the custom package and it worked
