### ISSUE TITLE
v10 breaking change

### ISSUE THREAD

**Issue by jeparrish** [jbogard/MediatR#689]
With v10, this code now no longer works.  What needs to be adjusted?

```csharp
    public class CachingBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : ICacheableMediatrQuery
```

Where ICacheableMediatrQuery looks like this
```csharp
public interface ICacheableMediatrQuery
    {
        /// <summary />
        public string Foo{ get; set; }
        /// <summary />
        bool BypassCache { get; }
        /// <summary />
        string CacheKey { get; }
        /// <summary />
        TimeSpan? SlidingExpiration { get; }
    }
```

**Comment by jbogard** [comment]
See the migration guide:

https://github.com/jbogard/MediatR/wiki/Migration-Guide-9.x-to-10.0

**Comment by ardalis** [comment]
Could you put a "Breaking Changes in v10" or "Migration Guide" link prominently in the README?

**Comment by jbogard** [comment]
To all of them? There's multiple migration guides.

**Comment by ardalis** [comment]
I'd say either just the most recent one, or to a page that has all of them. Either would have saved me time a few minutes ago. Also for some reason your README doesn't appear (fully) on Nuget.org, which is where I first looked for a "Breaking Changes in this Version" link:

![image](https://user-images.githubusercontent.com/782127/148991213-d6e7b835-cc6e-4e35-93ac-b4aa20253661.png)

**Comment by Sandeep7OnShell** [comment]
@jbogard 
Getting below errors after upgrade to MediatR 10.0.1

1. Reference to type 'IBaseRequest' claims it is defined in 'MediatR', but it could not be found
2. Reference to type 'IRequest<>' claims it is defined in 'MediatR', but it could not be found
3. Reference to type 'IRequest' claims it is defined in 'MediatR', but it could not be found

Any clues on these?

**Comment by jbogard** [comment]
@Sandeep7OnShell Looks like the types that we moved to the MediatR.Contracts package, I've updated the upgrade guide accordingly: https://github.com/jbogard/MediatR/wiki/Migration-Guide-9.x-to-10.0

**Comment by Sandeep7OnShell** [comment]
@jbogard Using the new package and still getting the same errors.

**Comment by jbogard** [comment]
Can you open a new issue? It's not related to the one here.
