### ISSUE TITLE
Generic types with MediatR

### ISSUE THREAD

**Issue by dannyc02** [jbogard/MediatR#69]
Hi @jbogard ,

I was wondering if it's possible to extend this framework to handle generic types in requests?  Here's an example of what I was hoping to achieve:

`mediator.Send(new CreateItemCommand<ItemType>(item))`

`public class CreateItemCommand<TItemType> : IRequest<T> where T: ISomeInterface`

(Apologies if this isn't the correct place to ask this question.)

**Comment by jbogard** [comment]
That's possible today in MediatR, provides your handler factory knows how
to create it. StructureMap for example can do that.

**Comment by dannyc02** [comment]
Thanks for the speedy response @jbogard!

I've got this working by explicitly registering the <TItemType> in StructureMap, like so:

`For<IRequestHandler<CreateItemCommand<Ping>, Ping>>().Use<CreateItemCommandHandler<Ping>>();`

Is there a way to register this in StructureMap to handle all object types passed in? Something along these lines:

`For<IRequestHandler<CreateItemCommand<T>, T>>().Use<CreateItemCommandHandler<T>>();`

**Comment by khellang** [comment]
From 6 year younger @jbogard: [Advanced StructureMap: connecting implementations to open generic types](https://lostechies.com/jimmybogard/2009/12/18/advanced-structuremap-connecting-implementations-to-open-generic-types/) :wink:

**Comment by dannyc02** [comment]
@khellang I'd attempted to use that method from that article without much luck :(
The article only has one 'level' deep of generics, like this:

`public interface IHandler<TEvent> `

where what I'm trying to achieve is this:

`public interface IHandler<TEvent<TObjectType>> `

Here's a snippet of what I've got in a single test - any help would be greatly appreciated.

```
[Test]
        public void ShouldResolveGenericHandler()
        {
            var container = new Container(cfg =>
            {
                cfg.Scan(scanner =>
                {
                    scanner.TheCallingAssembly();
                    scanner.IncludeNamespaceContainingType<Ping>();
                    scanner.WithDefaultConventions();
                    scanner.AddAllTypesOf(typeof(IRequestHandler<,>));
                    scanner.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>));
                });
                cfg.For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
                cfg.For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));
                cfg.For<IMediator>().Use<Mediator>();
            });

            var mediator = container.GetInstance<IMediator>();

            var response = mediator.Send(new CreateItemCommand<Ping>());

            response.Message.Should().NotBeNull();
        }


        public class CreateItemCommand<T> : IRequest<T>
        {
            
        }

        public class CreateItemCommandHandler<T> : IRequestHandler<CreateItemCommand<T>, T>
        {
            public T Handle(CreateItemCommand<T> message)
            {
                return default(T);
            }
        }
```

When looking at WhatDoIHave() - I can see the IRequestHandler in there:

`IRequestHandler<CreateItemCommand<T>, T>     MediatR          Transient     CreateItemCommandHandler<T>                  (Default)`

However, when calling it,  I get the following error:
` ----> StructureMap.StructureMapConfigurationException : No default Instance is registered and cannot be automatically determined for type 'IRequestHandler<CreateItemCommand<Ping>, Ping>'`

Any ideas how to configure this with structuremap please @jbogard  @khellang?

**Comment by jbogard** [comment]
I think you'll have to ask the StructureMap people on this one. But likely
you'll need to create a custom type scanner.

**Comment by dannyc02** [comment]
Ok thanks @jbogard.

Will report back findings.

**Comment by jeremydmiller** [comment]
@dannyc02 See this http://structuremap.github.io/generics/ and this http://structuremap.github.io/registration/auto-registration-and-conventions/. I'd urge you to be cautious about doing this though. You could easily get into a situation where the team just isn't going to be able to unravel the very fancy generics auto-registrations.

**Comment by dannyc02** [comment]
@jeremydmiller thanks for the info, really helped.

I managed to get it working using a custom convention, gist here: https://gist.github.com/dannyc02/6d42b90154d8478dc6fd

**Comment by marcels2204** [comment]
How to configure autofac to achieve this?
