### ISSUE TITLE
version 10 breaking change

### ISSUE THREAD

**Issue by steveoh** [jbogard/MediatR#690]
Do you have any idea why this package is [throwing](https://github.com/AustinDavies/MediatR.Behaviors.Authorization/issues/7)? 

I've browsed the [code](https://github.com/AustinDavies/MediatR.Behaviors.Authorization/blob/master/MediatR.Behaviors.Authorization/Extensions/DependencyInjection/AddMediatorAuthorizationExtension.cs) and nothing stands out based on your breaking changes doc.

Any help would be appreciated.

**Comment by jbogard** [comment]
`IRequest` is in a different package/assembly now, MediatR.Contracts

**Comment by steveoh** [comment]
Since that project is targeting 8 and those types exist in both places, does that require the 3rd party implementation to migration to 10 or what version where those types not in both assemblies?

**Comment by jbogard** [comment]
Yes, that's what's needed.
