### ISSUE TITLE
.NET48 no longer supported

### ISSUE THREAD

**Issue by Ericvf** [jbogard/MediatR#691]
Why has this support been dropped? We have been using this with our .NET48 solutions for several years but as of version 10 it is no longer possible to update / install the package.

> Could not install package 'MediatR 10.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jbogard** [comment]
You can continue to use v9 just fine. V10 includes support for `IAsyncEnumerable` which doesn't have much support in full .NET. Since I don't use .NET 4.x and haven't for many years, I decided to move on to the LTS releases of .NET Core.

**Comment by Ericvf** [comment]
Thanks for the response. I think this is a very unfortunate decision. .NET 48 isn't going away soon and many developers don't have the opportunity to use the newer versions yet. It would have been great to keep benefitting from future updates and the fact you don't support developers like that will influence future adoption of your library. We (my enterprise customer) have policies in place that ensure packages are maintained and up-to-date, unfortunately we have to move away from Mediatr now and that also means we have to do that in our .NET 5 and 6 apps. 

Thanks for all the work on Mediatr though, I have appreciated it in the past.

**Comment by jbogard** [comment]
Well, I do this for my customers first and I haven't had a paying customer that's used MediatR on .NET 4.x for many years now. If someone wants to pay me to support older frameworks, I'm happy to.

**Comment by Ericvf** [comment]
Interesting. What pricing model you have? Since I am not with legal I have not personally reviewed the license. I'd be happy to forward your pricing model that during our next architecture meeting where we discuss these types of things, especially if it makes you consider keeping support for net48! 

Thanks

**Comment by ardalis** [comment]
Maybe start with https://github.com/sponsors/jbogard and this link:
![image](https://user-images.githubusercontent.com/782127/148991705-1a99a5f6-dbba-4752-9b59-f6fdb1791c44.png)

**Comment by jbogard** [comment]
That would do it. Or we can work something else out.
