### ISSUE TITLE
Issues with MediatR 10.0 or did I implement incorrectly?

### ISSUE THREAD

**Issue by coderabsolute** [jbogard/MediatR#699]
I upgraded to MediatR 10 and the following code is broken and throwing me the following error. It made me think that all the while I have been using MediatR incorrectly or there is something else is wrong? I'm able to use MediatR 9.0 with no problems - it all works well. :) 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0311	The type 'ExpenseCategoryDeleteRequest' cannot be used as type parameter 'TRequest' in the generic type or method 'IPipelineBehavior<TRequest, TResponse>'. There is no implicit reference conversion from 'ExpenseCategoryDeleteRequest' to 'MediatR.IRequest<TResponse>'.	xxx.Api	C:\Test\MediatrPipelines\MastersMediatrPipeline.cs

My code as follows:

**ExpenseCategoryDeletePipeline**
```
public class ExpenseCategoryDeletePipeline<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : ExpenseCategoryDeleteRequest
        where TResponse : CommandResponse
    {
        public ExpenseCategoryDeletePipeline()
        {
        }

        public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            return await next();
        }
    }
```

**ExpenseCategoryDeleteRequest**
```
    public class ExpenseCategoryDeleteRequest : IRequest<CommandResponse>
    {
        public int ExpenseCategoryId { get; set; }
    }
```
**CommandResponse**
```
    public class CommandResponse
    {
        public string Success { get; private set; }
    }
```

The Registration is done at **MastersMediatrPipeline.cs**

`services.AddScoped(typeof(IPipelineBehavior<ExpenseCategoryDeleteRequest, TResponse>), typeof(ExpenseCategoryDeletePipeline<ExpenseCategoryDeleteRequest, TResponse>));`

**Comment by coderabsolute** [comment]
Looks like there are breaking changes mentioned here in the [Migration Guide](https://github.com/jbogard/MediatR/wiki/Migration-Guide-9.x-to-10.0) and refer to [this question](https://github.com/jbogard/MediatR/issues/689).

I have more than 200 pipelines that require a change on MediatR 10.0. Can I get a sample using my above code on how to implement this change correctly without breaking too many things?

**Comment by jbogard** [comment]
That part at the bottom should help? For open generics you need to add the additional constraint. Not sure why C# isn't smart enough to infer it.

**Comment by coderabsolute** [comment]
Awesome - that works.
