### ISSUE TITLE
Pipelines stop working after updating to MediatR 10.0 and .NET 6

### ISSUE THREAD

**Issue by ShevchukDenys** [jbogard/MediatR#701]
Hi! I have two pipelines behaviours: one with fluent validation and another with logging. So, after updating from MediatR 9.x to 10.0.1 I have faced the following issue: no validation or logging is triggered, in debugging it do not enter none of these classes. The changes I've done:
1) ![image](https://user-images.githubusercontent.com/44433382/152155092-1bbdeec1-6eba-4862-aac1-278b9b28bbca.png)
2) MediatR 9.0.0 => 10.0.1 & .net 5.0 => .net 6.0

**Comment by jbogard** [comment]
Try to isolate this in a test where you resolve from the container directly. The container package version changed too.

**Comment by ShevchukDenys** [comment]
It crashes with 'Sequence containes no elements' if I trying to get `IPipelineBehavior` or `FluentValidationBehhavior` directly from container, I suppose it means that this service isn't available in DI. As for container package I have updated it too, just forgot to mention.

**Comment by ShevchukDenys** [comment]
Also I have find out that it works if TResult is written explicitly, f.e.: 
![image](https://user-images.githubusercontent.com/44433382/152528974-363cd796-2b30-4261-a816-bf4dc8df11eb.png)

**Comment by claudioscatoli** [comment]
I confirm that, with versions >=10.0, IPipelineBehaviour implementations need the generic constraint added, as per ["Migration Guide 9.x to 10.0"](https://github.com/jbogard/MediatR/wiki/Migration-Guide-9.x-to-10.0)

E.g.

```cs
public class CanonicalLogLineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
{
    //...
}
```

becomes

```cs
public class CanonicalLogLineBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    //...
}
```

**Comment by teggno** [comment]
@rainerllera I've had the same problem. It could be solved with
```c#
class ValidationBehavior<TRequest, TResult> : IPipelineBehavior<TRequest, TResult>>
   where TRequest: IRequest<TResult>
```
(In this case, `TResult` corresponds to `Result<TResponse>` which doesn't appear in the code explicitly but it still works.)

**Comment by jbogard** [comment]
Looks like you'd need two constraints:

```csharp
public class CacheBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse> where TRequest : IRequest<TResponse>, ICachable
```

That compiles for me fine.

**Comment by wehnertb** [comment]
Thanks - that fixed it!

**Comment by plppp2001** [comment]
DO we need to add this where condition:    [where TRequest: IRequest<TResult>]

It's working for me without the where for me.
