### ISSUE TITLE
ServiceCollection problem after adding MediatR 10.0.1 to Net5 Console App

### ISSUE THREAD

**Issue by jantos1518** [jbogard/MediatR#708]
Updating a NET5 console app to utilize MediatR 10.0.1. After adding Mediator via Nuget Package Manager in VS2019, now getting compiler error that ServiceCollection exists in both 'Microsoft.Extensions.DependencyInjection.Abstractions, Version 6.0.0.0' and 'Microsoft.Extensions.DependencyInjection, Version 5.0.0.1'. I have not upgraded the app to NET6 at all. Is there an unknown Net6 dependency in MediatR 10.0.01?

**Comment by jantos1518** [comment]
I believe this may be a DI issue in MediatR.Extensions.Microsoft.DependencyInjection 10.0.1.

**Comment by jantos1518** [comment]
Just examined Nuget package dependencies, and it clearly states dependency on Microsoft.Extensions.DependencyInjection.Abstractions >= 6.0.0. Issue closed.

**Comment by remcoros** [comment]
MediatR.Extensions.Microsoft.DependencyInjection references Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0

You should update Microsoft.Extensions.DependencyInjection(.Abstractions) to 6.0.0 in your projects too.

Note that they still target netstandard, so they can be used also if your project is still on .net core 3/5

**Comment by jantos1518** [comment]
I was able to figure that out. Thank you!
