### ISSUE TITLE
The last 2 bullet points in the "Migration Guide 9.x to 10.0" are the same.

### ISSUE THREAD

**Issue by urielzen** [jbogard/MediatR#711]
The last 2 bullet points in the "Migration Guide 9.x to 10.0" are the same.

https://github.com/jbogard/MediatR/wiki/Migration-Guide-9.x-to-10.0

- Modification of generic constraint on `IRequestPostProcessor` from `where TRequest notnull` to `where TRequest : IRequest<TResponse>`
- Modification of generic constraint on `IRequestPostProcessor` from `where TRequest notnull` to `where TRequest : IRequest<TResponse>`

**Comment by jbogard** [comment]
It's a wiki, it's OK to make the edits :)

**Comment by urielzen** [comment]
I was going to do it, but I didn't know if the last bullet point needed to be removed completely, or if it was indented to be there, but its interface name just needed some edits.

Based on your answer I assume it needs to be gone? I can do it if you could please confirm.

**Comment by urielzen** [comment]
Done, thank u!

**Comment by neozhu** [comment]
Migration Guide 9.x to 10.0
_Modification of generic constraint on IRequestPreProcessor from where TRequest notnull to where TRequest : IRequest<TResponse>_
![image](https://user-images.githubusercontent.com/1549611/154633357-2253205a-e4e8-407c-be11-f9d9c64d01cf.png)
not change

**Comment by jbogard** [comment]
Ah of course I just assumed
