### ISSUE TITLE
Question: Orchestrate backend events

### ISSUE THREAD

**Issue by brazilianhue** [jbogard/MediatR#714]
I'm looking for a way to orchestrate commands / notifications but I dont know the best approach to do that.

In my case I have a request -> command -> rabbitmq events / subscriber triggering a response notification -> and I want to wait all occour to send a response back to customer (in the same HTTP request/response).

How can I achieve this?

**Comment by eskaufel** [comment]
This is not a good idea. Instead, you should use some web socket solution like Signal R to return the result asynchronously.
