### ISSUE TITLE
MediatR PipelineBehavior error message Unable to resolve service for type 'FluentValidation.IValidator`

### ISSUE THREAD

**Issue by warheat1990** [jbogard/MediatR#721]
I have this `ValidationBehavior`  
  
    public sealed class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : IRequest<TResponse>
    {
        private readonly IValidator<TRequest> _validator;

        public ValidationBehavior(IValidator<TRequest> validator)
        {
            _validator = validator;
        }

        public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            _validator.ValidateAndThrow(request);
            return await next();
        }
    }  
  
I have this handler  
  
    public class RemoveCurrencyHandler : IRequestHandler<RemoveCurrencyCommand, Unit>
    {
        private readonly ApplicationContext _context;

        public RemoveCurrencyHandler(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<Unit> Handle(RemoveCurrencyCommand request, CancellationToken cancellationToken)
        {
            var currency = await _context.Currency.FindAsync(request.Id);

            if (currency is null)
                throw new KeyNotFoundException();

            _context.Remove(currency);
            await _context.SaveChangesAsync();
            return Unit.Value;
        }
    }  
   
I'm getting error message `Unable to resolve service for type 'FluentValidation.IValidator'` everytime I call this handler, now obviously I know the reason is because I'm missing the validator, so it goes away if I add this  
  
    public class RemoveCurrencyValidator : AbstractValidator<RemoveCurrencyCommand>
    {

    }  
  
but not all my handler need a `Validator`, so I don't want to add empty `Validator` class to handler that doesn't need it. Is there any alternative?

**Comment by warheat1990** [comment]
ended up doing this  
  
```
public sealed class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : IRequest<TResponse>
    {
        private readonly IEnumerable<IValidator<TRequest>> _validators;

        public ValidationBehavior(IEnumerable<IValidator<TRequest>> validators)
        {
            _validators = validators;
        }

        public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            foreach (var validator in _validators)
                validator.ValidateAndThrow(request);

            return await next();
        }
    }
```  
  
But I'll keep this open for a while to see if there's any alternative

**Comment by galaldev** [comment]
Same issue here

**Comment by KurogamiLight3303** [comment]
The solution that U end with its the most common. U also can try the initial solution setting the 
`IValidator<TRequest>? validator = null` 
and check in the handler 
`if(_validator != null) _validator.ValidateAndThrow(request);`.

I also recomend set the Validations to Async to avoid future errors if U add a Async Rule to a validation
