### ISSUE TITLE
Expose method on Mediator class to retrieve handlers and notifications

### ISSUE THREAD

**Issue by andresantarosa** [jbogard/MediatR#722]
I'm currently working on a [lib](https://github.com/andresantarosa/Orchesflow) to work along MediatR. This lib is focused on orchestrating events and I would need to access the list of handlers (_requestHandlers) and notifications (_notificationHandlers) that belong to Mediator class. Is there any chance to expose methods to return these values?

Thanks in advance

**Comment by jbogard** [comment]
I don't think those collections will give you what you want. Those are lazily-generated wrappers for calling into generic handlers from non-generic call sites but aren't equivalent to a full list of all possible handlers.

You'd need to interrogate the container for that - whatever container that might be.

**Comment by andresantarosa** [comment]
Awesome! Thank you very much for the fast response and the container suggestion. =)
