### ISSUE TITLE
Add response writing support directly from inside pipeline behavior

### ISSUE THREAD

**Issue by nicholasyin** [jbogard/MediatR#733]
Maybe someone has proposed this before. Anyway, is it possible to shortcut the pipeline handling from a behavior and return response directly, without calling any subsequent `next` handler/behavior?

**Comment by KurogamiLight3303** [comment]
Yes it is possible, but U are its pointless. Resolve it in a Pipeline Behavior or the Final Handler will take almost the same time run, but the Handler is easier to Code and Reuse

**Comment by nicholasyin** [comment]
> Yes it is possible, but U are its pointless. Resolve it in a Pipeline Behavior or the Final Handler will take almost the same time run, but the Handler is easier to Code and Reuse

I don't quite get this. If it's possible, how?

**Comment by KurogamiLight3303** [comment]
Like any other pipeline, but restricting  with
`where TResquet : CommandType`
But Then you have to register all those pipelines to the DI. I still think that it’s too much trouble

**Comment by vaclavholusa** [comment]
You can just return without calling next();.. Do you have a code sample? We can help
