### ISSUE TITLE
How to split a large request into smaller ones, then returning a response by merging smaller responses, In PipelineBehavior

### ISSUE THREAD

**Issue by mjalil** [jbogard/MediatR#738]
Hi,
I have a request like this:

```c#
public class TimeSerriesQuery 
{
    public DateTime From {get; set;}
    public DateTime To {get; set;}
}
 ```
and a response like this:

```c#
public class TimeSerries {
    public class DataPoint
    {
        public DateTime Time {get; set;}
        public double value {get; set;}
    }

    public DateTime LastTime {get; set;}
    public DataPoint[] DataPoints {get; set;}
}
 ```
I need to implement a `IPipelineBehavior` that split a `TimeSerriesQuery` with large time period into some queries with smaller time periods ,then send those requests to `next` handler in the pipeline, and then merge all small responses and return the final big response

I think the only possible way is to mutate the request to a smaller period and await on `next`, then mutate again and await again on `next` and do this until the whole period responses is ready, then merge them.
It seems it is not possible to call `next` multiple times concurrently with multiple split requests

How can I do that?

**Comment by jbogard** [comment]
You'd need to design your own solution inside a single `PipelineBehavior`. Delegate to some other interfaces and do this yourself. There's no out-of-the-box solution here.

The request exception actions/handlers are in a similar boat, that's why there's a separate interface for them and a behavior that coordinates calling into those separate behaviors.

**Comment by mjalil** [comment]
Jimmy,

After your comment on request exception actions/handlers, I checked the source of exception actions/handlers to see some sample code. I've found a mistake and requested pull #739 

Thank you

**Comment by KurogamiLight3303** [comment]
Hi, to solve the problem its not easy for you to create a handler for your **TimeSerriesQuery** a handler that if the time periods is too large split the periods into smaller **TimeSerriesQuery** and then send it with 
`Task.WhenAll(_mediator.Send(subquery1), _mediator.Send(subquery2));`?

**Comment by mjalil** [comment]
> Task.WhenAll(_mediator.Send(subquery1), _mediator.Send(subquery2));

yes, that makes sense. thank you 👍
