### ISSUE TITLE
Question:  good pattern to allow for variances in business logic?

### ISSUE THREAD

**Issue by cobysy** [jbogard/MediatR#75]
I'm looking for a good pattern to apply to create a small variance in the business logic based on a value of a parameter of the command object. 

The poor mans solution would be a `if-then-else` in code, but it breaks the S in SOLID, which I'm not too happy about.

Also I would like to avoid having to create a new command object just for the sake of separation.

**Comment by jbogard** [comment]
Sometimes an if isn't a big deal.

But I correlate commands to how they're exposed in the front end, is this
command from the UI?
