### ISSUE TITLE
Behaviors for handler with generic command handler interface

### ISSUE THREAD

**Issue by yarus** [jbogard/MediatR#752]
Hi,

We have additional level of abstractions build above IRequest<TResponse>:

```
public interface ICommand : IRequest<Result>
{
}

public interface ICommand<TResponse> : IRequest<Result<TResponse>>
{
}

public interface IQuery<TResponse> : IRequest<Result<TResponse>>
{
}
```

This allows us to split Commands and Queries in the code. The generic version of ICommand looks similar to IQuery but this covers cases when we have to return some kind of Command status result in addition to success or failure.

The issue we currently have is within Behavior. I am trying to extract UnitOfWork into behavior to have something like this:

```
public class CommandPersistenceBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : ICommand, IRequest<TResponse>
    where TResponse : ResultBase
{
    private readonly IUnitOfWork _uow;

    public CommandPersistenceBehavior(IMainDbContext db)
    {
        _db = db;
    }

public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        var response = await next();

        if (response.IsSuccess)
            await _uow.Commit(cancellationToken);

        return response;
    }
}
```

This works fine to handle ICommand inverface handlers but that doesn't work for generic ICommand<TResponse> command handlers. 

Is there a valid way to define such behavior for generic ICommand<TResponse> interface?

I ended up having this:

```
public class CommandUnitOfWorkBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
    where TResponse : ResultBase
{
    private readonly IUnitOfWork _uow;

    public CommandUnitOfWorkBehavior(IUnitOfWork uow)
    {
        _uow = uow;
    }

    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        var response = await next();

        var isNormalCommand = request is ICommand;

        var isGenericCommand = request.GetType().GetInterfaces().Any(x =>
            x.IsGenericType &&
            x.GetGenericTypeDefinition() == typeof(ICommand<>));

        var isCommand = isNormalCommand || isGenericCommand;

        if (isCommand && response.IsSuccess)
            await _uow.Commit(cancellationToken);

        return response;
    }
}
```

This Behavior catch all requests (including Queries) and commit only in case we are dealing with ICommand or generic ICommand but I don't really like that approach. It would be better if DI could call Behavior for me without generic code.

Thanks!

**Comment by jbogard** [comment]
You'll likely have to go that route, not many DI containers can fill in the generic constraints like that. You might try Lamar or Autofac? Those have better generics support that I've seen.
