### ISSUE TITLE
Mixing generic handler for base type does not behave correctly when used together with handler on derived type

### ISSUE THREAD

**Issue by Baramordax** [jbogard/MediatR#757]
I have a setup with a generic handler on a base type and some specific handlers for derived types from that base. This causes incorrect behavior. The generic handler by itself works as expected. The specific handlers without the generic handler works as expected. Mixing them causes the specific handler to be called twice instead of once for the generic and once for the specific.

Base and Derived classes:

    public class MyBase : INotification {
        public int Id { get; }

        protected MyBase(int id) {
            Id = id;
        }
    }

    public class MyDerived : MyBase {
        public MyDerived(int id) : base(id) {}
    }

-----

Handlers:

    public class GenericHandler<T> : INotificationHandler<T> where T : MyBase {
        public Task Handle(T myBase, CancellationToken cancellationToken) {
            Console.WriteLine($"Generic Handler Id: {myBase.Id}");
            return Task.CompletedTask;
        }
    }

    public class SpecificHandler : INotificationHandler<MyDerived> {
        public Task Handle(MyDerived myDerived, CancellationToken cancellationToken) {
            Console.WriteLine($"Specific Handler Id: {myDerived.Id}");
            return Task.CompletedTask;
        }
    }

-----

Test Method:

        public void Test()
        {
            var myType = new MyDerived(10);
            _mediator.Publish(myType);
        }

-----

Expected output:

    Specific Handler Id: 10
    Generic Handler Id: 10

Actual output:

    Specific Handler Id: 10
    Specific Handler Id: 10

**Comment by Baramordax** [comment]
Thanks for the quick response.

Pardon my lack of insight here. I'm using your other project MediatR.Extensions.Microsoft.DependencyInjection in an aspnet core application and nuget packages. The word container confuses me here I'm afraid. I'm guessing it's one of the inner items of MediatR?

**Comment by jbogard** [comment]
Oh sorry, if you're using `GetServices` you don't need `IEnumerable`. You need to assert the `handlers` there, to make sure the correct handlers are resolved.

You're using the built-in container, Microsoft.Extensions.DependencyInjection. That DI container isn't super feature-rich and will often encounter errors with more exotic generics scenarios. Some teams switch to using Autofac, Lamar, etc. that have better capabilities.

When I get these errors, I check two things:

- Service resolution
- Service registration

I check the resolution first - just like you're doing above, except validate the handler objects themselves.

Next is registration, which is harder to assert but not impossible. Often I'll just use a debugger to examine the `services` value there, check the service registrations and make sure the service/interface type look correct.

MediatR does not have any logic for resolution, it merely delegates to the DI container.

**Comment by Baramordax** [comment]
Great, thanks. I've got some pointers now and I'll come back to this thread if I have anything of value to add.

So far I can verify that the correct handlers are found through `GetServices<>` and looping through them gives the expected result.

I'll look into the service registration, but without knowing much about MediatR it does look a lot like 2 handlers are found and the first is called twice.

Will update if I find out more.

**Comment by Baramordax** [comment]
I have found a solution that works for me. Instead of 

    public class GenericHandler<T> : INotificationHandler<T> where T : MyBase {
        public Task Handle(T myBase, CancellationToken cancellationToken) {
            Console.WriteLine($"Generic Handler Id: {myBase.Id}");
            return Task.CompletedTask;
        }
    }

I can use 

    public class BaseHandler : INotificationHandler<MyBase> {
        public Task Handle(MyBase myBase, CancellationToken cancellationToken) {
            Console.WriteLine($"Base Handler Id: {myBase.Id}");
            return Task.CompletedTask;
        }
    }

I am not certain why it was written in a more complicated manner originally. Whatever the reason (including idiocy), this handler works with the latest release and that brings this to a close.

When inspecting the registered services when using the GenericHandler it added 2 entries. One for specific and a sort of untyped generic. My guess it tried to resolve things at runtime and for whatever reason failed.

When using the BaseHandler instead it gave 3 entries, 2 for MyDervied, one for each handler and a third for the base type and base handler. That just makes more sense overall.

Lesson learned.
