### ISSUE TITLE
Performance issue - Congestion - Memory leak

### ISSUE THREAD

**Issue by foliv57** [jbogard/MediatR#759]
First of all, I want to apology for this long and painful to read story, but I prefer to be as detailed as possible because I know that performance issue can easily become a matter of perspective. Especially with packages that are highly used by the community without any problem regarding this topic.

But since some times, and moreover since a migration to .net 6.0, I started to suspect MediatR to create performance issue in my application.

## Context

An Azure Function App which handle a simple HTTP GET request:
- **Hosting**: Linux P3V2 Azure App Service plan manually locked to 1 instance
- **Location**: West Europe
- **Azure Function App version**: V4 (Deployed as Docker image)
- **Framework**: .net 6.0
- **Docker image used to build**: mcr.microsoft.com/dotnet/sdk:6.0.301
- **Docker image used as base**: mcr.microsoft.com/azure-functions/dotnet:4.7.0-dotnet6-appservice
- **MediatR version**: 10.0.1
- **Dependency injection**: Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0
- **Lifetime**: MediatR injected with transient lifetime (Default)
- **Sending**: Request sent to handler with IMediator.Send method
- **Testing tool**: Artillery
- **Load target**: 250rps

## Test

First I launched my load test on a version which didn't use MediatR, to have a base-line.
I just moved the code from my handler to the function app, and removed MediatR injection.

I reached my 250rps target with a median **33ms** response time.
![WithoutMediatR](https://user-images.githubusercontent.com/59969260/177510813-7d4b467c-eefb-4e4c-bdd4-bd17fa223803.PNG)

Then, I launched the same test by using MediatR to send my request to a IRequestHandler.

After some seconds, the response time start to increase significantly, pushing my median response time to a **15000ms** at the end of the test.
![WithMediatR](https://user-images.githubusercontent.com/59969260/177510883-6b7d7b55-72a8-42c6-8b17-ffb92c126d47.PNG)

I compared the memory usage during the two tests and was surprised that I used 900MB with MediatR compare to 400 MB without MediatR.
![RAM](https://user-images.githubusercontent.com/59969260/177510908-9490152f-d268-49ad-9200-c834fa99fe90.PNG)

## Analyse

I started to analyse the source code to try to find a potential root cause for this.

I pointed one thing that can be at risk, without being 100% sure that it can creates this situation.

In file **"ServiceRegistrar.cs"** the **"ServiceFactory"** delegate is injected as transient. Meaning that for every **Mediator** instance creation, a new delegate will be created on **"IServiceProvider.GetRequiredService"**. This delegate is then used in the handle method to create the handler instance.
![Delegate](https://user-images.githubusercontent.com/59969260/177511287-297edddf-d07e-47bd-9a50-20396c945386.PNG)
![DelegateDI](https://user-images.githubusercontent.com/59969260/177511469-0179cfcb-d4e6-4eda-8828-643100e9c0e0.PNG)
![MediatorCtor](https://user-images.githubusercontent.com/59969260/177511616-0965dd63-2346-4f8d-afca-cce9afaa169e.PNG)
![HandlerCreation](https://user-images.githubusercontent.com/59969260/177513000-81f66b93-b8a7-43d9-a428-4369e4436637.PNG)

It seems that the resources created by the delegate are not properly managed/cleaned by the IOC container.

Another approach can be that the parallel access to the **IServiceProvider** via delegates creates congestion and snowball the performance drop.

To prevent this, I tested a run with MediatR injected as a singleton.

This fixed the problem (Performance + RAM usage), but can't be an effective solution, because we are using scoped services and this creates lifetime mismatch and errors.
![WithMediatR_Singleton](https://user-images.githubusercontent.com/59969260/177511695-cdbff943-829e-498c-bea5-2323389f1858.PNG)
![RAM_Singleton](https://user-images.githubusercontent.com/59969260/177511706-178ec450-6a21-4b9e-a4c1-2e8c156bb12a.PNG)

I attached the sample project that I used for the tests.
[PerfSample.zip](https://github.com/jbogard/MediatR/files/9053266/PerfSample.zip)

I will make some other tests by using out-of-process function app and other IOC containers, to see if it
changes the result.

Any help will be welcome.

Thank you.

**Comment by foliv57** [comment]
Just executed a test by running the function app in an isolated process using the base image:
**mcr.microsoft.com/azure-functions/dotnet-isolated:4.7.0-dotnet-isolated6.0-appservice**

![WithMediatR_Isolated](https://user-images.githubusercontent.com/59969260/177549800-dd6510cf-a933-437f-9a0b-1629cf26c25e.PNG)

The result seems to reveal that my performance issue root cause is the IOC container initialisation/configuration when using in-process function app.

I used the Microsoft guideline below to configure DI for in-process functions app:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection

So the problem is hidden in the core function runtime initialisation process.

Attached the new version which include the isolated function app:
[PerfSample_WithIsolatedFuncApp.zip](https://github.com/jbogard/MediatR/files/9054764/PerfSample_WithIsolatedFuncApp.zip)

**Comment by foliv57** [comment]
And found some time to run a test on an in-process function app with **Autofac DI 8.0** and **MediatR Autofac DI 8.1**
![WithMediatR_Autofac](https://user-images.githubusercontent.com/59969260/177604240-9a2d7b20-295f-40dc-badc-87e6f40099e7.PNG)

No luck for me, my problem appears only with the combo "in-process func app + MediatR + Microsoft DI". Which is my production setup.

Attached the new version which include Autofac:
[PerfSample_WithAutofac.zip](https://github.com/jbogard/MediatR/files/9056754/PerfSample_WithAutofac.zip)

**Comment by foliv57** [comment]
Today, I dug deeper the source code and found one interesting point.
In file **"ServiceRegistrar.cs"**, the devil is hidden here:
![image](https://user-images.githubusercontent.com/59969260/177836560-5ff5b307-1a72-4801-8633-38875b875742.png)

- If I remove **"RequestExceptionActionProcessorBehavior"** and keep **"RequestExceptionProcessorBehavior"**, everything is fine
- If I keep **"RequestExceptionActionProcessorBehavior"** and remove **"RequestExceptionProcessorBehavior"**, everything is fine
- If I keep both, I have the performance issue
- If I keep both, but remove the **ServiceFactory** injection, everything is fine
![image](https://user-images.githubusercontent.com/59969260/177837333-dddfbeae-e70e-4910-85e7-74469386a998.png)

Both behaviours instances need an injection of **ServiceFactory** delegate and are themselves instantiated by a **ServiceFactory** delegate injected in the **Mediator** instance.
![image](https://user-images.githubusercontent.com/59969260/177838309-458a3fae-35d2-40d5-9791-520bf238b8e3.png)

This seems to create a kind of lock or wait on the **IServiceProvider**. I tried to inject the **ServiceFactory** as scoped to have the same delegate used under the same scope, but this didn't change anything.

**Comment by jbogard** [comment]
Yes unless there is a proposed fix?

**Comment by foliv57** [comment]
Your question sounds weird. Should I fix it myself ?

**Comment by jbogard** [comment]
Yes.

**Comment by foliv57** [comment]
Ok I see.

Very interesting point of view. I will print that and hang it on my wall:
_"If there is no solution, there is no problem" (J. Bogard, 2022)_

Thanks a lot for your hard contribution. Hope it was not too tiring to close all open issues to give the impression that this package don't have problems.

Good reputation is so hard to obtain and so easy to loose. Sad to find out who you really are.

Hope that not too much people are using this package in Azure Function App, knowing that they may be confronted to denied of service with standard volume of HTTP requests.

From my side, sorry, I will not investigate more, knowing that this package is based on a sort of "Service Locator Pattern" by delegating the IOC container method "GetRequiredService" to create handler instances at runtime. This design is [not recommended by Microsoft](GetRequiredService), because it mixes IOC strategies and prevent memory optimisation on created instances.
![image](https://user-images.githubusercontent.com/59969260/193306057-8a4b8af7-b961-412d-892a-631a819e48f8.png)

So my proposed fix is "uninstall-package MediatR" for people matching the condition "in-process Azure Function App + MediatR + Microsoft DI".

Thank you very much for all the knowledge you share with the community, really helpful, have a nice and restful week-end.

**Comment by dzmitry-lahoda** [comment]
@foliv57

start value your time. you NEVER need MediatR. NEVER.
1. if you do stuff, just do the stuff - function/REST/ASP.NET/Orleans/GRPC/UDP/GQL.
2. if you need GQL+REST, just write exact this layer manually.
3. if need CQRS-ES - just use existing framework which composes with data or write your own. 
4. learn (if not yet) VS Code/Emacs/helix/Rider hotkeys for multiediting. mechanical copy pasted is better then reflection in most cases.
5. look here https://github.com/amis92/csharp-source-generators before using reflection

generally,
1. C# in not composable language. I proposed 3 type based patters which can run on exiting CLR. people did not get it.
2. EF leaks, logging leaks, Unity3D leaks, Cosmos SDK leaks  - .NET ecosystem is sloppy overengineered coding.
3. you want no leaks and not surprises ? use Rust, Go, Haskell. I used Rust libs of version <1, and never ever had issue like libs in C# with version >>1.
4. you want really composable code use strictly typed TypeScript. they have 20 config options when set - you are as typed in TS as in C#. but more composable with dependent types (see effects-core).
5. nobody pays you to play non valuable game of MediatR or any other such kind project. you just will earn more if stop touching this and similar projects.

**Comment by jbogard** [comment]
Ugh I see now why this is confusing. I closed a bunch of stale issues but GitHub treats those as "Close as completed". It also has "Close as not planned" but that's only looking at a single issue. It was not my intent to close this as "completed".

For this particular issue, I don't see any indication of a fix. There are observations of the current behavior, but no fix.

Ignoring the negative remarks, from your comments of "service location is bad", it's clear:

- You don't understand how MediatR works internally
- How it uses dynamic container resolution to build a handler and its pipeline
- What problems it solves
- That many libraries that use generics also use dynamic container resolution just like MediatR

So no, I don't think you should use MediatR unless you understand how it works and what problems it solves.

The problem you highlighted is with the stock MS DI container, which has plenty of issues and is meant to be a "least common denominator" container targeting pretty much exclusively the needs of ASP.NET Core. Any feature or fix must be validated against ASP.NET Core first (as I have had years of experience trying to get fixes applied).

**Comment by foliv57** [comment]
Hum,

![image](https://user-images.githubusercontent.com/59969260/193847615-1e685392-3dcb-4b4a-ab8c-3b545e837f74.png)
https://jimmybogard.com/service-locator-is-not-an-anti-pattern/

Did I mentioned "service location is bad" ? I just mentioned Microsoft recommendations to not mix IOC strategies: (Sorry, I pasted the wrong url in my previous comment, I will update it. Below the correct one):
https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#recommendations

Then, for sure, "recommendations" are just guidelines. They can be bypassed when there is no other solution. But they are always mentioned for good reasons. Our job is, unfortunately, full of trade-offs. But in my situation, the trade-off seems to be an unexpected high memory usage which causes a deny of my service. It's why I asked help to understand if it can be caused by the implementation, or by the IOC container framework which leaks memory for object instances created dynamically.

I pointed the service factory because of the big behaviour change when I just remove the ServiceFactory injection in "RequestExceptionActionProcessorBehavior" and "RequestExceptionProcessorBehavior". But maybe it's just by chance.

So let me just recap for "You don't understand how MediatR works internally", maybe I looked at the wrong code repository.
![image](https://user-images.githubusercontent.com/59969260/193860746-9d30e5e4-f91d-4628-86e3-877d0220c04c.png)
![image](https://user-images.githubusercontent.com/59969260/193860241-7bbddd4e-5d2a-4cd0-8d19-fb9534025cc8.png)

Totally agree that for point 1 "when you can use DI instead" was not an option for your package and you explain why in your article. That's fine.

Don't take me wrong, my only intention when I created this issue was to help to make this package as good at it can be, from the design improvement that it procures, to the performance that it should not compromises too much (I'm realistic).

So, please, forget all my previous bothering "blabla" and just focus on this question:
**"Are you 100% sure that injecting a delegate on GetRequiredService in multiple pipeline behaviours and static cached handler wrappers didn't create resource management issues for the IOC container ?"** 

Its a question that maybe exceeds the original issue. So I don't expect an answer "here/at all". Closed is closed.

Thank you for the clarification about the closing reason, it changes everything.

**Comment by jbogard** [comment]
> Are you 100% sure that injecting a delegate on GetRequiredService in multiple pipeline behaviours and static cached handler wrappers didn't create resource management issues for the IOC container ?

No, that was never a design consideration, I've never needed to care. I've never experienced any performance issues (I/O, CPU or otherwise) with MediatR in the situations I've used it. I've also never used MediatR in Azure Functions, and I can't say that I ever would. I don't think it's an appropriate fit for that programming/runtime model.

Regardless, the tone here is inappropriate, this is a free library and I offer no support or warranty otherwise.
