### ISSUE TITLE
Signed Nuget Version

### ISSUE THREAD

**Issue by nevaenuf** [jbogard/MediatR#76]
I'd love to use MediatR in my production environment, but the Nuget package does not provide a signed version for .Net 4.5.  Any reason for this?

**Comment by khellang** [comment]
Oh, here we go again... :stuck_out_tongue_closed_eyes: 

![Grabs Popcorn](http://i.imgur.com/DKJhx9l.gif)

Why don't you just use [Strong Namer](https://github.com/dsplaisted/strongnamer)?

**Comment by jbogard** [comment]
Strong Namer is the solution here. It works.

**Comment by jbogard** [comment]
And my general approach here is I will keep existing signed packages signed, and new packages I won't sign. Your production apps don't need to be signed.

**Comment by nevaenuf** [comment]
:)  Thanks!
