### ISSUE TITLE
Constrained postprocessor DI options

### ISSUE THREAD

**Issue by JBastiaan** [jbogard/MediatR#760]
Hello,

i've been stuck trying to create a generic postprocessor with generic constraints. I read alot here that the ASP.Net Core DI has its limitations, however in my project i cannot easily make the switch to a different DI container. So if i have the following setup, what other options do i have to make this work besides swapping DI container? And id rather not write out registrations for all implementations manually :). Any help would be greatly appreciated.

**Note**
The Result struct is from the CSharpFunctionalExtensions library

```
public interface ISaveStepRequest<TResponse> : IRequest<Result<TResponse>>
{
    public string StepName { get; }
}
```
Command + Handler
```
public record DoSomething(string StepName, string DoThis) : ISaveStepRequest<int>;
```
```
public class DoSomethingCommandHandler : IRequestHandler<DoSomething, Result<int>>
{
    
    public Task<Result<int>> Handle(DoSomething request, CancellationToken cancellationToken)
    {
        var doThis = request.DoThis;
        return Task.FromResult<Result<int>>(1);
    }
}
```
PostProcessor
```
public class SaveStepPostProcessor<TRequest, TResponse> : IRequestPostProcessor<TRequest, Result<TResponse>>
    where TRequest : ISaveStepRequest<TResponse>
{
    public Task Process(TRequest request, Result<TResponse> response, CancellationToken cancellationToken)
    {
        //Needs access to property on ISaveStepRequest interface
        var stepname = request.StepName;

        //Do some other stuff.
        return Task.CompletedTask;
    }
}
```
Usage in application
```
await _mediator.Send(
    new DoSomething("Step1", "DoThis"), 
    cancellationToken);
```
DI Setup
This works:
```
builder.Services.AddTransient(
    typeof(IRequestPostProcessor<DoSomething, Result<int>>), 
    typeof(SaveStepPostProcessor<DoSomething, int>));
```
This does not work:
```
builder.Services
    .AddTransient(typeof(IRequestPostProcessor<,>), typeof(SaveStepPostProcessor<,>));
```

**Comment by ThomasSkyldahl** [comment]
You might be able to get Scrutor [https://github.com/khellang/Scrutor](https://github.com/khellang/Scrutor) to create the registrations for you, it can create registrations for the default DI by assembly scanning
