### ISSUE TITLE
Cannot resolve parameter MediatR.SingleInstanceFactory singleInstanceFactory

### ISSUE THREAD

**Issue by TDK1964** [jbogard/MediatR#77]
I thought I'd give MediatR a try but keep getting autofac errors.

```
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'MediatR.Mediator' can be invoked with the available services and parameters:
Cannot resolve parameter 'MediatR.SingleInstanceFactory singleInstanceFactory' of constructor 'Void .ctor(MediatR.SingleInstanceFactory, MediatR.MultiInstanceFactory)'.
```

Autofac registration

```
builder.RegisterSource(new ContravariantRegistrationSource());
builder.RegisterAssemblyTypes(typeof(IMediator).Assembly).AsSelf().AsImplementedInterfaces();

```

My controller

```
 public class PeopleController : Controller
    {
        private readonly IMediator _mediator;

        public PeopleController(IMediator mediator)
        {
            _mediator = mediator;
        }
...
```

**Comment by TDK1964** [comment]
I've fixed the error by changing the registration to this 
```
builder.RegisterSource(new ContravariantRegistrationSource());
builder.RegisterAssemblyTypes(typeof(IMediator).Assembly).AsSelf().AsImplementedInterfaces();
builder.Register<SingleInstanceFactory>(ctx =>
{
	var c = ctx.Resolve<IComponentContext>();
	return t => c.Resolve(t);
});
builder.Register<MultiInstanceFactory>(ctx =>
{
	var c = ctx.Resolve<IComponentContext>();
	return t => (IEnumerable<object>)c.Resolve(typeof(IEnumerable<>).MakeGenericType(t));
});
```

But now it doesn't work with async actions
 
The requested service 'MediatR.IAsyncRequestHandler`2[[OfficeManager.Features.People.Edit+Query, OfficeManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[OfficeManager.Features.People.Edit+Command, OfficeManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

**Comment by kappy** [comment]
Hi @TDK1964 

you need to also register on Autofac your handlers. Try adding the following line after:

            builder.RegisterAssemblyTypes(assembly)
                .AsClosedTypesOf(typeof(IRequestHandler<,>))
                .AsImplementedInterfaces();

            builder.RegisterAssemblyTypes(assembly)
                .AsClosedTypesOf(typeof(IAsyncRequestHandler<,>))
                .AsImplementedInterfaces();

            builder.RegisterAssemblyTypes(assembly)
                .AsClosedTypesOf(typeof(INotificationHandler<>))
                .AsImplementedInterfaces();

            builder.RegisterAssemblyTypes(assembly)
                .AsClosedTypesOf(typeof(IAsyncNotificationHandler<>))
                .AsImplementedInterfaces();

**Comment by TDK1964** [comment]
@kappy thanks for the feedback.

I actually did this while I was waiting for replies and it seemed to work. Is this acceptable?

```
 builder.RegisterAssemblyTypes(AppDomain.CurrentDomain.GetAssemblies())
               .Where(t => t.Name.EndsWith("Handler"))
               .AsImplementedInterfaces()
               .InstancePerRequest();

```

**Comment by kappy** [comment]
That is more a Autofac related case other than MediatR. 
I don't know all the considerations about using  the name string compare vs the type.

**Comment by TDK1964** [comment]
@kappy, on a seprate note, do you know how to convert this the autofac?
```

private static IElementGenerator<T> GetGenerator<T>(T model) where T : class
{
      var library = StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance<HtmlConventionLibrary>();
      return ElementGenerator<T>.For(library, t => StructuremapMvc.ParentScope.CurrentNestedContainer.GetInstance(t), model);
}
```
