### ISSUE TITLE
[Subjective] Best Practice Question

### ISSUE THREAD

**Issue by mxmissile** [jbogard/MediatR#783]
I know this is probably subjective, but here goes anyway, let's say I have an `ActivateOrder` command/notification being called from a simple web action: 

`public class ActivateOrder : INotification{}`

Should the command contain an Order member or an OrderId member? Who's responsibility should it be to retrieve the order from a db(for example)? The command or a separate `IRequest` call before the Command that retrieves the order? 

```
public IActionResult ActivateOrder(int id)
{
  var order =  _mediar.Send(new GetOrder(){Id = id});
  var command = new ActivateOrder();
  command.Order = order;
...
}
```

or 

```
public IActionResult ActivateOrder(int id)
{
  var command = new ActivateOrder();
  command.OrderId = id;
...
}
```

**Comment by ardalis** [comment]
Just the id, IMO.

What if the handler doesn't do the work immediately but queues it up for another process? What if the state of the entity/order has changed between when the command was sent and the job runs? No sense sending around a bunch of data that might be stale anyway. Just the id keeps the sending code simple and allows the handler the flexibility it needs (to fetch it or not).

**Comment by mxmissile** [comment]
@ardalis thanks for confirming.
