### ISSUE TITLE
Error constructing handler for request of type MediatR.IRequestHandler

### ISSUE THREAD

**Issue by cmssantos** [jbogard/MediatR#784]
I have 3 projects, API, Application e Infra.IoC. The settings below work when run by VS Code and Visual Studio. However, when I run inside a docker container, the error occurs:

Error constructing handler for request of type MediatR.IRequestHandler`2[Monefy.Application.Features.AccountFeatures.Commands.CreateAccountCommand,Monefy.Application.Common.CommandResult]. Register your handlers with the container. See the samples in GitHub for examples. Not Handled

Anyone can help me?

ProjectApi -  Program.cs
`builder.Services.RegisterMediatRDependencies();`

ProjectApplication - AccountCommandHandler.cs

ProjectDependecyResolver - DependecyContainer.cs
`public static class ServicesExtensions
{
    public static void RegisterMediatRDependencies(this IServiceCollection services)
    {
        services.AddMediatR(typeof(CreateAccountCommandHandler).Assembly);
        services.AddTransient<IRequestHandler<CreateAccountCommand, CommandResult>, CreateAccountCommandHandler>();
    }
}`

**Comment by KostetskyiYaroslav** [comment]
Is DC.cs part of Infra.IoC project?

Looks like **CreateAccountCommandHandler** dependency should accept some paramers? 
`services.AddTransient<IRequestHandler<CreateAccountCommand, CommandResult>, CreateAccountCommandHandler>(); } }`

I'd try resolving `IRequestHandler<CreateAccountCommand, CommandResult>` above the line you're adding MediatR.

Good luck with it
