### ISSUE TITLE
WebApi, Ninject and MediatR binding issues

### ISSUE THREAD

**Issue by tetius88** [jbogard/MediatR#79]
Hi,

I seem to have an issue while hooking up WebApi with Ninject and Mediatr. I used the example in /samples for Ninject but I keep getting this:
Error: An error occurred when trying to create a controller of type 'PeopleController'. Make sure that the controller has a parameterless public constructor.

InnerException:
Error activating IMediator More than one matching bindings are available. Matching bindings: 
1) binding from IMediator to Mediator 
2) binding from IMediator to Mediator Activation path: 
3) Injection of dependency IMediator into parameter mediator of constructor of type PeopleController 
2) Injection of dependency PeopleController into parameter resolutionRoot of constructor of type NinjectDependencyResolver 
1) Request for IDependencyResolver Suggestions: 
1) Ensure that you have defined a binding for IMediator only once.

Any ideas?
Thanks!

**Comment by kiwipiet** [comment]
It looks like your bindings is not setup correctly.
Could you post your code where you setup your Ninject kernel?

**Comment by tetius88** [comment]
Hi @kiwipiet,

The code inside NinjectWebCommon is as follows:
```csharp
 private static IKernel CreateKernel()
        {
            var kernel = new StandardKernel();
            try
            {
                kernel.Bind<Func<IKernel>>().ToMethod(ctx => () => new Bootstrapper().Kernel);
                kernel.Bind<IHttpModule>().To<HttpApplicationInitializationHttpModule>();
                RegisterServices(kernel);
                return kernel;
            }
            catch
            {
                kernel.Dispose();
                throw;
            }
        } 
private static void RegisterServices(IKernel kernel)
        {
            kernel.Components.Add<IBindingResolver, ContravariantBindingResolver>();
            kernel.Bind(scan => scan.FromAssemblyContaining<IMediator>).SelectAllClasses().BindDefaultInterface());           
            kernel.Bind(scan => scan.FromAssemblyContaining(typeof(IAsyncRequestHandler<,>)).SelectAllClasses().BindAllInterfaces());
            kernel.Bind(scan => scan.FromAssemblyContaining(typeof(IAsyncRequest<>)).SelectAllClasses().BindAllInterfaces());
            kernel.Bind<SingleInstanceFactory>().ToMethod(ctx => t => ctx.Kernel.Get(t));
            kernel.Bind<MultiInstanceFactory>().ToMethod(ctx => t => ctx.Kernel.GetAll(t));
}
```

And I try to inject it in a ApiController like so:
```csharp      
        private readonly IMediator mediator;

        public PeopleController(IMediator mediator)
        {
            this.mediator = mediator;
        }
```

**Comment by kiwipiet** [comment]
`kernel.Bind(scan => scan.FromAssemblyContaining(typeof(IAsyncRequestHandler<,>)).SelectAllClasses().BindAllInterfaces());
            kernel.Bind(scan => scan.FromAssemblyContaining(typeof(IAsyncRequest<>)).SelectAllClasses().BindAllInterfaces());`

These are your problem lines.  The assembly it is going to find in both cases is 'MediatR.dll'.  And this assembly has already been bound in:
`kernel.Bind(scan => scan.FromAssemblyContaining<IMediator>).SelectAllClasses().BindDefaultInterface());`

If you have one assembly that contains your handlers and requests then only register that assembly once and don't re-register MediatR.dll

This is clearly a web app, and if you have all your requests and handlers in the web app assembly you could do the following:

`kernel.Bind(scan => scan.From(Assembly.GetExecutingAssembly()).SelectAllClasses().InNamespaceOf(type).BindAllInterfaces());`

or

`kernel.Bind(scan => scan.FromAssemblyContaining<MyAsyncRequestHandler>).SelectAllClasses().BindDefaultInterface());`
where MyAsyncRequestHandler is one of your handlers.

**Comment by tetius88** [comment]
Thank you! The solution you provided works!
