### ISSUE TITLE
Support for netstandard2.0 in latest versions of MediatR

### ISSUE THREAD

**Issue by ThomasBarnekow** [jbogard/MediatR#791]
Thanks for providing this awesome package!

We are considering MediatR in an application that, unfortunately, has frontend-related parts that must target .NET Framework or netstandard2.0. Therefore, we can only reference libraries targeting up to netstandard2.0 in those parts. Since MediatR 10.0.0, however, you only target netstandard2.1.

Is there a way to provide support for netstandard2.0? At the moment, I am playing around with MediatR 9.0.0 in those parts. However, I don't know whether that is a safe choice for the longer term.

**Comment by jbogard** [comment]
You'll have to use the 9.0.0 version for those cases if you want to use MediatR. Version 10.0 introduced features only available with `netstandard2.1`.

Alternatively, you can copy the important bits directly and leave out the things you don't want or can't use.

**Comment by ThomasBarnekow** [comment]
OK, thanks for your quick reply.
