### ISSUE TITLE
v11 Breaking Change

### ISSUE THREAD

**Issue by jeparrish** [jbogard/MediatR#792]
On the What's New for v11, the change **"CA1068: CancellationToken parameters must come last by @panosru in https://github.com/jbogard/MediatR/pull/772"** should be listed as a Breaking Change.  

IMO: The previous method with CancellationToken as 2nd param could have been marked with an obsolete tag and allowed to build.

**Comment by jbogard** [comment]
Many people do warnings as errors so it would have the same effect. Best to rip the bandage off.
