### ISSUE TITLE
 ASP.NET MVC Example

### ISSUE THREAD

**Issue by trustorm** [jbogard/MediatR#8]
Is there a complete example of using MediaR with ASP.NET MVC including the decorator pattern pipeline for validation, authorisation?

**Comment by mreyeros** [comment]
Hey Jimmy, any update on the MVC sample?

**Comment by jbogard** [comment]
Does the Web API example help at all? It would work for MVC too.

**Comment by getuliojr** [comment]
I have a complete working version with OWIN + MediatR + Autofac + Web Api 2 and the basic test it went just fine.

**Comment by jbogard** [comment]
@getuliojr if you're down for it, i'd love a PR that does something similar with what I did for StructureMap. Big ask though, I know

**Comment by mreyeros** [comment]
That works for me!

**Comment by getuliojr** [comment]
I will prepare a PR and build an example working with this tecnology by next week ok ? Glad to help the community back.

**Comment by jbogard** [comment]
Awesome!

**Comment by jbogard** [comment]
Updated Web API to include an MVC sample

**Comment by vrs-rajkumarbapu** [comment]
Hi jbogard, Thanx for your post here. You concept is good. But I am looking few steps in making an application using mediatr with my MVC EF 6 codefirst with angularjs. It will be much helpfull if you can recommend any posts or website to follow or even your guidance.

**Comment by vrs-rajkumarbapu** [comment]
I need to know how to run your mediatr application, just was trying to achieve ResourceName method through errors.

**Comment by zeeshanasgar** [comment]
I am trying to implement CQRS in ASP.NET MVC application But It didn't work can anyone help me how to implement CQRS in MVC.
