### ISSUE TITLE
MediatR - Not working while accessing via Webseal

### ISSUE THREAD

**Issue by vipinnair** [jbogard/MediatR#80]
I am trying to access my application via Webseal SSL. But the code is failing stating that it's not able to find the handler class or the dependency is not registered.. But when we try accessing the application without web seal its working. 

In the application start up, we have a dependency registered as 

`container.RegisterType<IRequestHandler<Query, Result>, Handler>();`

In order to filter out the root cause, I injected `IRequestHandler<Query, Result>` to the constructor and invoked the Handler. This is working fine with Webseal.

Hope you can provide help on this to resolve the issue. 

Full Error Information
[{"code":null,"source":{},"title":"Internal Server Error","details":"Handler was not found for request of type Query.\r\nContainer or service locator not configured properly or handlers not registered with your container."}]

**Comment by jbogard** [comment]
I'm gonna need some more context here. What is WebSeal SSL? How does it affect your web app? What container are you using?
