### ISSUE TITLE
Add support for IAsyncEnumerable<TRequest>

### ISSUE THREAD

**Issue by iamxiaozhuang** [jbogard/MediatR#804]
I know MediatR provides a CreateStream method that returns IAsyncEnumerable with IResponse, but I am wondering if we can add support for IAsyncEnumerable with TRequest.
Because I'm working on a [a MediatR-based RPC (Remote Procedure Calls) example](https://github.com/iamxiaozhuang/MediatRPC). I need to implement some functionality for Client Stream/Bidirectional Stream, such as the GRPC framework. 
Thank you.

**Comment by jbogard** [comment]
Can the request type be `IAsyncEnumerable` directly?

**Comment by jbogard** [comment]
Can your response type be the full async enumerable?
