### ISSUE TITLE
Polymorphic  INotification with handler

### ISSUE THREAD

**Issue by jvmlet** [jbogard/MediatR#806]
I'm after generic `INotification`  behavior:

```c#
public class OnSomethingHappenedNotification<T> : INotification {
    public T Payload { get; }

    public OnSomethingHappenedNotification(T payload ) {
        Payload = payload ;
    }
}
public class OnPocoHappenedHandler: INotificationHandler<OnSomethingHappenedNotification<MyPoco>> {
        public Task Handle(OnSomethingHappenedNotification<MyPoco> notification, CancellationToken cancellationToken) {

        }
    }

MyPoco poco = ... ;
Type type = typeof(OnSomethingHappenedNotification<>).MakeGenericType(poco.GetType());
object notification = Activator.CreateInstance(type, poco);
mediatr.Publish(notification!);

``` 

The handler is not invoked, I'm using  standard MS DI Container with `services.AddMediatR()`

**Comment by jbogard** [comment]
Yeah that doesn't work with the standard DI container. You'll have to use a container with more sophisticated registration capabilities.

**Comment by jvmlet** [comment]
Is there sample with `Autofac` ?

**Comment by jvmlet** [comment]
Or maybe  nuget with `MediatR` `Autofac` module  ?

**Comment by jvmlet** [comment]
Hm, according to the autofac's [docs ](https://autofac.readthedocs.io/en/latest/register/registration.html#open-generic-components)   I can reguster handler as generic type. 
The question is can MediatR resolve the handler if it's generic type?
