### ISSUE TITLE
Performance analysis of IPipelineBehavior for validation

### ISSUE THREAD

**Issue by arslanaybars** [jbogard/MediatR#813]
I use ```IPipelineBehavior``` with ```FluentValidation``` for validating my requests.

Most of us probably already use ```ValidationBehavior``` like **[CleanArchitecture](https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/Application/Common/Behaviours/ValidationBehaviour.cs)**    sample

But when I made a load test. I can receive three times as many responses without this pipeline behavior.

Example:

With  ```IPipelineBehavior```
![image](https://user-images.githubusercontent.com/3358953/209563838-e0011e38-812e-4b55-a786-c8acd1b2b042.png)

Without ```IPipelineBehavior```
![image](https://user-images.githubusercontent.com/3358953/209563881-fa7a7dfe-e31d-4356-89ec-859b001704f0.png)

I used [k6](https://k6.io/) for load testing.

Is this expected result or are there any suggestions to make it better?

Here is my ```ValidationBehavior``` class

```csharp
public class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
{
    private readonly IEnumerable<IValidator<TRequest>> _validators;

    public ValidationBehavior(IEnumerable<IValidator<TRequest>> validators)
    {
        _validators = validators;
    }

    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        if (!_validators.Any())
        {
            return await next();
        }
        
        var context = new ValidationContext<TRequest>(request);

        var validationResults = await Task.WhenAll(
            _validators.Select(v => v.ValidateAsync(context, cancellationToken)));
                
        var failures = validationResults
            .SelectMany(r => r.Errors)
            .Where(f => f != null)
            .ToArray();

        if (failures.Any())
        {
            throw new ValidationException(failures);
        }

        return await next();
    }
}
```

**Comment by neozhu** [comment]
try this
```
 public Task<TResponse> Handle(TRequest request, RequestHandlerDelegate<TResponse> next, CancellationToken cancellationToken)
    {
        if (_validators.Any())
        {
            foreach (var validator in _validators)
                validator.ValidateAndThrowAsync(request, cancellationToken);
        }
        return  next();
    }

**Comment by arslanaybars** [comment]
@neozhu  I tried but it doesn't affect with a big difference

**Comment by kentaasvang** [comment]
If you're throwing a lot of exceptions during your stress-test than I would suspect that to be the culprit

**Comment by arslanaybars** [comment]
I made the test in the happy path case so it means I don't throw any exceptions. 🤔

**Comment by PeterKneale** [comment]
What work is actually being performed in your handler? At just 3ms i'd be curious if you are actually reading / writing anything out of process.

I did a quick investigation into the perf impact of using something similar for both validation and logging some time back but after benchmarking found that if my handler was performing an out of process action like reading or writing to a database, cache or filesystem then the impact of the pipeline components was almost imperceptable compared to the overall duration (ie XXms for handler and XXXus for the pipeline).

This is inline with what more succintly here Jimmy says here:
https://jimmybogard.com/you-probably-dont-need-to-worry-about-mediatr/
> My handlers always hit a database or something, so anything MediatR does is a drop in the bucket

**Comment by jbogard** [comment]
See #828 , it might help with this as I won't register the built-in behaviors if they're not needed
