### ISSUE TITLE
Process events in isolation

### ISSUE THREAD

**Issue by MeTitus** [jbogard/MediatR#82]
It would be nice if you could pass in a parameter to the publish method, or a global configuration which allowed events to be processed in isolation, i.e.: if one fails should it continue processing the next ones. This is happening in a process but in between states, using aspects I might want to add a queue just to persist some messages. Also if I add in transactions my Unit of Work will be quite expensive if I have a couple of handlers per event.

Just an idea:

```
    public void Publish(INotification notification, ref IEnumerable<FailedNotificationHandlerWrapperExecution> failedHandlers, bool processInIsolation = false)
    {
        var notificationHandlers = GetNotificationHandlers(notification);

        if(!processInIsolation)
        {
            notificationHandlers.ToList().ForEach(x => handler.Handle);
        }
        else
        {
            var failHandlers = new List<FailedNotificationHandlerWrapperExecution>();

            foreach (var handler in notificationHandlers)
            {
                try
                {
                    handler.Handle(notification);
                }
                catch(Exception ex)
                {
                    failHandlers.Add(handler, ex);
                }
            }
        }
    }
```

**Comment by jbogard** [comment]
Can you build your own MediatR pipeline for events like you can for
commands?

**Comment by MeTitus** [comment]
Hi Jimmy,

thanks for your reply, but I'm not sure what you're referring to. As it stands if I have a chain of handlers, if one fails the whole thing rollbacks and the remaining handlers are not processed. I know this is a Mediator not an actual esb, but it would be nice if I could, by I means of configuration set whether a failing handler should stop the rest of the execution.

**Comment by jbogard** [comment]
So do this:

https://lostechies.com/jimmybogard/2014/09/09/tackling-cross-cutting-concerns-with-a-mediator-pipeline/

And wrap your event handlers with whatever behavior you want.

**Comment by MeTitus** [comment]
Yes you can use aspects but that just requires a adding extra code which could be easily provided by the library itself.

**Comment by jbogard** [comment]
Soooo one of the goals of MediatR is to *not* provide this by the library. You can add your own behavior via containers or manual DI, and I'll never be able to address the infinite scenarios I could imagine would be possible in a processing pipeline.

**Comment by MeTitus** [comment]
Jimmy, where abouts in the code in my OP do you see any custom behavior? It would be impossible to cover all the infinite scenarios as you say, but that's not even what I'm talking about :P

**Comment by MeTitus** [comment]
Jimmy, where abouts in the code in my OP do you see any custom behavior? It would be impossible to cover all the infinite scenarios as you say, but that's not even what I'm talking about :P

**Comment by MeTitus** [comment]
Jimmy, where abouts in the code in my OP do you see any custom behavior? It would be impossible to cover all the infinite scenarios as you say, but that's not even what I'm talking about :P

The Idea is just to wrap the call to an event in a try/catch, and if set to process in isolation just catch the exception and move on and this is different from having a UoW which is what I think you though I was talking about.

**Comment by MeTitus** [comment]
Probably the best way to implement this would be to create an interface

`public inteface IMediatorConfiguration
{
     bool ProcessInIsolation {get; set;}
}`

and have it set as a property in the IMediator interface, otherwise, like my sample in the OP, it would be necessary to create overloads for a few of the methods.

**Comment by jbogard** [comment]
My other goal is to not have any configuration for MediatR. This example is simple - yes, but I could still see other people wanting more. Transactions, parallel or not parallel dispatching etc.

Could this be solved by making something in the Mediator class virtual, so that you could subclass and override? I can see that would be easier versus container configuration.

**Comment by MeTitus** [comment]
Yes that will do. In terms of the configuration, it wouldn't need to be mandatory that's why I said it could be set as a property in the IMediator rather than as a constructor dependency, but you should now that as more and more requests start coming along, it will be difficult to move forward without having some sort of configuration, even if it is like the model used in the NServiceBus, which is what I think it would be nice to have

`class CustomizingHost : IConfigureThisEndpoint
{
    public void Customize(BusConfiguration busConfiguration)
    {
        // To customize, use the configuration parameter.
        busConfiguration.UseSerialization<JsonSerializer>();
        busConfiguration.UsePersistence<InMemoryPersistence>();
    }
}`

**Comment by jbogard** [comment]
I just added the ability to subclass MediatR and allow you to have complete control over Publish. Just override PublishCore and do what you like!
