### ISSUE TITLE
Create marker interface for handler

### ISSUE THREAD

**Issue by MeTitus** [jbogard/MediatR#83]
Hi Jimmy,

It would be nice if you could add a marker interface (IRequestHandler) and make all handler interfaces extend this interface, this would allow me to register all handlers in one go like so:

**Without marker interface**

```
                builder.RegisterAssemblyTypes(AssemblyUtils.GetAssemblies)
                    .AsClosedTypesOf(typeof(IRequestHandler<,>))
                    .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies)
                    .AsImplementedInterfaces();

                builder.RegisterAssemblyTypes(AssemblyUtils.GetAssemblies)
                    .AsClosedTypesOf(typeof(IAsyncRequestHandler<,>))
                    .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies)
                    .AsImplementedInterfaces();

                builder.RegisterAssemblyTypes(AssemblyUtils.GetAssemblies)
                    .AsClosedTypesOf(typeof(INotificationHandler<>))
                    .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies)
                    .AsImplementedInterfaces();

                builder.RegisterAssemblyTypes(AssemblyUtils.GetAssemblies)
                    .AsClosedTypesOf(typeof(IAsyncNotificationHandler<>))
                    .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies)
                    .AsImplementedInterfaces();

                builder.RegisterAssemblyTypes(AssemblyUtils.GetAssemblies)
                    .Where(t => t.IsClass && typeof(IRepository).IsAssignableFrom(t))
                    .AsImplementedInterfaces()
                    .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies)
                    .InstancePerRequest();
```

**With marker interface**

```
                builder.RegisterAssemblyTypes(AssemblyUtils.GetAssemblies)
                    .AsClosedTypesOf(typeof(IRequestHandler))
                    .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies)
                    .AsImplementedInterfaces();
```

**Comment by valdisiljuconoks** [comment]
What about `serviceCollection.AddMediatR();` or .Net Core is not an option for you?

**Comment by MeTitus** [comment]
@valdisiljuconoks I can't see how that is related to the request tbh.

**Comment by valdisiljuconoks** [comment]
Yes, I got your idea. Nevermind :)

**Comment by jbogard** [comment]
So would this apply to notification handlers too?

**Comment by MeTitus** [comment]
@jbogard I would say so - it would be nice to be able to register all the handlers in one go.

**Comment by jbogard** [comment]
Does this actually work for your container? It doesn't for a couple I tried - I have to pass in an actual open generic type to scan for.

**Comment by MeTitus** [comment]
Hi Jimmy, it does work yes but your marker interface would have to be non-generic, something like this would do:

    public interface IRequestHandler
    { }

    public interface IRequestHandler<..> : IRequestHandler
    { }

**Comment by jbogard** [comment]
So what does it look like? I'm happy to entertain a PR, then you could modify the container config of your choice so that I get an idea.

**Comment by MeTitus** [comment]
I think we aren't on the same boat Jimmy, but in either case this is an example:

`    public interface IRepository
    { }

    public interface IRepository<T> : IRepository
    { }

    builder.RegisterAssemblyTypes(assemblies)
                .Where(t => typeof(IRepository).IsAssignableFrom(t).IsAssignableFrom(t))
                .AsImplementedInterfaces()
                .InstancePerDependency()
                .PropertiesAutowired();`

I get all the generic types registered, that's why I said in the OP that you would have to introduce a non-generic type, to act as a marker.

**Comment by jbogard** [comment]
Would you be able to get a PR with the marker interface, and modified container config in the examples to show it working? I'm happy to add it - unless the containers don't actually support this ability. A PR would show me that it does :)

**Comment by MeTitus** [comment]
Give me a few days and all do it, just been caught in the middle of some serious work.

**Comment by valdisiljuconoks** [comment]
ping

**Comment by remcoros** [comment]
.AsClosedTypesOf(typeof(IRequestHandler))

This is not possible with Autofac and can't imagine with any container, as with only an IRequestHandler, you know nothing about its inheritors without first scanning them.

https://github.com/autofac/Autofac/blob/4a75106b7f7dbf0d62f5452f3c3f0d58333df414/src/Autofac/Features/Scanning/ScanningRegistrationExtensions.cs#L118

https://github.com/autofac/Autofac/blob/41044d7d1a4fa277c628021537d5a12016137c3b/src/Autofac/TypeExtensions.cs#L83

**Comment by MeTitus** [comment]
Allow me disagree. This works fine in a setup I have:

` public interface IRepository
    { }

    public interface IRepository<T> : IRepository where T : class, new()
    { }
...

            builder.RegisterAssemblyTypes(AssemblyUtils.Assemblies)
                .Where(t => typeof(IRepository).IsAssignableFrom(t))
                .AsImplementedInterfaces()
                .InstancePerDependency()
                .PropertiesAutowired();`

All implementations of IRepository<T> will be registered, so I'm not really sure what you are talking about. Been very busy and working with a difference stack now, that's why I didnt implement it myself.

**Comment by jbogard** [comment]
Like i mentioned earlier, if you can show a PR with how it simplifies
registration and the tests pass, I’m all for it.

**Comment by jbogard** [comment]
Closed due to inactivity.
