### ISSUE TITLE
Migration question

### ISSUE THREAD

**Issue by steveoh** [jbogard/MediatR#832]
Based on https://github.com/jbogard/MediatR/wiki/Migration-Guide-9.x-to-10.0 you recommend adding 

`where TRequest : IRequest<TResponse>`

I have a couple of validation behaviors that set the request and response like 

```cs
public class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : Query
        where TResponse : ObjectResult {
```

where Query is

```cs
public class Query : IRequest<ObjectResult>
```

and it's registered with autofac by

```cs
services.AddTransient<IPipelineBehavior<GeocodeQuery.Query, ObjectResult>,
                GeocodeQuery.ValidationBehavior<GeocodeQuery.Query, ObjectResult>>();
```

Pardon my ignorance, but I'm trying to pick up this project after a few years and just started with upgrading to net 7 and updating dependencies. 

Was I abusing the API prior to this change? Am I able to complete this migration or will I need significant change?

I plan to keep familiarizing myself with this code base again and may have a solution by the time you read this. If so, I'll close it, otherwise, I would love any suggestions you might have.

Can I simply 

```cs
public class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
        where TRequest : Query, IRequest<TResponse>
        where TResponse : ObjectResult {
```

**Comment by jbogard** [comment]
Well...I'm looking at reverting that because it seems to have caused more problems. Maybe hold off on this one.

**Comment by jbogard** [comment]
See the release notes:

https://github.com/jbogard/MediatR/releases/tag/v12.0.0

And upgrade guide:

https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0
