### ISSUE TITLE
PipelineBehaviour not working .NET 7

### ISSUE THREAD

**Issue by fernanduandrade** [jbogard/MediatR#833]
Good evening! I tried to follow the approach to use PipelineBehaviour with FluentValidation and it's not working with .NET 7, although the Logging behaviour works just fine. Can someone help with this problem?

here's the behaviour validation -> https://github.com/fernanduandrade/clean-architecture-api/blob/main/Bot.Application/Common/Behaviours/ValidationBehavior.cs

the depedency injection -> https://github.com/fernanduandrade/clean-architecture-api/blob/main/Bot.Application/ConfigureServices.cs

and a simple validation for testing -> https://github.com/fernanduandrade/clean-architecture-api/blob/main/Bot.Application/Event/Validations/EventCommandValidator.cs

**Comment by jbogard** [comment]
I suggest writing some tests against the container directly and working backwards from there. MediatR merely delegates to the container to resolve services.

**Comment by fernanduandrade** [comment]
I got it work, thanks for the tip =D
