### ISSUE TITLE
errors upgrading from version 10 to 11

### ISSUE THREAD

**Issue by lucamorelli** [jbogard/MediatR#837]
Hi, I upgraded a solution from ver 10 to 11 and now I receive an error for every request class that is not defining a return type using : IRequest

`The type '....' cannot be used as type parameter 'TRequest' in the generic type or method 'IRequestHandler<TRequest, TResponse>'. There is no implicit reference conversion from '...' to 'MediatR.IRequest<MediatR.Unit>'.
`
the only way I see to fix it is convert to IRequest<Unit>. 
Do I have to do this? I have seen no notice of deprecation or anything related to this. I have upgraded to the latest version the **Mediatr**, **Mediatr.Contracts** and **Mediatr.Extensions.Microsoft.DependencyInjection** packages

**Comment by jbogard** [comment]
I'm in the process of putting out a new major version, so this should all be resolved shortly. In the meantime, do NOT update your `MediatR.Contracts` package, that's going to target the next (imminent) release.

**Comment by lucamorelli** [comment]
ok, thanks

**Comment by jbogard** [comment]
See the release notes:

https://github.com/jbogard/MediatR/releases/tag/v12.0.0

And upgrade guide:

https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0
