### ISSUE TITLE
System.TypeLoadException on v12

### ISSUE THREAD

**Issue by ducanhtk5** [jbogard/MediatR#840]
I received an error: System.TypeLoadException: Could not load type 'MediatR.ServiceFactory' from assembly 'MediatR, Version=12.0.0.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'.

**Comment by ducanhtk5** [comment]
@jbogard Please check this urgent bug.
My project information:
.NET 7.0.3 (latest today).
Type: Aspnetcore MVC

Thank you!

**Comment by normandev92** [comment]
I also got this issue

**Comment by jackthip** [comment]
Please try 
```
builder.Services.AddMediatR(cfg =>
{
    cfg.RegisterServicesFromAssemblies(typeof(Startup).Assembly, typeof(YourHandler).Assembly);
});
```
Ref: https://github.com/jbogard/MediatR/releases

**Comment by alex289** [comment]
> @normandev92 @ducanhtk5 Please try.
> 
> ```
> builder.Services.AddMediatR(cfg =>
> {
>     cfg.RegisterServicesFromAssemblies(typeof(Startup).Assembly, typeof(YourHandler).Assembly);
> });
> ```
> 
> Ref: https://github.com/jbogard/MediatR/releases

Hey, this works for me but what if I dont have a Startup?

**Comment by deeprobin** [comment]
Can confirm. Since upgrading my application crashes.

**Comment by petrechitashvili** [comment]
Same issue here

**Comment by RoelVerhees** [comment]
Same issue, was working before

**Comment by andyamacdonald** [comment]
> @normandev92 @ducanhtk5 Please try.
> 
> ```
> builder.Services.AddMediatR(cfg =>
> {
>     cfg.RegisterServicesFromAssemblies(typeof(Startup).Assembly, typeof(YourHandler).Assembly);
> });
> ```
> 
> Ref: https://github.com/jbogard/MediatR/releases

That sort of worked for me however due to change breaking changes in v12 I've ported any handlers which implemented `AsyncRequestHandler` to implement `IRequestHandler`. Those handlers are still breaking with the following error:

```
No service for type 'MediatR.IRequestHandler`1[Path,To.Command]' has been registered
```

An example command would be:

```
public record DeleteUnavailableTimeCommand(Guid Id) : IRequest;
```

With a corresponding handler:

```
public class DeleteUnavailableTime : IRequestHandler<DeleteUnavailableTimeCommand>
```

Previously the handler would have been defined as:

```
public class DeleteUnavailableTime : AsyncRequestHandler<DeleteUnavailableTimeCommand>
```

**Comment by ducanhtk5** [comment]
> @normandev92 @ducanhtk5 Please try.
> 
> ```
> builder.Services.AddMediatR(cfg =>
> {
>     cfg.RegisterServicesFromAssemblies(typeof(Startup).Assembly, typeof(YourHandler).Assembly);
> });
> ```
> 
> Ref: https://github.com/jbogard/MediatR/releases

Good now. Thank you!

**Comment by jamiewinder** [comment]
> > @normandev92 @ducanhtk5 Please try.
> > ```
> > builder.Services.AddMediatR(cfg =>
> > {
> >     cfg.RegisterServicesFromAssemblies(typeof(Startup).Assembly, typeof(YourHandler).Assembly);
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ref: https://github.com/jbogard/MediatR/releases
> 
> Hey, this works for me but what if I dont have a Startup?

Here you're just referencing a type that contains MediatR's services (handlers, etc.). It doesn't need to be the Startup class.

**Comment by FaizulHussain** [comment]
I've had the same problem today after upgrading to version 12.0

this worked for me too:

`builder.Services.AddMediatR(cfg =>
{
    cfg.RegisterServicesFromAssemblies(typeof(BaseHandler).Assembly);
});`

**Comment by jbogard** [comment]
See the release notes:

https://github.com/jbogard/MediatR/releases/tag/v12.0.0

And upgrade guide:

https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0
