### ISSUE TITLE
SimpleInjector IMediator registration

### ISSUE THREAD

**Issue by rnarayana** [jbogard/MediatR#842]
In the SimpleInjector sample, it says to Register IMediator this way:

`container.RegisterSingleton<IMediator, Mediator>();`

However I could make it work only by:

`container.RegisterInstance(typeof(IMediator), new Mediator(container));`

as now there are 2 public constructors for Mediator.

SimpleInjector version: 5.4.1
MediatR version: 12.0.0

Shall I raise a PR if this is correct?

**Comment by jbogard** [comment]
See the release notes:

https://github.com/jbogard/MediatR/releases/tag/v12.0.0

And upgrade guide:

https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0

**Comment by jwagon** [comment]
@jbogard Can you point us to the specific area of the migration guide that addresses this, and/or why @rnarayana 's workaround isn't the way to go here? I don't see anything except a note that there's been a constructor added. Thanks!

**Comment by jbogard** [comment]
I don't use SimpleInjector, but it's a wiki so feel free to add your notes or add a PR. I have no idea lol
