### ISSUE TITLE
IPipelineBehaviour does not run for IRequest

### ISSUE THREAD

**Issue by stefannikolei** [jbogard/MediatR#843]
After updating to V12 i have the problem that my pipelines do not run for requests which just implement IRequest.

I had to remove Unit as TResponse from my Handler

Before:

`MyHandler: IRequestHandler<MyRequest, Unit>`

After the update:
`MyHandler: IRequestHandler<MyRequest>`

After this change the Pipelines are not running. When i change my Request from
`MyRequest: IRequest`
to:
`MyRequest: IRequest<Unit>`

the pipelines are running again.

**Comment by stefannikolei** [comment]
Ok i have to add something. I think the problem is how i register my IPipelineBehaviors.

I add them to the DI by using this:

`services.AddScoped(typeof(IPipelineBehavior<,>), typeof(MyPipeLineBehaviour<,>));`

the pipeline is defined like this

`public class MyPipeLineBehaviour<TIn, TOut> : IPipelineBehavior<TIn, TOut>
    where TIn : IRequest<TOut>`


Before the update the pipeline ran for all Requests. Now i am having trouble with my approach.

**Comment by jbogard** [comment]
See the release notes:

**Comment by stefannikolei** [comment]
Ty. I overlooked that part in the migration guide. Sorry for the noise.

Replacing the constraint `where TIn : IRequest<TOut ` with `where TIn : notnull` fixed my problems.

**Comment by jbogard** [comment]
Well I JUST made the migration guide this morning. Hard to get this all out together!

**Comment by stefannikolei** [comment]
Yeah and a dependabot picks it up immediately. 

But good job on this release. Removing the necessity for Unit
