### ISSUE TITLE
BUG - register open generic pipeline

### ISSUE THREAD

**Issue by don-flamingo** [jbogard/MediatR#846]
Hey! 

I have pulled the newest 12.00 MediatR version into my modular monolith application.
Previously, I registered my validation pipeline as the code:
```C#
    public static IServiceCollection AddPipelinesModule(this IServiceCollection serviceCollection) =>
        serviceCollection.AddScoped(typeof(IPipelineBehavior<,>), typeof(ValidationPipeline<,>));
```
After migration, the validation doesn't work correctly. I have checked the lib methods and transformed the upper piece of code into

```C#
builder.Services
    .AddMediatR(cfg =>
    {
        cfg.AddOpenBehavior(
            typeof(ValidationPipeline<,>));
        cfg.RegisterServicesFromAssembly(typeof(Program).Assembly);
    });
```

**But still without success.** 

_Btw. when I have skipped **RegisterServicesFromAssembly(typeof(Program).Assembly);** the library throws an exception - no assemblies to scan. It's problematic because a program is only a shared entry point to my app._

My app looks like this:
WebApi - Controllers, Entrypoint,
ModuleA - Logic for A, Command handlers,
ModuleB - logic for B, Bommand handlers,
etc.

**Comment by marcantoinecouture** [comment]
I have the same problem in my application.

**Comment by jbogard** [comment]
Have a repro? The tests look fine here.

**Comment by don-flamingo** [comment]
Looks like it happens when I have IRequestHandler<Command> implementation without returning anything.

**Comment by don-flamingo** [comment]
Ok, I Found it. 
It happens when Pipeline implementation looks like

```C#
public class ValidationPipeline<TRequest, TResponse> :
    IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest<TResponse>
```

When I changed into

```C#
public class ValidationPipeline<TRequest, TResponse> :
    IPipelineBehavior<TRequest, TResponse>
    where TRequest : IRequest
```

Void pipelines works correctly, but.... 
When handler return something, in the upper case not working.

So, currently to hack it, I must have 2 pipelines instead of 1.

**Comment by jbogard** [comment]
Did you follow the upgrade guide?

**Comment by jbogard** [comment]
I added a big bold message to also correct your behaviors:

https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0

That will fix your issue.
