### ISSUE TITLE
Suggestion: change Handle to HandleAsync

### ISSUE THREAD

**Issue by JCKodel** [jbogard/MediatR#85]
I was rendering a partial action in MVC (Html.RenderAction) and it cannot be async.

It would be nice to be able to implement both IRequestHandler and IHandler in the same query, so I can choose between async and normal methods, but a async Task<X> and a void X are the same for C# (it says they are identical signarures).

Changing the IAsyncRequestHandler.Handle method to IAsyncRequestHandler.HandleAsync not only solves that kind of issue, but also conforms to the C# nomenclature, where async methods should end in Async.

**Comment by jbogard** [comment]
In general I don't like a handler implementing both interfaces. It's a bit odd. You can do explicit implementation if you really like.
