### ISSUE TITLE
My behaviors no longer work after Mediatr 12

### ISSUE THREAD

**Issue by ffMathy** [jbogard/MediatR#851]
Here's how I register my behavior:

```csharp
services.AddMediatR(x =>
        {
            x.AddOpenBehavior(typeof(DatabaseTransactionBehavior<,>), ServiceLifetime.Scoped);
            x.Lifetime = ServiceLifetime.Transient;
            x.RegisterServicesFromAssemblies(assemblies);
        });
```

A breakpoint confirms that this registration is indeed being hit.

However, if I set a breakpoint within `DatabaseTransactionBehavior`, it doesn't ever run for any commands.

It worked with Mediatr 11, and the only thing I changed was the registration call. Before I was explicitly registering my behaviors - now I am using `AddMediatr`.

**Comment by ffMathy** [comment]
I should RTFM.

I read the migration notes, and it was because my `DatabaseTransactionBehavior` had a generic constraint of `IRequest<TResponse>` instead of `notnull`.

**Comment by jbogard** [comment]
Maybe I can make it big and bold or something that YOUR BEHAVIORS WILL BREAK. You're not the only one!

**Comment by ffMathy** [comment]
I think it's because it was such a subtle change. I think many people are kind of practical, and will just try to update Mediatr and see what errors the compiler produces.

And if that then produces a proper "runnable" result with no exceptions, they expect it to be fine and won't read the migration guide.

That's what happened in my case 😄
