### ISSUE TITLE
11.x to 12.0 migration says that IRequest no longer inherits IRequest<Unit>in MediatR.Contracts, but this isn't true

### ISSUE THREAD

**Issue by asimmon** [jbogard/MediatR#853]
In the [11.x to 12.0 migration guide](https://github.com/jbogard/MediatR/wiki/Migration-Guide-11.x-to-12.0), it is said that:
> `IRequest` does not inherit `IRequest<Unit>` instead `IBaseRequest`

While this is true in the current state of the master branch, this isn't true for the latest 2.0.0 package of the [MediatR.Contracts](https://www.nuget.org/packages/MediatR.Contracts/#versions-body-tab) nuget package that was released 12 days ago.

A quick look inside the package using [nuget.info](https://nuget.info/packages/MediatR.Contracts/2.0.0) shows that the actual commit for `IRequest` on version 2.0.0 is this:
https://raw.githubusercontent.com/jbogard/MediatR/528a6ccf552afeea4a1c11e83177b77df85124b0/src/MediatR.Contracts/IRequest.cs

Is it a documentation mistake or was the change accidentely not published?

**Comment by jbogard** [comment]
I didn't want to believe you but ooooof you're right. Mistake on my part. I'll get some updated packages (and delist the existing ones) today.
