### ISSUE TITLE
Signed / Strong named release of MediatR

### ISSUE THREAD

**Issue by jesuissur** [jbogard/MediatR#86]
Hi there

Our systems used signed assemblies and we'd like to integrate MediatR in it.  Could it be possible to sign MediatR component on future releases?

Thanks
Phil

**Comment by jbogard** [comment]
Nope, sorry. Strong-naming is basically useless at this point and won't be honored in .NET Core.

BUT you can use StrongNamer to add the strong name yourself, at build time. It works great if you're forced to use strong naming: https://github.com/dsplaisted/strongnamer

**Comment by jesuissur** [comment]
Thanks Jimmy.
We'll use StrongNamer because we are indeed forced to use signed assemblies.
Bye
