### ISSUE TITLE
it is possible to have a single handler class handle multiple messages?

### ISSUE THREAD

**Issue by mgmccarthy** [jbogard/MediatR#87]
example:
```
public class NotificationClass1  : IAsyncNotification
{
}

public class NotificationClass2  : IAsyncNotification
{
}

public HandlerForMoreThenOneNotification : IAsyncNotificationHandler<NotificationClass1>,
 IAsyncNotificationHandler<NotificationClass2>
{

    public async Task Handle(NotificationClass1 notification)
    {
    }

    public async Task Handle(NotificationClass2 notification)
    {
    }

    private method SomeSharedCodeThatHandlingBothMessagesCouldUse()
    {
    }
}
```

**Comment by jbogard** [comment]
Yeah, but why?

**Comment by mgmccarthy** [comment]
being an NSB user, sometimes I'll have one class handle two different messages b/c there is processing to be done between both messages that can utilize the same code.

So I've written code like this before:
```
public class HandleStuff : IHandleMessages<Message1>, IHandleMessages<Message2>
```

then in each `Handle` method, I'll invoke a private method on that class that would do some work both handlers need.

I realize I could also try polymorphic messaging (I think MediatR supports this?), but figured I'd ask first.

**Comment by jbogard** [comment]
MediatR supports whatever your underlying container supports, so you can certainly do what you're describing in most containers I'm aware of.

**Comment by mgmccarthy** [comment]
this works for ASP.NET Core RC1 and it looks like this is working out of the box with the way we have our container wired up, so you can close this Issue. Thanks!
