### ISSUE TITLE
Unit's IComparable.CompareTo should throw ArgumentException when obj is not of type Unit

### ISSUE THREAD

**Issue by vjacquet** [jbogard/MediatR#875]
Hello,

As it is currently implemented, CompareTo always return 0, meaning equality, for objects of any type or even for null references.
https://github.com/jbogard/MediatR/blob/a9e032dbf3d19aff0212fb12e4ba2c79450e61f4/src/MediatR.Contracts/Unit.cs#L47

This is inconsistent with Equals that correctly returns true only when the parameter is of the same type.
https://github.com/jbogard/MediatR/blob/a9e032dbf3d19aff0212fb12e4ba2c79450e61f4/src/MediatR.Contracts/Unit.cs#L73

IComparable contract states that [CompareTo](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable.compareto?view=net-7.0#system-icomparable-compareto(system-object)) throws ArgumentException when obj  is not the same type as this instance.

A possible implementation could be
```csharp
int IComparable.CompareTo(object? obj) => obj is Unit ? 0 : throw new ArgumentException();
```

**Comment by jbogard** [comment]
What issue is this causing for you?

**Comment by vjacquet** [comment]
None, but is it relevant?
Well, I guess it is, because even though it is probably inconsequential, fixing it would be a breaking change.
