### ISSUE TITLE
Unable to resolve service for type X while attempting to activate Handler

### ISSUE THREAD

**Issue by tihomir-kit** [jbogard/MediatR#887]
Hi, I recently tried upgrading a solution to MediatR 12 which was previously working fine with with MediatR 11. Now I'm getting this error and I can't figure out what's wrong:

`System.InvalidOperationException: Unable to resolve service for type 'XXX.Core.Auth.Token.IJwtTokenProvider' while attempting to activate 'XXX.Core.Application.Handlers.Account.Login+Handler'.`

`IJwtTokenProvider` is just a simple service registered in DI: `container.Register<IJwtTokenProvider, JwtTokenProvider>();`

The `Login` command is in the `XXX.Core.Application` project. `Program.cs` is in `XXX.WebAPI` project.

If I try to inject and access `IJwtTokenProvider` inside `AccountController` (which normally dispatches the Login command), I can access the `IJwtTokenProvider` without problems. However, it seems there's some issue between MediatR and SimpleInjector when I inject `IJwtTokenProvider` inside the Login handler. Also, it's not `IJwtTokenProvider` specifically that's the problem, it's other injected services as well.

This is my Program.cs (.net6)

```cs
var container = ContainerFactory.CreateSimpleInjectorContainer();
var builder = WebApplication.CreateBuilder(args);
var services = builder.Services;
var appSettings = new AppSettings(builder.Configuration);
var appEnvironment = new AppEnvironment(appSettings);

builder.Host.UseDefaultServiceProvider((context, options) => options.ValidateOnBuild = false);

services.AddApplicationInsightsTelemetry();
services.AddIdentityServices(appEnvironment);
services.AddJwtAuthentication(appSettings);
services.AddWebApiServices(appSettings);
services.AddSwaggerServices(appSettings);
services.AddSimpleInjector(container);
services.AddMemoryCache();

if (appEnvironment.IsDev())
{
    services.AddMiniProfiler();
}

// .Initialize() is my extension method where DI bindings for all the layters of the solution are set up
container.Initialize(appSettings, appEnvironment); 

var app = builder.Build();

app.Services.UseSimpleInjector(container);

if (appEnvironment.IsDev())
{
    app.UseDeveloperExceptionPage();
}

app.UseMiddleware<ExceptionHandlingMiddleware>();
app.UseLLBLGen(appSettings);
app.UseRouting();
app.UseCors(AppConfigOptions.DefaultCorsPolicyName);
app.UseAuthentication();
app.UseAuthorization();
app.UseSwagger(appSettings); 

if (appEnvironment.IsDev())
{
    app.UseMiniProfiler();
}

app.UseEndpoints
(
    endpoints =>
    {
        endpoints.MapControllers();
    }
);

container.Verify();

app.Run();
```

This is my MediatR 11 config which works fine:

```cs
public static void RegisterPipeline(this Container container, Assembly[] assemblies)
{
    container.RegisterSingleton<IMediator, Mediator>();
    container.Register(typeof(IRequestHandler<,>), assemblies);

    container.RegisterHandlers(assemblies);
    container.RegisterBehaviors();

    container.Register(() => new ServiceFactory(container.GetInstance), Lifestyle.Singleton);
}

private static void RegisterHandlers(this Container container, Assembly[] assemblies)
{
    container.RegisterHandlers(typeof(INotificationHandler<>), assemblies);
    container.RegisterHandlers(typeof(IRequestExceptionAction<,>), assemblies);
    container.RegisterHandlers(typeof(IRequestExceptionHandler<,,>), assemblies);
}

private static void RegisterHandlers(this Container container, Type collectionType, Assembly[] assemblies)
{
    var handlerTypes = container.GetTypesToRegister
    (
        collectionType,
        assemblies,
        new TypesToRegisterOptions
        {
            IncludeGenericTypeDefinitions = true,
            IncludeComposites = false
        }
    );

    container.Collection.Register(collectionType, handlerTypes);
}

private static void RegisterBehaviors(this Container container)
{
    container.Collection.Register
    (
        typeof(IPipelineBehavior<,>),
        new[]
        {
            // NOTE: Add additional behaviors here. Order of binding = order of execution.
            typeof(RequestExceptionProcessorBehavior<,>),
            typeof(RequestExceptionActionProcessorBehavior<,>),
            typeof(AuthenticationBehavior<,>),
            typeof(AuthorizationBehavior<,>),
            typeof(ValidationBehavior<,>),
            typeof(MemoryCachedBehavior<,>),
            typeof(DbTransactionalBehavior<,>)
        }
    );
}
```

Mediatr 12 changes:

```cs
public static void RegisterPipeline(this Container container, IServiceCollection services, Assembly[] assemblies)
{
    container.RegisterSingleton<IMediator>(() => new Mediator(services.BuildServiceProvider()));
    container.Register(typeof(IRequestHandler<,>), assemblies);

    container.RegisterHandlers(assemblies);
    container.RegisterBehaviors();

    services.AddMediatR(config => config.RegisterServicesFromAssembly(typeof(Login).Assembly));
    // I also tried these two, but I'm under the assumption that I need to register the assembly where the Login handler is?
    // services.AddMediatR(config => config.RegisterServicesFromAssembly(typeof(Program).Assembly));
    // services.AddMediatR(config => config.RegisterServicesFromAssemblies(Assembly.GetExecutingAssembly()));
}
```

Any rough ideas on what I might be doing wrong?

Thank you.

**Comment by jbogard** [comment]
When you bring in other DI containers, they'll often have their own implementations of things. In general, don't build the service provider yourself. But you shouldn't be registering `IMediator` at all, `AddMediatR` already does that. I would look at the docs for `AddMediatR` and what it registers, and ONLY register anything else that it doesn't.

**Comment by tihomir-kit** [comment]
Is [this sample](https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.SimpleInjector/Program.cs) up to date? 

I'm obviously misunderstanding something but that's where I got the `IMediator` singleton bit from (probably.. as the initial setup was with MediatR 8 maybe 2 years ago or something like that). 

After the upgrade from 11 to 12 and after some googling around I found `container.Register<IMediator>(() => new Mediator(services.BuildServiceProvider()));` as a suggested fix for `container.Register<IMediator, Mediator>();` no longer working. So that explains it (to me) why I was even doing that registraiton).

AddMediatR is also only being used in AspNetCore sample. Perhaps that's where I should focus on.

**Comment by jbogard** [comment]
No, none of those samples are up to date. It takes me a bit to update those since I really only use either the vanilla container or Lamar. Probably I'll come back through and update them to use the various extensions of Ms.Ext.DI. I'm sure there are folks NOT using MS.Ext.DI but I'm not one of them.

**Comment by tihomir-kit** [comment]
Ok, that helps. Thnx!
