### ISSUE TITLE
IRequestExceptionAction invocation issues

### ISSUE THREAD

**Issue by nobugsincode** [jbogard/MediatR#890]
I have a custom exception defined in my project ```public class CustomException : Exception```.
To log the exception I'm trying to use 2 approaches: one using ```IRequestExceptionAction<TRequest>``` and the second using ```IRequestExceptionAction<TRequest, TException>```.
MediatR registered in the service collection via ```services.AddMediatr(config => ...)```

### Problem
When I throw ```CustomException``` in one of my RequestHandlers I'm getting an invalid log lines in my console.

### Expected behavior
I see a single log line for the exception thrown

### Actual behavior
I see two log lines for same exception.
Implementation of ```IRequestExceptionHandler<TRequest>``` not called at all. 

### Questions

Is it a bug or it's a desired behavior? I'm asking because multiple actions found [here](https://github.com/jbogard/MediatR/blob/513c20214a84d7486d50eddf9eea8591c7360894/src/MediatR/Pipeline/RequestExceptionActionProcessorBehavior.cs#L36) which looks quite intentional. But in this case what's the point of performing the same action multiple times? 
At the same time I don't see any registration for ```IRequestExceptionAction<TRequest>``` but only for ```IRequestExceptionAction<TRequest, TException>``` [here](https://github.com/jbogard/MediatR/blob/513c20214a84d7486d50eddf9eea8591c7360894/src/MediatR/Registration/ServiceRegistrar.cs#L24). So what's the point to have any implementation of ```IRequestExceptionAction<TRequest>```?

**Comment by jbogard** [comment]
I think the right thing to do here is to remove these extra interfaces. They can confuse the registration and resolution logic.
