### ISSUE TITLE
IRequestExceptionHandler can not handle exceptions thrown by pipelinebehaviours

### ISSUE THREAD

**Issue by onurguler1** [jbogard/MediatR#897]
Hi, in my sceneraio I have 1 exceptionhandler, 2 pipeline behaviour validation and logging. I registered them by order that I want as below:
services.AddTransient(typeof(IRequestExceptionHandler<,,>), typeof(ExceptionHandlingBehaviour<,,>));
services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehaviour<,>));
 services.AddTransient(typeof(IPipelineBehavior<,>), typeof(LoggingBehaviour<,>));

When a validationException thrown by validationbehaviour, exceptionhandlingbehaviour can not handle.

**Comment by jbogard** [comment]
This is because the order isn't right. Exception behaviors should be the outermost ones.

**Comment by jbogard** [comment]
Also it doesn't look like you're using the `AddMediatR` method, that confuses things here. This looks like a container issue here.
