### ISSUE TITLE
Verson 12.0.1 supports .net standard 2.0?

### ISSUE THREAD

**Issue by jpmartinez-polstudios** [jbogard/MediatR#898]
I'm attempting to use MediatR on a .netstandard project but it seems like I keep getting a MissingMethodException, but looking at the history it seems like you didn't support .netstandard 2.0 but now you do, according to the nuget package dependencies. Is this accurate? Is there something else I might be doing wrong?

**Comment by asimmon** [comment]
MediatR does support .NET Standard 2.0, as mentioned in the [NuGet.org dependencies](https://www.nuget.org/packages/MediatR#dependencies-body-tab).

MediatR implementation is quite simple and doesn't use any framework-specific .NET APIs. It only targets .NET 6.0 to remove the dependency on `Microsoft.Bcl.AsyncInterfaces` which is already included in this version.

You should provide some details about your exception stacktrace, I believe the error happens in your code and not MediatR.

![image](https://user-images.githubusercontent.com/14242083/236692179-8ad80300-78c0-41a4-8961-2e5f9617b473.png)

**Comment by no1melman** [comment]
> I'm attempting to use MediatR on a .netstandard project but it seems like I keep getting a MissingMethodException, but looking at the history it seems like you didn't support .netstandard 2.0 but now you do, according to the nuget package dependencies. Is this accurate? Is there something else I might be doing wrong?

What missing method? have you got a lot more information you publish, there's not really anything to go on here.

**Comment by jpmartinez-polstudios** [comment]
Sorry for the lack of information, most of it was because I didn't have much to go off of. Became apparent that it was having dll issues with Revit. I was creating a revit plugin and I guess it didn't like it. But eventually got it working when I switched from Rider back to visual studio, wiped the bin/obj folders, and added the dll to the base revit folder. But definitely not an issue from MediatR.
