### ISSUE TITLE
Registering generic handlers

### ISSUE THREAD

**Issue by sjd2021** [jbogard/MediatR#905]
This PR to register generic request handlers (`RegisterGenericMediatRHandlers`) was opened in the old MediatR repository and closed. Is there an issue with it being ported over, as-is, or as close to that as possible since registration has somewhat changed?

https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/pull/115

**Comment by jbogard** [comment]
No there's no issue with someone doing that.

**Comment by amunim** [comment]
I have exams... will look into it by the end of the month

**Comment by jbogard** [comment]
I don't think the stock container can handle this anyway, you might need AutoFac or something else.

**Comment by advdotnet** [comment]
@sjd2021 or anyone stumbling upon this issue:
- make sure that your request and handler have a generic constraint like inheriting from an interface
- make sure the classes implementing this interface are in the assembly passed to the `RegisterGenericMediatRHandlers` extension method
