### ISSUE TITLE
Visual Studio shortcut?

### ISSUE THREAD

**Issue by mariusz96** [jbogard/MediatR#908]
I'm not sure if this question even belongs here but say I have MyRequest.cs file opened in Visual Studio - is there some nice shortcut I can use to navigate directly to its' handler?

I'm thinking something akin to "Go To Implementation" but for MediatR.

**Comment by maxime-poulain** [comment]
Hello,

if you are using Resharper (or Rider), 
you can use this: https://www.jetbrains.com/help/resharper/Navigate_To_Consuming_APIs.html
