### ISSUE TITLE
Best practice to decorate both IRequest and IAsyncRequest

### ISSUE THREAD

**Issue by parmarnishant** [jbogard/MediatR#91]
```
public class CacheHandlerAsync < TRequest, TResponse > :
 IAsyncRequestHandler <TRequest, TResponse> , IRequestHandler < TRequest, TResponse >
 where TRequest: BaseCommand <TResponse> {
  private readonly IRequestHandler <TRequest,TResponse> _inner;
  private readonly IAsyncRequestHandler <TRequest,TResponse> _innerAsync;

  async Task <TResponse> IAsyncRequestHandler <TRequest,TResponse> .Handle(TRequest request) {}
  public TResponse Handle(TRequest request) {}
 }
```

I have to write two methods. Is there better way ?

**Comment by jbogard** [comment]
Yes. If you only create async handlers, you only need to create the one wrapper. For handlers marked as async but don't actually need it, you can just do:

```
public class FooHandler : IAsyncRequestHandler<Foo, Bar> {
public Task<Bar> Handle(Foo request) {
   var bar = BuildBar(request);

   return Task.FromResult(bar);
}
}
```

You only would add the async/await keywords if you were actually awaiting something.

**Comment by eddiegroves** [comment]
We're moving to just IAsyncRequestHandler everywhere by default as we've found it similar to just think about one type of request. Any overhead around Task should be trivial.

**Comment by jbogard** [comment]
This will be taken care of more easily with pipelines too now. They will support all request types.
