### ISSUE TITLE
Calling AddMediatR multiple times?

### ISSUE THREAD

**Issue by maranmaran** [jbogard/MediatR#916]
Hello, couldn't filter out an answer for myself quickly. 

Can we call AddMediatR multiple times, say once per assembly?

AutoMapper for example allowed to do that in this change 
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/pull/135

From my perspective it's quite convenient, so far I've only seen one-place-all registration whereas that's possible and not a huge problem to manage I'd still like the flexibility

**Comment by jbogard** [comment]
You should be able to, the core registrations (`IMediator` etc.) are all done via `TryAdd`.
