### ISSUE TITLE
IRequestPreProcessor & IRequestPostProcessor 12.1.0

### ISSUE THREAD

**Issue by xts-velkumars** [jbogard/MediatR#929]
@jbogard, 

In the latest version of MediatR no longer scans for pre/post processors.

I'm not worrying about the Order. Because I one pre/post handlers

Can you please add a flag like below as discussed through Email. To scans for pre/post processors. That way it will not break my existing application. 

`cfg.ScanForRequestProcessors = true;`

**Comment by jtullos-bt** [comment]
Our post processors are no longer getting registered with 12.1.1, but we're working fine with 12.0.1, so I'm unsure if the issue is for the latest version rather than 12.0.1.

**Comment by jbogard** [comment]
Upppppppgraaaaadeeee guiiiiiiideeeee
