### ISSUE TITLE
Consider adding new overload to AddOpenBehavior

### ISSUE THREAD

**Issue by jonathanhallee** [jbogard/MediatR#934]
Hey,

We are currently in the process of migrating to Mediatr v12.1 and changing our old behavior registrations from generic `AddScoped` registrations to using the provided `AddOpenBehavior` extensions.

One thing we find missing is an overload of `AddOpenBehavior` that accepts a `Func<IServiceDescriptor, object>` which would allow us to more easily migrate funky registrations where we do constructor injection with a func.

Example:
```
services.AddScoped((Func<IServiceProvider, IPipelineBehavior<TRequest, TResponse>>)((IServiceProvider x) => new SomeBehavior<TRequest, TResponse>(someParameter)));
```

would be translated to something like

```
config.AddOpenBehavior(typeof(SomeBehavior<,>), (IServiceProvider x) => new SomeBehavior<TRequest, TResponse>(someParameter)))
```

The [ServiceDescriptor](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs) class already accepts it

I don't see anything else allowing us to do this? 

Thanks!

**Comment by jbogard** [comment]
I'll take a PR!

**Comment by jscarle** [comment]
I looked into this, its does not seem possible to do this with the way pipelines are currently registered. The Dependency Injection container doesn't support registering open generics with a factory directly. It throws an exception:
```
"Open generic service type 'MediatR.IPipelineBehavior`2[TRequest,TResponse]' requires registering an open generic implementation type. (Parameter 'descriptors')".
```
