### ISSUE TITLE
Using a single event class implementing both INotification and IAsyncNotification leads to cache exception

### ISSUE THREAD

**Issue by sickboy** [jbogard/MediatR#94]
```
Unable to cast object of type 'MediatR.Internal.NotificationHandlerWrapper`1[MyEvent]' to type 'MediatR.Internal.AsyncNotificationHandlerWrapper'.
```

In the meantime I found that in most of my projects usages there was a clear separation between events that are handled async and those that are handled sync, but I liked that I could just raise the events, and not worry about (future) consumer kinds. IMO it's a consumer, and not publisher concern.

**Comment by jbogard** [comment]
Ah hmmmm, is this just a bug in the cache then?

**Comment by sickboy** [comment]
@jbogard yea the same storage is used for all the kinds of handlers (Notification/Handler, AsyncNotification/AsyncHandler, AsyncNotificationWithCancellation/AsyncHandlerWithCancellation), based on the runtime type of the message class.

**Comment by valdisiljuconoks** [comment]
Yes, stepped on the same issue recently.

**Comment by maca88** [comment]
+1
