### ISSUE TITLE
INotificationHandler constructed, called twice for a single Notification

### ISSUE THREAD

**Issue by jakenuts** [jbogard/MediatR#946]
I'm running into an issue where the existence of a generic notifcation handler constrained to a specific base type is causing a explicit notification handler to be created & called twice when the event it handles is published. Here are the steps to reproduce and a github repository demonstrating the problem.

[Demo Repository](https://github.com/jakenuts/MediatRIssue)

* Define a base for "events" (notifications) and two derived events EventA, EventB
* Create a handler for EventA
* Create a generic handler for any event of the base type
* Publish EventA

-> Handler for EventA is constructed and called twice 

* Publish EventB

-> Handler for generic event type is constructed, called once.

MediatR 12.1.1

**Comment by jbogard** [comment]
You'll need to verify if this is an issue in the container or MediatR. Check the registrations to see if the handler is registered twice OR if you try to resolve the `IEnumerable<INotificationHandler<EventA>>` and it has the handlers twice.

**Comment by jbogard** [comment]
You can allow multiple calls to `AddMediatR` but just don't pass in the same assemblies to scan for handlers.

**Comment by neozhu** [comment]
<img width="660" alt="image" src="https://github.com/jbogard/MediatR/assets/1549611/0213ee73-147a-487c-97db-1f40d7ad49d4">
@jakenuts  I ran your code, and the test results seem normal. Have you already fixed the issue?

**Comment by jakenuts** [comment]
Odd! No, no changes and on my system (Win11/VS 17.8 preview 1.0) it looks like this:

![image](https://github.com/jbogard/MediatR/assets/344606/318191f8-5ca7-4e72-8c61-371d9b6952ce)

**Comment by ibrahimhaouari** [comment]
![image](https://github.com/jbogard/MediatR/assets/51293542/bbc58cfe-1dc0-4cf6-a946-f82e029d6fef)
looks normal!

**Comment by jakenuts** [comment]
Hmmm.. Well thanks everyone, I aparently have a "special" build of dotnet.

**Comment by Mayron** [comment]
@jakenuts Funny enough, I submitted the same issue ([here](https://github.com/jbogard/MediatR/issues/948)) last week but must have just missed you closing this! A big coincidence. Turns out this bug was submitted to Microsoft and merged in as a fix to .Net 8 but sadly .Net 8 is in preview and getting companies to migrate over can be tricky or not feasible.
