### ISSUE TITLE
Assembly.LoadFile("c:\SomePath\MyApp.dll") doesn't find handlers

### ISSUE THREAD

**Issue by TiisangMguni** [jbogard/MediatR#961]
Does anyone have a idea why this works:
```
assemblies.Add(typeof(SampleUseCaseHandler).Assembly);
builder.AddMediatR(assemblies)
```

But this doesn't work:
```
assemblies.Add(Assembly.LoadFile("c:\SomePath\MyApp.dll"));`
builder.AddMediatR(assemblies)

```

The reason why we need to load the DLL from disk is because we want to load "plugins" during runtime and cannot have a direct reference to the plugin DLLs

**Comment by jbogard** [comment]
This is better for StackOverflow, as it has less to do with MediatR and more to do with dynamically loading assemblies.

**Comment by christoneethling** [comment]
I had the same issue with MediatR and solved it by using LoadFrom(path), instead of LoadFile(path)

Like this:

```
assemblies.Add(Assembly.LoadFrom("c:\SomePath\MyApp.dll"));`
builder.AddMediatR(assemblies)
```
