### ISSUE TITLE
How to replicate previous api for registering pre/post processors

### ISSUE THREAD

**Issue by hisuwh** [jbogard/MediatR#963]
The guide for migrating to v12.1 is a bit unclear to me: https://github.com/jbogard/MediatR/wiki/Migration-Guide-12.0-to-12.1

We have dozens of pre/post processors and this makes it seem as if I would need to add them all individually when upgrading to 12.1

**Comment by jbogard** [comment]
Dozens? They're supposed to be analogous to filters in ASP.NET Core. Cross cutting concerns across multiple handlers with no domain logic.

But yes, because order matters you need to register them explicitly in the order you want them to execute. It was a mistake to ever auto-register them.

**Comment by hisuwh** [comment]
We have generic commands/handlers for CRUD operations and are using PostProcessors for side effects (notifications, updating related records etc.) that are specific to a certain type.  We don't have any open PostProcessors and order doesn't matter.

We are using PipelineBehaviours for cross-cutting concerns.

**Comment by jbogard** [comment]
Ah jeez my bad I was thinking pipeline behaviors not pre/post processors. One option is to include an "AutoRegisterRequestProcessors" flag or similar so that those can get registered by default as well.

Those are ordered as well which is why they were switched to manual, but if every handler only has 0-1 processors then order wouldn't matter.

**Comment by hisuwh** [comment]
@jbogard do I still need to register the behaviours manually?  Looks like this was taken out:
https://github.com/jbogard/MediatR/commit/9ebdf7b5305e161456224afe3193de1bf21ca6ed#diff-c4d1d5960b86a86bee0fd5974803c90f8656cde09914a4c43ae14dc193c3cf35L237

**Comment by hisuwh** [comment]
I found a bug which I have fixed:
https://github.com/jbogard/MediatR/pull/989

**Comment by hisuwh** [comment]
@jbogard any idea when the next release might be including #989 ?
