### ISSUE TITLE
What is the best way of appling part of same logic in different handler?

### ISSUE THREAD

**Issue by vip30** [jbogard/MediatR#97]
```
public class InvoiceCreateCommandHandlerAsync: AsyncRequestHandler<InvoiceCreateCommand>
{
    private readonly DbContext _db;
    public InvoiceCreateCommandHandlerAsync(
       DbContext  db)
    {
        _db= db;
    }
    protected override async Task HandleCore(InvoiceCreateCommand command)
    {
        //Transaction
        //Save Invoice DB action
        //As the invoice is added, and the stock will be stocked out
       //Stock out Logic here
           .......
       //End
       //Commit
    }
}

public class StockOutCommandHandlerAsync: AsyncRequestHandler<StockOutCommand>
{
    private readonly DbContext _db;
    public StockOutCommandHandlerAsync(
       DbContext  db)
    {
        _db= db;
    }
    protected override async Task HandleCore(StockOutCommand command)
    {
       //Stock out Logic here
           .......
       //End
    }
}
```

Sorry about the poor format.
I would like to ask what is the best approach for applying same logic in different handler?
As the stock out logic is need to provide in create invoice and also in the stock out page
Thanks

**Comment by abatishchev** [comment]
You can inject a helper into both handlers and call shared logic method from there

**Comment by vip30** [comment]
I see we can inject a service/helper for helping the stock out function,
but it will not be treated as a command, I just want to know is that violate the CQRS pattern?
Many Thanks

**Comment by abatishchev** [comment]
I don't think a handler to have a dependency is illegal, and injecting it into its ctor violates any principle. Rather follows these principles. Also it's better than inheriting both handlers from a base class (see the composition over inheritance principle)

**Comment by valdisiljuconoks** [comment]
Hi, I would think of `StockOut` logic as code fragment that does not need to treated as command separately, but it's always called from the "hosting" command -> one or another handler. `StockOut` code fragment makes no sense by itself, but is always executed within the command. And handler having a dependency - don't think it's illegal. Think about it as ordinary service injection for the handler.

**Comment by jbogard** [comment]
https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/
