### ISSUE TITLE
System.InvalidOperationException: No service for type 'MediatR.IRequestHandler`2   has been registered.

### ISSUE THREAD

**Issue by kamhawy4** [jbogard/MediatR#976]
when i execute  api give me this error.

the project by core 7

swagger
![Screenshot 2023-11-21 111813](https://github.com/jbogard/MediatR/assets/25951080/48b70c4c-cd64-4f8c-88d5-d47ea91de86e)

program.cs

![Screenshot 2023-11-21 111733](https://github.com/jbogard/MediatR/assets/25951080/ae455de0-ccf3-4464-8443-62a8ff7b048a)

controller

![Screenshot 2023-11-21 111919](https://github.com/jbogard/MediatR/assets/25951080/5af7961f-235f-40ee-b0c5-e68c7dda53a4)

**Comment by EstebanP-dev** [comment]
How many layers do you have on your project? In this case, MediatR threw the error because it cannot read the assembly where the request handler is implemented. Instead, you can try using the layer assembly of your command handler.

**Comment by gkot-softwaredeveloper** [comment]
Remember that you can pass the 'array' as an argument into mediatR configuration.
It seems that Program.cs assembly just contains the IMediatR <-- probably u use it only for initializing your query/command flow from controllers. However, the real handlers are in the Application Layer for example. So just add one more assembly 

`builder.Services.AddMediatR(cfg =>
{
    cfg.RegisterServicesFromAssemblies([typeof(Program).Assembly, typeof(xxxxxx).Assembly]);
});`

**Comment by tienpmw** [comment]
services.AddMediatR(config => config.RegisterServicesFromAssemblies(AppDomain.CurrentDomain.GetAssemblies()));

**Comment by YazanYahya98** [comment]
> services.AddMediatR(config => config.RegisterServicesFromAssemblies(AppDomain.CurrentDomain.GetAssemblies()));

Thanks, This works when you have the request handler in different projects as dependecies
