### ISSUE TITLE
docs: I'm able to edit the wiki

### ISSUE THREAD

**Issue by VividLemon** [jbogard/MediatR#982]
Editing the wiki appears to be public :monocle_face:

![image](https://github.com/jbogard/MediatR/assets/31498096/943f159f-0781-43c9-a89d-b26083e71b81)

(I removed the footer after btw)

**Comment by maxime-poulain** [comment]
Hello, 
you won't be able to actually edit the README.

![image](https://github.com/jbogard/MediatR/assets/6811304/10818401-8cce-4fd4-b824-ee559ac6f6a7)
When saving, it will just create a pull request.

**Comment by VividLemon** [comment]
> Hello, you won't be able to actually edit the README.
> 
> ![image](https://private-user-images.githubusercontent.com/6811304/287484337-10818401-8cce-4fd4-b824-ee559ac6f6a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDE2OTgsIm5iZiI6MTcwMTcwMTM5OCwicGF0aCI6Ii82ODExMzA0LzI4NzQ4NDMzNy0xMDgxODQwMS04Y2NlLTRmZDQtYjgyNC1lZTU1OWFjNmY2YTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTQ0OTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjE0NjRlOWFjYmY0ZDgzNWE2YWUxNTAwOWEyNWQ5N2ZmYjc1N2QzYjJiMGI4YTQzNTg1ZmIxNDFlMmRiNWQ0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DsWTbilCGMiEOIANdOr-i_NGJ1zRq_VGV67mbFQgv6o) When saving, it will just create a pull request.

I had changed the footer of the index page, then proceeded to open it in a private window, and successfully viewed the change. Perhaps I am missing something. If you want to verify, I changed the footer at https://github.com/jbogard/MediatR/wiki to _Footer

**Comment by jbogard** [comment]
The wiki is separate than the readme.md. The wiki is also backed by git and can be reverted so I'm not terribly worried about it. The idea was to allow others to edit besides just me.
