### ISSUE TITLE
"No service for type 'MediatR.IRequestHandler' has been registered." issue

### ISSUE THREAD

**Issue by longvietcode** [jbogard/MediatR#984]
So i'm new to MediatR and I got this error, please help me, thanks!
![image](https://github.com/jbogard/MediatR/assets/32150437/bd8d51a9-f8b0-4c27-b563-6b588008bab6)
_ Version:
.NET 8
MediatR 12.2.0

This is my solution structure:
![image](https://github.com/jbogard/MediatR/assets/32150437/b6ad6a42-d9ec-46df-a6bb-daf90984ccba)

This is my Program file:
![image](https://github.com/jbogard/MediatR/assets/32150437/e7454af2-52e4-4ab0-8f0c-de82f390f967)

This is my controller file:
![image](https://github.com/jbogard/MediatR/assets/32150437/6e0d33e2-d4c6-4a2e-a2b1-169a90d64b19)

This is where I implement MediatR request and request handler
![image](https://github.com/jbogard/MediatR/assets/32150437/b25417bf-ef0f-4c82-af3e-e1b130427a9c)

**Comment by AndrewPearson** [comment]
I think the issue is that you only register Mediatr request handlers from the assembly containing the class Program. The request handlers are in a different assembly, the application project.

**Comment by MuhammadKhalilzadeh** [comment]
> > > > I think the issue is that you only register Mediatr request handlers from the assembly containing the class Program. The request handlers are in a different assembly, the application project.
> > > 
> > > 
> > > > Same as #976.
> > > 
> > > 
> > > Thanks for the comments, do you guys have the code example for how I can register IRequestHandler in my Application layer? Thanks!
> > 
> > 
> > All you need to do is amend the code in Program.cs that calls AddMediatr. This currently takes the type 'Program' which makes Mediatr add DI registration for any request handlers that are in Program's project. As there are no request handlers in that project, none are added. Instead of passing the type Program, pass a type from the Application project which contains the handlers.
> 
> It works, thank you so much

What was the type from the Application project that you passed?

**Comment by gkot-softwaredeveloper** [comment]
Remember that you can pass the 'array' as an argument into mediatR configuration.
It seems that Program.cs assembly just contains the IMediatR <-- probably u use it only for initializing your query/command flow from controllers. However, the real handlers are in the Application Layer for example. So just add one more assembly

builder.Services.AddMediatR(cfg => { cfg.RegisterServicesFromAssemblies([typeof(Program).Assembly, typeof(xxxxxx).Assembly]); });

**Comment by HugoDeveloperBR** [comment]
If your handlers are in a separate project, an alternative is to register the assembly of that project explicitly.

```cssharp
var assemblies = Assembly.Load("YourOther.ProjectWithHandlers");

**Comment by ShivaChenna** [comment]
> > > I think the issue is that you only register Mediatr request handlers from the assembly containing the class Program. The request handlers are in a different assembly, the application project.
> > 
> > 
> > > Same as #976.
> > 
> > 
> > Thanks for the comments, do you guys have the code example for how I can register IRequestHandler in my Application layer? Thanks!
> 
> All you need to do is amend the code in Program.cs that calls AddMediatr. This currently takes the type 'Program' which makes Mediatr add DI registration for any request handlers that are in Program's project. As there are no request handlers in that project, none are added. Instead of passing the type Program, pass a type from the Application project which contains the handlers.

Thank you

**Comment by kplkasteel** [comment]
System.InvalidOperationException: 'Cannot resolve 'MediatR.IRequestHandler`2[Version1.Decipher.Application.Features.ProjectMember.Queries.GetUserProjectAuthorisation.GetUserProjectAuthorizationQuery,Version1.Decipher.Common.Results.RequestResult`1[System.Boolean]]' from root provider because it requires scoped service 'Version1.Decipher.Infrastructure.EntityFramework.IDbContext'.'
