### ISSUE TITLE
Why not IRequestHandler<TRequest>?

### ISSUE THREAD

**Issue by geirsagberg** [jbogard/MediatR#99]
For requests that do not need to return a value, the docs say to use the `RequestHandler` base class.

Why not just overload the `IRequestHandler` interface like so?

    public interface IRequestHandler<in TRequest, out TResponse>
        where TRequest : IRequest<TResponse>
    {
        TResponse Handle(TRequest message);
    }

    public interface IRequestHandler<in TRequest>
        where TRequest : IRequest
    {
        void Handle(TRequest message);
    }

It would be more consistent, and avoid unnecessary inheritance.

**Comment by jbogard** [comment]
Fork it and try it in the codebase! I don't remember off the top of my head why.

**Comment by khellang** [comment]
Cause it's much easier to deal with a single interface with two generic arguments than two different ones with different generic arguments :smile:

**Comment by geirsagberg** [comment]
@khellang not sure if you're kidding :P Anyway, I made a PR, looks good so far https://github.com/jbogard/MediatR/pull/100

**Comment by abatishchev** [comment]
>Cause it's much easier to deal with a single interface with two generic arguments than two different ones with different generic arguments
+1

**Comment by geirsagberg** [comment]
The issue isn't a single interface vs two interfaces though, it's an interface *and* an abstract class (`RequestHandler`) vs two interfaces, and I for one prefer composition over inheritance whenever possible.

If both interfaces having the same name is confusing, the new interface can be called `IVoidRequestHandler` or `ICommandHandler` or anything else... The point is that having an interface for handlers that handle requests without responses is superior to having an abstract class for the same thing.

**Comment by jbogard** [comment]
Well, there's nothing stopping you from doing that today. IRequest just
inherits IRequest<T> where T is the Unit type. There's nothing forcing you
to use the base class.

**Comment by geirsagberg** [comment]
@jbogard Good point, I updated the wiki with an example:

> In the rare case your message does not require a response, use the base `RequestHandler` class, or return the special void type `Unit` (`IRequest` inherits `IRequest<Unit>`):
```csharp
public class OneWay : IRequest { }
public class OneWayHandlerWithBaseClass : RequestHandler<OneWay> {
    protected override void HandleCore(OneWay request) {
        // Twiddle thumbs
    }
}
public class OneWayHandlerWithInterface : IRequestHandler<OneWay, Unit> {
    public Unit Handle(OneWay request) {
        ...
        return Unit.Value;
    }
}
```

However, I would still argue that the first of these is more clean and intuitive:
```csharp
public class SendMailHandler : IRequestHandler<SendMailRequest> {
    ...
    public void Handle(SendMailRequest request) {
        mailService.SendMail(request.To, request.From, request.Subject, request.Body);
    }
}
public class SendMailHandler : IRequestHandler<SendMailRequest, Unit> {
    ...
    public Unit Handle(SendMailRequest request) {
        mailService.SendMail(request.To, request.From, request.Subject, request.Body);
        return Unit.Value;
    }
}
```
In fact, with having a separate void interface, the `Unit` type is no longer needed as far as I can see.

**Comment by khellang** [comment]
> The issue isn't a single interface vs two interfaces though, it's an interface and an abstract class (RequestHandler) vs two interfaces, and I for one prefer composition over inheritance whenever possible.

You're looking at this from the users POV, I was looking at it from the library's POV. I wasn't kidding. It's much easier to handle a single interface (with an abstract base class to hide away some stuff for the consumer) than two interfaces.

**Comment by geirsagberg** [comment]
@khellang Gotcha, and from the library's POV I agree, my method does require some more code.

However, now that the work is done, I would think the benefit to the consumer outweighs the few extra lines of code to maintain?

**Comment by abatishchev** [comment]
From user's perspective, it's better to have an interface than an abstract class since C# doesn't have multiple inheritance.

**Comment by jbogard** [comment]
The abstract class is strictly a convenience thing. There's nothing forcing anyone to use the abstract class. It's more C# doesn't have a proper void type, so I borrowed F#.

See also the silliness of having both an Action and Func delegate types.

**Comment by jbogard** [comment]
One other thing - having two interfaces makes it quite a bit harder to build your own decorators. Having a single interface is better.

**Comment by iangriffin** [comment]
I came here with the same thought that there had to be a better way with void, but I much prefer the single interface if only for decoration. I hadn't thought that far through it before I was searching this out. So I'll be using `Unit`

**Comment by mrtank** [comment]
In users point of view sometimes it's hard to get why can't I `IRequestHandler<TRequest>` when I really don't have response type. It's not clear why to have a Handler implementation of type `Task<Unit>`, with a `return Unit.Value;`, when you could have a `Task` without `return`. The main reason I would go with
```
public class SendMailHandler : IRequestHandler<SendMailRequest> {
    ...
    public Task Handle(SendMailRequest request) {
        await mailService.SendMail(request.To, request.From, request.Subject, request.Body);
    }
}
```
is compile time check. You can't register a handler crossed (handler with return, while the implementation have `return Unit.Value`).

**Comment by lukpep** [comment]
One more thing regarding this topic.
How should one use `AsyncRequestHandler<TRequest>` and solve cross-cutting concerns?
Behaviours are not an option since:

> The pipeline behaviors are only compatible with IRequestHandler<TRequest,TResponse> and can't be used with INotificationHandler<TRequest>.

Decorators also - since `Handle` method of `AsyncRequestHandler` is protected and I can't write a generic decorator for all of my handlers eg:

 `public class JaegerCommandHandlerDecorator<TCommand> : AsyncRequestHandler<TCommand> where TCommand : class, IRequest`

at least not using any reflection magic which I would like to avoid if possible ;-)
Am I missing something? Or is switching to `IRequestHandler<IRequest, Unit>` only option?

**Comment by jbogard** [comment]
That’s a convenience class. It still implements the same request handler
interface underneath.

Keeping things as a single interface makes MediatR much simpler. I do
expect C# to make things easier at some point seeing as how it’s becoming
more functional.
