### ISSUE TITLE
Add assembly with handlers without ServiceCollection

### ISSUE THREAD

**Issue by zoinkydoink** [jbogard/MediatR#999]
We are using v9.0 (cant upgrade to higher), also using this in .NET Framework 4.6.2 with WPF app.

We are dynamically loading dlls that contain Notification handlers, this is done well after the initial load of application, hence why ServiceCollection is not available.

Is there a way I can register Assemblies that are dynamically loaded and well after app start?
If so how can i do this, thank you

**Comment by jbogard** [comment]
This isn't a MediatR question, it's a DI container question. Check with your container docs on this.
